# -*- coding: utf-8 -*-
"""Add hand-curated 'From Short Stories' vocabulary (base forms, story examples,
AI translations) into public/data/vocab.json, then report new per-level counts.
Curated from the 9 short-story transcripts. Does NOT deploy."""
import json, os, datetime
proj = r'C:\Users\ADELEKEOLORUNISOLAO\Desktop\goethe-trainer'
VJSON = os.path.join(proj,'public','data','vocab.json')

# (w, t, de_example, en_example, level)
E = [
 # ---------- A1 ----------
 ("darin","in it / inside","Darin ist ein kleiner Vogel.","Inside is a small bird.","A1"),
 ("vorbei","past / over","Ein Mann rennt an ihr vorbei.","A man runs past her.","A1"),
 ("der Spaß","fun","Er gewann nicht, aber er hatte Spaß.","He didn't win, but he had fun.","A1"),
 ("bekommen","to get / receive","Nicht alle bekamen heute gute Nachrichten.","Not everyone got good news today.","A1"),
 ("der Magen","stomach","Sein Magen fühlte sich komisch an.","His stomach felt strange.","A1"),
 # ---------- A2 ----------
 ("namens","named / by the name of","Ein Junge namens Theo lächelte ihn an.","A boy named Theo smiled at him.","A2"),
 ("lustig","funny","Sie heißt Sarah und ist lustig.","Her name is Sarah and she is funny.","A2"),
 ("diesmal","this time","Diesmal fügten sie ein Schloss hinzu.","This time they added a lock.","A2"),
 ("froh","glad","Er ist froh, dass er helfen konnte.","He is glad that he could help.","A2"),
 ("der Dollar","dollar","Sie hat nur 30 Dollar.","She only has 30 dollars.","A2"),
 ("mögen","to like","Möchtest du ihn mit mir teilen?","Would you like to share it with me?","A2"),
 ("bewegen","to move","Es bewegte sich aber nicht.","But it did not move.","A2"),
 ("das Boot","boat","Bald kamen zwei Fischer und reparierten das Boot.","Soon two fishermen came and fixed the boat.","A2"),
 ("herum","around","Sie kaut auf dem Hut herum.","She is chewing on the hat.","A2"),
 ("hinzu","in addition","Diesmal fügten sie ein Schloss hinzu.","This time they added a lock.","A2"),
 ("der Ball","ball","Der Torwart ließ den Ball fallen.","The goalkeeper dropped the ball.","A2"),
 ("großartig","great / wonderful","Theo, du warst großartig.","Theo, you were great.","A2"),
 ("schlimm","bad / terrible","Der Sturm war schlimm.","The storm was bad.","A2"),
 ("letzte","last","Letztes Jahr hatten ihre Freunde ihn vergessen.","Last year her friends forgot it.","A2"),
 ("erwarten","to expect","Die schönsten Dinge geschehen, wenn man sie am wenigsten erwartet.","The best things happen when you least expect them.","A2"),
 ("die Planung","planning","Er hatte bei der Planung geholfen.","He had helped with the planning.","A2"),
 ("der Schwanz","tail","Der Hund wedelte mit dem Schwanz.","The dog wagged its tail.","A2"),
 ("komisch","strange / odd","Sein Magen fühlte sich komisch an.","His stomach felt strange.","A2"),
 ("zuvor","before / previously","Der Garten gedieh besser als zuvor.","The garden grew better than before.","A2"),
 ("verpassen","to miss","Sie hatte ihren Bus verpasst.","She had missed her bus.","A2"),
 ("daneben","next to it / beside","Seine Katze saß daneben.","His cat sat next to it.","A2"),
 ("innen","inside","Keine Geräusche kamen von innen.","No sounds came from inside.","A2"),
 ("behalten","to keep","Sie konnte das Geld behalten.","She could keep the money.","A2"),
 # ---------- B1 ----------
 ("klopfen","to knock","Priya klopfte ihm auf den Rücken.","Priya patted him on the back.","B1"),
 ("die Kiste","box / crate","Darin lag eine kleine schwarze Kiste.","Inside lay a small black box.","B1"),
 ("seltsam","strange","Sie denken über den seltsamen Mann nach.","They think about the strange man.","B1"),
 ("herein","in (inward)","Sie kommt herein und bleibt stehen.","She comes in and stops.","B1"),
 ("die Bushaltestelle","bus stop","Sie ging zur Bushaltestelle und wartete.","She went to the bus stop and waited.","B1"),
 ("betrachten","to look at / regard","Der große Löwe betrachtete den Ballon.","The big lion looked at the balloon.","B1"),
 ("der Keks","biscuit / cookie","Nächstes Mal bringe ich Kekse mit.","Next time I'll bring cookies.","B1"),
 ("springen","to jump","Affen sprangen zwischen den Bäumen.","Monkeys jumped between the trees.","B1"),
 ("die Ziege","goat","Diese Ziege stiehlt immer etwas.","This goat always steals something.","B1"),
 ("der Eimer","bucket","Theo schaut auf seinen leeren Eimer.","Theo looks at his empty bucket.","B1"),
 ("zittern","to tremble / shake","Seine Hände zitterten.","His hands were trembling.","B1"),
 ("beobachten","to observe / watch","Ein Mann in der Nähe beobachtet sie.","A man nearby watches them.","B1"),
 ("sich unterhalten","to chat / talk","Sie unterhielten sich lange.","They chatted for a long time.","B1"),
 ("silbern","silver (made of)","Er zeigt ihr einen kleinen silbernen Stift.","He shows her a small silver pen.","B1"),
 ("verloren","lost","Sie haben einem verlorenen Vogel geholfen.","They helped a lost bird.","B1"),
 ("der Zettel","note / slip of paper","Sie findet einen Zettel auf seinem Tisch.","She finds a note on his desk.","B1"),
 ("der Löwe","lion","Der Ballon landete im Gehege der Löwen.","The balloon landed in the lions' enclosure.","B1"),
 ("der Knopf","button","Im Museum sah Mira einen großen roten Knopf.","In the museum Mira saw a big red button.","B1"),
 ("drücken","to press","Sie drückte einen kleinen blauen Knopf.","She pressed a small blue button.","B1"),
 ("krachen","to crash / bang","Plötzlich krachte es.","Suddenly there was a crash.","B1"),
 ("der Heimweg","way home","Auf dem Heimweg kauft er einen kleinen Kuchen.","On the way home he buys a small cake.","B1"),
 ("die Magie","magic","Die Magie war schon immer in ihm.","The magic was in him all along.","B1"),
 ("merken","to notice / realise","Bald merkten die Menschen sein gutes Herz.","Soon people noticed his good heart.","B1"),
 ("das Tuch","cloth","Noa nimmt ein Tuch.","Noa picks up a cloth.","B1"),
 ("der Zoo","zoo","Der Zoobesuch war nicht perfekt.","The zoo visit was not perfect.","B1"),
 ("das Müsli","muesli / cereal","Sie braucht Milch für ihr Müsli.","She needs milk for her cereal.","B1"),
 ("verschwinden","to disappear","Die Müdigkeit verschwand aus ihrer Stimme.","The tiredness disappeared from her voice.","B1"),
 ("sich drehen","to turn (around)","Eine Schülerin dreht sich zu ihm um.","A student turns around to him.","B1"),
 ("besorgt","worried","Er sah besorgt aus.","He looked worried.","B1"),
 ("fremd","strange / foreign","Er stößt mit einem Fremden zusammen.","He bumps into a stranger.","B1"),
 ("erfahren","to find out","Eva erfuhr, dass sie Musikerin war.","Eva found out that she was a musician.","B1"),
 ("beibringen","to teach","Ich kann es dir beibringen, sagte er.","I can teach you, he said.","B1"),
 ("rutschen","to slip / slide","Plötzlich rutscht er aus und fällt.","Suddenly he slips and falls.","B1"),
 ("zerbrechen","to break / shatter","Das Glas zerbricht.","The glass breaks.","B1"),
 ("graben","to dig","Er gräbt im Sand.","He digs in the sand.","B1"),
 ("der Sand","sand","Sie sitzen im Sand und schauen aufs Wasser.","They sit in the sand and look at the water.","B1"),
 ("der Ballon","balloon","Der große Löwe betrachtete den Ballon.","The big lion looked at the balloon.","B1"),
 ("die Halbzeit","half-time","Zur Halbzeit stand es null zu null.","At half-time it was nil-nil.","B1"),
 ("der Torwart","goalkeeper","Der Torwart ließ den Ball fallen.","The goalkeeper dropped the ball.","B1"),
 ("verärgert","annoyed","Aber die andere Mannschaft sah verärgert aus.","But the other team looked annoyed.","B1"),
 ("überraschen","to surprise","Ruhige Menschen überraschen manchmal alle.","Quiet people sometimes surprise everyone.","B1"),
 ("der Alarm","alarm","Ein lauter Alarm ertönte.","A loud alarm sounded.","B1"),
 ("der Dachboden","attic","Der Dachboden war leer.","The attic was empty.","B1"),
 ("glänzend","shiny / shining","Der Preis war ein glänzend neues Messerset.","The prize was a shiny new knife set.","B1"),
 ("der Käfig","cage","Eli betrachtete den Vogel im Käfig.","Eli looked at the bird in the cage.","B1"),
 ("das Unkraut","weeds","Sie räumten das Unkraut gemeinsam weg.","They cleared the weeds together.","B1"),
 ("beschließen","to decide","Sie beschloss zu helfen.","She decided to help.","B1"),
 ("schief","crooked / lopsided","Er sah seltsam aus, schief und zu braun.","It looked strange, lopsided and too brown.","B1"),
 ("der/die Angestellte","employee","Sie fragte die Angestellte im Café.","She asked the employee in the café.","B1"),
 ("die Kette","chain / necklace","In dieser Nacht trug sie die Kette.","That night she wore the necklace.","B1"),
 ("die Notiz","note","Drinnen war ein Schlüssel und eine Notiz.","Inside was a key and a note.","B1"),
 ("der Atem","breath","Eva hielt den Atem an.","Eva held her breath.","B1"),
 ("herbei","over (to here)","Theo rennt herbei, um zu helfen.","Theo runs over to help.","B1"),
 ("notieren","to note down","Der Kellner notiert ihre Bestellungen.","The waiter notes down their orders.","B1"),
 ("die Heimatstadt","home town","Das ist meine Heimatstadt.","This is my home town.","B1"),
 ("schmal","narrow","Die Straßen sind schmal.","The streets are narrow.","B1"),
 ("vermissen","to miss (someone)","Er vermisst Rohan, ist aber glücklich.","He misses Rohan, but is happy.","B1"),
 ("das Papier","paper","Papiere bedecken den Tisch.","Papers cover the table.","B1"),
 ("retten","to save / rescue","Du hast mich gerettet.","You saved me.","B1"),
 ("der Geruch","smell","Der Geruch erfüllt den Raum.","The smell fills the room.","B1"),
 ("kräftig","strong / hearty","Die Pasta ist gut, heiß und kräftig.","The pasta is good, hot and hearty.","B1"),
 ("fressen","to eat (animals)","Die Hühner fressen schnell.","The chickens eat quickly.","B1"),
 ("der Stall","stable / barn","Alle rennen in den Stall.","Everyone runs into the barn.","B1"),
 ("stoßen","to bump / push","Er stößt mit einem Fremden zusammen.","He bumps into a stranger.","B1"),
 ("riechen","to smell","Die Küche riecht gut.","The kitchen smells good.","B1"),
 ("die Zwiebel","onion","Sie schneidet Zwiebeln.","She cuts onions.","B1"),
 ("die Trommel","drum","Die Tänzer bewegen sich zu schnellen Trommeln.","The dancers move to fast drums.","B1"),
 ("blass","pale","Ihr Gesicht wird blass.","Her face turns pale.","B1"),
 ("der Staub","dust","Der Staub fliegt überall hin.","The dust flies everywhere.","B1"),
 ("rüber","over (here)","Gut, ich komme rüber.","Good, I'll come over.","B1"),
 ("umher","around / about","Jetzt läuft sie langsam umher.","Now it walks slowly around.","B1"),
 ("die Flut","tide / flood","Die Flut kommt.","The tide is coming in.","B1"),
 ("die Welle","wave","Sie läuft in die Wellen.","It runs into the waves.","B1"),
 ("die Astronomie","astronomy","Magst du Astronomie?","Do you like astronomy?","B1"),
 ("deuten (auf)","to point (at)","Er deutet auf ihr Buch.","He points at her book.","B1"),
 ("die Zeichnung","drawing","Darin ist eine Zeichnung einer Galaxie.","Inside is a drawing of a galaxy.","B1"),
 ("die Galaxie","galaxy","Darin ist eine Zeichnung einer Galaxie.","Inside is a drawing of a galaxy.","B1"),
 ("hinein","in (inward)","Der Mann schaut hinein.","The man looks inside.","B1"),
 ("jener","that (one)","An jenem Abend lud Elias uns zum Essen ein.","That evening Elias invited us to dinner.","B1"),
 ("verwirrt","confused","Jara war verwirrt, stimmte aber zu.","Jara was confused, but agreed.","B1"),
 ("schmücken","to decorate","Der Raum war mit Luftballons geschmückt.","The room was decorated with balloons.","B1"),
 ("das Fell","fur / coat","Er hatte braunes Fell.","It had brown fur.","B1"),
 ("das Futter","feed / animal food","Sie gab ihm Futter und Wasser.","She gave it food and water.","B1"),
 ("begleiten","to accompany","Seine Tante begleitete ihn zur Bushaltestelle.","His aunt accompanied him to the bus stop.","B1"),
 ("der Affe","monkey","Sie beobachteten verspielte Affen.","They watched playful monkeys.","B1"),
 ("die Oma","grandma","Mira saß mit ihrer Oma auf dem Sofa.","Mira sat with her grandma on the sofa.","B1"),
 ("der Duft","scent / aroma","Der Duft von Tee erfüllte die Luft.","The scent of tea filled the air.","B1"),
 ("erfüllen","to fill / fulfil","Der Geruch erfüllte den Raum.","The smell filled the room.","B1"),
 ("winzig","tiny","Er sah eine winzige Tür in einem alten Baum.","He saw a tiny door in an old tree.","B1"),
 ("der Schmuck","jewellery","Drinnen war kein Gold oder Schmuck.","Inside there was no gold or jewellery.","B1"),
 ("der Schatz","treasure","Der Schatz ist deine Güte.","The treasure is your kindness.","B1"),
 ("die Güte","kindness / goodness","Der Schatz ist deine Güte.","The treasure is your kindness.","B1"),
 ("örtlich","local","Er spielte auf dem örtlichen Platz.","He played on the local field.","B1"),
 ("schießen","to shoot / kick","Er schoss den Ball hart.","He kicked the ball hard.","B1"),
 ("bemerken","to notice","Er bemerkte es nicht.","He didn't notice it.","B1"),
 ("erledigen","to get done / run (errands)","Sie wird erst ihre Einkäufe erledigen.","She'll do her shopping first.","B1"),
 ("der Tropfen","drop","Dann fielen viele Tropfen.","Then many drops fell.","B1"),
 ("endlos","endless","Am Meer ist das Wasser blau und endlos.","At the sea the water is blue and endless.","B1"),
 ("woanders","somewhere else","Nächsten Sommer fahren wir woanders hin.","Next summer we'll go somewhere else.","B1"),
 ("hinauf","up (upward)","Mira und Theo stiegen hinauf.","Mira and Theo climbed up.","B1"),
 ("der Honig","honey","Sie träufelten Honig auf den Kuchen.","They drizzled honey on the cake.","B1"),
 ("reinigen","to clean","Eine Maschine, die schmutziges Wasser reinigen konnte.","A machine that could clean dirty water.","B1"),
 ("das Kabel","cable","Sie überprüfte die Kabel und fand das Problem.","She checked the cables and found the problem.","B1"),
 ("versagen","to fail","Wir hätten fast versagt, sagte er.","We almost failed, he said.","B1"),
 ("die Richterin","judge (female)","Die Richterin beobachtete genau.","The judge watched closely.","B1"),
 ("wahr","true / real","Der wahre Preis ist Können.","The real prize is skill.","B1"),
 ("schüchtern","shy","Theo war schüchtern.","Theo was shy.","B1"),
 ("die Königin","queen","Mira wird die Königin spielen.","Mira will play the queen.","B1"),
 ("aufgehen","to rise (sun)","Die Sonne ist noch nicht aufgegangen.","The sun has not risen yet.","B1"),
 ("der Samen","seed","Priya war da mit Schaufeln und Samen.","Priya was there with shovels and seeds.","B1"),
 ("nebenan","next door","Ich wohne nebenan.","I live next door.","B1"),
 ("wochenlang","for weeks","Er übte wochenlang.","He practised for weeks.","B1"),
 ("die Schüssel","bowl","Seine zweite Schüssel bekam Risse.","His second bowl got cracks.","B1"),
 ("der Riss","crack","Die Schüssel bekam Risse.","The bowl got cracks.","B1"),
 ("trocknen","to dry","Er ließ die Vase trocknen.","He let the vase dry.","B1"),
 ("stabil","stable / sturdy","Die neue Vase war stabiler und höher.","The new vase was sturdier and taller.","B1"),
 ("betreten","to enter","Eva betrat die helle Galerie.","Eva entered the bright gallery.","B1"),
 ("hinüber","over (to there)","Dann ging sie hinüber.","Then she went over.","B1"),
 ("die Lektion","lesson","Sie folgte der Lektion online.","She followed the lesson online.","B1"),
 ("hetzen","to rush / hurry","Die Leute hetzen.","The people rush.","B1"),
 ("das Kätzchen","kitten","Darin ist ein schwarzes Kätzchen.","Inside is a black kitten.","B1"),
 ("der Knoblauch","garlic","Sie kauft Tomaten, Knoblauch und Basilikum.","She buys tomatoes, garlic and basil.","B1"),
 ("das Abenteuer","adventure","Das Abenteuer von gestern.","Yesterday's adventure.","B1"),
 ("das Plakat","poster","Am nächsten Tag hängte sie Plakate auf.","The next day she put up posters.","B1"),
 ("die Kerze","candle","Sie zündete eine Kerze an.","She lit a candle.","B1"),
 ("der Stein","stone","Der Regen prasselte wie kleine Steine.","The rain pelted like small stones.","B1"),
 ("die Jahreszeit","season","Die Jahreszeiten wechselten dort oft.","The seasons changed often there.","B1"),
 ("genießen","to enjoy","Sie ging nach Hause und genoss den Schnee.","She went home and enjoyed the snow.","B1"),
 ("das Rätsel","riddle / mystery","Der Winter hatte ein kleines Rätsel mitgebracht.","Winter had brought a little mystery.","B1"),
 ("die Soße","sauce","Sie möchte, dass die Soße perfekt wird.","She wants the sauce to be perfect.","B1"),
 ("stumm","silent / mute","Doch eines Tages blieb Kiki stumm.","But one day Kiki stayed silent.","B1"),
 ("sinken","to sink","Sein Herz sank.","His heart sank.","B1"),
 ("freiwillig","voluntary / voluntarily","Gemeinschaftsgarten, Freiwillige gesucht.","Community garden, volunteers wanted.","B1"),
 # ---------- B2 ----------
 ("nicken","to nod","Der Polizist hört zu und nickt.","The police officer listens and nods.","B2"),
 ("schütteln","to shake","Er schüttelte ihre Hände und sagte: gutes Spiel.","He shook their hands and said: good game.","B2"),
 ("die Krabbe","crab","Die Krabbe hört auf zu kneifen.","The crab stops pinching.","B2"),
 ("die Brieftasche","wallet","Plötzlich lässt der Mann seine Brieftasche fallen.","Suddenly the man drops his wallet.","B2"),
 ("die Karotte","carrot","Tomaten, Karotten und Blumen füllten den Raum.","Tomatoes, carrots and flowers filled the space.","B2"),
 ("wischen","to wipe","Der Mann wischte sich die Augen.","The man wiped his eyes.","B2"),
 ("winken","to wave","Ein Mann winkte uns zu.","A man waved at us.","B2"),
 ("der Luftballon","balloon","Der Raum war mit Luftballons geschmückt.","The room was decorated with balloons.","B2"),
 ("das Sandwich","sandwich","Sie aßen die Sandwiches und lachten.","They ate the sandwiches and laughed.","B2"),
 ("schweigen","to be silent","Sie gehen schweigend nach Hause.","They walk home in silence.","B2"),
 ("unordentlich","messy / untidy","Seine Wohnung ist immer noch unordentlich.","His apartment is still messy.","B2"),
 ("das Lieblingsessen","favourite food","Sie hat ihr Lieblingsessen geteilt.","She shared her favourite food.","B2"),
 ("kauen","to chew","Sie kaut auf dem Hut herum.","It chews on the hat.","B2"),
 ("belebt","busy / lively","Elias geht eine belebte Straße entlang.","Elias walks along a busy street.","B2"),
 ("unerwartet","unexpected","Sie sind zufrieden mit ihrem unerwarteten Essen.","They are happy with their unexpected meal.","B2"),
 ("kneifen","to pinch","Die Krabbe hört auf zu kneifen.","The crab stops pinching.","B2"),
 ("salzig","salty","Der Kuchen war salzig.","The cake was salty.","B2"),
 ("ausgefallen","fancy / unusual","Andere Köche hatten ausgefallene Gerichte.","Other cooks had fancy dishes.","B2"),
 ("sich weiten","to widen","Ihre Augen weiteten sich.","Her eyes widened.","B2"),
 ("der Laden","shop / store","Sie sah eine Gitarre im Schaufenster eines Ladens.","She saw a guitar in a shop window.","B2"),
 ("töpfern","to do pottery","Jetzt macht Elias jedes Wochenende Töpfern.","Now Elias does pottery every weekend.","B2"),
 ("der Schultag","school day","Heute war sein erster Schultag.","Today was his first school day.","B2"),
 ("sich hinsetzen","to sit down","Er hilft ihm, sich hinzusetzen.","He helps him sit down.","B2"),
 ("herüber","over (to here)","Tascha läuft herüber.","Tascha runs over.","B2"),
 ("stöhnen","to groan","Elias stöhnte.","Elias groaned.","B2"),
 ("grinsen","to grin","Mira grinste.","Mira grinned.","B2"),
 ("die Parkbank","park bench","Eva sitzt auf einer grünen Parkbank.","Eva sits on a green park bench.","B2"),
 ("das Spielzeug","toy","Sie hat alte Spielsachen darin gefunden.","She found old toys inside.","B2"),
 ("bedecken","to cover","Papiere bedecken den Tisch.","Papers cover the table.","B2"),
 ("die Tomatensauce","tomato sauce","Ihr Lieblingsgericht ist Pasta mit Tomatensauce.","Her favourite dish is pasta with tomato sauce.","B2"),
 ("das Basilikum","basil","Sie kauft Tomaten, Knoblauch und Basilikum.","She buys tomatoes, garlic and basil.","B2"),
 ("füttern","to feed","Er füttert die Hühner.","He feeds the chickens.","B2"),
 ("starren","to stare","Eine große braune Kuh starrt ihn an.","A big brown cow stares at him.","B2"),
 ("eilen","to hurry / rush","Die Menschen eilen überall hin.","People hurry everywhere.","B2"),
 ("aufheben","to pick up","Elias hilft, sie aufzuheben.","Elias helps to pick them up.","B2"),
 ("das Kochbuch","cookbook","Er hält ein Kochbuch und liest das Rezept.","He holds a cookbook and reads the recipe.","B2"),
 ("das Gewürz","spice","Sie kochen Karotten mit Gewürzen.","They cook carrots with spices.","B2"),
 ("schaukeln","to swing / rock","Eine Frau schaukelt ihren Sohn.","A woman rocks her son.","B2"),
 ("klettern","to climb","Ein Junge klettert die Rutsche hoch.","A boy climbs up the slide.","B2"),
 ("der Tänzer","dancer","Eine Gruppe von Tänzern bewegt sich zu Trommeln.","A group of dancers moves to drums.","B2"),
 ("fegen","to sweep","Er fegt den Boden.","He sweeps the floor.","B2"),
 ("die Muschel","seashell","Sie sucht nach Muscheln.","She looks for seashells.","B2"),
 ("zappeln","to wriggle / squirm","Mira sieht etwas am Wasser zappeln.","Mira sees something wriggling by the water.","B2"),
 ("wiederkommen","to come back","Ich hatte gehofft, du würdest wiederkommen.","I had hoped you would come back.","B2"),
 ("verängstigt","frightened / scared","Er hatte braunes Fell und sah verängstigt aus.","It had brown fur and looked scared.","B2"),
 ("das Halsband","collar","Sie überprüfte sein Halsband.","She checked its collar.","B2"),
 ("die Giraffe","giraffe","Zuerst sahen sie große Giraffen.","First they saw tall giraffes.","B2"),
 ("verspielt","playful","Sie beobachteten verspielte Affen.","They watched playful monkeys.","B2"),
 ("das Gehege","enclosure","Der Ballon landete im Gehege der Löwen.","The balloon landed in the lions' enclosure.","B2"),
 ("beängstigend","frightening / scary","Der Sturm war beängstigend gewesen.","The storm had been frightening.","B2"),
 ("der Einband","cover / binding (book)","Oma hielt ein altes Buch mit rotem Einband.","Grandma held an old book with a red cover.","B2"),
 ("das Fußballspiel","football match","Ravi liebte das Fußballspiel.","Ravi loved the football match.","B2"),
 ("jubeln","to cheer","Ravis Mannschaft jubelte.","Ravi's team cheered.","B2"),
 ("die Nettigkeit","kindness","Für ihre Nettigkeit gab er ihr ein Brot.","For her kindness he gave her a loaf.","B2"),
 ("der Regentropfen","raindrop","Sie spürt einen Regentropfen.","She feels a raindrop.","B2"),
 ("ertönen","to sound / ring out","Ein lauter Alarm ertönte.","A loud alarm sounded.","B2"),
 ("verriegelt","locked / bolted","Eine Stimme sagte: Notfall, Türen verriegelt.","A voice said: emergency, doors locked.","B2"),
 ("stoppen","to stop","Der Alarm stoppte.","The alarm stopped.","B2"),
 ("durchsuchen","to search through","Sie durchsuchten das Haus.","They searched the house.","B2"),
 ("die Geburtstagsfeier","birthday party","Heute war ihre Geburtstagsfeier.","Today was her birthday party.","B2"),
 ("testen","to test","Sie bauten und testeten sie oft.","They built and tested it often.","B2"),
 ("umarmen","to hug","Mira umarmte sie.","Mira hugged her.","B2"),
 ("erwidern","to reply / retort","Wir werden üben, erwiderte Mira.","We will practise, Mira replied.","B2"),
 ("verbrennen","to burn","Theo verbrannte den Reis.","Theo burned the rice.","B2"),
 ("klatschen","to clap / applaud","Das Publikum lachte und klatschte.","The audience laughed and applauded.","B2"),
 ("dunkelblau","dark blue","Der Mantel war dunkelblau und warm.","The coat was dark blue and warm.","B2"),
 ("atmen","to breathe","Er atmet tief durch und geht.","He takes a deep breath and leaves.","B2"),
 ("die Schaufel","shovel / spade","Priya war da mit Schaufeln und Samen.","Priya was there with shovels and seeds.","B2"),
 ("hinzufügen","to add","Diesmal fügten sie ein Schloss hinzu.","This time they added a lock.","B2"),
 ("der Karton","cardboard box","Eva sah überall Kartons.","Eva saw boxes everywhere.","B2"),
 ("zerbrochen","broken / shattered","Am nächsten Morgen fand er die Vase zerbrochen.","The next morning he found the vase broken.","B2"),
 ("die Pfote","paw","Die Katze legte ihre Pfote darauf.","The cat put its paw on it.","B2"),
 ("schimpfen","to scold / grumble","Aber er schimpfte nicht.","But he didn't scold.","B2"),
 ("die Kunstausstellung","art exhibition","Eva betrat die Kunstausstellung.","Eva entered the art exhibition.","B2"),
 ("betreiben","to run / operate","Ich betreibe eine kleine Galerie.","I run a small gallery.","B2"),
 ("klingen","to sound","Die Saiten klangen schlecht.","The strings sounded bad.","B2"),
 ("scherzen","to joke","Du bist jetzt besser als ich, scherzte er.","You're better than me now, he joked.","B2"),
 ("der Tagesablauf","daily routine","Das ist mein Tagesablauf.","This is my daily routine.","B2"),
 ("seufzen","to sigh","Der Mann seufzt.","The man sighs.","B2"),
 ("das Dessert","dessert","Sie bitten den Kellner, ein Dessert zu bringen.","They ask the waiter to bring a dessert.","B2"),
 ("zubereiten","to prepare (food)","Eine Mahlzeit zubereiten.","Preparing a meal.","B2"),
 ("berühren","to touch","Sie berührte seinen Arm.","She touched his arm.","B2"),
 ("reinlegen","to trick / fool","Ihr habt mich reingelegt, sagte sie.","You tricked me, she said.","B2"),
 ("anzünden","to light","Sie zündete eine Kerze an.","She lit a candle.","B2"),
 ("toben","to rage / romp","Sie unterhielten sich, während der Sturm tobte.","They talked while the storm raged.","B2"),
 ("stillstehen","to stand still","Er wollte sprechen, nicht stillstehen.","He wanted to speak, not stand still.","B2"),
 ("der Schneefall","snowfall","Sie wartete auf den ersten Schneefall.","She waited for the first snowfall.","B2"),
 ("die Flocke","flake","Weiße Flocken fielen sanft.","White flakes fell softly.","B2"),
 ("die Türschwelle","doorstep","Eine kleine Schachtel lag auf ihrer Türschwelle.","A small box lay on her doorstep.","B2"),
 ("das Mietshaus","apartment building","Eva lebte in einem kleinen Mietshaus.","Eva lived in a small apartment building.","B2"),
 ("der Donner","thunder","Donner krachte und Regen prasselte.","Thunder crashed and rain pelted down.","B2"),
 ("der Schoß","lap","Sie setzt sich auf seinen Schoß.","It sits down on his lap.","B2"),
 ("hupen","to honk","Autos hupen.","Cars honk.","B2"),
]

data = json.load(open(VJSON, encoding='utf-8'))
# guard: skip any whose word already exists as a headword (safety)
existing = set()
for c in data:
    for e in c['entries']:
        existing.add((e.get('w') or '').strip().lower())

TITLE = {'A1':'FROM SHORT STORIES','A2':'FROM SHORT STORIES','B1':'FROM SHORT STORIES','B2':'AUS KURZGESCHICHTEN'}
cats = {}
added = {'A1':0,'A2':0,'B1':0,'B2':0}
skipped = []
for w,t,de,en,lv in E:
    if w.strip().lower() in existing:
        skipped.append(w); continue
    c = cats.get(lv)
    if not c:
        c = {'id': f'{lv}_FROM_SHORT_STORIES','emoji':'📖','title':TITLE[lv],'level':lv,'entries':[]}
        cats[lv]=c
    c['entries'].append({'w':w,'t':t,'de':de,'en':en})
    added[lv]+=1

ts = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
os.makedirs(os.path.join(proj,'backups'),exist_ok=True)
json.dump(data, open(os.path.join(proj,'backups',f'vocab.pre-storyadd-{ts}.json'),'w',encoding='utf-8'), ensure_ascii=False, indent=2)

for lv in ['A1','A2','B1','B2']:
    if lv in cats: data.append(cats[lv])
json.dump(data, open(VJSON,'w',encoding='utf-8'), ensure_ascii=False, indent=2)

# new per-level totals
tot = {'A1':0,'A2':0,'B1':0,'B2':0}
for c in data:
    if c.get('level') in tot: tot[c['level']] += len(c['entries'])
print('added per level:', added, ' total added:', sum(added.values()))
print('skipped (already existed):', len(skipped), skipped[:10])
print('NEW per-level totals:', tot)
