/* Generate correct conjugations for verbs absent from verbs.json.
   The source docx is unreliable (treats all verbs as weak), so we use it ONLY
   as a candidate word list (verb + meaning + level) and generate every form
   ourselves with a hand-verified strong-verb table + weak-verb rules. */
const fs = require('fs');

/* ── Hand-verified principal parts for base strong/irregular verbs ──
   [pres3 (er/sie), praet (ich/er), partizip2, aux]  */
const STRONG = {
  backen:['backt','backte','gebacken','haben'], // modern weak prät
  befehlen:['befiehlt','befahl','befohlen','haben'],
  beginnen:['beginnt','begann','begonnen','haben'],
  beissen:['beißt','biss','gebissen','haben'],
  biegen:['biegt','bog','gebogen','haben'],
  bieten:['bietet','bot','geboten','haben'],
  binden:['bindet','band','gebunden','haben'],
  bitten:['bittet','bat','gebeten','haben'],
  blasen:['bläst','blies','geblasen','haben'],
  bleiben:['bleibt','blieb','geblieben','sein'],
  braten:['brät','briet','gebraten','haben'],
  brechen:['bricht','brach','gebrochen','haben'],
  brennen:['brennt','brannte','gebrannt','haben'],
  bringen:['bringt','brachte','gebracht','haben'],
  denken:['denkt','dachte','gedacht','haben'],
  duerfen:['darf','durfte','gedurft','haben'],
  empfehlen:['empfiehlt','empfahl','empfohlen','haben'],
  essen:['isst','aß','gegessen','haben'],
  fahren:['fährt','fuhr','gefahren','sein'],
  fallen:['fällt','fiel','gefallen','sein'],
  fangen:['fängt','fing','gefangen','haben'],
  finden:['findet','fand','gefunden','haben'],
  fliegen:['fliegt','flog','geflogen','sein'],
  fliehen:['flieht','floh','geflohen','sein'],
  fliessen:['fließt','floss','geflossen','sein'],
  fressen:['frisst','fraß','gefressen','haben'],
  frieren:['friert','fror','gefroren','haben'],
  geben:['gibt','gab','gegeben','haben'],
  gehen:['geht','ging','gegangen','sein'],
  gelingen:['gelingt','gelang','gelungen','sein'],
  gelten:['gilt','galt','gegolten','haben'],
  geniessen:['genießt','genoss','genossen','haben'],
  geschehen:['geschieht','geschah','geschehen','sein'],
  gewinnen:['gewinnt','gewann','gewonnen','haben'],
  giessen:['gießt','goss','gegossen','haben'],
  graben:['gräbt','grub','gegraben','haben'],
  greifen:['greift','griff','gegriffen','haben'],
  haben:['hat','hatte','gehabt','haben'],
  halten:['hält','hielt','gehalten','haben'],
  hangen:['hängt','hing','gehangen','haben'], // hängen (intrans, strong)
  heben:['hebt','hob','gehoben','haben'],
  heissen:['heißt','hieß','geheißen','haben'],
  helfen:['hilft','half','geholfen','haben'],
  kennen:['kennt','kannte','gekannt','haben'],
  klingen:['klingt','klang','geklungen','haben'],
  kommen:['kommt','kam','gekommen','sein'],
  koennen:['kann','konnte','gekonnt','haben'],
  kriechen:['kriecht','kroch','gekrochen','sein'],
  laden:['lädt','lud','geladen','haben'],
  lassen:['lässt','ließ','gelassen','haben'],
  laufen:['läuft','lief','gelaufen','sein'],
  leihen:['leiht','lieh','geliehen','haben'],
  lesen:['liest','las','gelesen','haben'],
  liegen:['liegt','lag','gelegen','haben'],
  luegen:['lügt','log','gelogen','haben'],
  messen:['misst','maß','gemessen','haben'],
  moegen:['mag','mochte','gemocht','haben'],
  muessen:['muss','musste','gemusst','haben'],
  nehmen:['nimmt','nahm','genommen','haben'],
  nennen:['nennt','nannte','genannt','haben'],
  pfeifen:['pfeift','pfiff','gepfiffen','haben'],
  preisen:['preist','pries','gepriesen','haben'],
  raten:['rät','riet','geraten','haben'],
  reiben:['reibt','rieb','gerieben','haben'],
  reissen:['reißt','riss','gerissen','haben'],
  reiten:['reitet','ritt','geritten','sein'],
  rennen:['rennt','rannte','gerannt','sein'],
  riechen:['riecht','roch','gerochen','haben'],
  rufen:['ruft','rief','gerufen','haben'],
  saugen:['saugt','sog','gesogen','haben'],
  schaffen:['schafft','schuf','geschaffen','haben'],
  scheinen:['scheint','schien','geschienen','haben'],
  schieben:['schiebt','schob','geschoben','haben'],
  schiessen:['schießt','schoss','geschossen','haben'],
  schlafen:['schläft','schlief','geschlafen','haben'],
  schlagen:['schlägt','schlug','geschlagen','haben'],
  schliessen:['schließt','schloss','geschlossen','haben'],
  schmelzen:['schmilzt','schmolz','geschmolzen','sein'],
  schneiden:['schneidet','schnitt','geschnitten','haben'],
  schreiben:['schreibt','schrieb','geschrieben','haben'],
  schreien:['schreit','schrie','geschrien','haben'],
  schweigen:['schweigt','schwieg','geschwiegen','haben'],
  schwimmen:['schwimmt','schwamm','geschwommen','sein'],
  sehen:['sieht','sah','gesehen','haben'],
  sein:['ist','war','gewesen','sein'],
  senden:['sendet','sandte','gesandt','haben'],
  singen:['singt','sang','gesungen','haben'],
  sinken:['sinkt','sank','gesunken','sein'],
  sitzen:['sitzt','saß','gesessen','haben'],
  sollen:['soll','sollte','gesollt','haben'],
  sprechen:['spricht','sprach','gesprochen','haben'],
  springen:['springt','sprang','gesprungen','sein'],
  spinnen:['spinnt','
