const fs = require('fs');
const path = require('path');
const DATA = path.join(__dirname, '..', 'public', 'data');

const SPEAKERS_A = [
  [{name:'Max',voice:1},{name:'Lena',voice:2}],
  [{name:'Tom',voice:1},{name:'Anna',voice:2}],
  [{name:'Felix',voice:1},{name:'Sara',voice:2}],
  [{name:'Klaus',voice:1},{name:'Maria',voice:2}],
  [{name:'David',voice:1},{name:'Nina',voice:2}],
  [{name:'Erik',voice:1},{name:'Julia',voice:2}],
  [{name:'Paul',voice:1},{name:'Lisa',voice:2}],
  [{name:'Hans',voice:1},{name:'Emma',voice:2}],
];
function spk(i){ return SPEAKERS_A[i % SPEAKERS_A.length]; }
function mk(sp,lines){ return { speakers:sp, lines:lines.map((l,i)=>({speaker:sp[i%2].name,side:i%2===0?'left':'right',de:l[0],en:l[1]}))}; }

// A1 conversations CONV021–CONV100
const a1 = [
  {id:'CONV021',level:'A1',title:'Im Café',description:'Zwei Freunde treffen sich im Café.',...mk(spk(0),[
    ['Hallo! Schön, dich zu sehen. Was möchtest du trinken?','Hello! Nice to see you. What would you like to drink?'],
    ['Ich nehme einen Kaffee, bitte. Und du?','I will have a coffee, please. And you?'],
    ['Ich möchte einen Tee mit Milch.','I would like a tea with milk.'],
    ['Möchtest du auch etwas essen?','Would you also like something to eat?'],
    ['Ja, ich nehme ein Stück Kuchen. Der Apfelkuchen sieht lecker aus.','Yes, I will have a piece of cake. The apple cake looks delicious.'],
    ['Gute Wahl! Die Kuchen hier sind immer frisch.','Good choice! The cakes here are always fresh.'],
    ['Super. Ich komme gerne hierher.','Great. I like coming here.'],
  ])},
  {id:'CONV022',level:'A1',title:'Im Restaurant',description:'Eine Familie bestellt im Restaurant.',...mk(spk(1),[
    ['Guten Abend! Haben Sie reserviert?','Good evening! Do you have a reservation?'],
    ['Ja, auf den Namen Müller. Für zwei Personen.','Yes, under the name Müller. For two people.'],
    ['Sehr schön. Hier ist Ihre Speisekarte.','Very good. Here is your menu.'],
    ['Danke. Ich nehme die Suppe und das Schnitzel.','Thank you. I will have the soup and the schnitzel.'],
    ['Und zu trinken?','And to drink?'],
    ['Ein Glas Wasser, bitte.','A glass of water, please.'],
    ['Gerne. Das Essen kommt gleich.','Of course. The food will come shortly.'],
  ])},
  {id:'CONV023',level:'A1',title:'Am Bahnhof',description:'Eine Person kauft eine Fahrkarte.',...mk(spk(2),[
    ['Guten Tag! Ich möchte eine Fahrkarte nach München.','Good day! I would like a ticket to Munich.'],
    ['Einfach oder hin und zurück?','One way or return?'],
    ['Hin und zurück, bitte. Für morgen.','Return, please. For tomorrow.'],
    ['Erster oder zweiter Klasse?','First or second class?'],
    ['Zweiter Klasse, bitte. Was kostet das?','Second class, please. How much does that cost?'],
    ['Das kostet 49 Euro.','That costs 49 euros.'],
    ['Gut. Ich zahle mit Karte.','Good. I will pay by card.'],
  ])},
  {id:'CONV024',level:'A1',title:'Im Bus',description:'Zwei Personen sprechen im Bus.',...mk(spk(3),[
    ['Entschuldigung, fährt dieser Bus zum Marktplatz?','Excuse me, does this bus go to the market square?'],
    ['Ja, das tut er. In etwa zehn Minuten sind wir dort.','Yes, it does. We will be there in about ten minutes.'],
    ['Danke! Muss ich umsteigen?','Thank you! Do I need to change?'],
    ['Nein, dieser Bus fährt direkt dorthin.','No, this bus goes there directly.'],
    ['Super. Das ist mein erster Tag in der Stadt.','Great. This is my first day in the city.'],
    ['Willkommen! Die Stadt ist sehr schön.','Welcome! The city is very beautiful.'],
    ['Danke. Ich freue mich schon darauf.','Thank you. I am already looking forward to it.'],
  ])},
  {id:'CONV025',level:'A1',title:'Beim Arzt',description:'Ein Patient spricht mit dem Arzt.',...mk(spk(4),[
    ['Guten Morgen. Was fehlt Ihnen?','Good morning. What is wrong with you?'],
    ['Ich habe Kopfschmerzen und Fieber seit gestern.','I have a headache and fever since yesterday.'],
    ['Wie hoch ist das Fieber?','How high is the fever?'],
    ['Etwa 38,5 Grad.','About 38.5 degrees.'],
    ['Ich schaue kurz nach. Öffnen Sie bitte den Mund.','Let me take a quick look. Please open your mouth.'],
    ['Der Hals ist etwas rot. Sie brauchen Ruhe und viel Wasser.','Your throat is a bit red. You need rest and lots of water.'],
    ['Brauche ich Medikamente?','Do I need medication?'],
    ['Ja, ich gebe Ihnen ein Rezept.','Yes, I will give you a prescription.'],
  ])},
  {id:'CONV026',level:'A1',title:'Auf dem Markt',description:'Eine Kundin kauft Gemüse auf dem Markt.',...mk(spk(5),[
    ['Guten Morgen! Was hätten Sie gerne?','Good morning! What would you like?'],
    ['Ich möchte ein Kilo Tomaten und eine Gurke.','I would like a kilogram of tomatoes and a cucumber.'],
    ['Sehr frisch heute! Die Tomaten kosten 2 Euro das Kilo.','Very fresh today! The tomatoes cost 2 euros per kilogram.'],
    ['Und die Gurken?','And the cucumbers?'],
    ['80 Cent das Stück.','80 cents each.'],
    ['Gut. Ich nehme auch noch zwei Äpfel.','Good. I will also take two apples.'],
    ['Das macht zusammen 3,60 Euro.','That comes to 3.60 euros in total.'],
  ])},
  {id:'CONV027',level:'A1',title:'Im Hotel',description:'Ein Gast checkt im Hotel ein.',...mk(spk(6),[
    ['Guten Abend. Ich habe eine Reservierung. Mein Name ist Schmidt.','Good evening. I have a reservation. My name is Schmidt.'],
    ['Einen Moment, bitte. Ja, Zimmer 204 für zwei Nächte.','One moment, please. Yes, room 204 for two nights.'],
    ['Richtig. Ist das Frühstück inklusive?','Correct. Is breakfast included?'],
    ['Ja, das Frühstück ist von 7 bis 10 Uhr.','Yes, breakfast is from 7 to 10 o\'clock.'],
    ['Sehr schön. Gibt es WLAN im Zimmer?','Very good. Is there Wi-Fi in the room?'],
    ['Ja, das Passwort ist auf der Karte. Hier ist Ihr Schlüssel.','Yes, the password is on the card. Here is your key.'],
    ['Danke schön. Gute Nacht!','Thank you very much. Good night!'],
  ])},
  {id:'CONV028',level:'A1',title:'Im Kino',description:'Zwei Freunde kaufen Kinokarten.',...mk(spk(7),[
    ['Welchen Film möchtest du sehen?','Which film would you like to see?'],
    ['Ich möchte den neuen Animationsfilm sehen. Um wie viel Uhr beginnt er?','I would like to see the new animated film. What time does it start?'],
    ['Um 19 Uhr und um 21 Uhr.','At 7 pm and at 9 pm.'],
    ['Dann nehmen wir die 19-Uhr-Vorstellung.','Then let\'s take the 7 pm showing.'],
    ['Zwei Karten, bitte. Was kostet das?','Two tickets, please. How much does that cost?'],
    ['Das macht 18 Euro zusammen.','That comes to 18 euros in total.'],
    ['Super! Möchtest du auch Popcorn?','Great! Would you also like popcorn?'],
  ])},
  {id:'CONV029',level:'A1',title:'Im Park',description:'Eine Mutter spricht mit ihrer Tochter im Park.',...mk(spk(0),[
    ['Das Wetter ist heute so schön! Spielst du gerne draußen?','The weather is so nice today! Do you like playing outside?'],
    ['Ja, Mama! Ich spiele am liebsten auf der Schaukel.','Yes, Mum! I like playing on the swing most.'],
    ['Und mit deinen Freunden? Kommt Lisa auch heute?','And with your friends? Is Lisa coming today too?'],
    ['Ja! Lisa und Tom kommen um drei Uhr.','Yes! Lisa and Tom are coming at three o\'clock.'],
    ['Dann haben wir noch Zeit. Möchtest du ein Eis?','Then we still have time. Would you like an ice cream?'],
    ['Ja bitte! Ich möchte Schokoladeneis.','Yes please! I would like chocolate ice cream.'],
    ['Gut. Dort ist ein Eiswagen.','Good. There is an ice cream van over there.'],
  ])},
  {id:'CONV030',level:'A1',title:'Am Telefon',description:'Zwei Bekannte sprechen am Telefon.',...mk(spk(1),[
    ['Hallo Tom! Wie geht es dir?','Hello Tom! How are you?'],
    ['Hallo Anna! Danke, gut. Und dir?','Hello Anna! Thanks, good. And you?'],
    ['Auch gut. Hast du heute Abend Zeit?','Also good. Do you have time this evening?'],
    ['Ja, ich bin frei. Was möchtest du machen?','Yes, I am free. What would you like to do?'],
    ['Wir könnten ins Kino gehen oder zu Hause kochen.','We could go to the cinema or cook at home.'],
    ['Ich koche lieber. Ich mache Pasta!','I prefer cooking. I will make pasta!'],
    ['Super! Ich bringe den Salat mit. Bis dann!','Great! I will bring the salad. See you then!'],
  ])},
  {id:'CONV031',level:'A1',title:'In der Schule',description:'Ein Schüler spricht mit seinem Lehrer.',...mk(spk(2),[
    ['Guten Morgen, Herr Müller. Darf ich etwas fragen?','Good morning, Mr Müller. May I ask something?'],
    ['Natürlich! Was möchtest du wissen?','Of course! What would you like to know?'],
    ['Ich verstehe die Hausaufgaben nicht. Können Sie mir helfen?','I do not understand the homework. Can you help me?'],
    ['Zeig mir mal. Ah, das ist Aufgabe vier. Das ist ein bisschen schwierig.','Show me. Ah, that is exercise four. That is a bit difficult.'],
    ['Ja, ich weiß nicht, wie ich anfangen soll.','Yes, I do not know how to start.'],
    ['Kein Problem. Fangen wir zusammen an.','No problem. Let\'s start together.'],
    ['Danke, Herr Müller. Das ist sehr nett von Ihnen.','Thank you, Mr Müller. That is very kind of you.'],
  ])},
  {id:'CONV032',level:'A1',title:'Beim Bäcker',description:'Eine Kundin kauft Brot beim Bäcker.',...mk(spk(3),[
    ['Guten Morgen! Was darf es sein?','Good morning! What can I get you?'],
    ['Ich möchte ein Vollkornbrot und vier Brötchen, bitte.','I would like a wholemeal loaf and four rolls, please.'],
    ['Frisch vom Ofen! Möchten Sie auch etwas Süßes?','Fresh from the oven! Would you also like something sweet?'],
    ['Ja, zwei Croissants, bitte.','Yes, two croissants, please.'],
    ['Das macht 4,80 Euro.','That comes to 4.80 euros.'],
    ['Hier sind fünf Euro.','Here are five euros.'],
    ['Und 20 Cent zurück. Einen schönen Tag!','And 20 cents change. Have a nice day!'],
  ])},
  {id:'CONV033',level:'A1',title:'Im Sportverein',description:'Ein neues Mitglied kommt zum Sportverein.',...mk(spk(4),[
    ['Guten Tag! Ich möchte Mitglied werden. Welche Sportarten bieten Sie an?','Good day! I would like to become a member. What sports do you offer?'],
    ['Wir haben Fußball, Tennis, Schwimmen und Yoga.','We have football, tennis, swimming and yoga.'],
    ['Super! Ich spiele gerne Tennis. Wann sind die Kurse?','Great! I like playing tennis. When are the courses?'],
    ['Tennis ist dienstags und donnerstags, von 18 bis 20 Uhr.','Tennis is on Tuesdays and Thursdays, from 6 to 8 pm.'],
    ['Was kostet die Mitgliedschaft?','How much does membership cost?'],
    ['20 Euro pro Monat. Das erste Training ist kostenlos.','20 euros per month. The first training session is free.'],
    ['Perfekt! Ich melde mich an.','Perfect! I will sign up.'],
  ])},
  {id:'CONV034',level:'A1',title:'Beim Friseur',description:'Eine Kundin geht zum Friseur.',...mk(spk(5),[
    ['Guten Tag! Haben Sie einen Termin?','Good day! Do you have an appointment?'],
    ['Ja, um 14 Uhr. Mein Name ist Weber.','Yes, at 2 pm. My name is Weber.'],
    ['Perfekt. Was darf ich für Sie tun?','Perfect. What can I do for you?'],
    ['Ich möchte die Haare schneiden und färben lassen.','I would like my hair cut and coloured.'],
    ['Welche Farbe möchten Sie?','What colour would you like?'],
    ['Dunkelbraun, bitte. Nicht zu kurz.','Dark brown, please. Not too short.'],
    ['Sehr schön. Das dauert etwa eine Stunde.','Very nice. That will take about an hour.'],
  ])},
  {id:'CONV035',level:'A1',title:'An der Kasse',description:'Ein Kunde zahlt an der Supermarktkasse.',...mk(spk(6),[
    ['Haben Sie eine Kundenkarte?','Do you have a loyalty card?'],
    ['Nein, leider nicht. Kann ich mit Karte zahlen?','No, unfortunately not. Can I pay by card?'],
    ['Natürlich. Das macht 23,40 Euro.','Of course. That comes to 23.40 euros.'],
    ['Hier ist meine Karte.','Here is my card.'],
    ['Bitte geben Sie Ihre PIN ein.','Please enter your PIN.'],
    ['Danke. Brauche ich noch eine Tüte?','Thank you. Do I also need a bag?'],
    ['Ja bitte. Die Tüten kosten 20 Cent.','Yes please. The bags cost 20 cents.'],
  ])},
  {id:'CONV036',level:'A1',title:'Am Flughafen',description:'Eine Reisende fragt am Flughafen nach.',...mk(spk(7),[
    ['Entschuldigung, wo ist der Gate B7?','Excuse me, where is Gate B7?'],
    ['Gehen Sie geradeaus und dann links. Es ist nicht weit.','Go straight ahead and then left. It is not far.'],
    ['Danke! Wann beginnt das Boarding?','Thank you! When does boarding start?'],
    ['In etwa zwanzig Minuten.','In about twenty minutes.'],
    ['Und wie lange dauert der Flug nach London?','And how long does the flight to London take?'],
    ['Etwa zwei Stunden.','About two hours.'],
    ['Perfekt. Danke für Ihre Hilfe!','Perfect. Thank you for your help!'],
  ])},
  {id:'CONV037',level:'A1',title:'Im Schwimmbad',description:'Zwei Kinder sprechen im Schwimmbad.',...mk(spk(0),[
    ['Kannst du gut schwimmen?','Can you swim well?'],
    ['Ja! Ich schwimme seit drei Jahren. Und du?','Yes! I have been swimming for three years. And you?'],
    ['Ich lerne gerade. Ich kann schon 25 Meter schwimmen.','I am learning at the moment. I can already swim 25 metres.'],
    ['Super! Kannst du auch tauchen?','Great! Can you also dive?'],
    ['Nein, noch nicht. Das ist schwierig.','No, not yet. That is difficult.'],
    ['Ich zeige dir, wie es geht. Schau her!','I will show you how it is done. Watch!'],
    ['Wow, das war toll! Danke!','Wow, that was great! Thank you!'],
  ])},
  {id:'CONV038',level:'A1',title:'Beim Zahnarzt',description:'Ein Patient ist beim Zahnarzt.',...mk(spk(1),[
    ['Guten Morgen. Ich habe um 10 Uhr einen Termin.','Good morning. I have an appointment at 10 o\'clock.'],
    ['Ihr Name bitte?','Your name please?'],
    ['Mein Name ist Fischer. Ich habe Zahnschmerzen.','My name is Fischer. I have toothache.'],
    ['Bitte setzen Sie sich. Der Doktor kommt gleich.','Please sit down. The doctor will come shortly.'],
    ['Öffnen Sie bitte den Mund. Welcher Zahn schmerzt?','Please open your mouth. Which tooth hurts?'],
    ['Der hintere Zahn rechts oben.','The back tooth, top right.'],
    ['Ich sehe das Problem. Sie brauchen eine kleine Füllung.','I can see the problem. You need a small filling.'],
  ])},
  {id:'CONV039',level:'A1',title:'Im Museum',description:'Eine Besucherin fragt im Museum nach.',...mk(spk(2),[
    ['Guten Tag! Was kostet der Eintritt?','Good day! How much is the entry fee?'],
    ['Erwachsene zahlen 8 Euro, Kinder bis 14 Jahre zahlen nichts.','Adults pay 8 euros, children up to 14 years are free.'],
    ['Gut. Ich möchte eine Karte. Gibt es auch Führungen?','Good. I would like one ticket. Are there also guided tours?'],
    ['Ja, die nächste Führung beginnt um 14 Uhr.','Yes, the next guided tour starts at 2 pm.'],
    ['Wie lange dauert sie?','How long does it take?'],
    ['Etwa eine Stunde. Die Führung ist auf Deutsch und Englisch.','About one hour. The tour is in German and English.'],
    ['Perfekt! Ich nehme teil.','Perfect! I will take part.'],
  ])},
  {id:'CONV040',level:'A1',title:'Im Zoo',description:'Eine Familie besucht den Zoo.',...mk(spk(3),[
    ['Schau mal! Da sind die Elefanten!','Look! There are the elephants!'],
    ['Wow! Die sind so groß! Und was essen Elefanten?','Wow! They are so big! And what do elephants eat?'],
    ['Elefanten essen Gras, Früchte und Blätter.','Elephants eat grass, fruit and leaves.'],
    ['Können wir auch die Affen sehen?','Can we also see the monkeys?'],
    ['Ja, das Affenhaus ist gleich dort drüben.','Yes, the monkey house is right over there.'],
    ['Und die Giraffen? Ich liebe Giraffen!','And the giraffes? I love giraffes!'],
    ['Die sind am Ende des Weges. Komm, wir gehen!','They are at the end of the path. Come, let\'s go!'],
  ])},
  {id:'CONV041',level:'A1',title:'In der Bibliothek',description:'Ein Schüler sucht ein Buch in der Bibliothek.',...mk(spk(4),[
    ['Guten Tag! Ich suche ein Buch über die Französische Revolution.','Good day! I am looking for a book about the French Revolution.'],
    ['Das ist in der Geschichtsabteilung, Regal 12.','That is in the history section, shelf 12.'],
    ['Danke. Kann ich die Bücher mit nach Hause nehmen?','Thank you. Can I take the books home?'],
    ['Ja, mit Ihrem Bibliotheksausweis. Haben Sie einen?','Yes, with your library card. Do you have one?'],
    ['Nein, noch nicht. Wie bekomme ich einen?','No, not yet. How do I get one?'],
    ['Füllen Sie bitte dieses Formular aus. Dann dauert es nur fünf Minuten.','Please fill in this form. Then it will only take five minutes.'],
    ['Sehr gut! Danke für Ihre Hilfe.','Very good! Thank you for your help.'],
  ])},
  {id:'CONV042',level:'A1',title:'Am Strand',description:'Zwei Urlauber sprechen am Strand.',...mk(spk(5),[
    ['Das Wasser ist heute sehr warm!','The water is very warm today!'],
    ['Ja, perfekt zum Schwimmen. Bist du oft am Strand?','Yes, perfect for swimming. Do you come to the beach often?'],
    ['Nur im Sommer. Wir machen jeden Jahr Urlaub hier.','Only in summer. We go on holiday here every year.'],
    ['Das klingt schön. Woher kommst du?','That sounds nice. Where are you from?'],
    ['Ich komme aus Frankfurt. Und du?','I am from Frankfurt. And you?'],
    ['Ich bin aus München. Wir sind zum ersten Mal hier.','I am from Munich. We are here for the first time.'],
    ['Dann willkommen! Der Strand hier ist wirklich wunderschön.','Welcome then! The beach here is truly wonderful.'],
  ])},
  {id:'CONV043',level:'A1',title:'Im Taxi',description:'Ein Fahrgast fährt mit dem Taxi.',...mk(spk(6),[
    ['Guten Abend! Wohin möchten Sie?','Good evening! Where would you like to go?'],
    ['Zum Hauptbahnhof, bitte. Und schnell, ich habe es eilig.','To the main station, please. And quickly, I am in a hurry.'],
    ['Kein Problem. Ihr Zug fährt um wie viel Uhr?','No problem. What time does your train leave?'],
    ['Um 20:30 Uhr. Es ist jetzt 20:00 Uhr.','At 8:30 pm. It is 8:00 pm now.'],
    ['Das schaffen wir. Es ist nicht viel Verkehr.','We will make it. There is not much traffic.'],
    ['Was kostet die Fahrt ungefähr?','How much does the journey cost approximately?'],
    ['Etwa 12 Euro. Wir sind in zehn Minuten da.','About 12 euros. We will be there in ten minutes.'],
  ])},
  {id:'CONV044',level:'A1',title:'In der Post',description:'Eine Kundin schickt ein Paket.',...mk(spk(7),[
    ['Guten Tag! Ich möchte dieses Paket nach Spanien schicken.','Good day! I would like to send this parcel to Spain.'],
    ['Wie schwer ist das Paket?','How heavy is the parcel?'],
    ['Etwa zwei Kilogramm.','About two kilograms.'],
    ['Möchten Sie Standardversand oder Express?','Would you like standard delivery or express?'],
    ['Standard reicht. Wie lange dauert das?','Standard is fine. How long does that take?'],
    ['Etwa fünf bis sieben Werktage.','About five to seven working days.'],
    ['Das kostet 12 Euro. Brauchen Sie eine Quittung?','That costs 12 euros. Do you need a receipt?'],
  ])},
  {id:'CONV045',level:'A1',title:'Im Kaufhaus',description:'Eine Frau sucht ein Geschenk im Kaufhaus.',...mk(spk(0),[
    ['Entschuldigung, ich suche ein Geschenk für meine Mutter.','Excuse me, I am looking for a gift for my mother.'],
    ['Was interessiert Ihre Mutter? Bücher, Parfüm, Kleidung?','What is your mother interested in? Books, perfume, clothing?'],
    ['Sie liest gerne. Haben Sie aktuelle Romane?','She likes reading. Do you have current novels?'],
    ['Ja, die Buchhandlung ist im dritten Stock.','Yes, the bookshop is on the third floor.'],
    ['Danke! Haben Sie auch Parfüm im Angebot?','Thank you! Do you also have perfume on offer?'],
    ['Ja, die Kosmetikabteilung ist rechts von Ihnen.','Yes, the cosmetics department is to your right.'],
    ['Wunderbar. Ich schaue mir beides an.','Wonderful. I will look at both.'],
  ])},
  {id:'CONV046',level:'A1',title:'Im Fitnessstudio',description:'Ein neues Mitglied meldet sich im Fitnessstudio an.',...mk(spk(1),[
    ['Guten Tag! Ich möchte Mitglied werden.','Good day! I would like to become a member.'],
    ['Willkommen! Haben Sie schon Sport gemacht?','Welcome! Have you done sport before?'],
    ['Ja, ich jogge gerne. Aber ich möchte auch Kraft trainieren.','Yes, I like jogging. But I would also like to do strength training.'],
    ['Super. Wir haben Kurse für Anfänger und für Fortgeschrittene.','Great. We have courses for beginners and advanced.'],
    ['Was ist im Mitgliedsbeitrag enthalten?','What is included in the membership fee?'],
    ['Alle Geräte, das Schwimmbad und zwei Kurse pro Woche.','All equipment, the swimming pool and two courses per week.'],
    ['Das klingt gut. Was kostet das pro Monat?','That sounds good. How much does that cost per month?'],
  ])},
  {id:'CONV047',level:'A1',title:'In der Mensa',description:'Zwei Studenten essen in der Mensa.',...mk(spk(2),[
    ['Was nimmst du heute?','What are you having today?'],
    ['Ich nehme das Tagesgericht. Es gibt Hähnchen mit Reis.','I am having the daily special. There is chicken with rice.'],
    ['Klingt lecker! Ich nehme die Suppe und einen Salat.','Sounds delicious! I am having the soup and a salad.'],
    ['Die Mensa ist heute sehr voll.','The canteen is very full today.'],
    ['Ja, alle haben heute eine Pause zur gleichen Zeit.','Yes, everyone has a break at the same time today.'],
    ['Wollen wir draußen sitzen? Das Wetter ist schön.','Shall we sit outside? The weather is nice.'],
    ['Gute Idee! Komm, wir nehmen unsere Tabletts.','Good idea! Come, let\'s take our trays.'],
  ])},
  {id:'CONV048',level:'A1',title:'Beim Geburtstag',description:'Freunde feiern einen Geburtstag.',...mk(spk(3),[
    ['Herzlichen Glückwunsch zum Geburtstag!','Happy birthday!'],
    ['Danke! Ich bin so froh, dass ihr alle gekommen seid.','Thank you! I am so glad that you all came.'],
    ['Hier ist ein kleines Geschenk für dich.','Here is a small gift for you.'],
    ['Oh, wie nett! Darf ich es aufmachen?','Oh, how kind! May I open it?'],
    ['Natürlich! Ich hoffe, es gefällt dir.','Of course! I hope you like it.'],
    ['Es ist wunderschön! Vielen Dank! Möchtet ihr Kuchen?','It is beautiful! Thank you very much! Would you like cake?'],
    ['Ja bitte! Dein Kuchen ist immer der beste.','Yes please! Your cake is always the best.'],
  ])},
  {id:'CONV049',level:'A1',title:'Im Garten',description:'Nachbarn sprechen über den Garten.',...mk(spk(4),[
    ['Guten Morgen! Ihr Garten sieht wunderschön aus.','Good morning! Your garden looks beautiful.'],
    ['Danke! Ich arbeite jeden Tag daran. Haben Sie auch einen Garten?','Thank you! I work on it every day. Do you also have a garden?'],
    ['Ja, aber meiner ist nicht so groß. Was pflanzen Sie alles?','Yes, but mine is not as large. What do you plant?'],
    ['Ich habe Tomaten, Kräuter und viele Blumen.','I have tomatoes, herbs and many flowers.'],
    ['Super! Ich möchte auch Tomaten anpflanzen. Ist es schwierig?','Great! I would also like to grow tomatoes. Is it difficult?'],
    ['Nein, nicht wirklich. Man braucht nur viel Wasser und Sonne.','No, not really. You just need lots of water and sun.'],
    ['Vielleicht geben Sie mir ein paar Tipps?','Perhaps you can give me a few tips?'],
  ])},
  {id:'CONV050',level:'A1',title:'In der Küche',description:'Zwei Freunde kochen zusammen.',...mk(spk(5),[
    ['Was kochen wir heute Abend?','What are we cooking tonight?'],
    ['Ich möchte Spaghetti mit Tomatensauce machen.','I would like to make spaghetti with tomato sauce.'],
    ['Super! Ich kann den Salat vorbereiten.','Great! I can prepare the salad.'],
    ['Perfekt. Kannst du auch die Zwiebeln schneiden?','Perfect. Can you also chop the onions?'],
    ['Klar! Wie viele Zwiebeln brauchen wir?','Of course! How many onions do we need?'],
    ['Zwei sollten reichen. Die Pasta kocht in zehn Minuten.','Two should be enough. The pasta will cook in ten minutes.'],
    ['Ich decke schon mal den Tisch.','I will set the table already.'],
  ])},
  {id:'CONV051',level:'A1',title:'Am Frühstückstisch',description:'Eine Familie frühstückt zusammen.',...mk(spk(6),[
    ['Guten Morgen! Hast du gut geschlafen?','Good morning! Did you sleep well?'],
    ['Ja, sehr gut. Was gibt es zum Frühstück?','Yes, very well. What is there for breakfast?'],
    ['Brot, Käse, Marmelade und Orangensaft.','Bread, cheese, jam and orange juice.'],
    ['Lecker! Ich mag Marmelade sehr gerne.','Delicious! I really like jam.'],
    ['Möchtest du auch Kaffee oder Tee?','Would you also like coffee or tea?'],
    ['Tee, bitte. Ohne Zucker.','Tea, please. Without sugar.'],
    ['Hier. Guten Appetit!','Here you go. Enjoy your meal!'],
  ])},
  {id:'CONV052',level:'A1',title:'Im Tierheim',description:'Eine Familie besucht das Tierheim.',...mk(spk(7),[
    ['Guten Tag! Wir möchten einen Hund adoptieren.','Good day! We would like to adopt a dog.'],
    ['Herzlich willkommen! Wie groß soll der Hund sein?','Welcome! How big should the dog be?'],
    ['Nicht zu groß. Wir haben eine kleine Wohnung.','Not too big. We have a small flat.'],
    ['Dann zeige ich Ihnen diese drei Hunde. Der kleine ist erst zwei Jahre alt.','Then I will show you these three dogs. The small one is only two years old.'],
    ['Oh, der ist so süß! Wie heißt er?','Oh, he is so cute! What is his name?'],
    ['Er heißt Bello und ist sehr freundlich.','He is called Bello and is very friendly.'],
    ['Wir nehmen ihn! Was müssen wir jetzt tun?','We will take him! What do we need to do now?'],
  ])},
  {id:'CONV053',level:'A1',title:'Im Reisebüro',description:'Ein Paar bucht einen Urlaub im Reisebüro.',...mk(spk(0),[
    ['Guten Tag! Wir möchten einen Urlaub buchen.','Good day! We would like to book a holiday.'],
    ['Wohin möchten Sie reisen?','Where would you like to travel?'],
    ['Wir denken an Spanien oder Italien.','We are thinking of Spain or Italy.'],
    ['Wann möchten Sie reisen und wie lange?','When would you like to travel and for how long?'],
    ['Im Juli, für zwei Wochen.','In July, for two weeks.'],
    ['Haben Sie ein Budget?','Do you have a budget?'],
    ['Etwa 2000 Euro pro Person.','About 2000 euros per person.'],
    ['Ich zeige Ihnen die besten Angebote.','I will show you the best offers.'],
  ])},
  {id:'CONV054',level:'A1',title:'An der Bushaltestelle',description:'Zwei Personen warten auf den Bus.',...mk(spk(1),[
    ['Wissen Sie, wann der nächste Bus kommt?','Do you know when the next bus comes?'],
    ['Laut Fahrplan um 14:15 Uhr. Es ist jetzt 14:05 Uhr.','According to the timetable at 2:15 pm. It is 2:05 pm now.'],
    ['Danke! Fährt dieser Bus in die Stadtmitte?','Thank you! Does this bus go to the city centre?'],
    ['Ja, er hält am Marktplatz und am Rathaus.','Yes, it stops at the market square and the town hall.'],
    ['Perfekt. Das ist genau, wo ich hinmöchte.','Perfect. That is exactly where I want to go.'],
    ['Ich auch. Woher kommen Sie?','Me too. Where are you from?'],
    ['Ich bin neu hier. Ich lerne noch die Stadt kennen.','I am new here. I am still getting to know the city.'],
  ])},
  {id:'CONV055',level:'A1',title:'Beim Picknick',description:'Freunde machen ein Picknick im Park.',...mk(spk(2),[
    ['Das Wetter ist perfekt für ein Picknick!','The weather is perfect for a picnic!'],
    ['Ja! Ich habe Sandwiches und Obst mitgebracht.','Yes! I have brought sandwiches and fruit.'],
    ['Super! Ich habe Limonade und Chips.','Great! I have lemonade and crisps.'],
    ['Setzen wir uns unter den Baum. Dort ist Schatten.','Let\'s sit under the tree. There is shade there.'],
    ['Gute Idee. Ich breite die Decke aus.','Good idea. I will spread the blanket out.'],
    ['Möchtest du ein Sandwich? Ich habe Käse und Schinken.','Would you like a sandwich? I have cheese and ham.'],
    ['Käse, bitte! Danke. Das ist ein schöner Tag.','Cheese, please! Thank you. This is a beautiful day.'],
  ])},
  {id:'CONV056',level:'A1',title:'Im Waschsalon',description:'Zwei Nachbarn sprechen im Waschsalon.',...mk(spk(3),[
    ['Entschuldigung, ist diese Maschine frei?','Excuse me, is this machine free?'],
    ['Ja, die ist frei. Ich bin schon fertig.','Yes, that one is free. I am already finished.'],
    ['Danke! Wie funktioniert das? Ich bin zum ersten Mal hier.','Thank you! How does this work? It is my first time here.'],
    ['Kein Problem. Geben Sie zuerst die Wäsche in die Maschine.','No problem. First put the washing in the machine.'],
    ['Und dann?','And then?'],
    ['Dann wählen Sie das Programm und geben Geld ein. Ein Waschgang kostet 3 Euro.','Then select the programme and put in money. One wash cycle costs 3 euros.'],
    ['Verstanden. Vielen Dank für die Erklärung!','Understood. Thank you very much for the explanation!'],
  ])},
  {id:'CONV057',level:'A1',title:'Beim Optiker',description:'Eine Kundin kauft eine neue Brille.',...mk(spk(4),[
    ['Guten Tag! Ich brauche eine neue Brille. Meine ist kaputt.','Good day! I need new glasses. Mine are broken.'],
    ['Das ist kein Problem. Haben Sie ein Rezept vom Augenarzt?','That is no problem. Do you have a prescription from the ophthalmologist?'],
    ['Ja, hier ist es. Ich sehe ohne Brille sehr schlecht.','Yes, here it is. I see very badly without glasses.'],
    ['Ich sehe. Schauen Sie sich die Fassungen an. Was gefällt Ihnen?','I see. Have a look at the frames. What do you like?'],
    ['Diese schwarze Fassung hier. Wie viel kostet sie?','This black frame here. How much does it cost?'],
    ['89 Euro. Mit Gläsern nach Rezept kostet es insgesamt 189 Euro.','89 euros. With prescription lenses it costs 189 euros in total.'],
    ['Das ist in Ordnung. Ich nehme sie.','That is fine. I will take them.'],
  ])},
  {id:'CONV058',level:'A1',title:'Beim Flohmarkt',description:'Zwei Personen handeln auf dem Flohmarkt.',...mk(spk(5),[
    ['Wie viel kostet dieses Buch?','How much does this book cost?'],
    ['Zwei Euro.','Two euros.'],
    ['Und diese alte Lampe dort?','And that old lamp over there?'],
    ['Die kostet fünf Euro. Sie ist sehr alt und noch in gutem Zustand.','That costs five euros. It is very old and still in good condition.'],
    ['Würden Sie beides für sechs Euro verkaufen?','Would you sell both for six euros?'],
    ['Hmm, für sieben Euro gebe ich sie Ihnen.','Hmm, I will give them to you for seven euros.'],
    ['Einverstanden! Hier sind sieben Euro.','Agreed! Here are seven euros.'],
  ])},
  {id:'CONV059',level:'A1',title:'Am Kiosk',description:'Ein Kind kauft am Kiosk.',...mk(spk(6),[
    ['Hallo! Was möchtest du?','Hello! What would you like?'],
    ['Ich möchte ein Eis und eine Zeitung für meinen Vater.','I would like an ice cream and a newspaper for my father.'],
    ['Welches Eis? Schokolade, Erdbeer oder Vanille?','Which ice cream? Chocolate, strawberry or vanilla?'],
    ['Erdbeer, bitte! Wie viel kostet alles?','Strawberry, please! How much does everything cost?'],
    ['Das Eis kostet 1,50 Euro und die Zeitung 2 Euro.','The ice cream costs 1.50 euros and the newspaper 2 euros.'],
    ['Hier sind vier Euro.','Here are four euros.'],
    ['Und 50 Cent zurück. Genieß dein Eis!','And 50 cents change. Enjoy your ice cream!'],
  ])},
  {id:'CONV060',level:'A1',title:'Im Kindergarten',description:'Eine Mutter bringt ihr Kind in den Kindergarten.',...mk(spk(7),[
    ['Guten Morgen! Leo ist heute etwas müde.','Good morning! Leo is a bit tired today.'],
    ['Kein Problem. Leo, möchtest du malen oder draußen spielen?','No problem. Leo, would you like to paint or play outside?'],
    ['Draußen spielen! Mit dem Ball!','Play outside! With the ball!'],
    ['Super! Deine Freunde sind schon im Garten.','Great! Your friends are already in the garden.'],
    ['Um wie viel Uhr hole ich ihn ab?','What time shall I pick him up?'],
    ['Heute bis 16 Uhr, wegen der Bastelstunde.','Today by 4 pm, because of the craft session.'],
    ['Gut. Bis dann! Tschüss, Leo!','Good. See you then! Bye, Leo!'],
  ])},
  {id:'CONV061',level:'A1',title:'Im Theater',description:'Zwei Freunde nach dem Theater.',...mk(spk(0),[
    ['Das Stück war fantastisch! Wie hat es dir gefallen?','The play was fantastic! How did you like it?'],
    ['Sehr gut! Die Schauspieler waren wirklich toll.','Very good! The actors were really great.'],
    ['Die Hauptdarstellerin war besonders beeindruckend.','The lead actress was especially impressive.'],
    ['Ja! Und das Bühnenbild war so schön.','Yes! And the set was so beautiful.'],
    ['Kommst du nächsten Monat wieder mit?','Are you coming again next month?'],
    ['Sehr gerne! Was wird dann gespielt?','Very gladly! What will be playing then?'],
    ['Ein Musikstück. Ich glaube, du wirst es mögen.','A musical. I think you will like it.'],
  ])},
  {id:'CONV062',level:'A1',title:'Beim Autowaschen',description:'Ein Fahrer wäscht sein Auto.',...mk(spk(1),[
    ['Entschuldigung, wie funktioniert die Autowaschanlage?','Excuse me, how does the car wash work?'],
    ['Sie fahren rein und wählen ein Programm. Welches möchten Sie?','You drive in and choose a programme. Which would you like?'],
    ['Was kostet das günstigste Programm?','How much does the cheapest programme cost?'],
    ['Das Basispaket kostet 8 Euro. Es dauert fünf Minuten.','The basic package costs 8 euros. It takes five minutes.'],
    ['Gut. Ich nehme das. Wo zahle ich?','Good. I will take that. Where do I pay?'],
    ['Am Automat dort vorne. Er akzeptiert Münzen und Karte.','At the machine over there. It accepts coins and card.'],
    ['Danke! Wie gut das Auto jetzt aussehen wird!','Thank you! How good the car will look now!'],
  ])},
  {id:'CONV063',level:'A1',title:'Bei der Hochzeit',description:'Gäste sprechen auf einer Hochzeit.',...mk(spk(2),[
    ['Was für eine wunderschöne Hochzeit!','What a beautiful wedding!'],
    ['Ja! Das Brautpaar sieht so glücklich aus.','Yes! The bride and groom look so happy.'],
    ['Kennen Sie die Familie schon lange?','Have you known the family for a long time?'],
    ['Ja, ich bin ein Schulfreund des Bräutigams.','Yes, I am a school friend of the groom.'],
    ['Wie nett! Und das Essen ist hervorragend.','How nice! And the food is excellent.'],
    ['Ja, die Hochzeitstorte war besonders lecker.','Yes, the wedding cake was especially delicious.'],
    ['Möchten Sie tanzen? Die Musik ist so schön.','Would you like to dance? The music is so beautiful.'],
  ])},
  {id:'CONV064',level:'A1',title:'Auf dem Berg',description:'Zwei Wanderer rasten auf dem Berg.',...mk(spk(3),[
    ['Puh! Das war ein langer Aufstieg. Machst du eine Pause?','Phew! That was a long climb. Are you having a rest?'],
    ['Ja, ich bin müde. Aber die Aussicht ist wunderschön!','Yes, I am tired. But the view is wonderful!'],
    ['Wie hoch sind wir?','How high are we?'],
    ['Etwa 1500 Meter. Der Gipfel ist noch eine Stunde entfernt.','About 1500 metres. The summit is still one hour away.'],
    ['Schaffen wir das noch?','Can we still make it?'],
    ['Ja, natürlich! Trink etwas Wasser und iss einen Energieriegel.','Yes, of course! Drink some water and eat an energy bar.'],
    ['Gut. Dann weiter! Ich will den Gipfel sehen.','Good. Then onwards! I want to see the summit.'],
  ])},
  {id:'CONV065',level:'A1',title:'Im Konzert',description:'Zwei Konzertbesucher unterhalten sich.',...mk(spk(4),[
    ['Bist du auch zum ersten Mal bei diesem Konzert?','Is this also your first time at this concert?'],
    ['Nein, ich war letztes Jahr schon dabei. Es war fantastisch!','No, I was here last year too. It was fantastic!'],
    ['Super! Ich bin sehr gespannt. Wann fängt es an?','Great! I am very excited. When does it start?'],
    ['In zehn Minuten. Die Band ist sehr bekannt.','In ten minutes. The band is very well known.'],
    ['Was für Musik spielen sie?','What kind of music do they play?'],
    ['Rock und Pop. Die Sängerin hat eine tolle Stimme.','Rock and pop. The singer has a wonderful voice.'],
    ['Ich freue mich! Danke für die Info.','I am looking forward to it! Thank you for the information.'],
  ])},
  {id:'CONV066',level:'A1',title:'Beim Camping',description:'Zwei Camper richten ihr Zelt auf.',...mk(spk(5),[
    ['Wir sind da! Dieser Campingplatz ist toll.','We are here! This campsite is great.'],
    ['Ja! Der See ist direkt daneben. Bauen wir zuerst das Zelt auf.','Yes! The lake is right next to it. Let\'s put up the tent first.'],
    ['Wo ist die Anleitung?','Where is the instruction manual?'],
    ['Hier. Zuerst die Stangen durch die Schlaufen ziehen.','Here. First thread the poles through the loops.'],
    ['Und dann?','And then?'],
    ['Dann die Heringe in den Boden stecken und das Seil spannen.','Then put the pegs in the ground and tighten the rope.'],
    ['Fertig! Das war einfacher als gedacht.','Done! That was easier than expected.'],
  ])},
  {id:'CONV067',level:'A1',title:'Im Fundbüro',description:'Eine Person sucht ihre Tasche im Fundbüro.',...mk(spk(6),[
    ['Guten Tag! Ich habe heute meine Tasche verloren.','Good day! I lost my bag today.'],
    ['Wann und wo haben Sie sie verloren?','When and where did you lose it?'],
    ['Im Bus Linie 7, gegen 14 Uhr.','On bus line 7, around 2 pm.'],
    ['Beschreiben Sie die Tasche bitte.','Please describe the bag.'],
    ['Sie ist blau, aus Leder und hat einen langen Riemen.','It is blue, made of leather and has a long strap.'],
    ['Einen Moment... Ja! Hier ist eine blaue Ledertasche.','One moment... Yes! Here is a blue leather bag.'],
    ['Das ist sie! Vielen Dank! Ich bin so erleichtert.','That is it! Thank you very much! I am so relieved.'],
  ])},
  {id:'CONV068',level:'A1',title:'Beim Nachbarn',description:'Nachbarn sprechen an der Tür.',...mk(spk(7),[
    ['Guten Abend! Entschuldigung, haben Sie vielleicht Salz?','Good evening! Excuse me, do you perhaps have any salt?'],
    ['Natürlich! Wie viel brauchen Sie?','Of course! How much do you need?'],
    ['Nur ein bisschen. Ich koche gerade und habe keins mehr.','Just a little. I am cooking and have run out.'],
    ['Hier, nehmen Sie einfach diese kleine Tüte.','Here, just take this small bag.'],
    ['Das ist sehr nett von Ihnen! Ich bringe es morgen zurück.','That is very kind of you! I will bring it back tomorrow.'],
    ['Kein Problem. Kochen Sie etwas Besonderes?','No problem. Are you cooking something special?'],
    ['Ja, ein nigerianisches Gericht. Kommen Sie morgen zum Probieren!','Yes, a Nigerian dish. Come tomorrow to try it!'],
  ])},
  {id:'CONV069',level:'A1',title:'Am Schreibtisch',description:'Ein Schüler und seine Schwester machen Hausaufgaben.',...mk(spk(0),[
    ['Kannst du mir bei Mathe helfen? Ich verstehe das nicht.','Can you help me with maths? I do not understand this.'],
    ['Was ist das Problem? Zeig mal.','What is the problem? Show me.'],
    ['Diese Aufgabe hier: 15 mal 8.','This exercise here: 15 times 8.'],
    ['Okay. 15 mal 8 ist 120. Möchtest du wissen, wie man das rechnet?','Okay. 15 times 8 is 120. Would you like to know how to calculate it?'],
    ['Ja, bitte!','Yes, please!'],
    ['Du rechnest: 10 mal 8 ist 80, und 5 mal 8 ist 40. Zusammen ist das 120.','You calculate: 10 times 8 is 80, and 5 times 8 is 40. Together that is 120.'],
    ['Ah, ich verstehe! Danke, du bist die beste Schwester!','Ah, I understand! Thank you, you are the best sister!'],
  ])},
  {id:'CONV070',level:'A1',title:'Im Wohnzimmer',description:'Eine Familie schaut zusammen fern.',...mk(spk(1),[
    ['Was schauen wir heute Abend?','What are we watching this evening?'],
    ['Es gibt einen Spielfilm um 20 Uhr und eine Dokumentation.','There is a feature film at 8 pm and a documentary.'],
    ['Was ist die Dokumentation über?','What is the documentary about?'],
    ['Über Tiere in Afrika. Sehr interessant.','About animals in Africa. Very interesting.'],
    ['Ich möchte lieber den Spielfilm sehen.','I would prefer to watch the feature film.'],
    ['Ich auch. Was ist das für ein Film?','Me too. What kind of film is it?'],
    ['Eine Komödie. Die sollen sehr lustig sein.','A comedy. They are supposed to be very funny.'],
  ])},
  {id:'CONV071',level:'A1',title:'Beim Abendessen',description:'Eine Familie isst zusammen.',...mk(spk(2),[
    ['Das Essen riecht wunderbar! Was hast du gekocht?','The food smells wonderful! What did you cook?'],
    ['Ich habe Hähnchen mit Kartoffeln und Gemüse gemacht.','I made chicken with potatoes and vegetables.'],
    ['Mein Lieblingsessen! Darf ich schon anfangen?','My favourite food! May I start already?'],
    ['Natürlich! Lass es dir schmecken.','Of course! Enjoy your meal.'],
    ['Mmmh, das ist so lecker! Wie hast du das gemacht?','Mmmh, this is so delicious! How did you make this?'],
    ['Mit frischen Kräutern und ein bisschen Zitrone.','With fresh herbs and a little lemon.'],
    ['Kannst du mir das Rezept geben?','Can you give me the recipe?'],
  ])},
  {id:'CONV072',level:'A1',title:'Im Supermarkt – Spezialwunsch',description:'Ein Kunde fragt nach einem Produkt.',...mk(spk(3),[
    ['Entschuldigung, haben Sie Bio-Tomaten?','Excuse me, do you have organic tomatoes?'],
    ['Ja, die sind in der Bioabteilung, Gang 4.','Yes, they are in the organic section, aisle 4.'],
    ['Danke! Haben Sie auch glutenfreies Brot?','Thank you! Do you also have gluten-free bread?'],
    ['Ja, im gleichen Gang. Links neben dem Biobrot.','Yes, in the same aisle. To the left of the organic bread.'],
    ['Perfekt! Und wo finde ich die Milch?','Perfect! And where do I find the milk?'],
    ['Ganz hinten im Kühlregal.','Right at the back in the cold shelf.'],
    ['Vielen Dank für Ihre Hilfe!','Thank you very much for your help!'],
  ])},
  {id:'CONV073',level:'A1',title:'In der Disco',description:'Zwei Freunde gehen tanzen.',...mk(spk(4),[
    ['Hast du Lust, heute Abend tanzen zu gehen?','Do you feel like going dancing tonight?'],
    ['Ja! Ich liebe tanzen. Wohin möchtest du gehen?','Yes! I love dancing. Where do you want to go?'],
    ['In die neue Disco am Marktplatz.','To the new disco at the market square.'],
    ['Wann fängt es an?','When does it start?'],
    ['Um 21 Uhr. Der Eintritt kostet 10 Euro.','At 9 pm. Entry costs 10 euros.'],
    ['Gut. Ich ziehe mich noch um und dann fahren wir.','Good. I will change and then we will go.'],
    ['Super! Ich hole dich um 20:30 Uhr ab.','Great! I will pick you up at 8:30 pm.'],
  ])},
  {id:'CONV074',level:'A1',title:'Am Telefon – Verabredung',description:'Zwei Freunde verabreden sich.',...mk(spk(5),[
    ['Hallo! Hast du am Samstag Zeit?','Hello! Do you have time on Saturday?'],
    ['Ja, ich bin frei. Was hast du geplant?','Yes, I am free. What have you planned?'],
    ['Ich möchte ins Schwimmbad gehen. Kommst du mit?','I would like to go to the swimming pool. Are you coming along?'],
    ['Sehr gerne! Um wie viel Uhr?','I would love to! What time?'],
    ['Um 10 Uhr? Das Schwimmbad öffnet dann.','At 10 o\'clock? The swimming pool opens then.'],
    ['Perfekt! Treffen wir uns am Eingang?','Perfect! Shall we meet at the entrance?'],
    ['Ja, bis Samstag! Bis dann!','Yes, until Saturday! See you then!'],
  ])},
  {id:'CONV075',level:'A1',title:'Im Aufzug',description:'Zwei Nachbarn treffen sich im Aufzug.',...mk(spk(6),[
    ['Guten Morgen! In welchen Stock fahren Sie?','Good morning! Which floor are you going to?'],
    ['In den vierten, bitte. Danke!','To the fourth, please. Thank you!'],
    ['Das Wetter ist heute schön, oder?','The weather is nice today, isn\'t it?'],
    ['Ja, endlich Sonne nach dem vielen Regen!','Yes, finally sun after all the rain!'],
    ['Machen Sie heute etwas Besonderes?','Are you doing anything special today?'],
    ['Ich gehe einkaufen und dann in den Park.','I am going shopping and then to the park.'],
    ['Schön! Bis später!','Nice! Until later!'],
  ])},
  {id:'CONV076',level:'A1',title:'Beim Sport',description:'Zwei Sportler trainieren zusammen.',...mk(spk(7),[
    ['Wie oft trainierst du pro Woche?','How often do you train per week?'],
    ['Dreimal. Dienstag, Donnerstag und Samstag. Du?','Three times. Tuesday, Thursday and Saturday. You?'],
    ['Ich trainiere viermal. Aber ich bin noch Anfänger.','I train four times. But I am still a beginner.'],
    ['Das macht nichts. Hauptsache, du machst es regelmäßig.','That does not matter. The main thing is that you do it regularly.'],
    ['Hast du Tipps für mich?','Do you have tips for me?'],
    ['Beginne langsam und trink viel Wasser.','Start slowly and drink lots of water.'],
    ['Danke! Ich freue mich auf das Training.','Thank you! I am looking forward to the training.'],
  ])},
  {id:'CONV077',level:'A1',title:'Am See',description:'Eine Familie macht einen Ausflug an den See.',...mk(spk(0),[
    ['Der See ist so schön! Können wir schwimmen?','The lake is so beautiful! Can we swim?'],
    ['Ja, aber passt auf. Das Wasser ist noch etwas kalt.','Yes, but be careful. The water is still a bit cold.'],
    ['Ich gehe trotzdem! Ich bin nicht kälteempfindlich.','I am going anyway! I am not sensitive to cold.'],
    ['Okay, aber bleib in der Nähe.','Okay, but stay close.'],
    ['Können wir nachher ein Lagerfeuer machen?','Can we make a campfire later?'],
    ['Ja, wenn es dunkel wird. Ich habe Würstchen mitgebracht.','Yes, when it gets dark. I brought sausages.'],
    ['Hurra! Das wird ein toller Abend.','Hurray! That will be a great evening.'],
  ])},
  {id:'CONV078',level:'A1',title:'Im Wald',description:'Zwei Freunde machen eine Waldwanderung.',...mk(spk(1),[
    ['Ich liebe es, im Wald zu wandern!','I love hiking in the forest!'],
    ['Ich auch. Die Luft ist so frisch und es ist ruhig.','Me too. The air is so fresh and it is quiet.'],
    ['Hörst du die Vögel? Das ist wunderschön.','Can you hear the birds? That is wonderful.'],
    ['Ja! Ich glaube, das ist ein Specht.','Yes! I think that is a woodpecker.'],
    ['Wie lange wandern wir noch?','How much longer are we hiking?'],
    ['Noch etwa eine Stunde bis zur Hütte.','About another hour to the hut.'],
    ['Perfekt. Ich freue mich auf eine heiße Suppe!','Perfect. I am looking forward to a hot soup!'],
  ])},
  {id:'CONV079',level:'A1',title:'Im Zirkus',description:'Eltern und Kind beim Zirkus.',...mk(spk(2),[
    ['Schau mal! Der Clown ist so lustig!','Look! The clown is so funny!'],
    ['Ja! Und die Akrobaten sind so mutig!','Yes! And the acrobats are so brave!'],
    ['Kannst du sehen, wie die Frau auf dem Seil balanciert?','Can you see how the woman is balancing on the rope?'],
    ['Ja! Das kann ich nicht! Das ist schwierig.','Yes! I cannot do that! That is difficult.'],
    ['Möchtest du auch mal Zirkusartist werden?','Would you also like to become a circus artist?'],
    ['Ja! Ich will jonglieren lernen!','Yes! I want to learn to juggle!'],
    ['Das können wir zu Hause üben. Mit Äpfeln!','We can practise that at home. With apples!'],
  ])},
  {id:'CONV080',level:'A1',title:'Beim Konzert – Karten kaufen',description:'Zwei Freunde kaufen Konzerttickets.',...mk(spk(3),[
    ['Ich habe gehört, dass die Band nächste Woche hier spielt!','I heard that the band is playing here next week!'],
    ['Wirklich? Das ist toll! Haben wir noch Karten?','Really? That is great! Do we still have tickets?'],
    ['Ich schaue online... Ja, es gibt noch Karten!','I am looking online... Yes, there are still tickets!'],
    ['Wie viel kosten sie?','How much do they cost?'],
    ['35 Euro das Stück. Soll ich zwei kaufen?','35 euros each. Shall I buy two?'],
    ['Ja! Unbedingt! Ich zahle dir meinen Anteil zurück.','Yes! Definitely! I will pay you back my share.'],
    ['Okay, ich kaufe sie jetzt. Ich bin so aufgeregt!','Okay, I am buying them now. I am so excited!'],
  ])},
  {id:'CONV081',level:'A1',title:'Am Flughafen – Abholung',description:'Jemand wartet auf einen Freund am Flughafen.',...mk(spk(4),[
    ['Wann landet der Flug aus Lagos?','When does the flight from Lagos land?'],
    ['Laut Anzeige um 15:30 Uhr. Es ist jetzt 15:20 Uhr.','According to the display at 3:30 pm. It is 3:20 pm now.'],
    ['Ich warte schon seit einer Stunde. Ich bin so aufgeregt!','I have been waiting for an hour. I am so excited!'],
    ['Ist das ein Freund oder ein Familienmitglied?','Is it a friend or a family member?'],
    ['Meine Schwester! Sie kommt mich besuchen.','My sister! She is coming to visit me.'],
    ['Wie schön! Wie lange bleibt sie?','How nice! How long is she staying?'],
    ['Zwei Wochen! Ich freue mich so sehr!','Two weeks! I am so happy!'],
  ])},
  {id:'CONV082',level:'A1',title:'Im Supermarkt – Hilfe finden',description:'Eine Kundin sucht Hilfe im Supermarkt.',...mk(spk(5),[
    ['Entschuldigung! Wo finde ich die Gewürze?','Excuse me! Where do I find the spices?'],
    ['Die Gewürze sind in Gang 6, gleich nach der Pasta.','The spices are in aisle 6, right after the pasta.'],
    ['Danke! Haben Sie auch frischen Ingwer?','Thank you! Do you also have fresh ginger?'],
    ['Ja, der ist im Gemüseregal, gleich beim Knoblauch.','Yes, that is in the vegetable aisle, right next to the garlic.'],
    ['Und was ist das Angebot diese Woche?','And what is on offer this week?'],
    ['Olivenöl und Pasta sind im Angebot. 20% Rabatt.','Olive oil and pasta are on offer. 20% discount.'],
    ['Super! Dann nehme ich etwas mehr mit.','Great! Then I will take a bit more.'],
  ])},
  {id:'CONV083',level:'A1',title:'Beim Grillabend',description:'Nachbarn grillen zusammen.',...mk(spk(6),[
    ['Was für ein schöner Abend zum Grillen!','What a beautiful evening for a barbecue!'],
    ['Ja! Das Fleisch ist gleich fertig. Magst du Würstchen oder Hähnchen?','Yes! The meat is nearly ready. Do you like sausages or chicken?'],
    ['Beides, bitte! Ich bin sehr hungrig.','Both, please! I am very hungry.'],
    ['Hier, und hier ist auch noch Salat.','Here, and there is also salad here.'],
    ['Danke! Darf ich noch etwas Brot haben?','Thank you! May I have some more bread?'],
    ['Natürlich! Und was trinkst du?','Of course! And what are you drinking?'],
    ['Ein Mineralwasser, bitte. Es ist so warm heute.','A mineral water, please. It is so warm today.'],
  ])},
  {id:'CONV084',level:'A1',title:'Beim Einkaufen – Kleidung',description:'Eine Frau kauft neue Kleidung.',...mk(spk(7),[
    ['Kann ich Ihnen helfen?','Can I help you?'],
    ['Ja, ich suche ein Sommerkleid in Größe 38.','Yes, I am looking for a summer dress in size 38.'],
    ['Hier haben wir schöne Kleider. Welche Farbe gefällt Ihnen?','Here we have nice dresses. Which colour do you like?'],
    ['Ich mag blaue oder grüne Farben.','I like blue or green colours.'],
    ['Dieses türkisfarbene Kleid ist sehr beliebt.','This turquoise dress is very popular.'],
    ['Es ist schön! Kann ich es anprobieren?','It is beautiful! Can I try it on?'],
    ['Natürlich! Die Umkleidekabinen sind dort hinten.','Of course! The changing rooms are at the back there.'],
  ])},
  {id:'CONV085',level:'A1',title:'Auf dem Spielplatz – Eltern',description:'Zwei Eltern sprechen auf dem Spielplatz.',...mk(spk(0),[
    ['Ihr Kind ist so aktiv! Wie alt ist es?','Your child is so active! How old is it?'],
    ['Er ist vier Jahre alt. Er liebt den Spielplatz.','He is four years old. He loves the playground.'],
    ['Meine Tochter auch. Sie ist fünf. Kommen Sie oft hierher?','My daughter too. She is five. Do you come here often?'],
    ['Ja, fast jeden Tag nach dem Kindergarten.','Yes, almost every day after kindergarten.'],
    ['Das ist schön. Die Kinder brauchen frische Luft.','That is nice. Children need fresh air.'],
    ['Stimmt. Und sie schlafen danach viel besser.','True. And they sleep much better afterwards.'],
    ['Absolut! Sollen unsere Kinder zusammen spielen?','Absolutely! Shall our children play together?'],
  ])},
  {id:'CONV086',level:'A1',title:'Im Café – Kellner',description:'Ein Gast spricht mit dem Kellner.',...mk(spk(1),[
    ['Guten Tag! Darf ich die Karte sehen?','Good day! May I see the menu?'],
    ['Natürlich! Hier ist unsere Tageskarte.','Of course! Here is our daily menu.'],
    ['Was empfehlen Sie heute?','What do you recommend today?'],
    ['Die Quiche Lorraine ist sehr frisch und beliebt.','The Quiche Lorraine is very fresh and popular.'],
    ['Gut, das nehme ich. Und einen Cappuccino dazu.','Good, I will have that. And a cappuccino with it.'],
    ['Gerne. Möchten Sie auch noch Nachtisch?','Of course. Would you also like dessert?'],
    ['Vielleicht nachher. Danke!','Maybe later. Thank you!'],
  ])},
  {id:'CONV087',level:'A1',title:'Im Zug – Mitfahrer',description:'Zwei Reisende sprechen im Zug.',...mk(spk(2),[
    ['Ist dieser Platz frei?','Is this seat free?'],
    ['Ja, bitte nehmen Sie Platz.','Yes, please take a seat.'],
    ['Danke! Wohin fahren Sie?','Thank you! Where are you going?'],
    ['Nach Hamburg. Und Sie?','To Hamburg. And you?'],
    ['Ich fahre nach Köln. Lange Fahrt, oder?','I am going to Cologne. Long journey, isn\'t it?'],
    ['Ja, drei Stunden. Ich lese gerne im Zug.','Yes, three hours. I like reading on the train.'],
    ['Ich schlafe lieber. Angenehme Reise!','I prefer sleeping. Have a pleasant journey!'],
  ])},
  {id:'CONV088',level:'A1',title:'Bei der Hausparty',description:'Gäste sprechen auf einer Hausparty.',...mk(spk(3),[
    ['Hey! Schöne Party! Kennst du viele Leute hier?','Hey! Nice party! Do you know many people here?'],
    ['Ein paar. Ich kenne den Gastgeber aus der Arbeit.','A few. I know the host from work.'],
    ['Ich bin zum ersten Mal hier. Mein Name ist Kevin.','I am here for the first time. My name is Kevin.'],
    ['Hallo Kevin! Ich bin Sandra. Woher kommst du?','Hello Kevin! I am Sandra. Where are you from?'],
    ['Aus Düsseldorf. Ich bin erst seit einem Monat in Berlin.','From Düsseldorf. I have only been in Berlin for a month.'],
    ['Dann willkommen! Berlin ist eine tolle Stadt.','Welcome then! Berlin is a great city.'],
    ['Ja! Ich mag es schon sehr. Was machst du beruflich?','Yes! I already like it a lot. What do you do for work?'],
  ])},
  {id:'CONV089',level:'A1',title:'An der Ampel',description:'Zwei Fußgänger warten an der Ampel.',...mk(spk(4),[
    ['Entschuldigung, wie komme ich zum Stadtpark?','Excuse me, how do I get to the city park?'],
    ['Gehen Sie hier geradeaus bis zur nächsten Kreuzung.','Go straight ahead here to the next crossroads.'],
    ['Und dann?','And then?'],
    ['Dann biegen Sie links ab. Der Park ist auf der rechten Seite.','Then turn left. The park is on the right-hand side.'],
    ['Wie weit ist es?','How far is it?'],
    ['Etwa zehn Minuten zu Fuß.','About ten minutes on foot.'],
    ['Vielen Dank! Das ist sehr hilfreich.','Thank you very much! That is very helpful.'],
  ])},
  {id:'CONV090',level:'A1',title:'In der Tankstelle',description:'Ein Fahrer tankt sein Auto.',...mk(spk(5),[
    ['Guten Tag! Ich möchte volltanken.','Good day! I would like to fill up.'],
    ['Welchen Kraftstoff brauchen Sie? Benzin oder Diesel?','What fuel do you need? Petrol or diesel?'],
    ['Benzin, bitte.','Petrol, please.'],
    ['Zapfsäule Nummer 3 ist frei.','Pump number 3 is free.'],
    ['Danke. Kann ich auch das Öl prüfen lassen?','Thank you. Can I also have the oil checked?'],
    ['Ja, das machen wir gerne. Bitte stellen Sie das Auto dort ab.','Yes, we are happy to do that. Please park the car over there.'],
    ['Super. Das Öl war schon lange nicht geprüft.','Great. The oil has not been checked for a long time.'],
  ])},
  {id:'CONV091',level:'A1',title:'Im Fitnessstudio – Training',description:'Ein Trainer erklärt eine Übung.',...mk(spk(6),[
    ['Können Sie mir zeigen, wie diese Maschine funktioniert?','Can you show me how this machine works?'],
    ['Natürlich! Setzen Sie sich so hin und greifen Sie die Griffe.','Of course! Sit like this and grip the handles.'],
    ['So?','Like this?'],
    ['Fast! Die Arme etwas weiter auseinander.','Almost! The arms a little further apart.'],
    ['Wie viele Wiederholungen soll ich machen?','How many repetitions should I do?'],
    ['Für Anfänger: dreimal zwölf Wiederholungen.','For beginners: three times twelve repetitions.'],
    ['Verstanden. Danke für die Hilfe!','Understood. Thank you for the help!'],
  ])},
  {id:'CONV092',level:'A1',title:'Beim Arzt – Ergebnis',description:'Ein Patient bekommt seine Ergebnisse.',...mk(spk(7),[
    ['Guten Morgen. Ich habe einen Termin, um meine Ergebnisse abzuholen.','Good morning. I have an appointment to collect my results.'],
    ['Ah ja, Herr Bauer. Die Ergebnisse sind gut.','Ah yes, Mr Bauer. The results are good.'],
    ['Das ist eine Erleichterung! Was haben Sie gefunden?','That is a relief! What did you find?'],
    ['Ihr Blutdruck ist normal und die Blutwerte sind in Ordnung.','Your blood pressure is normal and the blood values are fine.'],
    ['Aber ich muss etwas mehr Sport machen, oder?','But I need to do a bit more sport, don\'t I?'],
    ['Ja, dreimal pro Woche wäre ideal. Und weniger Stress.','Yes, three times a week would be ideal. And less stress.'],
    ['Ich werde es versuchen. Danke, Herr Doktor!','I will try. Thank you, Doctor!'],
  ])},
  {id:'CONV093',level:'A1',title:'In der Metzgerei',description:'Ein Kunde kauft Fleisch.',...mk(spk(0),[
    ['Guten Morgen! Was darf es sein?','Good morning! What can I get you?'],
    ['Ich möchte 500 Gramm Hackfleisch und vier Koteletts.','I would like 500 grams of minced meat and four chops.'],
    ['Schwein oder Rind beim Hackfleisch?','Pork or beef for the minced meat?'],
    ['Gemischt, bitte. Und haben Sie auch Bratwürste?','Mixed, please. And do you also have bratwursts?'],
    ['Ja, frisch heute Morgen. Wie viele möchten Sie?','Yes, fresh this morning. How many would you like?'],
    ['Acht Stück, bitte. Ich grille heute Abend.','Eight pieces, please. I am barbecuing tonight.'],
    ['Das klingt gut! Das macht 12,50 Euro.','That sounds good! That comes to 12.50 euros.'],
  ])},
  {id:'CONV094',level:'A1',title:'An der Rezeption – Hotel Problem',description:'Ein Gast hat ein Problem im Hotel.',...mk(spk(1),[
    ['Entschuldigung, es gibt ein Problem mit meinem Zimmer.','Excuse me, there is a problem with my room.'],
    ['Oh! Was ist passiert?','Oh! What happened?'],
    ['Die Heizung funktioniert nicht. Ich friere.','The heating does not work. I am freezing.'],
    ['Das tut mir leid! Ich schicke sofort jemanden.','I am sorry! I will send someone immediately.'],
    ['Wann kommt jemand?','When will someone come?'],
    ['In zehn Minuten. Möchten Sie warten oder sollen Sie ein anderes Zimmer bekommen?','In ten minutes. Would you like to wait or shall you get another room?'],
    ['Ein anderes Zimmer wäre besser, danke.','Another room would be better, thank you.'],
  ])},
  {id:'CONV095',level:'A1',title:'Am Kopierer',description:'Zwei Kollegen am Kopierer.',...mk(spk(2),[
    ['Funktioniert der Kopierer wieder?','Is the photocopier working again?'],
    ['Ja, endlich! Das Papier war alle.','Yes, finally! The paper had run out.'],
    ['Gut. Ich brauche dringend Kopien für das Meeting.','Good. I urgently need copies for the meeting.'],
    ['Wie viele Kopien brauchst du?','How many copies do you need?'],
    ['Zwanzig Stück, beidseitig.','Twenty copies, double-sided.'],
    ['Kein Problem. Ich bin gleich fertig.','No problem. I am done in a moment.'],
    ['Danke! Du rettest mein Leben!','Thank you! You are saving my life!'],
  ])},
  {id:'CONV096',level:'A1',title:'Im Park – Joggen',description:'Zwei Jogger treffen sich im Park.',...mk(spk(3),[
    ['Guten Morgen! Joggst du hier jeden Tag?','Good morning! Do you jog here every day?'],
    ['Fast. Dreimal pro Woche. Du bist neu hier?','Almost. Three times a week. Are you new here?'],
    ['Ja, ich jogge erst seit einem Monat.','Yes, I have only been jogging for a month.'],
    ['Das ist toll! Wie weit läufst du?','That is great! How far do you run?'],
    ['Nur drei Kilometer. Ich bin noch langsam.','Only three kilometres. I am still slow.'],
    ['Das macht nichts. Hauptsache, du machst es.','That does not matter. The main thing is you do it.'],
    ['Danke! Vielleicht laufen wir nächste Woche zusammen.','Thank you! Perhaps we will run together next week.'],
  ])},
  {id:'CONV097',level:'A1',title:'In der Apotheke',description:'Ein Kunde kauft Medizin in der Apotheke.',...mk(spk(4),[
    ['Guten Tag! Haben Sie etwas gegen Erkältung?','Good day! Do you have something for a cold?'],
    ['Ja, ich empfehle diesen Hustensaft und diese Nasentropfen.','Yes, I recommend this cough syrup and these nasal drops.'],
    ['Brauche ich dafür ein Rezept?','Do I need a prescription for that?'],
    ['Nein, das sind freiverkäufliche Mittel.','No, those are over-the-counter medicines.'],
    ['Gut. Was kostet das alles?','Good. How much does all that cost?'],
    ['Der Hustensaft kostet 8 Euro und die Tropfen 6 Euro.','The cough syrup costs 8 euros and the drops 6 euros.'],
    ['Ich nehme beides. Danke für die Beratung!','I will take both. Thank you for the advice!'],
  ])},
  {id:'CONV098',level:'A1',title:'Beim Yogakurs',description:'Zwei Teilnehmer vor dem Yogakurs.',...mk(spk(5),[
    ['Machst du auch das erste Mal Yoga?','Is this also your first time doing yoga?'],
    ['Nein, ich mache es seit zwei Jahren. Und du?','No, I have been doing it for two years. And you?'],
    ['Ich bin Anfängerin. Ist es schwierig?','I am a beginner. Is it difficult?'],
    ['Am Anfang schon etwas. Aber die Lehrerin ist sehr geduldig.','A bit at the beginning. But the teacher is very patient.'],
    ['Das ist gut zu hören. Ich bin sehr unflexibel.','That is good to hear. I am very inflexible.'],
    ['Das ändert sich schnell! Nach einem Monat merkst du schon den Unterschied.','That changes quickly! After a month you already notice the difference.'],
    ['Toll! Ich freue mich auf die Stunde.','Great! I am looking forward to the class.'],
  ])},
  {id:'CONV099',level:'A1',title:'Am Informationsschalter',description:'Ein Tourist fragt nach Sehenswürdigkeiten.',...mk(spk(6),[
    ['Guten Tag! Ich bin Tourist. Was sollte ich in der Stadt sehen?','Good day! I am a tourist. What should I see in the city?'],
    ['Das Rathaus und der Marktplatz sind sehr schön.','The town hall and the market square are very beautiful.'],
    ['Wie weit ist das vom Hotel?','How far is that from the hotel?'],
    ['Etwa zehn Minuten zu Fuß.','About ten minutes on foot.'],
    ['Gibt es auch ein Museum?','Is there also a museum?'],
    ['Ja, das Stadtmuseum ist sehr empfehlenswert. Eintritt frei!','Yes, the city museum is highly recommended. Free entry!'],
    ['Perfekt! Danke für die Informationen.','Perfect! Thank you for the information.'],
  ])},
  {id:'CONV100',level:'A1',title:'Im Jugendclub',description:'Zwei Jugendliche sprechen im Jugendclub.',...mk(spk(7),[
    ['Hallo! Ich bin neu hier. Was macht ihr hier so?','Hello! I am new here. What do you do here?'],
    ['Wir spielen Tischtennis, machen Musik und reden einfach.','We play table tennis, make music and just talk.'],
    ['Cool! Ich spiele gerne Tischtennis. Kann ich mitmachen?','Cool! I like playing table tennis. Can I join?'],
    ['Natürlich! Wir brauchen noch einen Spieler.','Of course! We still need another player.'],
    ['Super! Wie oft kommt ihr hierher?','Great! How often do you come here?'],
    ['Dienstags und freitags nach der Schule.','Tuesdays and Fridays after school.'],
    ['Das passt mir gut! Ich komme nächsten Dienstag wieder.','That suits me well! I will come back next Tuesday.'],
  ])},
];

fs.writeFileSync(path.join(DATA,'convo_a1.json'), JSON.stringify(a1,null,2));
console.log('convo_a1.json:', a1.length, 'conversations');
