/**
 * Stories batch 1 — A1 stories (1–50)
 * Run: node scripts/gen_stories_a1.js
 */
const fs = require('fs');
const OUT = 'C:/Users/ADELEKEOLORUNISOLAO/Desktop/goethe-trainer/public/data/stories_a1.json';

const stories = [
  {id:'S001',num:1,title:'Mein Morgen',titleEn:'My Morning',level:'A1',
   de:'Ich heiße Lena. Jeden Morgen stehe ich um sieben Uhr auf. Ich gehe ins Badezimmer und putze meine Zähne. Dann ziehe ich mich an und gehe in die Küche. Ich trinke einen Kaffee und esse ein Brot mit Butter. Um acht Uhr fahre ich mit dem Bus zur Arbeit. Mein Tag beginnt gut.',
   en:'My name is Lena. Every morning I get up at seven o\'clock. I go to the bathroom and brush my teeth. Then I get dressed and go to the kitchen. I drink a coffee and eat bread with butter. At eight o\'clock I take the bus to work. My day starts well.',
   vocab:[{de:'aufstehen',en:'to get up'},{de:'das Badezimmer',en:'bathroom'},{de:'sich anziehen',en:'to get dressed'},{de:'die Arbeit',en:'work'}]},
  {id:'S002',num:2,title:'Meine Familie',titleEn:'My Family',level:'A1',
   de:'Wir sind eine kleine Familie. Mein Vater heißt Thomas und meine Mutter heißt Anna. Ich habe einen Bruder. Er heißt Max und ist zehn Jahre alt. Wir haben auch einen Hund. Der Hund heißt Bello. Am Wochenende essen wir zusammen. Ich liebe meine Familie.',
   en:'We are a small family. My father is called Thomas and my mother is called Anna. I have a brother. His name is Max and he is ten years old. We also have a dog. The dog is called Bello. On the weekend we eat together. I love my family.',
   vocab:[{de:'die Familie',en:'family'},{de:'der Bruder',en:'brother'},{de:'der Hund',en:'dog'},{de:'zusammen',en:'together'}]},
  {id:'S003',num:3,title:'Im Supermarkt',titleEn:'At the Supermarket',level:'A1',
   de:'Heute gehe ich in den Supermarkt. Ich brauche Milch, Brot und Äpfel. Im Supermarkt nehme ich einen Korb. Die Äpfel sind rot und sehr frisch. An der Kasse bezahle ich mit Karte. Dann gehe ich nach Hause.',
   en:'Today I go to the supermarket. I need milk, bread and apples. In the supermarket I take a basket. The apples are red and very fresh. At the checkout I pay with a card. Then I go home.',
   vocab:[{de:'der Supermarkt',en:'supermarket'},{de:'brauchen',en:'to need'},{de:'die Kasse',en:'checkout'},{de:'bezahlen',en:'to pay'}]},
  {id:'S004',num:4,title:'Mein Hund Bello',titleEn:'My Dog Bello',level:'A1',
   de:'Bello ist mein Hund. Er ist braun und sehr lieb. Jeden Tag gehe ich mit ihm in den Park. Bello läuft schnell und spielt mit einem Ball. Manchmal trifft er andere Hunde. Am Abend schläft er auf seinem Bett.',
   en:'Bello is my dog. He is brown and very sweet. Every day I go with him to the park. Bello runs fast and plays with a ball. Sometimes he meets other dogs. In the evening he sleeps on his bed.',
   vocab:[{de:'der Park',en:'park'},{de:'laufen',en:'to run'},{de:'spielen',en:'to play'},{de:'schlafen',en:'to sleep'}]},
  {id:'S005',num:5,title:'Im Café',titleEn:'At the Café',level:'A1',
   de:'Am Samstag gehe ich mit meiner Freundin in ein Café. Wir setzen uns an einen Tisch am Fenster. Ich bestelle einen Kaffee und ein Stück Kuchen. Meine Freundin trinkt Tee. Wir reden lange und lachen viel.',
   en:'On Saturday I go to a café with my friend. We sit at a table by the window. I order a coffee and a piece of cake. My friend drinks tea. We talk for a long time and laugh a lot.',
   vocab:[{de:'das Café',en:'café'},{de:'bestellen',en:'to order'},{de:'der Kuchen',en:'cake'},{de:'lachen',en:'to laugh'}]},
  {id:'S006',num:6,title:'Ein neuer Tag',titleEn:'A New Day',level:'A1',
   de:'Die Sonne scheint. Es ist Montag. Ich öffne das Fenster und atme tief. Im Garten singen die Vögel. Ich mache mein Bett und gehe in die Küche. Heute habe ich viele Pläne.',
   en:'The sun is shining. It is Monday. I open the window and breathe deeply. In the garden the birds are singing. I make my bed and go to the kitchen. Today I have many plans.',
   vocab:[{de:'die Sonne',en:'sun'},{de:'öffnen',en:'to open'},{de:'der Vogel',en:'bird'},{de:'der Plan',en:'plan'}]},
  {id:'S007',num:7,title:'Mein Lieblingsessen',titleEn:'My Favorite Food',level:'A1',
   de:'Mein Lieblingsessen ist Pizza. Ich esse gern Pizza mit Tomaten und Käse. Manchmal mache ich die Pizza zu Hause. Meine Mutter hilft mir. Wir essen die Pizza im Wohnzimmer und sehen einen Film.',
   en:'My favorite food is pizza. I like to eat pizza with tomatoes and cheese. Sometimes I make the pizza at home. My mother helps me. We eat the pizza in the living room and watch a movie.',
   vocab:[{de:'das Lieblingsessen',en:'favorite food'},{de:'der Käse',en:'cheese'},{de:'helfen',en:'to help'},{de:'der Film',en:'movie'}]},
  {id:'S008',num:8,title:'Die Schule',titleEn:'School',level:'A1',
   de:'Ich heiße Tim und ich bin zwölf Jahre alt. Meine Schule ist nicht weit. Ich gehe zu Fuß. Mein Lieblingsfach ist Mathematik. Nach der Schule mache ich Hausaufgaben und spiele Fußball.',
   en:'My name is Tim and I am twelve years old. My school is not far. I walk there. My favorite subject is mathematics. After school I do homework and play football.',
   vocab:[{de:'die Schule',en:'school'},{de:'zu Fuß',en:'on foot'},{de:'das Lieblingsfach',en:'favorite subject'},{de:'die Hausaufgaben',en:'homework'}]},
  {id:'S009',num:9,title:'Im Park',titleEn:'In the Park',level:'A1',
   de:'Heute ist das Wetter schön. Ich gehe in den Park. Im Park sehe ich viele Kinder. Sie spielen mit Bällen und Hunden. Ich setze mich auf eine Bank und lese ein Buch.',
   en:'Today the weather is nice. I go to the park. In the park I see many children. They play with balls and dogs. I sit down on a bench and read a book.',
   vocab:[{de:'das Wetter',en:'weather'},{de:'das Kind',en:'child'},{de:'die Bank',en:'bench'},{de:'lesen',en:'to read'}]},
  {id:'S010',num:10,title:'Mein Zimmer',titleEn:'My Room',level:'A1',
   de:'Mein Zimmer ist klein, aber gemütlich. Es gibt ein Bett, einen Schreibtisch und einen Schrank. Auf dem Schreibtisch steht mein Laptop. An der Wand hängen Fotos von meinen Freunden. Ich liebe mein Zimmer.',
   en:'My room is small but cozy. There is a bed, a desk and a wardrobe. On the desk is my laptop. On the wall hang photos of my friends. I love my room.',
   vocab:[{de:'das Zimmer',en:'room'},{de:'der Schreibtisch',en:'desk'},{de:'der Schrank',en:'wardrobe'},{de:'die Wand',en:'wall'}]},
  {id:'S011',num:11,title:'Ein Brief an Oma',titleEn:'A Letter to Grandma',level:'A1',
   de:'Liebe Oma, wie geht es dir? Mir geht es gut. Die Schule ist okay. Heute regnet es, aber ich bin zu Hause. Ich freue mich auf den Sommer. Dann besuche ich dich. Liebe Grüße, Sara.',
   en:'Dear Grandma, how are you? I am fine. School is okay. Today it is raining, but I am at home. I am looking forward to summer. Then I will visit you. Love, Sara.',
   vocab:[{de:'der Brief',en:'letter'},{de:'regnen',en:'to rain'},{de:'besuchen',en:'to visit'},{de:'liebe Grüße',en:'best regards'}]},
  {id:'S012',num:12,title:'Meine Hobbys',titleEn:'My Hobbies',level:'A1',
   de:'Ich habe viele Hobbys. Ich lese gern Bücher und höre Musik. Am Wochenende fahre ich Fahrrad. Manchmal koche ich auch. Mein Lieblingshobby ist aber Fotografieren.',
   en:'I have many hobbies. I like to read books and listen to music. On weekends I ride my bike. Sometimes I also cook. But my favorite hobby is photography.',
   vocab:[{de:'das Hobby',en:'hobby'},{de:'Fahrrad fahren',en:'to ride a bike'},{de:'kochen',en:'to cook'},{de:'fotografieren',en:'to take photos'}]},
  {id:'S013',num:13,title:'Beim Arzt',titleEn:'At the Doctor\'s',level:'A1',
   de:'Ich fühle mich nicht gut. Ich habe Kopfschmerzen und Husten. Heute gehe ich zum Arzt. Der Arzt ist nett. Er sagt: Sie haben eine Erkältung. Ich kaufe Medikamente und gehe nach Hause.',
   en:'I don\'t feel well. I have a headache and a cough. Today I go to the doctor. The doctor is nice. He says: You have a cold. I buy medicine and go home.',
   vocab:[{de:'der Arzt',en:'doctor'},{de:'die Kopfschmerzen',en:'headache'},{de:'die Erkältung',en:'cold (illness)'},{de:'das Medikament',en:'medicine'}]},
  {id:'S014',num:14,title:'Ein Geschenk',titleEn:'A Gift',level:'A1',
   de:'Heute ist der Geburtstag meiner Schwester. Ich kaufe ein Geschenk. Es ist ein rotes Buch. Meine Schwester liebt Bücher. Sie freut sich sehr und sagt: Danke!',
   en:'Today is my sister\'s birthday. I buy a gift. It is a red book. My sister loves books. She is very happy and says: Thank you!',
   vocab:[{de:'der Geburtstag',en:'birthday'},{de:'das Geschenk',en:'gift'},{de:'die Schwester',en:'sister'},{de:'sich freuen',en:'to be happy'}]},
  {id:'S015',num:15,title:'Im Restaurant',titleEn:'At the Restaurant',level:'A1',
   de:'Wir gehen am Freitag in ein Restaurant. Der Kellner bringt die Speisekarte. Ich nehme eine Suppe und einen Salat. Mein Freund nimmt Fisch mit Reis. Das Essen ist sehr lecker.',
   en:'We go to a restaurant on Friday. The waiter brings the menu. I have a soup and a salad. My friend has fish with rice. The food is very tasty.',
   vocab:[{de:'das Restaurant',en:'restaurant'},{de:'der Kellner',en:'waiter'},{de:'die Speisekarte',en:'menu'},{de:'lecker',en:'tasty'}]},
  {id:'S016',num:16,title:'Das Wochenende',titleEn:'The Weekend',level:'A1',
   de:'Am Wochenende habe ich frei. Am Samstag schlafe ich lange. Dann gehe ich in die Stadt. Am Sonntag besuche ich meine Großeltern. Wir trinken Kaffee und essen Kuchen.',
   en:'On the weekend I am free. On Saturday I sleep in. Then I go into town. On Sunday I visit my grandparents. We drink coffee and eat cake.',
   vocab:[{de:'das Wochenende',en:'weekend'},{de:'frei',en:'free / off'},{de:'die Stadt',en:'town/city'},{de:'die Großeltern',en:'grandparents'}]},
  {id:'S017',num:17,title:'Ein neuer Freund',titleEn:'A New Friend',level:'A1',
   de:'In meinem Kurs gibt es einen neuen Studenten. Er heißt Paul und kommt aus Frankreich. Paul ist sehr freundlich. Wir sprechen über die Schule und über Musik. Ich glaube, wir werden gute Freunde.',
   en:'In my class there is a new student. His name is Paul and he comes from France. Paul is very friendly. We talk about school and about music. I think we will be good friends.',
   vocab:[{de:'der Kurs',en:'course/class'},{de:'freundlich',en:'friendly'},{de:'sprechen',en:'to speak'},{de:'der Freund',en:'friend'}]},
  {id:'S018',num:18,title:'Wetter im Winter',titleEn:'Winter Weather',level:'A1',
   de:'Im Winter ist es sehr kalt. Es schneit oft. Die Kinder spielen im Schnee. Ich trage einen warmen Mantel und einen Schal. Zu Hause trinke ich heißen Tee.',
   en:'In winter it is very cold. It often snows. The children play in the snow. I wear a warm coat and a scarf. At home I drink hot tea.',
   vocab:[{de:'der Winter',en:'winter'},{de:'schneien',en:'to snow'},{de:'der Mantel',en:'coat'},{de:'der Schal',en:'scarf'}]},
  {id:'S019',num:19,title:'Mein Auto',titleEn:'My Car',level:'A1',
   de:'Ich habe ein kleines Auto. Es ist blau und alt, aber es fährt gut. Jeden Morgen fahre ich damit zur Arbeit. Am Wochenende fahre ich oft ans Meer. Ich liebe mein Auto.',
   en:'I have a small car. It is blue and old, but it drives well. Every morning I drive it to work. On the weekend I often drive to the sea. I love my car.',
   vocab:[{de:'das Auto',en:'car'},{de:'fahren',en:'to drive'},{de:'das Meer',en:'sea'},{de:'alt',en:'old'}]},
  {id:'S020',num:20,title:'Frühstück',titleEn:'Breakfast',level:'A1',
   de:'Mein Frühstück ist einfach. Ich esse Brötchen mit Marmelade. Manchmal esse ich auch ein Ei. Dazu trinke ich Orangensaft und Kaffee. Das Frühstück ist meine Lieblingsmahlzeit.',
   en:'My breakfast is simple. I eat rolls with jam. Sometimes I also eat an egg. With it I drink orange juice and coffee. Breakfast is my favorite meal.',
   vocab:[{de:'das Frühstück',en:'breakfast'},{de:'die Marmelade',en:'jam'},{de:'das Ei',en:'egg'},{de:'die Mahlzeit',en:'meal'}]},
  {id:'S021',num:21,title:'Mein Bruder',titleEn:'My Brother',level:'A1',
   de:'Mein Bruder heißt Leon. Er ist sechzehn Jahre alt. Leon spielt Gitarre und singt sehr gut. Manchmal nervt er mich, aber ich liebe ihn. Wir sind beste Freunde.',
   en:'My brother is called Leon. He is sixteen years old. Leon plays guitar and sings very well. Sometimes he annoys me, but I love him. We are best friends.',
   vocab:[{de:'die Gitarre',en:'guitar'},{de:'singen',en:'to sing'},{de:'nerven',en:'to annoy'},{de:'beste Freunde',en:'best friends'}]},
  {id:'S022',num:22,title:'Im Zoo',titleEn:'At the Zoo',level:'A1',
   de:'Heute gehe ich mit meiner Klasse in den Zoo. Wir sehen Löwen, Elefanten und Affen. Die Affen sind sehr lustig. Wir machen viele Fotos. Der Tag im Zoo ist toll.',
   en:'Today I go to the zoo with my class. We see lions, elephants and monkeys. The monkeys are very funny. We take many photos. The day at the zoo is great.',
   vocab:[{de:'der Zoo',en:'zoo'},{de:'der Löwe',en:'lion'},{de:'der Affe',en:'monkey'},{de:'lustig',en:'funny'}]},
  {id:'S023',num:23,title:'Mein Lieblingsbuch',titleEn:'My Favorite Book',level:'A1',
   de:'Ich lese sehr gern. Mein Lieblingsbuch heißt Momo. Es ist eine schöne Geschichte. Ich habe das Buch schon dreimal gelesen. Manchmal lese ich abends im Bett.',
   en:'I love to read. My favorite book is called Momo. It is a beautiful story. I have already read the book three times. Sometimes I read in bed in the evening.',
   vocab:[{de:'das Buch',en:'book'},{de:'die Geschichte',en:'story'},{de:'schon',en:'already'},{de:'abends',en:'in the evening'}]},
  {id:'S024',num:24,title:'Im Bus',titleEn:'On the Bus',level:'A1',
   de:'Jeden Morgen fahre ich mit dem Bus zur Schule. Der Bus kommt um sieben Uhr fünfzehn. Im Bus höre ich Musik. Manchmal lese ich auch ein Buch. Die Fahrt dauert zwanzig Minuten.',
   en:'Every morning I take the bus to school. The bus comes at seven fifteen. On the bus I listen to music. Sometimes I also read a book. The journey takes twenty minutes.',
   vocab:[{de:'der Bus',en:'bus'},{de:'die Musik',en:'music'},{de:'die Fahrt',en:'ride/journey'},{de:'dauern',en:'to last/take'}]},
  {id:'S025',num:25,title:'Geburtstag',titleEn:'Birthday',level:'A1',
   de:'Heute ist mein Geburtstag. Ich werde dreißig Jahre alt. Meine Freunde kommen zu mir nach Hause. Wir essen Pizza und trinken Wein. Es gibt eine große Torte mit Kerzen.',
   en:'Today is my birthday. I am turning thirty years old. My friends come over to my house. We eat pizza and drink wine. There is a big cake with candles.',
   vocab:[{de:'der Geburtstag',en:'birthday'},{de:'die Torte',en:'cake'},{de:'die Kerze',en:'candle'},{de:'der Wein',en:'wine'}]},
  {id:'S026',num:26,title:'Eine kleine Reise',titleEn:'A Little Trip',level:'A1',
   de:'Am Samstag fahre ich nach Berlin. Ich fahre mit dem Zug. Die Reise dauert vier Stunden. In Berlin besuche ich einen Freund. Wir gehen ins Museum und essen zusammen.',
   en:'On Saturday I go to Berlin. I travel by train. The trip lasts four hours. In Berlin I visit a friend. We go to the museum and eat together.',
   vocab:[{de:'die Reise',en:'trip'},{de:'der Zug',en:'train'},{de:'das Museum',en:'museum'},{de:'zusammen',en:'together'}]},
  {id:'S027',num:27,title:'Im Schwimmbad',titleEn:'At the Swimming Pool',level:'A1',
   de:'Ich gehe gern ins Schwimmbad. Das Wasser ist warm und blau. Ich schwimme zehn Runden. Danach lege ich mich in die Sonne. Schwimmen macht mir Spaß.',
   en:'I like going to the swimming pool. The water is warm and blue. I swim ten laps. Then I lie in the sun. Swimming is fun for me.',
   vocab:[{de:'das Schwimmbad',en:'swimming pool'},{de:'schwimmen',en:'to swim'},{de:'die Sonne',en:'sun'},{de:'Spaß machen',en:'to be fun'}]},
  {id:'S028',num:28,title:'Meine Katze',titleEn:'My Cat',level:'A1',
   de:'Meine Katze heißt Mimi. Sie ist weiß und sehr ruhig. Mimi schläft gern auf dem Sofa. Manchmal spielt sie mit einem Ball aus Wolle. Ich liebe meine Katze sehr.',
   en:'My cat is called Mimi. She is white and very calm. Mimi likes to sleep on the sofa. Sometimes she plays with a ball of wool. I love my cat very much.',
   vocab:[{de:'die Katze',en:'cat'},{de:'ruhig',en:'calm/quiet'},{de:'das Sofa',en:'sofa'},{de:'die Wolle',en:'wool'}]},
  {id:'S029',num:29,title:'Eine kalte Nacht',titleEn:'A Cold Night',level:'A1',
   de:'Es ist Winter und es ist sehr kalt. Ich bin zu Hause und mache ein Feuer. Ich trinke heißen Kakao. Draußen schneit es. Im Bett lese ich noch ein Buch.',
   en:'It is winter and very cold. I am at home and make a fire. I drink hot chocolate. Outside it is snowing. In bed I still read a book.',
   vocab:[{de:'kalt',en:'cold'},{de:'das Feuer',en:'fire'},{de:'der Kakao',en:'hot chocolate'},{de:'draußen',en:'outside'}]},
  {id:'S030',num:30,title:'Mein Freund Max',titleEn:'My Friend Max',level:'A1',
   de:'Max ist mein bester Freund. Wir wohnen in der gleichen Straße. Jeden Tag spielen wir Fußball. Max ist sehr lustig und nett. Wir sind seit zehn Jahren Freunde.',
   en:'Max is my best friend. We live on the same street. Every day we play football. Max is very funny and nice. We have been friends for ten years.',
   vocab:[{de:'der Freund',en:'friend'},{de:'die Straße',en:'street'},{de:'der Fußball',en:'football'},{de:'nett',en:'nice'}]},
  {id:'S031',num:31,title:'Im Kino',titleEn:'At the Cinema',level:'A1',
   de:'Heute gehen wir ins Kino. Der Film beginnt um acht Uhr. Wir kaufen Popcorn und Cola. Der Film ist eine Komödie. Wir lachen viel.',
   en:'Today we are going to the cinema. The film starts at eight o\'clock. We buy popcorn and cola. The film is a comedy. We laugh a lot.',
   vocab:[{de:'das Kino',en:'cinema'},{de:'der Film',en:'film'},{de:'kaufen',en:'to buy'},{de:'die Komödie',en:'comedy'}]},
  {id:'S032',num:32,title:'Auf dem Markt',titleEn:'At the Market',level:'A1',
   de:'Am Samstag gehe ich auf den Markt. Es gibt frisches Obst und Gemüse. Ich kaufe Tomaten, Gurken und Erdbeeren. Der Verkäufer ist sehr freundlich. Ich gebe ihm zehn Euro.',
   en:'On Saturday I go to the market. There is fresh fruit and vegetables. I buy tomatoes, cucumbers and strawberries. The seller is very friendly. I give him ten euros.',
   vocab:[{de:'der Markt',en:'market'},{de:'das Obst',en:'fruit'},{de:'das Gemüse',en:'vegetables'},{de:'der Verkäufer',en:'seller'}]},
  {id:'S033',num:33,title:'Mein Garten',titleEn:'My Garden',level:'A1',
   de:'Ich habe einen kleinen Garten. Im Garten gibt es Blumen und einen Apfelbaum. Im Sommer sitze ich oft draußen. Ich lese und trinke Limonade. Die Vögel singen im Baum.',
   en:'I have a small garden. In the garden there are flowers and an apple tree. In summer I often sit outside. I read and drink lemonade. The birds sing in the tree.',
   vocab:[{de:'der Garten',en:'garden'},{de:'die Blume',en:'flower'},{de:'der Apfelbaum',en:'apple tree'},{de:'die Limonade',en:'lemonade'}]},
  {id:'S034',num:34,title:'Eine Postkarte',titleEn:'A Postcard',level:'A1',
   de:'Hallo Mama! Ich bin in Italien. Das Wetter ist super und das Essen ist toll. Heute war ich am Strand. Morgen besuchen wir Rom. Liebe Grüße, Lisa.',
   en:'Hello Mom! I am in Italy. The weather is super and the food is great. Today I was at the beach. Tomorrow we are visiting Rome. Love, Lisa.',
   vocab:[{de:'die Postkarte',en:'postcard'},{de:'der Strand',en:'beach'},{de:'das Essen',en:'food'},{de:'morgen',en:'tomorrow'}]},
  {id:'S035',num:35,title:'Auf dem Spielplatz',titleEn:'At the Playground',level:'A1',
   de:'Die Kinder spielen auf dem Spielplatz. Anna fährt Schaukel. Tim klettert auf die Rutsche. Lisa und Sam spielen im Sand. Alle Kinder lachen und sind glücklich.',
   en:'The children play on the playground. Anna is on the swing. Tim climbs the slide. Lisa and Sam play in the sand. All the children laugh and are happy.',
   vocab:[{de:'der Spielplatz',en:'playground'},{de:'die Schaukel',en:'swing'},{de:'die Rutsche',en:'slide'},{de:'glücklich',en:'happy'}]},
  {id:'S036',num:36,title:'Mein Computer',titleEn:'My Computer',level:'A1',
   de:'Ich habe einen neuen Computer. Er ist schnell und schön. Mit dem Computer schreibe ich E-Mails. Ich sehe auch Filme und spiele Spiele. Mein Computer ist sehr wichtig für mich.',
   en:'I have a new computer. It is fast and beautiful. With the computer I write emails. I also watch films and play games. My computer is very important to me.',
   vocab:[{de:'der Computer',en:'computer'},{de:'schnell',en:'fast'},{de:'die E-Mail',en:'email'},{de:'wichtig',en:'important'}]},
  {id:'S037',num:37,title:'Ein Tag am Meer',titleEn:'A Day at the Sea',level:'A1',
   de:'Heute sind wir am Meer. Die Sonne scheint. Ich schwimme und meine Schwester baut eine Sandburg. Wir essen Eis. Am Abend sehen wir den Sonnenuntergang.',
   en:'Today we are at the sea. The sun is shining. I swim and my sister builds a sandcastle. We eat ice cream. In the evening we see the sunset.',
   vocab:[{de:'das Meer',en:'sea'},{de:'die Sandburg',en:'sandcastle'},{de:'das Eis',en:'ice cream'},{de:'der Sonnenuntergang',en:'sunset'}]},
  {id:'S038',num:38,title:'Telefon',titleEn:'Telephone',level:'A1',
   de:'Mein Telefon klingelt. Es ist meine Mutter. Sie fragt: Wie geht es dir? Ich sage: Mir geht es gut. Wir sprechen zehn Minuten.',
   en:'My phone rings. It is my mother. She asks: How are you? I say: I am fine. We talk for ten minutes.',
   vocab:[{de:'das Telefon',en:'telephone'},{de:'klingeln',en:'to ring'},{de:'fragen',en:'to ask'},{de:'sagen',en:'to say'}]},
  {id:'S039',num:39,title:'Im Hotel',titleEn:'At the Hotel',level:'A1',
   de:'Wir sind im Hotel in Wien. Das Zimmer ist groß und hell. Es gibt ein Bett, einen Fernseher und ein Bad. Das Frühstück ist sehr gut. Wir bleiben drei Tage.',
   en:'We are at the hotel in Vienna. The room is big and bright. There is a bed, a TV and a bathroom. The breakfast is very good. We are staying three days.',
   vocab:[{de:'das Hotel',en:'hotel'},{de:'hell',en:'bright'},{de:'der Fernseher',en:'TV'},{de:'bleiben',en:'to stay'}]},
  {id:'S040',num:40,title:'Mein Lieblingsfilm',titleEn:'My Favorite Movie',level:'A1',
   de:'Mein Lieblingsfilm heißt Harry Potter. Ich habe ihn schon zehnmal gesehen. Die Geschichte ist spannend. Ich finde Hermione besonders cool. Heute Abend sehe ich den Film wieder.',
   en:'My favorite movie is called Harry Potter. I have already seen it ten times. The story is exciting. I find Hermione especially cool. Tonight I will watch the film again.',
   vocab:[{de:'der Lieblingsfilm',en:'favorite movie'},{de:'spannend',en:'exciting'},{de:'besonders',en:'especially'},{de:'wieder',en:'again'}]},
  {id:'S041',num:41,title:'Im Bahnhof',titleEn:'At the Train Station',level:'A1',
   de:'Ich bin am Bahnhof. Mein Zug fährt um zehn Uhr. Ich kaufe ein Ticket und einen Kaffee. Auf dem Bahnsteig warten viele Menschen. Endlich kommt der Zug.',
   en:'I am at the train station. My train leaves at ten o\'clock. I buy a ticket and a coffee. Many people are waiting on the platform. Finally the train arrives.',
   vocab:[{de:'der Bahnhof',en:'train station'},{de:'das Ticket',en:'ticket'},{de:'der Bahnsteig',en:'platform'},{de:'warten',en:'to wait'}]},
  {id:'S042',num:42,title:'Eine kleine Stadt',titleEn:'A Small Town',level:'A1',
   de:'Ich wohne in einer kleinen Stadt. Es gibt eine Kirche, eine Schule und einen Park. Die Leute sind freundlich. Im Sommer ist es ruhig. Ich liebe meine Stadt.',
   en:'I live in a small town. There is a church, a school and a park. The people are friendly. In summer it is quiet. I love my town.',
   vocab:[{de:'die Stadt',en:'town/city'},{de:'die Kirche',en:'church'},{de:'die Leute',en:'people'},{de:'ruhig',en:'quiet'}]},
  {id:'S043',num:43,title:'Beim Friseur',titleEn:'At the Hairdresser',level:'A1',
   de:'Heute gehe ich zum Friseur. Mein Haar ist zu lang. Die Friseurin schneidet es kurz. Sie wäscht und föhnt mein Haar. Jetzt sehe ich besser aus.',
   en:'Today I go to the hairdresser. My hair is too long. The hairdresser cuts it short. She washes and dries my hair. Now I look better.',
   vocab:[{de:'der Friseur',en:'hairdresser'},{de:'das Haar',en:'hair'},{de:'schneiden',en:'to cut'},{de:'föhnen',en:'to blow-dry'}]},
  {id:'S044',num:44,title:'Ein neues Handy',titleEn:'A New Phone',level:'A1',
   de:'Ich habe ein neues Handy. Es ist schwarz und sehr modern. Mit dem Handy mache ich Fotos. Ich schreibe meinen Freunden Nachrichten. Mein altes Handy schenke ich meinem Bruder.',
   en:'I have a new phone. It is black and very modern. With the phone I take photos. I write messages to my friends. I give my old phone to my brother.',
   vocab:[{de:'das Handy',en:'mobile phone'},{de:'modern',en:'modern'},{de:'die Nachricht',en:'message'},{de:'schenken',en:'to give as a gift'}]},
  {id:'S045',num:45,title:'Mein Lehrer',titleEn:'My Teacher',level:'A1',
   de:'Mein Deutschlehrer heißt Herr Müller. Er ist groß und hat eine Brille. Sein Unterricht ist immer interessant. Wir lernen viele neue Wörter. Ich mag Herrn Müller sehr.',
   en:'My German teacher is called Mr. Müller. He is tall and wears glasses. His lessons are always interesting. We learn many new words. I like Mr. Müller a lot.',
   vocab:[{de:'der Lehrer',en:'teacher'},{de:'die Brille',en:'glasses'},{de:'der Unterricht',en:'lesson/class'},{de:'interessant',en:'interesting'}]},
  {id:'S046',num:46,title:'Im Bett',titleEn:'In Bed',level:'A1',
   de:'Es ist spät. Ich liege im Bett. Das Licht ist aus. Ich höre nur die Uhr ticken. Ich schließe die Augen und schlafe.',
   en:'It is late. I am lying in bed. The light is off. I only hear the clock ticking. I close my eyes and sleep.',
   vocab:[{de:'das Bett',en:'bed'},{de:'das Licht',en:'light'},{de:'die Uhr',en:'clock'},{de:'das Auge',en:'eye'}]},
  {id:'S047',num:47,title:'Eine kleine Pause',titleEn:'A Short Break',level:'A1',
   de:'Im Büro arbeite ich seit drei Stunden. Jetzt mache ich eine Pause. Ich gehe in die Küche. Ich trinke ein Glas Wasser. Dann arbeite ich weiter.',
   en:'In the office I have been working for three hours. Now I am taking a break. I go to the kitchen. I drink a glass of water. Then I continue working.',
   vocab:[{de:'das Büro',en:'office'},{de:'die Pause',en:'break'},{de:'das Wasser',en:'water'},{de:'weiterarbeiten',en:'to keep working'}]},
  {id:'S048',num:48,title:'Ein Sonntag',titleEn:'A Sunday',level:'A1',
   de:'Heute ist Sonntag. Ich bleibe im Bett bis zehn Uhr. Dann frühstücke ich lang. Am Nachmittag spaziere ich im Wald. Sonntage sind schön.',
   en:'Today is Sunday. I stay in bed until ten o\'clock. Then I have a long breakfast. In the afternoon I take a walk in the woods. Sundays are nice.',
   vocab:[{de:'der Sonntag',en:'Sunday'},{de:'frühstücken',en:'to have breakfast'},{de:'der Nachmittag',en:'afternoon'},{de:'der Wald',en:'forest'}]},
  {id:'S049',num:49,title:'Eine Reise mit dem Fahrrad',titleEn:'A Bike Trip',level:'A1',
   de:'Heute mache ich eine kleine Tour mit dem Fahrrad. Ich fahre durch das Dorf und über die Brücke. Im Wald ist es kühl. Nach zwei Stunden bin ich am See. Dort esse ich mein Sandwich.',
   en:'Today I am taking a small bike tour. I cycle through the village and over the bridge. In the forest it is cool. After two hours I am at the lake. There I eat my sandwich.',
   vocab:[{de:'das Fahrrad',en:'bicycle'},{de:'die Brücke',en:'bridge'},{de:'der See',en:'lake'},{de:'das Sandwich',en:'sandwich'}]},
  {id:'S050',num:50,title:'Gute Nacht',titleEn:'Good Night',level:'A1',
   de:'Es ist elf Uhr. Ich putze die Zähne und ziehe meinen Schlafanzug an. Ich gehe ins Bett. Meine Mutter sagt: Gute Nacht, Schatz. Ich schlafe schnell ein.',
   en:'It is eleven o\'clock. I brush my teeth and put on my pajamas. I go to bed. My mother says: Good night, sweetheart. I fall asleep quickly.',
   vocab:[{de:'der Schlafanzug',en:'pajamas'},{de:'ins Bett gehen',en:'to go to bed'},{de:'der Schatz',en:'sweetheart/treasure'},{de:'einschlafen',en:'to fall asleep'}]},
];

fs.writeFileSync(OUT, JSON.stringify(stories, null, 2));
console.log('✅ Saved', stories.length, 'A1 stories to', OUT);
