const fs = require('fs');
const OUT = 'C:/Users/ADELEKEOLORUNISOLAO/Desktop/goethe-trainer/public/data/stories_a2.json';

const stories = [
  {id:'S051',num:51,title:'Der verlorene Schlüssel',titleEn:'The Lost Key',level:'A2',
   de:'Heute Morgen war ich spät dran. Ich rannte aus dem Haus und vergaß meinen Schlüssel. Am Abend stand ich vor der Tür und konnte nicht hinein. Meine Nachbarin sah mich und lachte. Sie hatte einen Ersatzschlüssel von meiner Wohnung. Ich war so froh und brachte ihr am nächsten Tag einen Kuchen als Dankeschön.',
   en:'This morning I was late. I ran out of the house and forgot my key. In the evening I stood in front of the door and couldn\'t get in. My neighbor saw me and laughed. She had a spare key to my apartment. I was so glad and brought her a cake the next day as a thank-you.',
   vocab:[{de:'der Schlüssel',en:'key'},{de:'vergessen',en:'to forget'},{de:'die Nachbarin',en:'neighbour (f.)'},{de:'der Ersatzschlüssel',en:'spare key'}]},
  {id:'S052',num:52,title:'Ein Tag in München',titleEn:'A Day in Munich',level:'A2',
   de:'Letzten Samstag besuchten wir München. Wir fuhren mit dem Zug und kamen um zehn Uhr an. Zuerst gingen wir zum Marienplatz und sahen das Glockenspiel. Danach aßen wir Bratwurst mit Brezel auf dem Viktualienmarkt. Am Nachmittag besichtigten wir das Deutsche Museum. Müde, aber glücklich fuhren wir abends nach Hause.',
   en:'Last Saturday we visited Munich. We took the train and arrived at ten o\'clock. First we went to Marienplatz and saw the Glockenspiel. Then we ate Bratwurst with pretzel at the Viktualienmarkt. In the afternoon we visited the German Museum. Tired but happy, we went home in the evening.',
   vocab:[{de:'besuchen',en:'to visit'},{de:'ankommen',en:'to arrive'},{de:'besichtigen',en:'to tour/visit a sight'},{de:'müde',en:'tired'}]},
  {id:'S053',num:53,title:'Mein erster Job',titleEn:'My First Job',level:'A2',
   de:'Mit siebzehn fand ich meinen ersten Job. Ich arbeitete in einem kleinen Café im Zentrum. Am Anfang war ich nervös, weil ich viele neue Sachen lernen musste. Mein Chef war geduldig und half mir oft. Nach ein paar Wochen kannte ich alle Stammkunden mit Namen. Diese Zeit war für mich sehr wichtig: Ich lernte, Verantwortung zu übernehmen.',
   en:'At seventeen I found my first job. I worked at a small café in the center. At first I was nervous because I had to learn many new things. My boss was patient and often helped me. After a few weeks I knew all the regulars by name. That time was very important to me: I learned to take responsibility.',
   vocab:[{de:'der Job',en:'job'},{de:'der Chef',en:'boss'},{de:'der Stammkunde',en:'regular customer'},{de:'die Verantwortung',en:'responsibility'}]},
  {id:'S054',num:54,title:'Ein Missverständnis',titleEn:'A Misunderstanding',level:'A2',
   de:'Gestern wartete ich vor dem Kino auf meinen Freund Tom. Es war kalt und es regnete. Nach einer Stunde kam er immer noch nicht. Ich war wütend und ging nach Hause. Zu Hause las ich seine Nachricht: Treffen wir uns morgen? Ich hatte den Tag verwechselt. Ich musste lachen.',
   en:'Yesterday I waited in front of the cinema for my friend Tom. It was cold and raining. After an hour he still hadn\'t come. I was angry and went home. At home I read his message: Shall we meet tomorrow? I had confused the days. I had to laugh.',
   vocab:[{de:'warten auf',en:'to wait for'},{de:'wütend',en:'angry'},{de:'die Nachricht',en:'message'},{de:'verwechseln',en:'to mix up'}]},
  {id:'S055',num:55,title:'Umzug in eine neue Stadt',titleEn:'Moving to a New City',level:'A2',
   de:'Vor drei Monaten bin ich nach Hamburg gezogen. Am Anfang war alles fremd. Ich kannte niemanden und vermisste meine Familie. Aber dann lernte ich in einem Sprachkurs nette Leute kennen. Wir gingen oft zusammen aus und besichtigten die Stadt. Heute fühle ich mich in Hamburg richtig zu Hause.',
   en:'Three months ago I moved to Hamburg. At first everything was unfamiliar. I knew no one and missed my family. But then I met nice people in a language course. We often went out together and explored the city. Today I feel really at home in Hamburg.',
   vocab:[{de:'der Umzug',en:'move (relocation)'},{de:'fremd',en:'unfamiliar/foreign'},{de:'vermissen',en:'to miss'},{de:'kennenlernen',en:'to get to know'}]},
  {id:'S056',num:56,title:'Ein Wochenende in den Bergen',titleEn:'A Weekend in the Mountains',level:'A2',
   de:'Letztes Wochenende war ich mit Freunden in den Alpen. Wir wohnten in einer kleinen Hütte. Am Samstag wanderten wir sechs Stunden bis zum Gipfel. Die Aussicht war fantastisch. Abends grillten wir und sangen Lieder am Lagerfeuer. Ich werde dieses Wochenende nie vergessen.',
   en:'Last weekend I was in the Alps with friends. We stayed in a small hut. On Saturday we hiked for six hours to the summit. The view was fantastic. In the evening we grilled and sang songs at the campfire. I will never forget this weekend.',
   vocab:[{de:'die Berge',en:'mountains'},{de:'wandern',en:'to hike'},{de:'die Aussicht',en:'view'},{de:'das Lagerfeuer',en:'campfire'}]},
  {id:'S057',num:57,title:'Mein Praktikum',titleEn:'My Internship',level:'A2',
   de:'Im Sommer machte ich ein Praktikum in einer Werbeagentur. Am ersten Tag war ich sehr aufgeregt. Meine Aufgaben waren spannend: Ich half bei Präsentationen und schrieb kurze Texte. Die Kollegen waren offen und freundlich. Nach drei Monaten wusste ich: Ich möchte später in dieser Branche arbeiten.',
   en:'In summer I did an internship at an advertising agency. On my first day I was very excited. My tasks were interesting: I helped with presentations and wrote short texts. The colleagues were open and friendly. After three months I knew: I want to work in this industry later.',
   vocab:[{de:'das Praktikum',en:'internship'},{de:'aufgeregt',en:'excited/nervous'},{de:'die Aufgabe',en:'task'},{de:'die Branche',en:'industry'}]},
  {id:'S058',num:58,title:'Eine besondere Begegnung',titleEn:'A Special Encounter',level:'A2',
   de:'Im Zug nach Köln saß ich neben einer alten Dame. Sie war achtzig Jahre alt und reiste allein. Wir sprachen über das Leben, über Krieg und Frieden, über Liebe. Ihre Geschichten waren sehr berührend. Als der Zug ankam, bedankte ich mich bei ihr für das schöne Gespräch.',
   en:'On the train to Cologne I sat next to an old lady. She was eighty years old and traveling alone. We talked about life, about war and peace, about love. Her stories were very moving. When the train arrived, I thanked her for the nice conversation.',
   vocab:[{de:'die Begegnung',en:'encounter'},{de:'der Krieg',en:'war'},{de:'berührend',en:'moving/touching'},{de:'das Gespräch',en:'conversation'}]},
  {id:'S059',num:59,title:'Der erste Schultag',titleEn:'The First Day of School',level:'A2',
   de:'Ich erinnere mich noch genau an meinen ersten Schultag. Meine Mutter kaufte mir eine große, bunte Schultüte. Vor der Schule waren viele Kinder mit ihren Eltern. Ich war ein bisschen ängstlich, aber meine Lehrerin war sehr nett. Am Ende des Tages wollte ich gar nicht nach Hause.',
   en:'I still remember my first day of school exactly. My mother bought me a big, colorful school cone. In front of the school there were many children with their parents. I was a bit scared, but my teacher was very nice. By the end of the day I didn\'t want to go home at all.',
   vocab:[{de:'sich erinnern',en:'to remember'},{de:'die Schultüte',en:'school cone (gift)'},{de:'ängstlich',en:'scared'},{de:'am Ende',en:'at the end'}]},
  {id:'S060',num:60,title:'Eine gute Tat',titleEn:'A Good Deed',level:'A2',
   de:'An einem regnerischen Nachmittag sah ich eine Frau mit vielen Tüten. Sie konnte die Tür nicht öffnen. Ich half ihr und trug die Tüten in den dritten Stock. Sie lächelte und schenkte mir einen Apfel aus ihrer Tasche. Manchmal sind kleine Gesten wichtiger als große Geschenke.',
   en:'On a rainy afternoon I saw a woman with many bags. She couldn\'t open the door. I helped her and carried the bags to the third floor. She smiled and gave me an apple from her bag. Sometimes small gestures are more important than big gifts.',
   vocab:[{de:'regnerisch',en:'rainy'},{de:'die Tüte',en:'bag'},{de:'der Stock',en:'floor (story)'},{de:'die Geste',en:'gesture'}]},
  {id:'S061',num:61,title:'Mein Traumberuf',titleEn:'My Dream Job',level:'A2',
   de:'Schon als Kind wollte ich Tierärztin werden. Ich liebte Tiere und kümmerte mich oft um die Katzen aus der Nachbarschaft. Heute studiere ich Veterinärmedizin in Berlin. Das Studium ist schwer, aber ich gebe nicht auf. In ein paar Jahren werde ich endlich meinen Traumberuf haben.',
   en:'Even as a child I wanted to be a veterinarian. I loved animals and often took care of the cats in the neighborhood. Today I study veterinary medicine in Berlin. The studies are hard, but I won\'t give up. In a few years I will finally have my dream job.',
   vocab:[{de:'der Traumberuf',en:'dream job'},{de:'die Tierärztin',en:'vet (f.)'},{de:'sich kümmern um',en:'to take care of'},{de:'aufgeben',en:'to give up'}]},
  {id:'S062',num:62,title:'Ein Tag im Krankenhaus',titleEn:'A Day at the Hospital',level:'A2',
   de:'Vor zwei Wochen brach ich mir den Arm beim Skifahren. Ich kam ins Krankenhaus und musste lange warten. Die Ärztin machte ein Röntgenbild und sagte: Drei Wochen Gips. Mein Bruder besuchte mich jeden Tag. Jetzt geht es mir wieder besser, aber ich darf noch keinen Sport machen.',
   en:'Two weeks ago I broke my arm while skiing. I went to the hospital and had to wait a long time. The doctor took an X-ray and said: Three weeks in a cast. My brother visited me every day. Now I am better again, but I am not allowed to do sports yet.',
   vocab:[{de:'brechen',en:'to break'},{de:'das Krankenhaus',en:'hospital'},{de:'der Gips',en:'cast'},{de:'der Sport',en:'sport'}]},
  {id:'S063',num:63,title:'Sprachen lernen',titleEn:'Learning Languages',level:'A2',
   de:'Ich lerne sehr gern Sprachen. Ich spreche schon Englisch und Französisch. Jetzt lerne ich Deutsch, weil ich nach Wien ziehen möchte. Jeden Tag höre ich deutsche Podcasts und lese kleine Geschichten. Manchmal ist die Grammatik schwierig, besonders die Artikel. Aber ich glaube, mit Geduld kann jeder eine neue Sprache lernen.',
   en:'I really like learning languages. I already speak English and French. Now I am learning German because I want to move to Vienna. Every day I listen to German podcasts and read short stories. Sometimes the grammar is difficult, especially the articles. But I believe that with patience anyone can learn a new language.',
   vocab:[{de:'die Sprache',en:'language'},{de:'die Grammatik',en:'grammar'},{de:'der Artikel',en:'article'},{de:'die Geduld',en:'patience'}]},
  {id:'S064',num:64,title:'Ein verregnetes Picknick',titleEn:'A Rainy Picnic',level:'A2',
   de:'Wir hatten alles vorbereitet: Brot, Käse, Obst und Saft. Doch als wir am See ankamen, fing es plötzlich an zu regnen. Wir liefen unter einen Baum, aber wir wurden trotzdem nass. Am Ende aßen wir das Picknick im Auto. Es war komisch, aber wir lachten viel und hatten Spaß.',
   en:'We had prepared everything: bread, cheese, fruit and juice. But when we arrived at the lake, it suddenly started to rain. We ran under a tree, but we still got wet. In the end we ate the picnic in the car. It was strange, but we laughed a lot and had fun.',
   vocab:[{de:'vorbereiten',en:'to prepare'},{de:'plötzlich',en:'suddenly'},{de:'nass',en:'wet'},{de:'komisch',en:'strange/funny'}]},
  {id:'S065',num:65,title:'Mein Großvater',titleEn:'My Grandfather',level:'A2',
   de:'Mein Großvater war ein besonderer Mensch. Er erzählte uns viele Geschichten aus seiner Jugend. Jeden Sommer arbeiteten wir zusammen im Garten. Er brachte mir bei, wie man Tomaten pflanzt. Er ist letztes Jahr gestorben, aber ich denke jeden Tag an ihn.',
   en:'My grandfather was a special person. He told us many stories from his youth. Every summer we worked together in the garden. He taught me how to plant tomatoes. He died last year, but I think of him every day.',
   vocab:[{de:'der Großvater',en:'grandfather'},{de:'die Jugend',en:'youth'},{de:'beibringen',en:'to teach'},{de:'sterben',en:'to die'}]},
  {id:'S066',num:66,title:'Ein peinlicher Moment',titleEn:'An Embarrassing Moment',level:'A2',
   de:'Auf einer Party rutschte ich auf dem nassen Boden aus und fiel hin. Mein Glas Wein landete auf dem weißen Hemd des Gastgebers. Alle schauten mich an. Ich wollte unter den Tisch verschwinden. Doch der Gastgeber lachte und sagte: Kein Problem, das ist nur ein Hemd. Seitdem trinke ich auf Partys vorsichtiger.',
   en:'At a party I slipped on the wet floor and fell. My glass of wine landed on the host\'s white shirt. Everyone looked at me. I wanted to disappear under the table. But the host laughed and said: No problem, it\'s just a shirt. Since then I drink more carefully at parties.',
   vocab:[{de:'ausrutschen',en:'to slip'},{de:'hinfallen',en:'to fall down'},{de:'der Gastgeber',en:'host'},{de:'vorsichtig',en:'careful'}]},
  {id:'S067',num:67,title:'Mein erstes Konzert',titleEn:'My First Concert',level:'A2',
   de:'Mit fünfzehn ging ich zu meinem ersten Rockkonzert. Die Halle war voll und die Musik war sehr laut. Ich kannte fast alle Lieder und sang mit. Am Ende war ich heiser, aber sehr glücklich. Seitdem gehe ich jedes Jahr auf mindestens ein Konzert.',
   en:'At fifteen I went to my first rock concert. The hall was full and the music was very loud. I knew almost all the songs and sang along. By the end I was hoarse, but very happy. Since then I go to at least one concert every year.',
   vocab:[{de:'das Konzert',en:'concert'},{de:'laut',en:'loud'},{de:'mitsingen',en:'to sing along'},{de:'heiser',en:'hoarse'}]},
  {id:'S068',num:68,title:'Ein Tag im Büro',titleEn:'A Day at the Office',level:'A2',
   de:'Mein Tag im Büro beginnt um neun Uhr. Zuerst lese ich meine E-Mails und plane meine Aufgaben. Um zwölf Uhr esse ich mit Kollegen in der Kantine. Am Nachmittag haben wir oft Meetings. Um sechs Uhr fahre ich erschöpft, aber zufrieden nach Hause.',
   en:'My day at the office starts at nine o\'clock. First I read my emails and plan my tasks. At twelve o\'clock I eat with colleagues in the canteen. In the afternoon we often have meetings. At six I drive home exhausted but satisfied.',
   vocab:[{de:'die Kantine',en:'canteen'},{de:'die Kollegen',en:'colleagues'},{de:'erschöpft',en:'exhausted'},{de:'zufrieden',en:'satisfied'}]},
  {id:'S069',num:69,title:'Ein verlorener Hund',titleEn:'A Lost Dog',level:'A2',
   de:'Im Park fand ich einen kleinen Hund ohne Halsband. Er war schmutzig und sah hungrig aus. Ich brachte ihn zum Tierarzt. Dort hatte er einen Chip. Wir riefen seine Besitzerin an. Sie weinte vor Freude. Sie hatte schon eine Woche nach ihrem Hund gesucht.',
   en:'In the park I found a small dog without a collar. He was dirty and looked hungry. I took him to the vet. There he had a chip. We called his owner. She cried with joy. She had already been looking for her dog for a week.',
   vocab:[{de:'das Halsband',en:'collar'},{de:'schmutzig',en:'dirty'},{de:'der Tierarzt',en:'vet'},{de:'die Besitzerin',en:'owner (f.)'}]},
  {id:'S070',num:70,title:'Sport ist gesund',titleEn:'Sport is Healthy',level:'A2',
   de:'Früher saß ich oft auf dem Sofa und aß Chips. Ich fühlte mich müde und unglücklich. Vor einem Jahr begann ich zu joggen. Am Anfang war es hart, aber ich gab nicht auf. Heute laufe ich viermal pro Woche und fühle mich viel besser.',
   en:'Before, I often sat on the sofa and ate chips. I felt tired and unhappy. A year ago I started jogging. At first it was hard, but I didn\'t give up. Today I run four times a week and feel much better.',
   vocab:[{de:'früher',en:'before/in the past'},{de:'joggen',en:'to jog'},{de:'hart',en:'hard'},{de:'pro Woche',en:'per week'}]},
  {id:'S071',num:71,title:'Mein Lieblingskoch',titleEn:'My Favorite Cook',level:'A2',
   de:'Mein Vater ist der beste Koch der Welt. Am Wochenende verbringt er Stunden in der Küche. Er macht oft Pasta mit selbstgemachter Tomatensoße. Manchmal probiert er auch neue Rezepte. Wenn er kocht, riecht das ganze Haus wunderbar.',
   en:'My father is the best cook in the world. On the weekend he spends hours in the kitchen. He often makes pasta with homemade tomato sauce. Sometimes he also tries new recipes. When he cooks, the whole house smells wonderful.',
   vocab:[{de:'der Koch',en:'cook'},{de:'selbstgemacht',en:'homemade'},{de:'das Rezept',en:'recipe'},{de:'riechen',en:'to smell'}]},
  {id:'S072',num:72,title:'Der Streit',titleEn:'The Argument',level:'A2',
   de:'Letzte Woche hatte ich einen Streit mit meiner besten Freundin. Wir sprachen drei Tage nicht miteinander. Ich war traurig und konnte nicht schlafen. Am Donnerstag rief ich sie an und entschuldigte mich. Wir trafen uns im Café und alles war wieder gut.',
   en:'Last week I had an argument with my best friend. We didn\'t speak to each other for three days. I was sad and couldn\'t sleep. On Thursday I called her and apologized. We met at the café and everything was fine again.',
   vocab:[{de:'der Streit',en:'argument'},{de:'traurig',en:'sad'},{de:'anrufen',en:'to call'},{de:'sich entschuldigen',en:'to apologize'}]},
  {id:'S073',num:73,title:'Ein Tag ohne Handy',titleEn:'A Day Without a Phone',level:'A2',
   de:'Am Sonntag entschied ich, einen ganzen Tag ohne Handy zu verbringen. Am Anfang war es seltsam. Meine Hand suchte automatisch das Telefon. Doch nach ein paar Stunden fühlte ich mich freier. Ich las ein Buch und ging lange spazieren. Am Abend wusste ich: Ich brauche solche Tage öfter.',
   en:'On Sunday I decided to spend an entire day without my phone. At first it was strange. My hand automatically reached for the phone. But after a few hours I felt freer. I read a book and went for a long walk. By evening I knew: I need days like this more often.',
   vocab:[{de:'entscheiden',en:'to decide'},{de:'seltsam',en:'strange'},{de:'automatisch',en:'automatically'},{de:'frei',en:'free'}]},
  {id:'S074',num:74,title:'Im Sprachkurs',titleEn:'In the Language Course',level:'A2',
   de:'In meinem Deutschkurs sind zwölf Studenten aus zehn Ländern. Wir kommen aus Brasilien, Japan, Spanien und vielen anderen Ländern. Unsere Lehrerin ist sehr geduldig. Wir lernen jeden Tag neue Wörter und machen Übungen. Am liebsten mache ich Rollenspiele mit den anderen Studenten.',
   en:'In my German course there are twelve students from ten countries. We come from Brazil, Japan, Spain and many other countries. Our teacher is very patient. We learn new words every day and do exercises. I most like to do role-plays with the other students.',
   vocab:[{de:'der Sprachkurs',en:'language course'},{de:'das Land',en:'country'},{de:'die Übung',en:'exercise'},{de:'das Rollenspiel',en:'role-play'}]},
  {id:'S075',num:75,title:'Eine Überraschungsparty',titleEn:'A Surprise Party',level:'A2',
   de:'Zum vierzigsten Geburtstag meiner Mutter planten wir eine Überraschungsparty. Wir luden alle ihre Freunde ein und kauften viele Blumen. Als sie nach Hause kam, riefen wir Überraschung! Sie war so erstaunt, dass sie zu weinen begann. Es war einer der schönsten Abende unseres Lebens.',
   en:'For my mother\'s fortieth birthday we planned a surprise party. We invited all her friends and bought many flowers. When she came home, we shouted Surprise! She was so amazed that she began to cry. It was one of the most beautiful evenings of our lives.',
   vocab:[{de:'die Überraschung',en:'surprise'},{de:'einladen',en:'to invite'},{de:'erstaunt',en:'amazed'},{de:'weinen',en:'to cry'}]},
  {id:'S076',num:76,title:'Das alte Foto',titleEn:'The Old Photo',level:'A2',
   de:'Auf dem Dachboden fand ich eine alte Schachtel. Darin lagen viele Schwarz-Weiß-Fotos. Ich erkannte meine Großmutter als junge Frau. Sie trug ein elegantes Kleid und lächelte sanft. Ich zeigte ihr das Foto und sie erzählte mir lange ihre Geschichte.',
   en:'In the attic I found an old box. Inside were many black-and-white photos. I recognized my grandmother as a young woman. She wore an elegant dress and smiled softly. I showed her the photo and she told me her story at length.',
   vocab:[{de:'der Dachboden',en:'attic'},{de:'die Schachtel',en:'box'},{de:'erkennen',en:'to recognize'},{de:'sanft',en:'soft/gently'}]},
  {id:'S077',num:77,title:'Ein Abend allein',titleEn:'An Evening Alone',level:'A2',
   de:'Heute Abend bin ich allein zu Hause. Ich kochte Pasta und öffnete eine Flasche Wein. Im Hintergrund läuft leise Klaviermusik. Ich lese ein interessantes Buch über Geschichte. Manchmal genieße ich solche ruhigen Abende sehr.',
   en:'Tonight I am home alone. I cooked pasta and opened a bottle of wine. In the background quiet piano music is playing. I am reading an interesting book about history. Sometimes I really enjoy such quiet evenings.',
   vocab:[{de:'allein',en:'alone'},{de:'die Flasche',en:'bottle'},{de:'der Hintergrund',en:'background'},{de:'genießen',en:'to enjoy'}]},
  {id:'S078',num:78,title:'Ein neues Hobby',titleEn:'A New Hobby',level:'A2',
   de:'Vor drei Monaten begann ich, Klavier zu lernen. Am Anfang waren meine Finger ungeschickt. Aber ich übe jeden Tag eine halbe Stunde. Letzte Woche spielte ich mein erstes ganzes Lied. Ich war so stolz, dass ich es meiner Familie vorspielte.',
   en:'Three months ago I started learning the piano. At first my fingers were clumsy. But I practice every day for half an hour. Last week I played my first whole song. I was so proud that I played it for my family.',
   vocab:[{de:'das Klavier',en:'piano'},{de:'ungeschickt',en:'clumsy'},{de:'üben',en:'to practice'},{de:'stolz',en:'proud'}]},
  {id:'S079',num:79,title:'Im Flugzeug',titleEn:'On the Plane',level:'A2',
   de:'Ich saß im Flugzeug nach New York. Es war mein erster langer Flug. Neben mir saß ein freundlicher Mann aus Polen. Wir sprachen über Reisen und unsere Familien. Plötzlich gab es Turbulenzen und ich bekam Angst. Mein Nachbar lächelte und sagte: Keine Sorge, das ist normal.',
   en:'I sat on the plane to New York. It was my first long flight. Next to me sat a friendly man from Poland. We talked about travel and our families. Suddenly there was turbulence and I got scared. My neighbor smiled and said: Don\'t worry, that\'s normal.',
   vocab:[{de:'das Flugzeug',en:'airplane'},{de:'der Flug',en:'flight'},{de:'die Angst',en:'fear'},{de:'die Sorge',en:'worry'}]},
  {id:'S080',num:80,title:'Die alte Bibliothek',titleEn:'The Old Library',level:'A2',
   de:'In meiner Stadt gibt es eine wunderschöne alte Bibliothek. Die Decken sind hoch und die Regale aus dunklem Holz. Es riecht nach altem Papier. Ich verbringe dort manchmal ganze Nachmittage. Bücher sind wie Türen in andere Welten.',
   en:'In my town there is a beautiful old library. The ceilings are high and the shelves are made of dark wood. It smells of old paper. I sometimes spend whole afternoons there. Books are like doors to other worlds.',
   vocab:[{de:'die Bibliothek',en:'library'},{de:'die Decke',en:'ceiling'},{de:'das Regal',en:'shelf'},{de:'die Welt',en:'world'}]},
  {id:'S081',num:81,title:'Ein Wettlauf',titleEn:'A Race',level:'A2',
   de:'Letzten Sonntag lief ich meinen ersten Halbmarathon. Schon um sechs Uhr stand ich auf und aß ein leichtes Frühstück. Bei Kilometer fünfzehn dachte ich, ich kann nicht mehr. Aber ich biss die Zähne zusammen und lief weiter. Im Ziel weinte ich vor Glück.',
   en:'Last Sunday I ran my first half-marathon. I got up at six and ate a light breakfast. At kilometer fifteen I thought I couldn\'t go on. But I gritted my teeth and kept running. At the finish I cried with happiness.',
   vocab:[{de:'der Halbmarathon',en:'half-marathon'},{de:'aufstehen',en:'to get up'},{de:'die Zähne zusammenbeißen',en:'to grit one\'s teeth'},{de:'das Ziel',en:'finish/goal'}]},
  {id:'S082',num:82,title:'Mein erstes Auto',titleEn:'My First Car',level:'A2',
   de:'Mit zwanzig kaufte ich mein erstes Auto. Es war ein alter, roter Polo, aber ich war stolz wie ein König. Ich fuhr zuerst nur in meinem Dorf. Später machte ich lange Reisen damit. Nach acht Jahren musste ich es leider verkaufen.',
   en:'At twenty I bought my first car. It was an old red Polo, but I was proud as a king. I first drove only in my village. Later I made long trips with it. After eight years I unfortunately had to sell it.',
   vocab:[{de:'kaufen',en:'to buy'},{de:'der König',en:'king'},{de:'verkaufen',en:'to sell'},{de:'leider',en:'unfortunately'}]},
  {id:'S083',num:83,title:'Ein Hund namens Rex',titleEn:'A Dog Named Rex',level:'A2',
   de:'Als Kind hatte ich einen Hund namens Rex. Er war groß, schwarz und sehr lieb. Jeden Tag wartete er auf mich nach der Schule. Wir spielten stundenlang im Garten. Rex starb, als ich vierzehn war. Ich werde ihn nie vergessen.',
   en:'As a child I had a dog named Rex. He was big, black and very sweet. Every day he waited for me after school. We played for hours in the garden. Rex died when I was fourteen. I will never forget him.',
   vocab:[{de:'der Hund',en:'dog'},{de:'warten',en:'to wait'},{de:'stundenlang',en:'for hours'},{de:'vergessen',en:'to forget'}]},
  {id:'S084',num:84,title:'Ein freier Tag',titleEn:'A Day Off',level:'A2',
   de:'Endlich hatte ich einen freien Tag. Ich wachte ohne Wecker auf und blieb lange im Bett. Zum Frühstück machte ich Pfannkuchen mit Erdbeeren. Am Nachmittag traf ich eine Freundin und wir gingen ins Museum. So sollten alle Tage sein.',
   en:'Finally I had a day off. I woke up without an alarm clock and stayed in bed for a long time. For breakfast I made pancakes with strawberries. In the afternoon I met a friend and we went to the museum. All days should be like this.',
   vocab:[{de:'der freie Tag',en:'day off'},{de:'der Wecker',en:'alarm clock'},{de:'der Pfannkuchen',en:'pancake'},{de:'treffen',en:'to meet'}]},
  {id:'S085',num:85,title:'Ein neues Lieblingsessen',titleEn:'A New Favorite Food',level:'A2',
   de:'Letzte Woche besuchten mich Freunde aus Vietnam. Sie kochten für mich Pho, eine traditionelle Suppe. Sie roch wunderbar nach Kräutern und Gewürzen. Ich aß zwei Schüsseln und wollte das Rezept lernen. Jetzt mache ich Pho selbst, aber nicht so gut wie meine Freunde.',
   en:'Last week friends from Vietnam visited me. They cooked Pho for me, a traditional soup. It smelled wonderful, of herbs and spices. I ate two bowls and wanted to learn the recipe. Now I make Pho myself, but not as well as my friends.',
   vocab:[{de:'traditionell',en:'traditional'},{de:'die Kräuter',en:'herbs'},{de:'das Gewürz',en:'spice'},{de:'die Schüssel',en:'bowl'}]},
  {id:'S086',num:86,title:'Eine neue Sportart',titleEn:'A New Sport',level:'A2',
   de:'Vor zwei Monaten begann ich mit Yoga. Am Anfang dachte ich, das ist langweilig und einfach. Aber schon nach der ersten Stunde tat mir alles weh. Heute fühle ich mich ruhiger und stärker. Yoga ist viel mehr als nur Sport.',
   en:'Two months ago I started doing yoga. At first I thought it was boring and easy. But after the first class everything hurt. Today I feel calmer and stronger. Yoga is much more than just a sport.',
   vocab:[{de:'das Yoga',en:'yoga'},{de:'langweilig',en:'boring'},{de:'wehtun',en:'to hurt'},{de:'stark',en:'strong'}]},
  {id:'S087',num:87,title:'Im Schnee',titleEn:'In the Snow',level:'A2',
   de:'Heute Morgen wachte ich auf und sah aus dem Fenster. Alles war weiß. In der Nacht hatte es viel geschneit. Die Kinder im Hof bauten einen großen Schneemann. Ich zog mir warme Kleidung an und ging hinaus. Wir machten eine fröhliche Schneeballschlacht.',
   en:'This morning I woke up and looked out of the window. Everything was white. During the night it had snowed a lot. The children in the yard were building a big snowman. I put on warm clothes and went out. We had a cheerful snowball fight.',
   vocab:[{de:'der Schnee',en:'snow'},{de:'der Schneemann',en:'snowman'},{de:'die Kleidung',en:'clothing'},{de:'die Schneeballschlacht',en:'snowball fight'}]},
  {id:'S088',num:88,title:'Ein Tag im Wald',titleEn:'A Day in the Woods',level:'A2',
   de:'Wir machten einen Spaziergang im Wald. Die Sonne schien zwischen den Bäumen hindurch. Wir hörten Vögel singen und sahen sogar ein Reh. Mein Sohn fand viele bunte Blätter. Am Ende waren wir müde, aber sehr entspannt.',
   en:'We took a walk in the woods. The sun shone through the trees. We heard birds singing and even saw a deer. My son found many colorful leaves. By the end we were tired but very relaxed.',
   vocab:[{de:'der Spaziergang',en:'walk'},{de:'der Baum',en:'tree'},{de:'das Reh',en:'deer'},{de:'entspannt',en:'relaxed'}]},
  {id:'S089',num:89,title:'Ein neues Buch',titleEn:'A New Book',level:'A2',
   de:'Gestern kaufte ich einen Roman in einer kleinen Buchhandlung. Die Verkäuferin empfahl mir ein Buch über eine Frau in Indien. Ich begann zu lesen und konnte nicht mehr aufhören. Bis zwei Uhr nachts las ich. Heute bin ich müde, aber das Buch war es wert.',
   en:'Yesterday I bought a novel in a small bookstore. The saleswoman recommended a book about a woman in India. I started reading and couldn\'t stop. I read until two in the morning. Today I am tired, but the book was worth it.',
   vocab:[{de:'der Roman',en:'novel'},{de:'empfehlen',en:'to recommend'},{de:'aufhören',en:'to stop'},{de:'wert sein',en:'to be worth'}]},
  {id:'S090',num:90,title:'Mein Lieblingsplatz',titleEn:'My Favorite Place',level:'A2',
   de:'In meiner Stadt gibt es einen kleinen Park am Fluss. Dort steht eine alte Bank unter einem großen Baum. Wenn ich traurig bin, gehe ich dorthin. Ich sitze still und schaue auf das Wasser. Nach einer Stunde fühle ich mich immer besser.',
   en:'In my town there is a small park by the river. There is an old bench under a big tree. When I am sad, I go there. I sit quietly and look at the water. After an hour I always feel better.',
   vocab:[{de:'der Lieblingsplatz',en:'favorite place'},{de:'der Fluss',en:'river'},{de:'still',en:'quiet/still'},{de:'schauen',en:'to look'}]},
  {id:'S091',num:91,title:'Eine wichtige Entscheidung',titleEn:'An Important Decision',level:'A2',
   de:'Letztes Jahr hatte ich eine schwierige Wahl: zwei Jobs in zwei Städten. Berlin war aufregender, aber Hamburg fühlte sich wie Heimat an. Ich sprach lange mit meiner Familie. Am Ende entschied ich mich für Hamburg. Bis heute bin ich glücklich mit dieser Entscheidung.',
   en:'Last year I had a difficult choice: two jobs in two cities. Berlin was more exciting, but Hamburg felt like home. I talked with my family for a long time. In the end I chose Hamburg. To this day I am happy with this decision.',
   vocab:[{de:'die Entscheidung',en:'decision'},{de:'schwierig',en:'difficult'},{de:'die Heimat',en:'home/homeland'},{de:'sich entscheiden',en:'to decide'}]},
  {id:'S092',num:92,title:'Beim Zahnarzt',titleEn:'At the Dentist',level:'A2',
   de:'Ich habe Angst vor dem Zahnarzt, aber gestern musste ich hingehen. Mein Zahn tat seit einer Woche weh. Die Zahnärztin war sehr nett und erklärte mir alles. Die Behandlung dauerte nur zwanzig Minuten. Jetzt habe ich keine Schmerzen mehr.',
   en:'I am afraid of the dentist, but yesterday I had to go. My tooth had hurt for a week. The dentist was very nice and explained everything. The treatment took only twenty minutes. Now I no longer have any pain.',
   vocab:[{de:'der Zahnarzt',en:'dentist'},{de:'der Zahn',en:'tooth'},{de:'die Behandlung',en:'treatment'},{de:'die Schmerzen',en:'pain'}]},
  {id:'S093',num:93,title:'Ein Tag voller Glück',titleEn:'A Day Full of Luck',level:'A2',
   de:'Heute war einfach mein Glückstag. Im Bus fand ich einen Sitzplatz, obwohl es voll war. Mein Chef lobte mich für meine Arbeit. Am Abend gewann ich ein Konzertticket im Radio. Manchmal ist das Leben einfach schön.',
   en:'Today was just my lucky day. On the bus I found a seat, even though it was crowded. My boss praised me for my work. In the evening I won a concert ticket on the radio. Sometimes life is just beautiful.',
   vocab:[{de:'das Glück',en:'luck/happiness'},{de:'der Sitzplatz',en:'seat'},{de:'loben',en:'to praise'},{de:'gewinnen',en:'to win'}]},
  {id:'S094',num:94,title:'Reisen mit dem Rucksack',titleEn:'Backpack Travel',level:'A2',
   de:'Letzten Sommer reiste ich mit dem Rucksack durch Europa. Ich besuchte fünf Länder in drei Wochen. Ich übernachtete in günstigen Hostels und lernte viele neue Leute kennen. Manchmal war es anstrengend, oft auch lustig. Diese Reise hat mein Leben verändert.',
   en:'Last summer I traveled through Europe with a backpack. I visited five countries in three weeks. I stayed in cheap hostels and met many new people. Sometimes it was exhausting, often also fun. This trip changed my life.',
   vocab:[{de:'der Rucksack',en:'backpack'},{de:'übernachten',en:'to stay overnight'},{de:'anstrengend',en:'exhausting'},{de:'verändern',en:'to change'}]},
  {id:'S095',num:95,title:'Ein Brief aus der Vergangenheit',titleEn:'A Letter from the Past',level:'A2',
   de:'Beim Aufräumen fand ich einen Brief aus der Schulzeit. Meine beste Freundin hatte ihn mir vor fünfzehn Jahren geschrieben. Wir hatten uns viele große Träume erzählt. Heute leben wir in verschiedenen Ländern. Ich werde sie diese Woche anrufen.',
   en:'While tidying up I found a letter from my school days. My best friend had written it to me fifteen years ago. We had told each other many big dreams. Today we live in different countries. I will call her this week.',
   vocab:[{de:'aufräumen',en:'to tidy up'},{de:'die Schulzeit',en:'school days'},{de:'der Traum',en:'dream'},{de:'verschieden',en:'different'}]},
  {id:'S096',num:96,title:'Ein Versprechen',titleEn:'A Promise',level:'A2',
   de:'Ich versprach meinem kleinen Bruder, dass wir an seinem Geburtstag in den Zoo gehen. Doch an diesem Tag war ich krank und konnte nicht aufstehen. Ich sah seine traurigen Augen und versprach ihm: Nächste Woche, ganz sicher. Eine Woche später gingen wir wirklich in den Zoo. Sein Lächeln war mein größtes Geschenk.',
   en:'I promised my little brother we would go to the zoo for his birthday. But on that day I was sick and couldn\'t get up. I saw his sad eyes and promised him: Next week, for sure. A week later we really went to the zoo. His smile was my greatest gift.',
   vocab:[{de:'versprechen',en:'to promise'},{de:'krank',en:'sick'},{de:'sicher',en:'sure/safe'},{de:'das Lächeln',en:'smile'}]},
  {id:'S097',num:97,title:'Mein erstes Mal kochen',titleEn:'My First Time Cooking',level:'A2',
   de:'Mit zwölf Jahren wollte ich meinen Eltern eine Überraschung machen. Ich kochte allein eine Spaghetti Bolognese. Die Tomatensoße war zu salzig und die Pasta zu weich. Aber meine Eltern aßen alles und sagten: Sehr lecker! Heute weiß ich, dass Liebe der beste Geschmack ist.',
   en:'At twelve I wanted to make a surprise for my parents. I cooked Spaghetti Bolognese all by myself. The tomato sauce was too salty and the pasta too soft. But my parents ate everything and said: Very tasty! Today I know that love is the best flavor.',
   vocab:[{de:'kochen',en:'to cook'},{de:'salzig',en:'salty'},{de:'weich',en:'soft'},{de:'der Geschmack',en:'taste/flavor'}]},
  {id:'S098',num:98,title:'Eine ungewöhnliche Reise',titleEn:'An Unusual Trip',level:'A2',
   de:'Im letzten Jahr reisten wir mit einem alten Wohnmobil durch Skandinavien. Wir kochten draußen, schliefen unter Sternen und sahen wilde Tiere. Einmal kam ein Elch nahe an unser Auto. Wir hatten kein Internet, aber wir vermissten es nicht. Es war die schönste Reise meines Lebens.',
   en:'Last year we traveled through Scandinavia in an old motorhome. We cooked outside, slept under the stars and saw wild animals. Once a moose came close to our car. We had no internet, but we didn\'t miss it. It was the most beautiful trip of my life.',
   vocab:[{de:'ungewöhnlich',en:'unusual'},{de:'das Wohnmobil',en:'motorhome'},{de:'der Stern',en:'star'},{de:'der Elch',en:'moose'}]},
  {id:'S099',num:99,title:'Ein zweites Leben',titleEn:'A Second Life',level:'A2',
   de:'Mit fünfzig Jahren begann meine Mutter ein neues Leben. Sie verließ ihren alten Job und eröffnete eine kleine Buchhandlung. Am Anfang hatte sie Angst und wenig Geld. Aber heute, nach fünf Jahren, ist ihr Laden ein Treffpunkt für Bücherfreunde. Sie zeigt mir jeden Tag: Es ist nie zu spät, neu anzufangen.',
   en:'At fifty my mother started a new life. She left her old job and opened a small bookstore. At first she was afraid and had little money. But today, after five years, her shop is a meeting point for book lovers. She shows me every day: it is never too late to start over.',
   vocab:[{de:'verlassen',en:'to leave'},{de:'eröffnen',en:'to open (a business)'},{de:'der Treffpunkt',en:'meeting point'},{de:'anfangen',en:'to begin'}]},
  {id:'S100',num:100,title:'Ein Brief an mich selbst',titleEn:'A Letter to Myself',level:'A2',
   de:'Liebes Ich, ich schreibe dir aus der Zukunft. Du wirst Fehler machen und manchmal weinen. Aber du wirst auch reisen, lieben und neue Sprachen lernen. Hab keine Angst vor dem Leben. Am Ende wirst du sagen: Es war alles richtig.',
   en:'Dear me, I am writing to you from the future. You will make mistakes and sometimes cry. But you will also travel, love and learn new languages. Don\'t be afraid of life. In the end you will say: it was all right.',
   vocab:[{de:'die Zukunft',en:'future'},{de:'der Fehler',en:'mistake'},{de:'die Angst',en:'fear'},{de:'richtig',en:'right/correct'}]},
];

fs.writeFileSync(OUT, JSON.stringify(stories, null, 2));
console.log('✅ Saved', stories.length, 'A2 stories to', OUT);
