/**
 * Batch 1 — 20 A1 conversations
 * Run: node scripts/gen_convo_batch1.js
 */
const fs = require('fs');
const OUT = 'C:/Users/ADELEKEOLORUNISOLAO/Desktop/goethe-trainer/public/data/convo_a1.json';

const a1 = [
  {
    id:'CONV001',level:'A1',title:'Hallo, ich heiße…',
    description:'Zwei Menschen treffen sich zum ersten Mal in einem Deutschkurs.',
    speakers:[{name:'Max',voice:1},{name:'Lena',voice:2}],
    lines:[
      {speaker:'Max',side:'left',de:'Hallo! Ich heiße Max. Wie heißt du?',en:'Hello! My name is Max. What is your name?'},
      {speaker:'Lena',side:'right',de:'Hi Max! Ich bin Lena. Schön, dich kennenzulernen!',en:'Hi Max! I am Lena. Nice to meet you!'},
      {speaker:'Max',side:'left',de:'Woher kommst du, Lena?',en:'Where are you from, Lena?'},
      {speaker:'Lena',side:'right',de:'Ich komme aus Wien. Und du?',en:'I come from Vienna. And you?'},
      {speaker:'Max',side:'left',de:'Ich bin aus Berlin. Wie lange bist du schon in Hamburg?',en:'I am from Berlin. How long have you been in Hamburg?'},
      {speaker:'Lena',side:'right',de:'Seit zwei Monaten. Ich lerne hier Deutsch.',en:'For two months. I am learning German here.'},
      {speaker:'Max',side:'left',de:'Toll! Dein Deutsch ist schon sehr gut. Was machst du beruflich?',en:'Great! Your German is already very good. What do you do for work?'},
      {speaker:'Lena',side:'right',de:'Ich bin Studentin. Ich studiere Informatik. Und du?',en:'I am a student. I study computer science. And you?'},
      {speaker:'Max',side:'left',de:'Ich arbeite als Lehrer. Vielleicht können wir zusammen üben!',en:'I work as a teacher. Maybe we can practise together!'},
      {speaker:'Lena',side:'right',de:'Ja, sehr gerne! Hier ist meine Handynummer.',en:'Yes, I would love that! Here is my mobile number.'},
    ],
  },
  {
    id:'CONV002',level:'A1',title:'Im Café',
    description:'Ein Gast bestellt Kaffee und Kuchen in einem kleinen Café.',
    speakers:[{name:'Tom',voice:1},{name:'Kellner Ahmed',voice:2}],
    lines:[
      {speaker:'Tom',side:'left',de:'Guten Morgen! Haben Sie noch Platz?',en:'Good morning! Do you have a free table?'},
      {speaker:'Kellner Ahmed',side:'right',de:'Ja, natürlich. Setzen Sie sich bitte. Hier ist die Karte.',en:'Yes, of course. Please have a seat. Here is the menu.'},
      {speaker:'Tom',side:'left',de:'Danke. Was empfehlen Sie heute?',en:'Thank you. What do you recommend today?'},
      {speaker:'Kellner Ahmed',side:'right',de:'Der Apfelkuchen ist sehr frisch. Und der Cappuccino ist sehr gut.',en:'The apple cake is very fresh. And the cappuccino is very good.'},
      {speaker:'Tom',side:'left',de:'Gut, dann nehme ich einen Cappuccino und ein Stück Apfelkuchen.',en:'Good, then I will have a cappuccino and a piece of apple cake.'},
      {speaker:'Kellner Ahmed',side:'right',de:'Mit Sahne?',en:'With cream?'},
      {speaker:'Tom',side:'left',de:'Ja, bitte. Was kostet das?',en:'Yes, please. How much does that cost?'},
      {speaker:'Kellner Ahmed',side:'right',de:'Der Cappuccino kostet drei Euro fünfzig und der Kuchen zwei Euro achtzig.',en:'The cappuccino costs three euros fifty and the cake two euros eighty.'},
      {speaker:'Tom',side:'left',de:'Okay, zusammen bitte. Ich bezahle mit Karte.',en:'Okay, together please. I will pay by card.'},
      {speaker:'Kellner Ahmed',side:'right',de:'Kein Problem. Einen Moment, bitte!',en:'No problem. One moment, please!'},
    ],
  },
  {
    id:'CONV003',level:'A1',title:'Im Supermarkt',
    description:'Eine Kundin sucht Hilfe beim Einkaufen.',
    speakers:[{name:'Anna',voice:1},{name:'Verkäufer',voice:2}],
    lines:[
      {speaker:'Anna',side:'left',de:'Entschuldigung, wo finde ich die Milch?',en:'Excuse me, where can I find the milk?'},
      {speaker:'Verkäufer',side:'right',de:'Die Milch ist in Gang drei, auf der linken Seite.',en:'The milk is in aisle three, on the left side.'},
      {speaker:'Anna',side:'left',de:'Danke. Und haben Sie auch Bio-Milch?',en:'Thank you. And do you also have organic milk?'},
      {speaker:'Verkäufer',side:'right',de:'Ja, die Bio-Milch steht ganz oben im Regal.',en:'Yes, the organic milk is at the very top of the shelf.'},
      {speaker:'Anna',side:'left',de:'Super. Ich brauche auch Brot. Wo ist die Bäckerei?',en:'Great. I also need bread. Where is the bakery?'},
      {speaker:'Verkäufer',side:'right',de:'Die Bäckerei ist hinten rechts, neben der Kasse.',en:'The bakery is at the back right, next to the checkout.'},
      {speaker:'Anna',side:'left',de:'Und was kostet das Vollkornbrot?',en:'And how much does the wholegrain bread cost?'},
      {speaker:'Verkäufer',side:'right',de:'Das Vollkornbrot kostet zwei Euro zwanzig.',en:'The wholegrain bread costs two euros twenty.'},
      {speaker:'Anna',side:'left',de:'Gut. Haben Sie auch Erdbeeren? Ich sehe keine.',en:'Good. Do you also have strawberries? I cannot see any.'},
      {speaker:'Verkäufer',side:'right',de:'Tut mir leid, die Erdbeeren sind heute leider ausverkauft.',en:'I am sorry, the strawberries are unfortunately sold out today.'},
    ],
  },
  {
    id:'CONV004',level:'A1',title:'Wie ist das Wetter?',
    description:'Zwei Freunde reden über das Wetter und ihre Pläne.',
    speakers:[{name:'Sara',voice:1},{name:'Felix',voice:2}],
    lines:[
      {speaker:'Sara',side:'left',de:'Felix, schau mal! Es regnet schon wieder!',en:'Felix, look! It is raining again!'},
      {speaker:'Felix',side:'right',de:'Ja, das Wetter ist heute wirklich schlecht.',en:'Yes, the weather is really bad today.'},
      {speaker:'Sara',side:'left',de:'Ich wollte eigentlich in den Park gehen.',en:'I actually wanted to go to the park.'},
      {speaker:'Felix',side:'right',de:'Das geht heute leider nicht. Wie ist das Wetter morgen?',en:'Unfortunately that is not possible today. What is the weather like tomorrow?'},
      {speaker:'Sara',side:'left',de:'Ich habe die App gecheckt. Morgen scheint die Sonne!',en:'I checked the app. The sun will shine tomorrow!'},
      {speaker:'Felix',side:'right',de:'Toll! Dann machen wir morgen ein Picknick.',en:'Great! Then we will have a picnic tomorrow.'},
      {speaker:'Sara',side:'left',de:'Gute Idee. Wie viel Grad sind es morgen?',en:'Good idea. How many degrees will it be tomorrow?'},
      {speaker:'Felix',side:'right',de:'Etwa zwanzig Grad. Perfekt für draußen.',en:'About twenty degrees. Perfect for being outside.'},
      {speaker:'Sara',side:'left',de:'Super! Ich bringe Sandwiches. Du bringst Saft.',en:'Super! I will bring sandwiches. You bring juice.'},
      {speaker:'Felix',side:'right',de:'Abgemacht! Wir treffen uns um elf Uhr.',en:'Deal! We will meet at eleven o\'clock.'},
    ],
  },
  {
    id:'CONV005',level:'A1',title:'Meine Familie',
    description:'Zwei Kursmitglieder stellen ihre Familien vor.',
    speakers:[{name:'Maria',voice:1},{name:'Kenji',voice:2}],
    lines:[
      {speaker:'Maria',side:'left',de:'Kenji, hast du Geschwister?',en:'Kenji, do you have siblings?'},
      {speaker:'Kenji',side:'right',de:'Ja, ich habe eine ältere Schwester. Sie heißt Yuki. Und du?',en:'Yes, I have an older sister. Her name is Yuki. And you?'},
      {speaker:'Maria',side:'left',de:'Ich habe zwei Brüder. Sie sind sieben und zehn Jahre alt.',en:'I have two brothers. They are seven and ten years old.'},
      {speaker:'Kenji',side:'right',de:'Oh, du bist die Älteste! Wohnst du mit deinen Eltern?',en:'Oh, you are the oldest! Do you live with your parents?'},
      {speaker:'Maria',side:'left',de:'Ja, noch. Aber ich möchte bald eine eigene Wohnung haben.',en:'Yes, for now. But I would like to have my own flat soon.'},
      {speaker:'Kenji',side:'right',de:'Ich verstehe. Ich wohne allein. Am Anfang war es schwer.',en:'I understand. I live alone. At first it was difficult.'},
      {speaker:'Maria',side:'left',de:'Was machen deine Eltern beruflich?',en:'What do your parents do for work?'},
      {speaker:'Kenji',side:'right',de:'Mein Vater ist Arzt und meine Mutter ist Lehrerin.',en:'My father is a doctor and my mother is a teacher.'},
      {speaker:'Maria',side:'left',de:'Interessant! Meine Mutter arbeitet im Supermarkt und mein Vater ist Elektriker.',en:'Interesting! My mother works in a supermarket and my father is an electrician.'},
      {speaker:'Kenji',side:'right',de:'Schön. Familien sind alle verschieden, aber alle wichtig.',en:'Nice. Families are all different, but all important.'},
    ],
  },
  {
    id:'CONV006',level:'A1',title:'Entschuldigung, wo ist…?',
    description:'Ein Tourist fragt nach dem Weg zur Post.',
    speakers:[{name:'Tourist Reza',voice:1},{name:'Frau Bauer',voice:2}],
    lines:[
      {speaker:'Tourist Reza',side:'left',de:'Entschuldigung! Können Sie mir helfen? Ich suche die Post.',en:'Excuse me! Can you help me? I am looking for the post office.'},
      {speaker:'Frau Bauer',side:'right',de:'Ja, natürlich! Die Post ist nicht weit von hier.',en:'Yes, of course! The post office is not far from here.'},
      {speaker:'Tourist Reza',side:'left',de:'Wie komme ich dorthin?',en:'How do I get there?'},
      {speaker:'Frau Bauer',side:'right',de:'Gehen Sie geradeaus, dann rechts in die Hauptstraße.',en:'Go straight ahead, then turn right into the main street.'},
      {speaker:'Tourist Reza',side:'left',de:'Geradeaus und dann rechts. Okay. Wie weit ist das?',en:'Straight ahead and then right. Okay. How far is that?'},
      {speaker:'Frau Bauer',side:'right',de:'Etwa fünf Minuten zu Fuß.',en:'About five minutes on foot.'},
      {speaker:'Tourist Reza',side:'left',de:'Und gibt es dort auch eine Bank?',en:'And is there also a bank there?'},
      {speaker:'Frau Bauer',side:'right',de:'Ja, direkt neben der Post. Sie können es nicht verpassen.',en:'Yes, right next to the post office. You cannot miss it.'},
      {speaker:'Tourist Reza',side:'left',de:'Vielen Dank! Sie sind sehr nett.',en:'Thank you very much! You are very kind.'},
      {speaker:'Frau Bauer',side:'right',de:'Bitte sehr! Gute Reise!',en:'You are welcome! Have a good trip!'},
    ],
  },
  {
    id:'CONV007',level:'A1',title:'Im Restaurant',
    description:'Ein Gast bestellt sein Abendessen.',
    speakers:[{name:'Herr Koch',voice:1},{name:'Kellnerin',voice:2}],
    lines:[
      {speaker:'Herr Koch',side:'left',de:'Guten Abend. Einen Tisch für eine Person, bitte.',en:'Good evening. A table for one person, please.'},
      {speaker:'Kellnerin',side:'right',de:'Guten Abend! Hier bitte, am Fenster. Die Karte.',en:'Good evening! Here please, by the window. The menu.'},
      {speaker:'Herr Koch',side:'left',de:'Danke. Was ist die Tagessuppe?',en:'Thank you. What is the soup of the day?'},
      {speaker:'Kellnerin',side:'right',de:'Heute haben wir Tomatensuppe mit Brot.',en:'Today we have tomato soup with bread.'},
      {speaker:'Herr Koch',side:'left',de:'Sehr gut. Ich nehme die Suppe und dann den Fisch mit Salat.',en:'Very good. I will have the soup and then the fish with salad.'},
      {speaker:'Kellnerin',side:'right',de:'Möchten Sie etwas trinken?',en:'Would you like something to drink?'},
      {speaker:'Herr Koch',side:'left',de:'Ja, bitte ein Glas Weißwein und ein Wasser.',en:'Yes, please a glass of white wine and a water.'},
      {speaker:'Kellnerin',side:'right',de:'Sehr gerne. Noch etwas?',en:'With pleasure. Anything else?'},
      {speaker:'Herr Koch',side:'left',de:'Nein danke, das ist alles.',en:'No thank you, that is all.'},
      {speaker:'Kellnerin',side:'right',de:'Einen Moment, ich bringe alles sofort.',en:'One moment, I will bring everything right away.'},
    ],
  },
  {
    id:'CONV008',level:'A1',title:'Herzlichen Glückwunsch!',
    description:'Eine Freundin überrascht den anderen zum Geburtstag.',
    speakers:[{name:'Lisa',voice:1},{name:'Ben',voice:2}],
    lines:[
      {speaker:'Lisa',side:'left',de:'Ben! Herzlichen Glückwunsch zum Geburtstag!',en:'Ben! Happy birthday!'},
      {speaker:'Ben',side:'right',de:'Oh danke, Lisa! Das ist eine Überraschung!',en:'Oh thank you, Lisa! That is a surprise!'},
      {speaker:'Lisa',side:'left',de:'Hier, das ist für dich! Ich hoffe, es gefällt dir.',en:'Here, this is for you! I hope you like it.'},
      {speaker:'Ben',side:'right',de:'Oh wow, ein Buch! Ich liebe Bücher. Du kennst mich gut!',en:'Oh wow, a book! I love books. You know me well!'},
      {speaker:'Lisa',side:'left',de:'Wie alt bist du jetzt?',en:'How old are you now?'},
      {speaker:'Ben',side:'right',de:'Ich bin dreißig! Kannst du das glauben?',en:'I am thirty! Can you believe it?'},
      {speaker:'Lisa',side:'left',de:'Dreißig ist super! Machst du eine Party?',en:'Thirty is great! Are you having a party?'},
      {speaker:'Ben',side:'right',de:'Ja! Am Samstag kommen alle meine Freunde.',en:'Yes! On Saturday all my friends are coming.'},
      {speaker:'Lisa',side:'left',de:'Ich freue mich sehr! Kann ich etwas mitbringen?',en:'I am really looking forward to it! Can I bring something?'},
      {speaker:'Ben',side:'right',de:'Bring einfach gute Laune mit! Das reicht!',en:'Just bring a good mood! That is enough!'},
    ],
  },
  {
    id:'CONV009',level:'A1',title:'Was machst du am Wochenende?',
    description:'Zwei Kollegen planen ihr Wochenende.',
    speakers:[{name:'Paul',voice:1},{name:'Eva',voice:2}],
    lines:[
      {speaker:'Paul',side:'left',de:'Eva, was machst du am Wochenende?',en:'Eva, what are you doing at the weekend?'},
      {speaker:'Eva',side:'right',de:'Am Samstag gehe ich mit meiner Mutter einkaufen. Am Sonntag bin ich frei.',en:'On Saturday I am going shopping with my mother. On Sunday I am free.'},
      {speaker:'Paul',side:'left',de:'Möchtest du am Sonntag ins Kino gehen?',en:'Would you like to go to the cinema on Sunday?'},
      {speaker:'Eva',side:'right',de:'Ja, gerne! Welcher Film läuft?',en:'Yes, I would love to! Which film is showing?'},
      {speaker:'Paul',side:'left',de:'Es gibt einen neuen deutschen Film. Eine Komödie.',en:'There is a new German film. A comedy.'},
      {speaker:'Eva',side:'right',de:'Perfekt! Ich lache gerne. Um wie viel Uhr?',en:'Perfect! I love to laugh. What time?'},
      {speaker:'Paul',side:'left',de:'Um siebzehn Uhr. Wir treffen uns vorher um halb fünf.',en:'At five o\'clock. We will meet beforehand at half past four.'},
      {speaker:'Eva',side:'right',de:'Okay. Vor dem Kino oder am Bahnhof?',en:'Okay. In front of the cinema or at the station?'},
      {speaker:'Paul',side:'left',de:'Am Bahnhof. Dann gehen wir zusammen.',en:'At the station. Then we will go together.'},
      {speaker:'Eva',side:'right',de:'Super! Ich freue mich schon!',en:'Super! I am already looking forward to it!'},
    ],
  },
  {
    id:'CONV010',level:'A1',title:'Meine Hobbys',
    description:'Zwei neue Freunde erzählen sich von ihren Hobbys.',
    speakers:[{name:'Mia',voice:1},{name:'Tim',voice:2}],
    lines:[
      {speaker:'Mia',side:'left',de:'Tim, was machst du in deiner Freizeit?',en:'Tim, what do you do in your free time?'},
      {speaker:'Tim',side:'right',de:'Ich spiele gern Gitarre und mache Sport. Und du?',en:'I like playing guitar and doing sport. And you?'},
      {speaker:'Mia',side:'left',de:'Ich lese viel und male gerne Bilder.',en:'I read a lot and like painting pictures.'},
      {speaker:'Tim',side:'right',de:'Toll! Was liest du gerne?',en:'Great! What do you like reading?'},
      {speaker:'Mia',side:'left',de:'Ich lese gerne Krimis und Abenteuergeschichten.',en:'I like reading crime novels and adventure stories.'},
      {speaker:'Tim',side:'right',de:'Interessant! Welchen Sport machst du?',en:'Interesting! What sport do you do?'},
      {speaker:'Mia',side:'left',de:'Ich schwimme dreimal pro Woche und fahre Fahrrad.',en:'I swim three times a week and ride my bike.'},
      {speaker:'Tim',side:'right',de:'Ich auch! Vielleicht können wir mal zusammen Fahrrad fahren.',en:'Me too! Maybe we can go cycling together sometime.'},
      {speaker:'Mia',side:'left',de:'Ja, gerne! Kennst du den Radweg am Fluss?',en:'Yes, I would love that! Do you know the cycle path along the river?'},
      {speaker:'Tim',side:'right',de:'Ja! Der ist wunderschön. Nächsten Samstag?',en:'Yes! It is wonderful. Next Saturday?'},
    ],
  },
  {
    id:'CONV011',level:'A1',title:'Beim Arzt',
    description:'Ein Patient beschreibt seine Symptome beim Arzt.',
    speakers:[{name:'Lars',voice:1},{name:'Ärztin Frau Meier',voice:2}],
    lines:[
      {speaker:'Lars',side:'left',de:'Guten Tag. Ich habe einen Termin. Mein Name ist Lars Fischer.',en:'Good day. I have an appointment. My name is Lars Fischer.'},
      {speaker:'Ärztin Frau Meier',side:'right',de:'Ja, Herr Fischer. Kommen Sie rein. Was fehlt Ihnen?',en:'Yes, Mr Fischer. Come in. What is the matter with you?'},
      {speaker:'Lars',side:'left',de:'Ich fühle mich nicht gut. Ich habe seit drei Tagen Halsschmerzen.',en:'I do not feel well. I have had a sore throat for three days.'},
      {speaker:'Ärztin Frau Meier',side:'right',de:'Haben Sie auch Fieber?',en:'Do you also have a temperature?'},
      {speaker:'Lars',side:'left',de:'Ja, gestern hatte ich 38,5 Grad.',en:'Yes, yesterday I had 38.5 degrees.'},
      {speaker:'Ärztin Frau Meier',side:'right',de:'Ich schaue mal. Öffnen Sie bitte den Mund.',en:'Let me have a look. Please open your mouth.'},
      {speaker:'Lars',side:'left',de:'Ist es schlimm?',en:'Is it bad?'},
      {speaker:'Ärztin Frau Meier',side:'right',de:'Nein, Sie haben eine leichte Erkältung. Ich verschreibe Ihnen etwas.',en:'No, you have a mild cold. I will prescribe you something.'},
      {speaker:'Lars',side:'left',de:'Muss ich viel trinken?',en:'Do I need to drink a lot?'},
      {speaker:'Ärztin Frau Meier',side:'right',de:'Ja, viel Tee und Wasser. Und bleiben Sie bitte zu Hause.',en:'Yes, lots of tea and water. And please stay at home.'},
    ],
  },
  {
    id:'CONV012',level:'A1',title:'Auf dem Markt',
    description:'Eine Käuferin kauft frisches Obst auf dem Wochenmarkt.',
    speakers:[{name:'Nina',voice:1},{name:'Händler Stefan',voice:2}],
    lines:[
      {speaker:'Nina',side:'left',de:'Guten Morgen! Was haben Sie heute frisch?',en:'Good morning! What do you have fresh today?'},
      {speaker:'Händler Stefan',side:'right',de:'Guten Morgen! Wir haben Erdbeeren, Kirschen und Äpfel. Alles frisch vom Bauernhof!',en:'Good morning! We have strawberries, cherries and apples. All fresh from the farm!'},
      {speaker:'Nina',side:'left',de:'Die Erdbeeren sehen toll aus! Was kosten sie?',en:'The strawberries look great! How much do they cost?'},
      {speaker:'Händler Stefan',side:'right',de:'Drei Euro pro Kilo. Heute im Angebot!',en:'Three euros per kilo. On offer today!'},
      {speaker:'Nina',side:'left',de:'Gut, dann nehme ich zwei Kilo Erdbeeren, bitte.',en:'Good, then I will take two kilos of strawberries, please.'},
      {speaker:'Händler Stefan',side:'right',de:'Gerne. Möchten Sie auch Kirschen probieren?',en:'Of course. Would you like to try the cherries?'},
      {speaker:'Nina',side:'left',de:'Ja, bitte! Oh, die sind sehr süß!',en:'Yes, please! Oh, those are very sweet!'},
      {speaker:'Händler Stefan',side:'right',de:'Frisch aus der Region. Ein Kilo für vier Euro.',en:'Fresh from the region. One kilo for four euros.'},
      {speaker:'Nina',side:'left',de:'Dann nehme ich auch ein Kilo Kirschen. Zusammen bitte.',en:'Then I will also take a kilo of cherries. Together please.'},
      {speaker:'Händler Stefan',side:'right',de:'Das macht zehn Euro, bitte. Guten Appetit!',en:'That comes to ten euros, please. Enjoy!'},
    ],
  },
  {
    id:'CONV013',level:'A1',title:'Im Hotel einchecken',
    description:'Eine Gästin kommt im Hotel an und checkt ein.',
    speakers:[{name:'Frau Wendt',voice:1},{name:'Rezeptionist Herr Park',voice:2}],
    lines:[
      {speaker:'Frau Wendt',side:'left',de:'Guten Tag! Ich habe eine Reservierung. Mein Name ist Wendt.',en:'Good day! I have a reservation. My name is Wendt.'},
      {speaker:'Rezeptionist Herr Park',side:'right',de:'Guten Tag, Frau Wendt. Einen Moment, ich schaue nach.',en:'Good day, Ms Wendt. One moment, let me check.'},
      {speaker:'Frau Wendt',side:'left',de:'Ich habe ein Einzelzimmer für drei Nächte reserviert.',en:'I reserved a single room for three nights.'},
      {speaker:'Rezeptionist Herr Park',side:'right',de:'Ja, alles da. Zimmer 214, zweiter Stock. Hier ist Ihr Schlüssel.',en:'Yes, everything is here. Room 214, second floor. Here is your key.'},
      {speaker:'Frau Wendt',side:'left',de:'Danke. Gibt es WLAN im Zimmer?',en:'Thank you. Is there Wi-Fi in the room?'},
      {speaker:'Rezeptionist Herr Park',side:'right',de:'Ja, das Passwort ist auf der Karte. Es ist kostenlos.',en:'Yes, the password is on the card. It is free of charge.'},
      {speaker:'Frau Wendt',side:'left',de:'Wunderbar. Und wann gibt es Frühstück?',en:'Wonderful. And when is breakfast served?'},
      {speaker:'Rezeptionist Herr Park',side:'right',de:'Frühstück ist von sieben bis zehn Uhr. Im Erdgeschoss.',en:'Breakfast is from seven to ten o\'clock. On the ground floor.'},
      {speaker:'Frau Wendt',side:'left',de:'Perfekt. Gibt es einen Parkplatz?',en:'Perfect. Is there a car park?'},
      {speaker:'Rezeptionist Herr Park',side:'right',de:'Ja, hinter dem Hotel. Ich wünsche Ihnen einen angenehmen Aufenthalt!',en:'Yes, behind the hotel. I wish you a pleasant stay!'},
    ],
  },
  {
    id:'CONV014',level:'A1',title:'Einen Tisch reservieren',
    description:'Jemand ruft in einem Restaurant an, um einen Tisch zu reservieren.',
    speakers:[{name:'Herr Braun',voice:1},{name:'Servicekraft Maria',voice:2}],
    lines:[
      {speaker:'Herr Braun',side:'left',de:'Guten Tag, ich möchte gerne einen Tisch reservieren.',en:'Good day, I would like to reserve a table.'},
      {speaker:'Servicekraft Maria',side:'right',de:'Gerne! Für wann und für wie viele Personen?',en:'Of course! For when and for how many people?'},
      {speaker:'Herr Braun',side:'left',de:'Für Samstag, den fünfzehnten. Für vier Personen.',en:'For Saturday the fifteenth. For four people.'},
      {speaker:'Servicekraft Maria',side:'right',de:'Und um wie viel Uhr möchten Sie kommen?',en:'And what time would you like to come?'},
      {speaker:'Herr Braun',side:'left',de:'Um acht Uhr abends, bitte.',en:'At eight o\'clock in the evening, please.'},
      {speaker:'Servicekraft Maria',side:'right',de:'Einen Moment. Ja, um zwanzig Uhr haben wir noch Platz.',en:'One moment. Yes, we still have space at eight o\'clock.'},
      {speaker:'Herr Braun',side:'left',de:'Wunderbar! Können wir bitte am Fenster sitzen?',en:'Wonderful! Can we sit by the window, please?'},
      {speaker:'Servicekraft Maria',side:'right',de:'Ich versuche es. Darf ich Ihren Namen?',en:'I will try. May I have your name?'},
      {speaker:'Herr Braun',side:'left',de:'Braun, Thomas Braun.',en:'Braun, Thomas Braun.'},
      {speaker:'Servicekraft Maria',side:'right',de:'Alles klar, Herr Braun. Wir freuen uns auf Sie!',en:'All noted, Mr Braun. We look forward to seeing you!'},
    ],
  },
  {
    id:'CONV015',level:'A1',title:'In der Klasse',
    description:'Ein Schüler fragt die Lehrerin nach seinen Hausaufgaben.',
    speakers:[{name:'Jonas',voice:1},{name:'Lehrerin Frau Schreiber',voice:2}],
    lines:[
      {speaker:'Jonas',side:'left',de:'Guten Morgen, Frau Schreiber!',en:'Good morning, Ms Schreiber!'},
      {speaker:'Lehrerin Frau Schreiber',side:'right',de:'Guten Morgen, Jonas. Hast du deine Hausaufgaben gemacht?',en:'Good morning, Jonas. Have you done your homework?'},
      {speaker:'Jonas',side:'left',de:'Ja! Aber Aufgabe drei war sehr schwer.',en:'Yes! But exercise three was very difficult.'},
      {speaker:'Lehrerin Frau Schreiber',side:'right',de:'Was hat dir dabei Probleme gemacht?',en:'What caused you problems with it?'},
      {speaker:'Jonas',side:'left',de:'Ich verstehe den Dativ nicht ganz.',en:'I do not quite understand the dative.'},
      {speaker:'Lehrerin Frau Schreiber',side:'right',de:'Kein Problem. Ich erkläre das heute noch einmal in der Klasse.',en:'No problem. I will explain it again in class today.'},
      {speaker:'Jonas',side:'left',de:'Danke! Haben wir heute auch ein Diktat?',en:'Thank you! Do we also have a dictation today?'},
      {speaker:'Lehrerin Frau Schreiber',side:'right',de:'Ja, nach der Pause. Aber es ist nicht schwer.',en:'Yes, after the break. But it is not difficult.'},
      {speaker:'Jonas',side:'left',de:'Oh! Ich muss noch einmal die Wörter lernen.',en:'Oh! I still need to learn the words again.'},
      {speaker:'Lehrerin Frau Schreiber',side:'right',de:'Du hast noch zehn Minuten. Viel Erfolg, Jonas!',en:'You still have ten minutes. Good luck, Jonas!'},
    ],
  },
  {
    id:'CONV016',level:'A1',title:'Mit dem Bus fahren',
    description:'Eine Frau kauft ein Ticket und fragt nach der Haltestelle.',
    speakers:[{name:'Luisa',voice:1},{name:'Busfahrer',voice:2}],
    lines:[
      {speaker:'Luisa',side:'left',de:'Guten Morgen! Eine Fahrkarte zum Hauptbahnhof, bitte.',en:'Good morning! One ticket to the main station, please.'},
      {speaker:'Busfahrer',side:'right',de:'Einfach oder hin und zurück?',en:'Single or return?'},
      {speaker:'Luisa',side:'left',de:'Einfach, bitte. Was kostet das?',en:'Single, please. How much does that cost?'},
      {speaker:'Busfahrer',side:'right',de:'Zwei Euro achtzig.',en:'Two euros eighty.'},
      {speaker:'Luisa',side:'left',de:'Hier sind drei Euro.',en:'Here are three euros.'},
      {speaker:'Busfahrer',side:'right',de:'Zwanzig Cent zurück. Hier, bitte.',en:'Twenty cents change. Here you go.'},
      {speaker:'Luisa',side:'left',de:'Danke. Wo muss ich aussteigen?',en:'Thank you. Where do I need to get off?'},
      {speaker:'Busfahrer',side:'right',de:'An der Haltestelle Marktplatz. Das sind noch vier Stationen.',en:'At the Marktplatz stop. That is four more stops.'},
      {speaker:'Luisa',side:'left',de:'Gut. Sagen Sie mir Bescheid?',en:'Good. Will you let me know?'},
      {speaker:'Busfahrer',side:'right',de:'Natürlich. Setzen Sie sich bitte.',en:'Of course. Please take a seat.'},
    ],
  },
  {
    id:'CONV017',level:'A1',title:'Kleidung kaufen',
    description:'Eine Kundin sucht ein T-Shirt in einem Bekleidungsgeschäft.',
    speakers:[{name:'Karin',voice:1},{name:'Verkäuferin',voice:2}],
    lines:[
      {speaker:'Karin',side:'left',de:'Entschuldigung! Ich suche ein rotes T-Shirt.',en:'Excuse me! I am looking for a red T-shirt.'},
      {speaker:'Verkäuferin',side:'right',de:'Gerne! In welcher Größe?',en:'Of course! What size?'},
      {speaker:'Karin',side:'left',de:'Größe 38, bitte.',en:'Size 38, please.'},
      {speaker:'Verkäuferin',side:'right',de:'Hier haben wir rote T-Shirts. Das hier ist sehr beliebt.',en:'Here we have red T-shirts. This one is very popular.'},
      {speaker:'Karin',side:'left',de:'Schön! Kann ich es anprobieren?',en:'Nice! Can I try it on?'},
      {speaker:'Verkäuferin',side:'right',de:'Natürlich. Die Umkleidekabine ist dort hinten.',en:'Of course. The changing room is at the back there.'},
      {speaker:'Karin',side:'left',de:'Es passt gut, aber haben Sie es auch in Dunkelblau?',en:'It fits well, but do you also have it in dark blue?'},
      {speaker:'Verkäuferin',side:'right',de:'Ja, einen Moment. Hier ist das Gleiche in Dunkelblau.',en:'Yes, one moment. Here is the same in dark blue.'},
      {speaker:'Karin',side:'left',de:'Perfekt! Was kostet es?',en:'Perfect! How much does it cost?'},
      {speaker:'Verkäuferin',side:'right',de:'Neunzehn Euro neunzig. Heute haben wir zehn Prozent Rabatt.',en:'Nineteen euros ninety. Today we have ten percent discount.'},
    ],
  },
  {
    id:'CONV018',level:'A1',title:'Telefonat mit Mama',
    description:'Sara ruft ihre Mutter an und erzählt von ihrem Alltag.',
    speakers:[{name:'Sara',voice:1},{name:'Mama',voice:2}],
    lines:[
      {speaker:'Sara',side:'left',de:'Hallo Mama! Wie geht es dir?',en:'Hello Mum! How are you?'},
      {speaker:'Mama',side:'right',de:'Hallo mein Schatz! Mir geht es gut. Und dir?',en:'Hello my darling! I am fine. And you?'},
      {speaker:'Sara',side:'left',de:'Auch gut, danke. Ich bin ein bisschen müde. Ich hatte viel Arbeit.',en:'Fine too, thank you. I am a little tired. I had a lot of work.'},
      {speaker:'Mama',side:'right',de:'Oh! Schläfst du genug? Isst du gut?',en:'Oh! Are you sleeping enough? Are you eating well?'},
      {speaker:'Sara',side:'left',de:'Ja, ja! Keine Sorge. Ich koche jeden Tag.',en:'Yes, yes! Don\'t worry. I cook every day.'},
      {speaker:'Mama',side:'right',de:'Gut. Wann kommst du uns besuchen?',en:'Good. When are you coming to visit us?'},
      {speaker:'Sara',side:'left',de:'Nächsten Monat, wenn die Prüfungen vorbei sind.',en:'Next month, when the exams are over.'},
      {speaker:'Mama',side:'right',de:'Wunderbar! Papa freut sich auch sehr.',en:'Wonderful! Dad is also very pleased.'},
      {speaker:'Sara',side:'left',de:'Ich auch! Ich vermisse euch.',en:'Me too! I miss you.'},
      {speaker:'Mama',side:'right',de:'Wir vermissen dich auch. Bis bald, mein Herz!',en:'We miss you too. See you soon, my love!'},
    ],
  },
  {
    id:'CONV019',level:'A1',title:'Am Flughafen',
    description:'Ein Reisender checkt am Flughafen ein.',
    speakers:[{name:'Herr Klein',voice:1},{name:'Mitarbeiterin am Schalter',voice:2}],
    lines:[
      {speaker:'Herr Klein',side:'left',de:'Guten Morgen. Ich möchte einchecken. Flug LH 342 nach München.',en:'Good morning. I would like to check in. Flight LH 342 to Munich.'},
      {speaker:'Mitarbeiterin am Schalter',side:'right',de:'Guten Morgen. Ihren Reisepass bitte.',en:'Good morning. Your passport please.'},
      {speaker:'Herr Klein',side:'left',de:'Hier bitte.',en:'Here you go.'},
      {speaker:'Mitarbeiterin am Schalter',side:'right',de:'Danke. Haben Sie Gepäck aufzugeben?',en:'Thank you. Do you have any luggage to check in?'},
      {speaker:'Herr Klein',side:'left',de:'Ja, einen Koffer. Er wiegt zwanzig Kilo.',en:'Yes, one suitcase. It weighs twenty kilos.'},
      {speaker:'Mitarbeiterin am Schalter',side:'right',de:'Das ist in Ordnung. Haben Sie Handgepäck?',en:'That is fine. Do you have hand luggage?'},
      {speaker:'Herr Klein',side:'left',de:'Nur einen kleinen Rucksack.',en:'Only a small backpack.'},
      {speaker:'Mitarbeiterin am Schalter',side:'right',de:'Gut. Hier ist Ihre Bordkarte. Gate B17.',en:'Good. Here is your boarding card. Gate B17.'},
      {speaker:'Herr Klein',side:'left',de:'Wann ist der Abflug?',en:'When is the departure?'},
      {speaker:'Mitarbeiterin am Schalter',side:'right',de:'Um zehn Uhr dreißig. Sie sollten jetzt zur Sicherheitskontrolle gehen.',en:'At ten thirty. You should go to security now.'},
    ],
  },
  {
    id:'CONV020',level:'A1',title:'Im Deutschkurs anmelden',
    description:'Ahmed möchte sich für einen Deutschkurs anmelden.',
    speakers:[{name:'Ahmed',voice:1},{name:'Sekretärin Frau Huber',voice:2}],
    lines:[
      {speaker:'Ahmed',side:'left',de:'Guten Tag! Ich möchte mich für einen Deutschkurs anmelden.',en:'Good day! I would like to sign up for a German course.'},
      {speaker:'Sekretärin Frau Huber',side:'right',de:'Willkommen! Welches Niveau haben Sie?',en:'Welcome! What is your level?'},
      {speaker:'Ahmed',side:'left',de:'Ich bin Anfänger. Ich lerne erst seit einem Monat Deutsch.',en:'I am a beginner. I have only been learning German for one month.'},
      {speaker:'Sekretärin Frau Huber',side:'right',de:'Dann empfehle ich Ihnen den A1 Kurs. Er beginnt nächsten Montag.',en:'Then I recommend the A1 course to you. It starts next Monday.'},
      {speaker:'Ahmed',side:'left',de:'Wie viele Stunden pro Woche?',en:'How many hours per week?'},
      {speaker:'Sekretärin Frau Huber',side:'right',de:'Vier Stunden, dienstags und donnerstags, von neun bis elf Uhr.',en:'Four hours, Tuesdays and Thursdays, from nine to eleven o\'clock.'},
      {speaker:'Ahmed',side:'left',de:'Perfekt! Was kostet der Kurs?',en:'Perfect! How much does the course cost?'},
      {speaker:'Sekretärin Frau Huber',side:'right',de:'Zweihundert Euro pro Monat. Bücher sind inklusive.',en:'Two hundred euros per month. Books are included.'},
      {speaker:'Ahmed',side:'left',de:'Gut. Kann ich jetzt bezahlen?',en:'Good. Can I pay now?'},
      {speaker:'Sekretärin Frau Huber',side:'right',de:'Ja, gerne. Bar oder mit Karte?',en:'Yes, of course. Cash or by card?'},
    ],
  },
];

fs.writeFileSync(OUT, JSON.stringify(a1, null, 2));
console.log('✅ Saved', a1.length, 'A1 conversations to', OUT);
