"""
Generates 400 sentence-order questions: A1:200  A2:150  B1:50
Each entry has: id, level, topic, words (scrambled), answer (tokens), correct (display), tip (English), structure (English pattern)
"""
import json, random
random.seed(99)

def sid(n): return f"SO{n:04d}"

def scramble(tokens):
    t = tokens[:]
    for _ in range(20):
        random.shuffle(t)
        if t != tokens:
            return t
    return t[::-1] if t == tokens else t

# (level, topic, tokens_CORRECT, correct_sentence, tip_english, structure_english)
RAW = [
# ══════════════════════════════════════════
# A1 — 200 sentences
# ══════════════════════════════════════════

# ── sein (1–30) ───────────────────────────
("A1","sein",["Ich","bin","müde","."],"Ich bin müde.","'sein' (to be) always sits at position 2 in a statement.","Subject + sein + Predicate adjective"),
("A1","sein",["Du","bist","sehr","nett","."],"Du bist sehr nett.","The verb holds position 2; 'sehr' (very) comes before the adjective.","Subject + sein + (sehr) + Predicate adjective"),
("A1","sein",["Er","ist","mein","Bruder","."],"Er ist mein Bruder.","Possessive pronouns come directly before the noun they modify.","Subject + sein + Possessive + Noun"),
("A1","sein",["Sie","ist","Lehrerin","."],"Sie ist Lehrerin.","Job titles after 'sein' take no article in German.","Subject + sein + Profession (no article)"),
("A1","sein",["Wir","sind","in","Berlin","."],"Wir sind in Berlin.","'in' + city name (dative) gives a location. No article with city names.","Subject + sein + in + City"),
("A1","sein",["Ihr","seid","willkommen","."],"Ihr seid willkommen.","'ihr seid' is the plural 'you are' for a group.","Subject (ihr) + seid + Adjective"),
("A1","sein",["Es","ist","kalt","heute","."],"Es ist kalt heute.","Time expressions like 'heute' often come after the predicate.","Es + sein + Adjective + Time"),
("A1","sein",["Das","ist","mein","Haus","."],"Das ist mein Haus.","'Das' points to something (demonstrative). Verb stays at position 2.","Das + sein + Possessive + Noun"),
("A1","sein",["Berlin","ist","eine","große","Stadt","."],"Berlin ist eine große Stadt.","A proper noun can be the subject. Adjective before a feminine noun gets '-e'.","Proper noun + sein + Article + Adjective + Noun"),
("A1","sein",["Meine","Mutter","ist","Ärztin","."],"Meine Mutter ist Ärztin.","Possessive + noun as subject, profession without article after 'ist'.","Possessive + Noun + sein + Profession"),
("A1","sein",["Das","Buch","ist","interessant","."],"Das Buch ist interessant.","Predicative adjectives have no ending (unlike attributive ones).","Subject + sein + Predicative adjective (no ending)"),
("A1","sein",["Die","Katze","ist","klein","und","süß","."],"Die Katze ist klein und süß.","'und' joins two adjectives; no comma needed.","Subject + sein + Adjective + und + Adjective"),
("A1","sein",["Heute","ist","Montag","."],"Heute ist Montag.","When a time word starts the sentence, the verb still comes second.","Time adverb + sein + Day (Verb-second rule)"),
("A1","sein",["Ich","bin","zwanzig","Jahre","alt","."],"Ich bin zwanzig Jahre alt.","German age: Subject + sein + number + Jahre alt.","Subject + sein + Number + Jahre + alt"),
("A1","sein",["Er","ist","nicht","hier","."],"Er ist nicht hier.","'nicht' negates 'hier'; it typically follows the verb and its complement.","Subject + sein + nicht + Adverb"),
("A1","sein",["Wir","sind","müde","und","hungrig","."],"Wir sind müde und hungrig.","Two predicative adjectives joined with 'und', no comma.","Subject + sein + Adj + und + Adj"),
("A1","sein",["Die","Kinder","sind","laut","."],"Die Kinder sind laut.","Plural subject + plural verb form 'sind'.","Plural subject + sind + Predicate adjective"),
("A1","sein",["Du","bist","meine","beste","Freundin","."],"Du bist meine beste Freundin.","Superlative adjective with possessive before a feminine noun.","Subject + sein + Possessive + Superlative + Noun"),
("A1","sein",["Das","Wetter","ist","heute","schön","."],"Das Wetter ist heute schön.","Time adverb 'heute' follows the verb before the predicate adjective.","Subject + sein + Time + Predicate adjective"),
("A1","sein",["Ich","bin","aus","Deutschland","."],"Ich bin aus Deutschland.","'aus' + country (no article for most countries) expresses origin.","Subject + sein + aus + Country"),
("A1","sein",["Sie","sind","Geschwister","."],"Sie sind Geschwister.","'Geschwister' (siblings) is always plural; no article after 'sein'.","Subject + sind + Noun (no article)"),
("A1","sein",["Der","Film","ist","sehr","gut","."],"Der Film ist sehr gut.","'sehr' intensifies the adjective; comes directly before it.","Subject + sein + sehr + Adjective"),
("A1","sein",["Mein","Vater","ist","fünfzig","Jahre","alt","."],"Mein Vater ist fünfzig Jahre alt.","Standard age formula: sein + number + Jahre + alt.","Possessive + Noun + sein + Number + Jahre + alt"),
("A1","sein",["Das","Essen","ist","lecker","."],"Das Essen ist lecker.","Neutral (das) subject + ist + predicative adjective.","Subject (das) + sein + Adjective"),
("A1","sein",["Sie","ist","sehr","intelligent","."],"Sie ist sehr intelligent.","Adverb 'sehr' always precedes the adjective it modifies.","Subject + sein + sehr + Adjective"),
("A1","sein",["Wir","sind","Freunde","."],"Wir sind Freunde.","Plural noun after 'sind' without an article (general reference).","Subject + sind + Plural noun (no article)"),
("A1","sein",["Das","ist","kein","Problem","."],"Das ist kein Problem.","'kein' negates a noun directly; replaces 'ein'.","Das + sein + kein + Noun"),
("A1","sein",["Er","ist","Arzt","von","Beruf","."],"Er ist Arzt von Beruf.","'von Beruf' (by profession) follows the job title to emphasise it.","Subject + sein + Profession + von Beruf"),
("A1","sein",["Ich","bin","glücklich","."],"Ich bin glücklich.","The simplest declarative: Subject – Verb – Predicate adjective.","Subject + sein + Predicate adjective"),
("A1","sein",["Die","Schule","ist","nicht","weit","."],"Die Schule ist nicht weit.","'nicht' negates the predicate adjective; follows 'ist' directly.","Subject + sein + nicht + Adjective"),

# ── haben (31–50) ─────────────────────────
("A1","haben",["Ich","habe","einen","Hund","."],"Ich habe einen Hund.","Masculine nouns take 'einen' (accusative) after action verbs like 'haben'.","Subject + haben + einen (masc. acc.) + Noun"),
("A1","haben",["Du","hast","ein","Fahrrad","."],"Du hast ein Fahrrad.","Neuter nouns stay 'ein' in the accusative.","Subject + haben + ein (neut. acc.) + Noun"),
("A1","haben",["Er","hat","keine","Zeit","."],"Er hat keine Zeit.","Feminine nouns use 'keine' to negate with 'haben'.","Subject + haben + keine (fem. acc.) + Noun"),
("A1","haben",["Sie","hat","lange","Haare","."],"Sie hat lange Haare.","Plural accusative without article: adjective gets '-e' ending.","Subject + haben + Adjective(-e) + Plural noun"),
("A1","haben",["Wir","haben","Hunger","."],"Wir haben Hunger.","'Hunger haben' is a fixed phrase; no article before 'Hunger'.","Subject + haben + Noun (no article, set phrase)"),
("A1","haben",["Ihr","habt","viele","Freunde","."],"Ihr habt viele Freunde.","'viele' (many) precedes a plural noun; no article needed.","Subject (ihr) + habt + viele + Plural noun"),
("A1","haben",["Sie","haben","ein","Auto","."],"Sie haben ein Auto.","Neuter noun 'Auto' keeps 'ein' in the accusative.","Subject + haben + ein (neut.) + Noun"),
("A1","haben",["Das","Kind","hat","blaue","Augen","."],"Das Kind hat blaue Augen.","Plural accusative without article; adjective gets '-e'.","Subject + haben + Adjective(-e) + Plural noun"),
("A1","haben",["Ich","habe","zwei","Brüder","."],"Ich habe zwei Brüder.","Numbers replace the article; noun stays in accusative plural.","Subject + haben + Number + Plural noun"),
("A1","haben",["Wir","haben","morgen","frei","."],"Wir haben morgen frei.","Time adverb 'morgen' slots in after the verb; 'frei haben' = to have a day off.","Subject + haben + Time adverb + frei (set phrase)"),
("A1","haben",["Du","hast","eine","Schwester","."],"Du hast eine Schwester.","Feminine noun 'Schwester' takes 'eine' in the accusative.","Subject + haben + eine (fem. acc.) + Noun"),
("A1","haben",["Er","hat","viel","Geld","."],"Er hat viel Geld.","'viel' (much) before a mass noun; no inflection ending needed.","Subject + haben + viel + Mass noun"),
("A1","haben",["Meine","Oma","hat","graue","Haare","."],"Meine Oma hat graue Haare.","Possessive subject + haben + adjective(-e) + plural noun.","Possessive + Noun + haben + Adj + Plural noun"),
("A1","haben",["Wir","haben","heute","keinen","Unterricht","."],"Wir haben heute keinen Unterricht.","Masculine noun in accusative negated with 'keinen'.","Subject + haben + Time + keinen (masc. acc.) + Noun"),
("A1","haben",["Ich","habe","Kopfschmerzen","."],"Ich habe Kopfschmerzen.","'-schmerzen' compounds are always plural; no article.","Subject + haben + Plural compound noun"),
("A1","haben",["Du","hast","ein","gutes","Gedächtnis","."],"Du hast ein gutes Gedächtnis.","Neuter indefinite + adjective: 'ein gutes' (strong ending '-es').","Subject + haben + ein + Adjective(-es) + Neuter noun"),
("A1","haben",["Das","Restaurant","hat","heute","geöffnet","."],"Das Restaurant hat heute geöffnet.","Time adverb 'heute' follows 'hat'; past participle goes to the end.","Subject + haben + Time + Past participle (end)"),
("A1","haben",["Sie","hat","eine","Katze","und","einen","Hund","."],"Sie hat eine Katze und einen Hund.","Two accusative objects: 'eine' (fem.) and 'einen' (masc.).","Subject + haben + eine + Noun + und + einen + Noun"),
("A1","haben",["Wir","haben","keine","Hausaufgaben","."],"Wir haben keine Hausaufgaben.","Plural negation: 'keine' before a plural noun.","Subject + haben + keine + Plural noun"),
("A1","haben",["Ich","habe","eine","Frage","."],"Ich habe eine Frage.","Feminine noun 'Frage' takes 'eine' in the accusative.","Subject + haben + eine (fem. acc.) + Noun"),

# ── W-Fragen (51–70) ──────────────────────
("A1","W-Fragen",["Wie","heißt","du","?"],"Wie heißt du?","W-questions: Question word – Verb – Subject (verb stays second).","W-word + Verb + Subject + ?"),
("A1","W-Fragen",["Woher","kommst","du","?"],"Woher kommst du?","'Woher' asks about origin; verb immediately follows.","Woher + Verb + Subject + ?"),
("A1","W-Fragen",["Wo","wohnst","du","?"],"Wo wohnst du?","'Wo' asks for a location; verb comes second.","Wo + Verb + Subject + ?"),
("A1","W-Fragen",["Was","machst","du","?"],"Was machst du?","'Was' asks about actions or things.","Was + Verb + Subject + ?"),
("A1","W-Fragen",["Wer","ist","das","?"],"Wer ist das?","'Wer' asks about a person; 'das' acts as a pointer.","Wer + ist + das + ?"),
("A1","W-Fragen",["Wann","kommt","er","?"],"Wann kommt er?","'Wann' asks about time; verb immediately follows.","Wann + Verb + Subject + ?"),
("A1","W-Fragen",["Warum","lernst","du","Deutsch","?"],"Warum lernst du Deutsch?","'Warum' asks for a reason; object follows subject.","Warum + Verb + Subject + Object + ?"),
("A1","W-Fragen",["Wie","viel","kostet","das","?"],"Wie viel kostet das?","'Wie viel' asks about price or quantity; treated as one unit.","Wie viel + Verb + Subject + ?"),
("A1","W-Fragen",["Wohin","gehst","du","?"],"Wohin gehst du?","'Wohin' asks about direction (where to); contrasts with 'wo' (where at).","Wohin + Verb + Subject + ?"),
("A1","W-Fragen",["Wie","alt","bist","du","?"],"Wie alt bist du?","'Wie alt' is a fixed phrase asking for age.","Wie alt + sein + Subject + ?"),
("A1","W-Fragen",["Welche","Sprachen","sprichst","du","?"],"Welche Sprachen sprichst du?","'Welche' (which/what) asks for selection; matches plural noun.","Welche + Plural noun + Verb + Subject + ?"),
("A1","W-Fragen",["Was","ist","dein","Lieblingsessen","?"],"Was ist dein Lieblingsessen?","'Was' can also ask for definitions or descriptions.","Was + ist + Possessive + Noun + ?"),
("A1","W-Fragen",["Wo","ist","die","Toilette","?"],"Wo ist die Toilette?","'Wo' + sein asks for the location of something.","Wo + ist + Article + Noun + ?"),
("A1","W-Fragen",["Wie","heißt","deine","Mutter","?"],"Wie heißt deine Mutter?","'Wie heißt' asks for a name; possessive before the noun.","Wie + heißt + Possessive + Noun + ?"),
("A1","W-Fragen",["Wann","hast","du","Geburtstag","?"],"Wann hast du Geburtstag?","'Geburtstag haben' is a fixed phrase (to have a birthday).","Wann + haben + Subject + Noun (set phrase) + ?"),
("A1","W-Fragen",["Woher","kommt","Ihr","Lehrer","?"],"Woher kommt Ihr Lehrer?","Formal possessive 'Ihr' (capitalised) before noun; verb at position 2.","Woher + Verb + Possessive + Noun + ?"),
("A1","W-Fragen",["Was","kostet","ein","Kaffee","?"],"Was kostet ein Kaffee?","'Was kostet' directly asks for the price.","Was + kostet + Article + Noun + ?"),
("A1","W-Fragen",["Wie","ist","deine","Telefonnummer","?"],"Wie ist deine Telefonnummer?","'Wie ist' requests a detail or description.","Wie + ist + Possessive + Noun + ?"),
("A1","W-Fragen",["Wer","spricht","Englisch","?"],"Wer spricht Englisch?","'Wer' as subject; verb stays at position 2.","Wer + Verb + Object + ?"),
("A1","W-Fragen",["Was","trinkst","du","gern","?"],"Was trinkst du gern?","'gern' (gladly/like to) follows the subject to express preference.","Was + Verb + Subject + gern + ?"),

# ── Ja/Nein-Fragen (71–85) ────────────────
("A1","Ja/Nein-Fragen",["Kommst","du","aus","Deutschland","?"],"Kommst du aus Deutschland?","Yes/No questions start with the verb; subject comes second.","Verb + Subject + Complement + ?"),
("A1","Ja/Nein-Fragen",["Bist","du","Student","?"],"Bist du Student?","Inversion: verb moves to position 1, subject to position 2.","sein + Subject + Noun + ?"),
("A1","Ja/Nein-Fragen",["Hast","du","Geschwister","?"],"Hast du Geschwister?","'haben' flips to the front for yes/no questions.","haben + Subject + Noun + ?"),
("A1","Ja/Nein-Fragen",["Sprichst","du","Deutsch","?"],"Sprichst du Deutsch?","Verb-first structure signals a yes/no question.","Verb + Subject + Language + ?"),
("A1","Ja/Nein-Fragen",["Wohnst","du","in","Berlin","?"],"Wohnst du in Berlin?","Location phrase comes after subject in yes/no questions.","Verb + Subject + in + City + ?"),
("A1","Ja/Nein-Fragen",["Isst","du","gern","Pizza","?"],"Isst du gern Pizza?","'gern' precedes the object to express a preference.","Verb + Subject + gern + Object + ?"),
("A1","Ja/Nein-Fragen",["Haben","Sie","einen","Termin","?"],"Haben Sie einen Termin?","Formal 'Sie' (capitalised) follows the verb in polite questions.","haben + Sie + acc. object + ?"),
("A1","Ja/Nein-Fragen",["Ist","das","dein","Buch","?"],"Ist das dein Buch?","'das' acts as a placeholder subject; possessive before noun.","sein + das + Possessive + Noun + ?"),
("A1","Ja/Nein-Fragen",["Lernst","du","gern","Deutsch","?"],"Lernst du gern Deutsch?","'gern' expresses enjoyment; sits between subject and object.","Verb + Subject + gern + Object + ?"),
("A1","Ja/Nein-Fragen",["Fährst","du","mit","dem","Auto","?"],"Fährst du mit dem Auto?","'mit + dative' expresses the means of transport.","Verb + Subject + mit + dem + Noun + ?"),
("A1","Ja/Nein-Fragen",["Kochst","du","gern","?"],"Kochst du gern?","Short yes/no question; 'gern' follows the subject.","Verb + Subject + gern + ?"),
("A1","Ja/Nein-Fragen",["Hat","er","ein","Handy","?"],"Hat er ein Handy?","Neuter 'ein' stays in the accusative after 'haben'.","haben + Subject + ein (neut.) + Noun + ?"),
("A1","Ja/Nein-Fragen",["Trinken","Sie","Kaffee","?"],"Trinken Sie Kaffee?","Formal question with 'Sie'; no article before 'Kaffee' (mass noun).","Verb + Sie + Noun (mass, no article) + ?"),
("A1","Ja/Nein-Fragen",["Gehst","du","heute","ins","Kino","?"],"Gehst du heute ins Kino?","'ins Kino' = in + das Kino (accusative, showing direction).","Verb + Subject + Time + ins + Noun + ?"),
("A1","Ja/Nein-Fragen",["Arbeitet","sie","in","einem","Büro","?"],"Arbeitet sie in einem Büro?","'in + einem' (dative) expresses location (where she works).","Verb + Subject + in + einem + Noun + ?"),

# ── Negation (86–110) ─────────────────────
("A1","Negation",["Ich","bin","nicht","müde","."],"Ich bin nicht müde.","'nicht' negates the predicate adjective and usually follows 'sein'.","Subject + sein + nicht + Adjective"),
("A1","Negation",["Er","kommt","heute","nicht","."],"Er kommt heute nicht.","When negating the whole verb, 'nicht' goes to the end.","Subject + Verb + Time + nicht (end)"),
("A1","Negation",["Das","ist","kein","Problem","."],"Das ist kein Problem.","'kein' negates a noun; replaces the indefinite article.","Das + sein + kein + Noun"),
("A1","Negation",["Ich","habe","kein","Geld","."],"Ich habe kein Geld.","'kein' replaces 'ein' in negation; neuter noun stays the same.","Subject + haben + kein (neut.) + Noun"),
("A1","Negation",["Sie","spricht","nicht","Englisch","."],"Sie spricht nicht Englisch.","'nicht' before the object negates specifically what is spoken.","Subject + Verb + nicht + Object"),
("A1","Negation",["Wir","haben","keine","Zeit","."],"Wir haben keine Zeit.","Feminine/plural nouns use 'keine' for negation.","Subject + haben + keine (fem./pl.) + Noun"),
("A1","Negation",["Das","ist","nicht","mein","Buch","."],"Das ist nicht mein Buch.","'nicht' before a possessive negates ownership.","Das + sein + nicht + Possessive + Noun"),
("A1","Negation",["Er","ist","kein","Arzt","."],"Er ist kein Arzt.","Profession after 'sein' is negated with 'kein'.","Subject + sein + kein + Profession"),
("A1","Negation",["Ich","verstehe","das","nicht","."],"Ich verstehe das nicht.","When negating the verb, 'nicht' goes to the very end.","Subject + Verb + Object + nicht (end)"),
("A1","Negation",["Sie","hat","keinen","Hunger","."],"Sie hat keinen Hunger.","Masculine nouns in accusative use 'keinen'.","Subject + haben + keinen (masc. acc.) + Noun"),
("A1","Negation",["Das","Wetter","ist","nicht","schön","."],"Das Wetter ist nicht schön.","'nicht' precedes the predicative adjective to negate it.","Subject + sein + nicht + Adjective"),
("A1","Negation",["Ich","trinke","keinen","Alkohol","."],"Ich trinke keinen Alkohol.","Masculine accusative noun negated with 'keinen'.","Subject + Verb + keinen (masc. acc.) + Noun"),
("A1","Negation",["Wir","kommen","nicht","aus","Frankreich","."],"Wir kommen nicht aus Frankreich.","'nicht' precedes the prepositional phrase it negates.","Subject + Verb + nicht + aus + Country"),
("A1","Negation",["Er","wohnt","nicht","in","München","."],"Er wohnt nicht in München.","'nicht' before 'in + city' negates the location.","Subject + Verb + nicht + in + City"),
("A1","Negation",["Das","ist","kein","gutes","Buch","."],"Das ist kein gutes Buch.","'kein' + adjective + noun; adjective takes '-es' (strong, neuter nom.).","Das + sein + kein + Adjective(-es) + Noun"),
("A1","Negation",["Ich","esse","kein","Fleisch","."],"Ich esse kein Fleisch.","Neuter mass noun negated with 'kein'.","Subject + Verb + kein (neut.) + Noun"),
("A1","Negation",["Sie","sind","nicht","verheiratet","."],"Sie sind nicht verheiratet.","'nicht' before a predicative adjective (past participle used as adjective).","Subject + sein + nicht + Adjective/Participle"),
("A1","Negation",["Er","hat","keine","Geschwister","."],"Er hat keine Geschwister.","Plural nouns are negated with 'keine'.","Subject + haben + keine + Plural noun"),
("A1","Negation",["Ich","mag","das","nicht","."],"Ich mag das nicht.","'nicht' at the end negates the entire predicate.","Subject + Verb + Object + nicht (end)"),
("A1","Negation",["Das","Café","hat","jetzt","nicht","geöffnet","."],"Das Café hat jetzt nicht geöffnet.","'nicht' before the participle negates the past action.","Subject + haben + Time + nicht + Participle"),
("A1","Negation",["Wir","gehen","heute","nicht","ins","Kino","."],"Wir gehen heute nicht ins Kino.","'nicht' before the directional phrase negates the destination.","Subject + Verb + Time + nicht + ins + Noun"),
("A1","Negation",["Ich","kenne","ihn","nicht","."],"Ich kenne ihn nicht.","'ihn' is the masculine accusative pronoun; 'nicht' follows at the end.","Subject + Verb + ihn (masc. acc.) + nicht"),
("A1","Negation",["Sie","kommt","nicht","aus","Spanien","."],"Sie kommt nicht aus Spanien.","'nicht aus' negates origin; precedes the prepositional phrase.","Subject + Verb + nicht + aus + Country"),
("A1","Negation",["Das","ist","kein","Tee",",","das","ist","Kaffee","."],"Das ist kein Tee, das ist Kaffee.","'kein' corrects a wrong identification; the second clause gives the truth.","Das + sein + kein + Noun, das + sein + Noun"),
("A1","Negation",["Ich","bin","nicht","dein","Freund","."],"Ich bin nicht dein Freund.","'nicht' before a possessive + noun negates the relationship.","Subject + sein + nicht + Possessive + Noun"),

# ── Verben im Präsens (111–140) ──────────
("A1","Verben",["Ich","gehe","jeden","Tag","spazieren","."],"Ich gehe jeden Tag spazieren.","'jeden Tag' (every day) follows the verb; 'spazieren gehen' is a split infinitive.","Subject + Verb + Time + Infinitive (split verb)"),
("A1","Verben",["Er","trinkt","morgens","Kaffee","."],"Er trinkt morgens Kaffee.","Time adverb 'morgens' slots in after the verb, before the object.","Subject + Verb + Time adverb + Object"),
("A1","Verben",["Wir","essen","zu","Mittag","in","der","Schule","."],"Wir essen zu Mittag in der Schule.","Time phrase before place phrase (TeKaMoLo rule: Time before Location).","Subject + Verb + Time + in + der + Place"),
("A1","Verben",["Sie","kauft","jeden","Samstag","ein","."],"Sie kauft jeden Samstag ein.","Separable verb 'einkaufen': the prefix 'ein' goes to the end.","Subject + Verb stem + Time + Prefix (end)"),
("A1","Verben",["Du","spielst","sehr","gut","Gitarre","."],"Du spielst sehr gut Gitarre.","Adverb phrase 'sehr gut' before the instrument (object).","Subject + Verb + sehr gut + Object"),
("A1","Verben",["Er","lernt","Deutsch","an","der","Universität","."],"Er lernt Deutsch an der Universität.","Object ('Deutsch') before the location phrase.","Subject + Verb + Object + an + der + Place"),
("A1","Verben",["Ich","schlafe","immer","acht","Stunden","."],"Ich schlafe immer acht Stunden.","'immer' (always) follows the verb; duration phrase comes after.","Subject + Verb + immer + Duration"),
("A1","Verben",["Sie","arbeitet","als","Lehrerin","."],"Sie arbeitet als Lehrerin.","'als' + profession (no article) describes the role.","Subject + Verb + als + Profession"),
("A1","Verben",["Wir","fahren","mit","dem","Bus","."],"Wir fahren mit dem Bus.","'mit + dative' expresses the means of transport.","Subject + Verb + mit + dem + Noun"),
("A1","Verben",["Er","liest","gern","Bücher","."],"Er liest gern Bücher.","'gern' follows the verb to show enjoyment; object after.","Subject + Verb + gern + Object"),
("A1","Verben",["Ich","koche","heute","Abend","Pasta","."],"Ich koche heute Abend Pasta.","'heute Abend' (this evening) is a compound time phrase; object follows.","Subject + Verb + Time + Object"),
("A1","Verben",["Du","machst","deine","Hausaufgaben","."],"Du machst deine Hausaufgaben.","Possessive 'deine' (your, plural) before the noun object.","Subject + Verb + Possessive + Object"),
("A1","Verben",["Das","Kind","spielt","im","Garten","."],"Das Kind spielt im Garten.","'im Garten' = in dem Garten; dative for static location.","Subject + Verb + im (in dem) + Noun"),
("A1","Verben",["Wir","sprechen","Deutsch","und","Englisch","."],"Wir sprechen Deutsch und Englisch.","Two language objects joined with 'und'; languages have no article.","Subject + Verb + Language + und + Language"),
("A1","Verben",["Er","kommt","aus","Italien","."],"Er kommt aus Italien.","'aus + country name' (most countries: no article) = origin.","Subject + Verb + aus + Country"),
("A1","Verben",["Sie","geht","jeden","Morgen","joggen","."],"Sie geht jeden Morgen joggen.","'jeden Morgen' (every morning) follows verb; activity infinitive at end.","Subject + Verb + Time + Infinitive"),
("A1","Verben",["Ich","brauche","ein","neues","Wörterbuch","."],"Ich brauche ein neues Wörterbuch.","Neuter indefinite article + adjective '-es' (strong ending) + noun.","Subject + Verb + ein + Adj(-es) + Neuter noun"),
("A1","Verben",["Du","schreibst","eine","E-Mail","an","deine","Freundin","."],"Du schreibst eine E-Mail an deine Freundin.","Direct object first, then 'an + accusative' shows the recipient.","Subject + Verb + Object + an + Possessive + Noun"),
("A1","Verben",["Das","Kind","schläft","um","acht","Uhr","."],"Das Kind schläft um acht Uhr.","'um + time' gives the exact clock time.","Subject + Verb + um + Time"),
("A1","Verben",["Wir","besuchen","morgen","unsere","Großeltern","."],"Wir besuchen morgen unsere Großeltern.","Time adverb 'morgen' follows the verb, before the object.","Subject + Verb + Time + Possessive + Object"),
("A1","Verben",["Er","fährt","mit","dem","Fahrrad","zur","Schule","."],"Er fährt mit dem Fahrrad zur Schule.","Means of transport (mit + dative) before destination (zur = zu der).","Subject + Verb + mit + dem + Noun + zur + Noun"),
("A1","Verben",["Ich","höre","gern","Musik","."],"Ich höre gern Musik.","'gern' shows preference; mass noun 'Musik' has no article.","Subject + Verb + gern + Object (no article)"),
("A1","Verben",["Sie","tanzt","sehr","gut","."],"Sie tanzt sehr gut.","'sehr gut' as an adverb phrase modifying the verb.","Subject + Verb + sehr + Adverb"),
("A1","Verben",["Du","isst","zu","viel","Süßes","."],"Du isst zu viel Süßes.","'zu viel' (too much) + nominalised adjective 'Süßes'.","Subject + Verb + zu viel + Noun"),
("A1","Verben",["Wir","wohnen","in","einer","kleinen","Wohnung","."],"Wir wohnen in einer kleinen Wohnung.","'in + dative' for location; feminine: 'einer', adjective '-en'.","Subject + Verb + in + einer + Adj(-en) + Noun"),
("A1","Verben",["Er","schreibt","jeden","Tag","in","sein","Tagebuch","."],"Er schreibt jeden Tag in sein Tagebuch.","Time before location; 'in + accusative' shows direction into the diary.","Subject + Verb + Time + in + Possessive + Noun"),
("A1","Verben",["Sie","lernt","für","die","Prüfung","."],"Sie lernt für die Prüfung.","'für + accusative' gives the purpose.","Subject + Verb + für + die + Noun"),
("A1","Verben",["Ich","kaufe","einen","Apfel","und","eine","Banane","."],"Ich kaufe einen Apfel und eine Banane.","Two accusative objects: 'einen' (masc.) and 'eine' (fem.).","Subject + Verb + einen + Noun + und + eine + Noun"),
("A1","Verben",["Er","wacht","um","sieben","Uhr","auf","."],"Er wacht um sieben Uhr auf.","Separable verb 'aufwachen': prefix 'auf' moves to the end.","Subject + Verb stem + Time + Prefix (end)"),
("A1","Verben",["Sie","singen","ein","Lied","."],"Sie singen ein Lied.","Neuter accusative: 'ein Lied'.","Subject + Verb + ein (neut.) + Noun"),

# ── Zeitangaben (141–160) ─────────────────
("A1","Zeit",["Der","Unterricht","beginnt","um","neun","Uhr","."],"Der Unterricht beginnt um neun Uhr.","'um + clock time' gives the exact start time.","Subject + Verb + um + Time"),
("A1","Zeit",["Heute","Abend","gehe","ich","ins","Theater","."],"Heute Abend gehe ich ins Theater.","Time phrase first → verb flips to position 2 (verb-second rule).","Time + Verb + Subject + ins + Noun"),
("A1","Zeit",["Morgen","haben","wir","keinen","Unterricht","."],"Morgen haben wir keinen Unterricht.","'Morgen' fronted → verb second; 'keinen' negates the masculine noun.","Time adverb + Verb + Subject + keinen + Noun"),
("A1","Zeit",["Er","kommt","um","halb","drei","."],"Er kommt um halb drei.","'halb drei' = half past two (2:30); 'um' introduces the time.","Subject + Verb + um + halb + Number"),
("A1","Zeit",["Am","Wochenende","schlafe","ich","lange","."],"Am Wochenende schlafe ich lange.","'am Wochenende' fronted → verb at position 2.","Time phrase + Verb + Subject + Adverb"),
("A1","Zeit",["Im","Sommer","fahren","wir","ans","Meer","."],"Im Sommer fahren wir ans Meer.","'Im Sommer' (in summer) fronted; verb flips before subject.","Time phrase + Verb + Subject + Destination"),
("A1","Zeit",["Jeden","Dienstag","habe","ich","Sport","."],"Jeden Dienstag habe ich Sport.","Repeated time ('jeden + weekday') fronted; verb second.","Time phrase + Verb + Subject + Activity"),
("A1","Zeit",["Der","Bus","fährt","alle","zehn","Minuten","."],"Der Bus fährt alle zehn Minuten.","'alle + time unit' expresses a regular interval.","Subject + Verb + alle + Number + Time unit"),
("A1","Zeit",["Das","Geschäft","öffnet","um","neun","Uhr","morgens","."],"Das Geschäft öffnet um neun Uhr morgens.","'morgens' (in the morning) clarifies the time of day.","Subject + Verb + um + Time + morgens"),
("A1","Zeit",["Ich","stehe","immer","früh","auf","."],"Ich stehe immer früh auf.","'immer' (always) follows the verb; 'früh' is an adverb; 'auf' is the separable prefix at the end.","Subject + Verb stem + immer + Adverb + Prefix (end)"),
("A1","Zeit",["Wir","essen","um","zwölf","Uhr","zu","Mittag","."],"Wir essen um zwölf Uhr zu Mittag.","'zu Mittag essen' (to have lunch) is a fixed phrase; time comes first.","Subject + Verb + Time + zu Mittag (set phrase)"),
("A1","Zeit",["Er","geht","abends","spazieren","."],"Er geht abends spazieren.","'abends' (in the evenings) is a time adverb; infinitive at end.","Subject + Verb + Time adverb + Infinitive"),
("A1","Zeit",["Sie","kommt","übermorgen","zurück","."],"Sie kommt übermorgen zurück.","'übermorgen' (the day after tomorrow); separable prefix 'zurück' at end.","Subject + Verb stem + Time + Prefix (end)"),
("A1","Zeit",["Im","Winter","ist","es","sehr","kalt","."],"Im Winter ist es sehr kalt.","Seasonal time phrase fronted; verb second; 'es' as weather subject.","Time phrase + sein + es + sehr + Adjective"),
("A1","Zeit",["Der","Zug","kommt","in","zehn","Minuten","."],"Der Zug kommt in zehn Minuten.","'in + time period' expresses how soon something happens.","Subject + Verb + in + Number + Time unit"),
("A1","Zeit",["Gestern","war","ich","im","Kino","."],"Gestern war ich im Kino.","Past time adverb 'gestern' fronted; 'war' (was) in position 2.","Time adverb + war + Subject + im + Noun"),
("A1","Zeit",["Heute","Nacht","regnet","es","."],"Heute Nacht regnet es.","'heute Nacht' (tonight) fronted; weather 'es' follows.","Time phrase + Verb + es"),
("A1","Zeit",["Die","Apotheke","ist","von","acht","bis","zwanzig","Uhr","geöffnet","."],"Die Apotheke ist von acht bis zwanzig Uhr geöffnet.","'von…bis' (from…to) frames a time range; participle at end.","Subject + sein + von + Time + bis + Time + Participle"),
("A1","Zeit",["Ich","arbeite","von","Montag","bis","Freitag","."],"Ich arbeite von Montag bis Freitag.","'von…bis + weekday' expresses a day range.","Subject + Verb + von + Day + bis + Day"),
("A1","Zeit",["Nächste","Woche","fahre","ich","nach","Berlin","."],"Nächste Woche fahre ich nach Berlin.","'Nächste Woche' fronted; verb second; 'nach + city' for destination.","Time phrase + Verb + Subject + nach + City"),

# ── Familie / Zahlen (161–200) ────────────
("A1","Familie",["Mein","Bruder","heißt","Thomas","."],"Mein Bruder heißt Thomas.","'mein' for masculine nouns in nominative; subject + verb + name.","Possessive + Noun + heißen + Name"),
("A1","Familie",["Meine","Schwester","ist","jünger","als","ich","."],"Meine Schwester ist jünger als ich.","Comparative 'jünger als' (younger than) + pronoun in nominative.","Subject + sein + Comparative + als + Pronoun"),
("A1","Familie",["Unser","Vater","arbeitet","als","Ingenieur","."],"Unser Vater arbeitet als Ingenieur.","'unser' (our) for masculine/neuter nominative; 'als' + profession.","Possessive + Noun + Verb + als + Profession"),
("A1","Familie",["Ihre","Mutter","kommt","aus","Österreich","."],"Ihre Mutter kommt aus Österreich.","'ihre' = her (feminine possessive); 'aus + country' for origin.","Possessive + Noun + Verb + aus + Country"),
("A1","Familie",["Meine","Eltern","wohnen","in","Hamburg","."],"Meine Eltern wohnen in Hamburg.","'meine Eltern' = my parents (plural possessive); location with 'in'.","Possessive + Plural noun + Verb + in + City"),
("A1","Familie",["Sein","Großvater","ist","achtzig","Jahre","alt","."],"Sein Großvater ist achtzig Jahre alt.","'sein' (his) for masculine nouns; age formula.","Possessive + Noun + sein + Number + Jahre alt"),
("A1","Familie",["Wir","haben","drei","Kinder","."],"Wir haben drei Kinder.","Number replaces article; noun stays in accusative plural.","Subject + haben + Number + Plural noun"),
("A1","Familie",["Ihr","Mann","ist","Koch","von","Beruf","."],"Ihr Mann ist Koch von Beruf.","'ihr' = her; 'von Beruf' emphasises the profession.","Possessive + Noun + sein + Profession + von Beruf"),
("A1","Familie",["Meine","Tante","hat","einen","Sohn","und","eine","Tochter","."],"Meine Tante hat einen Sohn und eine Tochter.","Two accusative objects: 'einen' (masc.) and 'eine' (fem.).","Possessive + Noun + haben + einen + Noun + und + eine + Noun"),
("A1","Familie",["Das","ist","mein","Onkel","Peter","."],"Das ist mein Onkel Peter.","Introductory 'Das ist' + possessive + relation + name.","Das + sein + Possessive + Noun + Name"),
("A1","Familie",["Mein","Cousin","studiert","in","Köln","."],"Mein Cousin studiert in Köln.","'in + city' (no article); location after verb.","Possessive + Noun + Verb + in + City"),
("A1","Familie",["Wir","besuchen","unsere","Oma","jedes","Wochenende","."],"Wir besuchen unsere Oma jedes Wochenende.","Accusative object before time phrase.","Subject + Verb + Possessive + Object + Time"),
("A1","Familie",["Meine","Nichte","heißt","Sophie","."],"Meine Nichte heißt Sophie.","'meine' for feminine nouns; 'heißen' + name.","Possessive + Noun + heißen + Name"),
("A1","Familie",["Ihr","Sohn","ist","sehr","klug","."],"Ihr Sohn ist sehr klug.","Possessive 'ihr' (her) + masculine noun; 'sehr' before adjective.","Possessive + Noun + sein + sehr + Adjective"),
("A1","Familie",["Unser","Hund","heißt","Bello","."],"Unser Hund heißt Bello.","'unser' for masculine nominative; verb 'heißen' + name.","Possessive + Noun + heißen + Name"),
("A1","Zahlen",["Ich","bin","dreiundzwanzig","Jahre","alt","."],"Ich bin dreiundzwanzig Jahre alt.","German compound numbers: units before tens (dreiundzwanzig = 23).","Subject + sein + Compound number + Jahre alt"),
("A1","Zahlen",["Das","kostet","fünfzehn","Euro","und","neunzig","Cent","."],"Das kostet fünfzehn Euro und neunzig Cent.","Price: euro amount + und + cent amount.","Subject + Verb + Number + Euro + und + Number + Cent"),
("A1","Zahlen",["Wir","haben","hundert","Wörter","gelernt","."],"Wir haben hundert Wörter gelernt.","Perfekt: haben + object + past participle at the end.","Subject + haben + Number + Object + Participle (end)"),
("A1","Zahlen",["Der","erste","Kurs","beginnt","am","Montag","."],"Der erste Kurs beginnt am Montag.","Ordinal 'erste' (first) as attributive adjective; 'am Montag' = on Monday.","Article + Ordinal + Noun + Verb + am + Day"),
("A1","Zahlen",["Er","hat","drei","Sprachen","gelernt","."],"Er hat drei Sprachen gelernt.","Number + plural noun as object; participle at end.","Subject + haben + Number + Plural noun + Participle"),
("A1","Zahlen",["Das","zweite","Haus","links","ist","unseres","."],"Das zweite Haus links ist unseres.","Ordinal adjective + noun + direction adverb as subject.","Article + Ordinal + Noun + Adverb + sein + Possessive"),
("A1","Zahlen",["Ich","brauche","zwei","Kilo","Äpfel","."],"Ich brauche zwei Kilo Äpfel.","Quantity + unit of measure + noun (no article, no case ending on Kilo).","Subject + Verb + Number + Unit + Noun"),
("A1","Zahlen",["Er","wohnt","im","dritten","Stock","."],"Er wohnt im dritten Stock.","Ordinal in dative: 'dritten' (third); 'im' = in dem.","Subject + Verb + im + Ordinal(-ten) + Noun"),
("A1","Zahlen",["Wir","treffen","uns","am","fünften","Mai","."],"Wir treffen uns am fünften Mai.","Date with ordinal: 'am + ordinal(-ten) + month'.","Subject + Verb + uns + am + Ordinal + Month"),
("A1","Zahlen",["Das","Ticket","kostet","neun","Euro","achtzig","."],"Das Ticket kostet neun Euro achtzig.","Spoken price: euros then cents without a decimal word.","Subject + Verb + Number + Euro + Cents"),

# ══════════════════════════════════════════
# A2 — 150 sentences
# ══════════════════════════════════════════

# ── Trennbare Verben (201–231) ────────────
("A2","Trennbare Verben",["Er","ruft","seine","Mutter","jeden","Sonntag","an","."],"Er ruft seine Mutter jeden Sonntag an.","Separable verbs split: the stem stays at position 2, the prefix moves to the very end.","Subject + Verb stem + Object + Time + Prefix (end)"),
("A2","Trennbare Verben",["Ich","stehe","um","sieben","Uhr","auf","."],"Ich stehe um sieben Uhr auf.","'aufstehen' splits: 'stehe' at position 2, 'auf' at the end.","Subject + Verb stem + Time + Prefix (end)"),
("A2","Trennbare Verben",["Sie","räumt","ihr","Zimmer","auf","."],"Sie räumt ihr Zimmer auf.","'aufräumen': stem 'räumt' stays, prefix 'auf' goes to end.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Wir","kaufen","samstags","im","Supermarkt","ein","."],"Wir kaufen samstags im Supermarkt ein.","'einkaufen': time adverb then location before the prefix 'ein'.","Subject + Verb stem + Time + Location + Prefix (end)"),
("A2","Trennbare Verben",["Er","sieht","jeden","Abend","fern","."],"Er sieht jeden Abend fern.","'fernsehen': stem 'sieht', prefix 'fern' at end.","Subject + Verb stem + Time + Prefix (end)"),
("A2","Trennbare Verben",["Du","fängst","zu","spät","an","."],"Du fängst zu spät an.","'anfangen': 'fängst' at position 2, manner adverb, prefix 'an' at end.","Subject + Verb stem + Manner + Prefix (end)"),
("A2","Trennbare Verben",["Ich","mache","das","Licht","aus","."],"Ich mache das Licht aus.","'ausmachen': object between stem and prefix.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Sie","zieht","nächste","Woche","um","."],"Sie zieht nächste Woche um.","'umziehen' (to move house): time before prefix 'um'.","Subject + Verb stem + Time + Prefix (end)"),
("A2","Trennbare Verben",["Er","schläft","am","Wochenende","aus","."],"Er schläft am Wochenende aus.","'ausschlafen': time phrase before prefix.","Subject + Verb stem + Time + Prefix (end)"),
("A2","Trennbare Verben",["Wir","laden","unsere","Freunde","ein","."],"Wir laden unsere Freunde ein.","'einladen' (to invite): accusative object before prefix 'ein'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Er","bringt","sein","Fahrrad","mit","."],"Er bringt sein Fahrrad mit.","'mitbringen': object between stem and prefix 'mit'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Sie","nimmt","ihren","Regenschirm","mit","."],"Sie nimmt ihren Regenschirm mit.","'mitnehmen': masculine accusative 'ihren' before prefix.","Subject + Verb stem + Object (masc. acc.) + Prefix (end)"),
("A2","Trennbare Verben",["Ich","komme","morgen","früh","zurück","."],"Ich komme morgen früh zurück.","'zurückkommen': two time adverbs ('morgen früh') before prefix.","Subject + Verb stem + Time + Prefix (end)"),
("A2","Trennbare Verben",["Du","siehst","wirklich","gut","aus","."],"Du siehst wirklich gut aus.","'aussehen' (to look/appear): manner adverbs before prefix 'aus'.","Subject + Verb stem + Manner + Prefix (end)"),
("A2","Trennbare Verben",["Wir","machen","um","achtzehn","Uhr","Schluss","."],"Wir machen um achtzehn Uhr Schluss.","'Schluss machen' (to finish): time before the noun object.","Subject + Verb stem + Time + Noun (end)"),
("A2","Trennbare Verben",["Sie","ruft","mich","heute","Abend","zurück","."],"Sie ruft mich heute Abend zurück.","'zurückrufen': accusative pronoun right after stem, time then prefix.","Subject + Verb stem + Pronoun + Time + Prefix (end)"),
("A2","Trennbare Verben",["Ich","fülle","das","Formular","aus","."],"Ich fülle das Formular aus.","'ausfüllen' (to fill in): object between stem and prefix.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Er","stellt","das","Radio","an","."],"Er stellt das Radio an.","'anstellen' (to switch on): object before prefix 'an'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Wir","holen","die","Kinder","von","der","Schule","ab","."],"Wir holen die Kinder von der Schule ab.","'abholen' (to pick up): object + prepositional phrase + prefix.","Subject + Verb stem + Object + von + der + Noun + Prefix (end)"),
("A2","Trennbare Verben",["Du","rufst","bitte","den","Arzt","an","."],"Du rufst bitte den Arzt an.","'anrufen': polite 'bitte' before the accusative object.","Subject + Verb stem + bitte + Object + Prefix (end)"),
("A2","Trennbare Verben",["Er","zieht","die","Jacke","aus","."],"Er zieht die Jacke aus.","'ausziehen' (to take off clothing): object between stem and prefix.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Sie","packt","ihren","Koffer","aus","."],"Sie packt ihren Koffer aus.","'auspacken': accusative object before prefix 'aus'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Ich","schalte","den","Computer","aus","."],"Ich schalte den Computer aus.","'ausschalten' (to switch off): object before prefix.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Wir","bereiten","das","Abendessen","vor","."],"Wir bereiten das Abendessen vor.","'vorbereiten' (to prepare): object between stem and prefix 'vor'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Sie","schreibt","die","Wörter","auf","."],"Sie schreibt die Wörter auf.","'aufschreiben' (to write down): object before prefix 'auf'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Ich","lese","die","Nachrichten","vor","."],"Ich lese die Nachrichten vor.","'vorlesen' (to read aloud): object before prefix 'vor'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Er","macht","das","Fenster","auf","."],"Er macht das Fenster auf.","'aufmachen' (to open): neuter object before prefix 'auf'.","Subject + Verb stem + Object + Prefix (end)"),
("A2","Trennbare Verben",["Er","packt","seinen","Koffer","für","die","Reise","ein","."],"Er packt seinen Koffer für die Reise ein.","'einpacken': object + purpose phrase ('für die Reise') + prefix.","Subject + Verb stem + Object + für + Object + Prefix (end)"),
("A2","Trennbare Verben",["Ich","rufe","dich","morgen","an","."],"Ich rufe dich morgen an.","'anrufen': pronoun object directly after stem, time before prefix.","Subject + Verb stem + Pronoun + Time + Prefix (end)"),
("A2","Trennbare Verben",["Wir","ziehen","nächsten","Monat","in","ein","neues","Haus","um","."],"Wir ziehen nächsten Monat in ein neues Haus um.","'umziehen': time + destination (in + acc.) + prefix at very end.","Subject + Verb stem + Time + in + Object + Prefix (end)"),

# ── Modalverben (231–260) ─────────────────
("A2","Modalverben",["Ich","kann","gut","schwimmen","."],"Ich kann gut schwimmen.","Modal verb at position 2; infinitive goes to the very end.","Subject + Modal + Adverb + Infinitive (end)"),
("A2","Modalverben",["Du","musst","jetzt","gehen","."],"Du musst jetzt gehen.","'müssen' expresses necessity; time adverb before infinitive.","Subject + Modal + Time + Infinitive (end)"),
("A2","Modalverben",["Er","will","Arzt","werden","."],"Er will Arzt werden.","'wollen' expresses intention; 'werden' is the infinitive.","Subject + Modal + Noun + Infinitive (end)"),
("A2","Modalverben",["Sie","darf","hier","nicht","rauchen","."],"Sie darf hier nicht rauchen.","'dürfen + nicht' = prohibition; location before 'nicht'.","Subject + Modal + Location + nicht + Infinitive (end)"),
("A2","Modalverben",["Wir","sollen","leise","sein","."],"Wir sollen leise sein.","'sollen' conveys an instruction; adjective before 'sein'.","Subject + Modal + Adjective + sein (end)"),
("A2","Modalverben",["Ihr","mögt","keinen","Spinat","."],"Ihr mögt keinen Spinat.","'mögen' expresses liking or disliking; 'keinen' negates the masculine noun.","Subject + mögen + keinen + Noun"),
("A2","Modalverben",["Ich","möchte","einen","Kaffee","bitte","."],"Ich möchte einen Kaffee bitte.","'möchte' (would like) is the polite form; 'bitte' at the end softens the request.","Subject + möchte + einen + Noun + bitte"),
("A2","Modalverben",["Er","kann","kein","Deutsch","sprechen","."],"Er kann kein Deutsch sprechen.","'kein' negates the language object; infinitive at end.","Subject + Modal + kein + Object + Infinitive (end)"),
("A2","Modalverben",["Wir","müssen","früh","aufstehen","."],"Wir müssen früh aufstehen.","'müssen' + separable infinitive; the whole infinitive (including prefix) goes to end.","Subject + Modal + Adverb + Separable infinitive (end)"),
("A2","Modalverben",["Du","kannst","mir","helfen","."],"Du kannst mir helfen.","'helfen' takes dative 'mir'; infinitive at end.","Subject + Modal + Dative pronoun + Infinitive (end)"),
("A2","Modalverben",["Sie","will","nicht","in","die","Schule","gehen","."],"Sie will nicht in die Schule gehen.","'nicht' before the destination phrase; infinitive at end.","Subject + Modal + nicht + Destination + Infinitive (end)"),
("A2","Modalverben",["Ich","soll","mehr","Sport","machen","."],"Ich soll mehr Sport machen.","'sollen' for advice/instruction; 'mehr' (more) before object.","Subject + Modal + mehr + Noun + Infinitive (end)"),
("A2","Modalverben",["Er","muss","zum","Arzt","gehen","."],"Er muss zum Arzt gehen.","'zum' = zu dem (dative); destination before infinitive.","Subject + Modal + zum + Noun + Infinitive (end)"),
("A2","Modalverben",["Wir","dürfen","hier","parken","."],"Wir dürfen hier parken.","'dürfen' expresses permission; location before infinitive.","Subject + Modal + Location + Infinitive (end)"),
("A2","Modalverben",["Du","musst","die","Hausaufgaben","machen","."],"Du musst die Hausaufgaben machen.","'müssen' + direct object + infinitive at end.","Subject + Modal + Object + Infinitive (end)"),
("A2","Modalverben",["Ich","kann","morgen","nicht","kommen","."],"Ich kann morgen nicht kommen.","Time adverb before 'nicht'; infinitive at very end.","Subject + Modal + Time + nicht + Infinitive (end)"),
("A2","Modalverben",["Sie","möchte","eine","Reise","nach","Italien","machen","."],"Sie möchte eine Reise nach Italien machen.","'möchte' + object + destination phrase + infinitive at end.","Subject + möchte + Object + Destination + Infinitive (end)"),
("A2","Modalverben",["Wir","wollen","ein","Haus","kaufen","."],"Wir wollen ein Haus kaufen.","'wollen' expresses desire; object before infinitive at end.","Subject + Modal + Object + Infinitive (end)"),
("A2","Modalverben",["Er","soll","sofort","zurückrufen","."],"Er soll sofort zurückrufen.","'sofort' (immediately) before the separable infinitive.","Subject + Modal + Adverb + Separable infinitive (end)"),
("A2","Modalverben",["Du","darfst","das","Wörterbuch","benutzen","."],"Du darfst das Wörterbuch benutzen.","'dürfen' for permission; object before infinitive.","Subject + Modal + Object + Infinitive (end)"),
("A2","Modalverben",["Kann","ich","Sie","etwas","fragen","?"],"Kann ich Sie etwas fragen?","Question: modal at position 1; formal 'Sie' as object.","Modal + Subject + Sie + etwas + Infinitive + ?"),
("A2","Modalverben",["Müsst","ihr","morgen","arbeiten","?"],"Müsst ihr morgen arbeiten?","Modal-first question: 'müsst ihr' = do you (pl.) have to.","Modal + Subject + Time + Infinitive + ?"),
("A2","Modalverben",["Er","kann","sehr","gut","kochen","."],"Er kann sehr gut kochen.","'sehr gut' adverb phrase before the infinitive.","Subject + Modal + sehr gut + Infinitive (end)"),
("A2","Modalverben",["Wir","müssen","das","Formular","ausfüllen","."],"Wir müssen das Formular ausfüllen.","Object before the separable infinitive ('ausfüllen').","Subject + Modal + Object + Separable infinitive (end)"),
("A2","Modalverben",["Sie","darf","das","Auto","benutzen","."],"Sie darf das Auto benutzen.","Permission: 'dürfen' + object + infinitive.","Subject + Modal + Object + Infinitive (end)"),
("A2","Modalverben",["Ich","will","ein","Buch","schreiben","."],"Ich will ein Buch schreiben.","'wollen' + object + infinitive at end.","Subject + Modal + Object + Infinitive (end)"),
("A2","Modalverben",["Du","sollst","die","Wahrheit","sagen","."],"Du sollst die Wahrheit sagen.","'sollen' for moral obligation; object before infinitive.","Subject + Modal + Object + Infinitive (end)"),
("A2","Modalverben",["Sie","kann","Klavier","spielen","."],"Sie kann Klavier spielen.","Ability with 'können'; instrument noun before infinitive.","Subject + Modal + Instrument + Infinitive (end)"),
("A2","Modalverben",["Er","muss","das","Projekt","fertig","machen","."],"Er muss das Projekt fertig machen.","'fertig machen' = to finish; 'fertig' acts as a complement before 'machen'.","Subject + Modal + Object + fertig + Infinitive (end)"),
("A2","Modalverben",["Wir","wollen","heute","Abend","ins","Kino","gehen","."],"Wir wollen heute Abend ins Kino gehen.","'ins Kino gehen' is a fixed phrase; time before destination.","Subject + Modal + Time + ins + Noun + Infinitive (end)"),
("A2","Modalverben",["Sie","muss","heute","Überstunden","machen","."],"Sie muss heute Überstunden machen.","Time adverb 'heute' before object; infinitive at end.","Subject + Modal + Time + Object + Infinitive (end)"),

# ── Perfekt (261–300) ─────────────────────
("A2","Perfekt",["Ich","habe","ein","Buch","gelesen","."],"Ich habe ein Buch gelesen.","Present perfect: auxiliary 'haben' at position 2; past participle at the end.","Subject + haben + Object + Past participle (end)"),
("A2","Perfekt",["Er","hat","Fußball","gespielt","."],"Er hat Fußball gespielt.","Regular past participle: ge- + stem + -t (gespielt).","Subject + hat + Object + Participle (ge-…-t)"),
("A2","Perfekt",["Wir","haben","Pizza","gegessen","."],"Wir haben Pizza gegessen.","Irregular participle: 'gegessen' (eaten); no article with 'Pizza'.","Subject + haben + Object + Irregular participle (end)"),
("A2","Perfekt",["Sie","ist","nach","Berlin","gefahren","."],"Sie ist nach Berlin gefahren.","Movement verbs use 'sein'; 'nach + city' for destination.","Subject + sein + Destination + Participle (end)"),
("A2","Perfekt",["Ich","bin","früh","aufgestanden","."],"Ich bin früh aufgestanden.","Separable verb perfekt: 'auf' inserts between 'ge-' and stem → 'aufgestanden'; uses 'sein'.","Subject + sein + Adverb + Separable participle (end)"),
("A2","Perfekt",["Du","hast","viel","geschlafen","."],"Du hast viel geschlafen.","Irregular participle: 'geschlafen'; 'viel' (much) before it.","Subject + hast + viel + Participle (end)"),
("A2","Perfekt",["Er","ist","gestern","gekommen","."],"Er ist gestern gekommen.","'kommen' uses 'sein'; time adverb before participle.","Subject + sein + Time + Participle (end)"),
("A2","Perfekt",["Wir","haben","das","Museum","besucht","."],"Wir haben das Museum besucht.","Inseparable verbs (be-, ver-, etc.) take no 'ge-' prefix.","Subject + haben + Object + Participle (no ge-, inseparable)"),
("A2","Perfekt",["Sie","hat","eine","E-Mail","geschrieben","."],"Sie hat eine E-Mail geschrieben.","Irregular participle: 'geschrieben'; object before participle.","Subject + hat + Object + Irregular participle (end)"),
("A2","Perfekt",["Ich","bin","zu","Fuß","gegangen","."],"Ich bin zu Fuß gegangen.","'gehen' uses 'sein'; manner phrase 'zu Fuß' before participle.","Subject + sein + zu Fuß + Participle (end)"),
("A2","Perfekt",["Er","hat","seinen","Schlüssel","verloren","."],"Er hat seinen Schlüssel verloren.","Inseparable verb 'verlieren': no 'ge-'; irregular participle 'verloren'.","Subject + hat + Object + Participle (no ge-)"),
("A2","Perfekt",["Wir","haben","die","ganze","Nacht","getanzt","."],"Wir haben die ganze Nacht getanzt.","Duration phrase 'die ganze Nacht' between auxiliary and participle.","Subject + haben + Duration + Participle (end)"),
("A2","Perfekt",["Sie","ist","um","Mitternacht","nach","Hause","gefahren","."],"Sie ist um Mitternacht nach Hause gefahren.","Movement + 'sein'; time first, then destination, participle at end.","Subject + sein + Time + Destination + Participle (end)"),
("A2","Perfekt",["Ich","habe","meinen","Vater","angerufen","."],"Ich habe meinen Vater angerufen.","Separable 'anrufen': participle = 'an' + 'ge' + 'rufen' = 'angerufen'.","Subject + haben + Object + Separable participle (end)"),
("A2","Perfekt",["Du","hast","einen","Fehler","gemacht","."],"Du hast einen Fehler gemacht.","Regular participle 'gemacht'; masculine accusative object.","Subject + hast + Object + Participle (end)"),
("A2","Perfekt",["Er","ist","nach","Hause","gegangen","."],"Er ist nach Hause gegangen.","'gehen' uses 'sein'; destination 'nach Hause' before participle.","Subject + sein + Destination + Participle (end)"),
("A2","Perfekt",["Wir","haben","lange","gewartet","."],"Wir haben lange gewartet.","Duration adverb 'lange' before the participle.","Subject + haben + lange + Participle (end)"),
("A2","Perfekt",["Sie","hat","das","Lied","gesungen","."],"Sie hat das Lied gesungen.","Irregular participle 'gesungen'; object before participle.","Subject + hat + Object + Irregular participle (end)"),
("A2","Perfekt",["Ich","habe","Deutsch","gelernt","."],"Ich habe Deutsch gelernt.","Regular participle 'gelernt'; no article for language names.","Subject + haben + Language + Participle (end)"),
("A2","Perfekt",["Er","hat","das","Auto","repariert","."],"Er hat das Auto repariert.","'-ieren' verbs: no 'ge-' prefix (repariert, not *gerepariert).","Subject + hat + Object + Participle (-iert, no ge-)"),
("A2","Perfekt",["Wir","sind","um","sechs","Uhr","aufgestanden","."],"Wir sind um sechs Uhr aufgestanden.","'aufstehen' (separable) + 'sein'; time before separable participle.","Subject + sein + Time + Separable participle (end)"),
("A2","Perfekt",["Sie","haben","den","Film","gesehen","."],"Sie haben den Film gesehen.","Irregular participle 'gesehen'; masculine accusative object.","Subject + haben + den + Noun + Participle (end)"),
("A2","Perfekt",["Ich","habe","meinen","Geburtstag","gefeiert","."],"Ich habe meinen Geburtstag gefeiert.","Regular participle 'gefeiert'; possessive accusative object.","Subject + haben + Object + Participle (end)"),
("A2","Perfekt",["Du","bist","mit","dem","Zug","gefahren","."],"Du bist mit dem Zug gefahren.","'fahren' uses 'sein'; means of transport with 'mit + dative'.","Subject + sein + mit + dem + Noun + Participle (end)"),
("A2","Perfekt",["Er","hat","seine","Hausaufgaben","vergessen","."],"Er hat seine Hausaufgaben vergessen.","Inseparable 'vergessen': no 'ge-'; irregular form stays 'vergessen'.","Subject + hat + Object + Participle (no ge-, inseparable)"),
("A2","Perfekt",["Wir","haben","im","Restaurant","gegessen","."],"Wir haben im Restaurant gegessen.","Location phrase before participle; 'gegessen' is irregular.","Subject + haben + Location + Participle (end)"),
("A2","Perfekt",["Sie","ist","nach","Hause","geflogen","."],"Sie ist nach Hause geflogen.","'fliegen' uses 'sein'; destination before participle.","Subject + sein + Destination + Participle (end)"),
("A2","Perfekt",["Ich","habe","ein","neues","Handy","gekauft","."],"Ich habe ein neues Handy gekauft.","Regular participle 'gekauft'; adjective inside the object phrase.","Subject + haben + ein + Adj + Object + Participle (end)"),
("A2","Perfekt",["Er","hat","die","Zeitung","gelesen","."],"Er hat die Zeitung gelesen.","Irregular participle 'gelesen'; definite accusative object.","Subject + hat + die + Noun + Participle (end)"),
("A2","Perfekt",["Du","hast","gut","gespielt","."],"Du hast gut gespielt.","Regular participle 'gespielt'; manner adverb 'gut' before it.","Subject + hast + gut + Participle (end)"),
("A2","Perfekt",["Sie","hat","einen","Deutschkurs","belegt","."],"Sie hat einen Deutschkurs belegt.","Inseparable 'belegen': no 'ge-'; regular ending '-t'.","Subject + hat + Object + Participle (no ge-)"),

# ── TeKaMoLo / Dativ / Präpositionen (301–350) ───────────────
("A2","TeKaMoLo",["Er","fährt","jeden","Tag","mit","dem","Fahrrad","zur","Arbeit","."],"Er fährt jeden Tag mit dem Fahrrad zur Arbeit.","TeKaMoLo order: Time (jeden Tag) → Manner (mit dem Fahrrad) → Place (zur Arbeit).","Subject + Verb + Time + Manner + Place"),
("A2","TeKaMoLo",["Sie","geht","abends","allein","ins","Fitnessstudio","."],"Sie geht abends allein ins Fitnessstudio.","Time (abends) → Manner (allein) → Place (ins Fitnessstudio).","Subject + Verb + Time + Manner + Place"),
("A2","TeKaMoLo",["Ich","fahre","morgen","mit","dem","Zug","nach","München","."],"Ich fahre morgen mit dem Zug nach München.","Time (morgen) → Manner (mit dem Zug) → Place (nach München).","Subject + Verb + Time + Manner + Place"),
("A2","TeKaMoLo",["Wir","essen","heute","Abend","zusammen","in","einem","Restaurant","."],"Wir essen heute Abend zusammen in einem Restaurant.","Time (heute Abend) → Manner (zusammen) → Place (in einem Restaurant).","Subject + Verb + Time + Manner + Place"),
("A2","TeKaMoLo",["Er","hat","gestern","schnell","seinen","Kaffee","getrunken","."],"Er hat gestern schnell seinen Kaffee getrunken.","Perfekt + TeKaMoLo: Time (gestern) → Manner (schnell) → Object → Participle.","Subject + haben + Time + Manner + Object + Participle (end)"),
("A2","Dativ",["Ich","helfe","meinem","Vater","im","Garten","."],"Ich helfe meinem Vater im Garten.","'helfen' always takes dative; 'meinem' is dative masculine.","Subject + helfen + Dative object + Location"),
("A2","Dativ",["Er","gibt","seiner","Schwester","ein","Geschenk","."],"Er gibt seiner Schwester ein Geschenk.","'geben' takes two objects: dative (seiner Schwester) then accusative (ein Geschenk).","Subject + geben + Dative + Accusative"),
("A2","Dativ",["Ich","danke","dir","für","deine","Hilfe","."],"Ich danke dir für deine Hilfe.","'danken' takes dative ('dir'); reason given with 'für + accusative'.","Subject + danken + Dative + für + Accusative"),
("A2","Dativ",["Sie","gehört","meiner","Freundin","."],"Sie gehört meiner Freundin.","'gehören' takes dative; feminine dative: 'meiner'.","Subject + gehören + Dative (fem.)"),
("A2","Dativ",["Wir","erzählen","unseren","Kindern","eine","Geschichte","."],"Wir erzählen unseren Kindern eine Geschichte.","'erzählen': dative ('unseren Kindern') then accusative ('eine Geschichte').","Subject + erzählen + Dative + Accusative"),
("A2","Dativ",["Er","schreibt","seinem","Bruder","eine","Nachricht","."],"Er schreibt seinem Bruder eine Nachricht.","'schreiben': dative recipient ('seinem Bruder') before accusative object.","Subject + schreiben + Dative + Accusative"),
("A2","Dativ",["Das","Buch","gefällt","mir","sehr","."],"Das Buch gefällt mir sehr.","'gefallen' takes dative; the thing liked is the grammatical subject.","Subject (thing) + gefallen + Dative + sehr"),
("A2","Dativ",["Ich","empfehle","Ihnen","dieses","Restaurant","."],"Ich empfehle Ihnen dieses Restaurant.","'empfehlen': dative 'Ihnen' (formal you) then accusative object.","Subject + empfehlen + Ihnen (dat.) + Accusative"),
("A2","Dativ",["Sie","hilft","ihrem","Nachbarn","oft","."],"Sie hilft ihrem Nachbarn oft.","'helfen' + dative; 'ihrem Nachbarn' = her neighbour (dative masculine).","Subject + helfen + Dative + Frequency"),
("A2","Dativ",["Das","Auto","gehört","unserem","Vater","."],"Das Auto gehört unserem Vater.","'gehören' + dative; 'unserem Vater' = dative masculine.","Subject + gehören + Dative (masc.)"),
("A2","Dativ",["Er","schenkt","seiner","Freundin","Blumen","."],"Er schenkt seiner Freundin Blumen.","'schenken': dative recipient then accusative object (no article with plural 'Blumen').","Subject + schenken + Dative + Accusative (pl.)"),
("A2","Dativ",["Ich","zeige","dir","den","Weg","."],"Ich zeige dir den Weg.","'zeigen': dative pronoun 'dir' before the accusative object.","Subject + zeigen + Dative pronoun + Accusative"),
("A2","Dativ",["Das","Essen","schmeckt","uns","sehr","gut","."],"Das Essen schmeckt uns sehr gut.","'schmecken' takes dative 'uns'; 'sehr gut' follows.","Subject + schmecken + Dative + sehr gut"),
("A2","Präpositionen",["Er","kommt","aus","einer","kleinen","Stadt","."],"Er kommt aus einer kleinen Stadt.","'aus + dative' for origin; 'einer' is dative feminine.","Subject + Verb + aus + einer + Adj + Noun"),
("A2","Präpositionen",["Sie","fährt","mit","ihren","Freunden","in","den","Urlaub","."],"Sie fährt mit ihren Freunden in den Urlaub.","'mit + dative' for company; 'in den Urlaub' (accusative, direction).","Subject + Verb + mit + Dative + in + Accusative"),
("A2","Präpositionen",["Das","Buch","liegt","auf","dem","Tisch","."],"Das Buch liegt auf dem Tisch.","'liegen auf + dative' = static position (where something rests).","Subject + liegen + auf + dem + Noun (dative, static)"),
("A2","Präpositionen",["Er","stellt","das","Buch","auf","den","Tisch","."],"Er stellt das Buch auf den Tisch.","'stellen auf + accusative' = movement onto a surface (direction).","Subject + stellen + Object + auf + den + Noun (acc., movement)"),
("A2","Präpositionen",["Ich","warte","auf","den","Bus","."],"Ich warte auf den Bus.","'warten auf + accusative' is a fixed prepositional verb.","Subject + warten + auf + Accusative"),
("A2","Präpositionen",["Er","interessiert","sich","für","Musik","."],"Er interessiert sich für Musik.","'sich interessieren für + accusative' is a reflexive prepositional verb.","Subject + sich interessieren + für + Accusative"),
("A2","Präpositionen",["Sie","freut","sich","auf","die","Ferien","."],"Sie freut sich auf die Ferien.","'sich freuen auf + accusative' = looking forward to something future.","Subject + sich freuen + auf + Accusative"),
("A2","Präpositionen",["Das","Café","ist","neben","dem","Bahnhof","."],"Das Café ist neben dem Bahnhof.","'neben + dative' for static location (next to).","Subject + sein + neben + dem + Noun"),
("A2","Präpositionen",["Er","hängt","das","Bild","an","die","Wand","."],"Er hängt das Bild an die Wand.","'hängen an + accusative' = movement (putting something on the wall).","Subject + hängen + Object + an + die + Noun (acc.)"),
("A2","Präpositionen",["Wir","treffen","uns","vor","dem","Kino","."],"Wir treffen uns vor dem Kino.","'vor + dative' for a static meeting point in front of something.","Subject + treffen + uns + vor + dem + Noun"),
("A2","Präpositionen",["Sie","denkt","oft","an","ihre","Heimat","."],"Sie denkt oft an ihre Heimat.","'denken an + accusative' is a fixed prepositional verb.","Subject + denken + oft + an + Accusative"),
("A2","Präpositionen",["Wir","sprechen","über","das","Wochenende","."],"Wir sprechen über das Wochenende.","'sprechen über + accusative' = to talk about something.","Subject + sprechen + über + Accusative"),
("A2","Präpositionen",["Er","ärgert","sich","über","den","Lärm","."],"Er ärgert sich über den Lärm.","'sich ärgern über + accusative' = to be annoyed about something.","Subject + sich ärgern + über + Accusative"),

# ── Komparativ / Imperativ (331–350) ──────
("A2","Komparativ",["Er","ist","größer","als","sein","Bruder","."],"Er ist größer als sein Bruder.","Comparative: adjective + -er + 'als' to compare two things.","Subject + sein + Adjective-er + als + Noun"),
("A2","Komparativ",["Das","neue","Handy","ist","teurer","als","das","alte","."],"Das neue Handy ist teurer als das alte.","'teurer' = teuer + -er (with umlaut); 'als' links the two items.","Subject + sein + Comparative + als + Object"),
("A2","Komparativ",["Sie","spricht","besser","Englisch","als","ich","."],"Sie spricht besser Englisch als ich.","Irregular comparative: 'gut → besser'; pronoun after 'als' stays nominative.","Subject + Verb + besser + Object + als + Pronoun"),
("A2","Komparativ",["Dieses","Restaurant","ist","so","gut","wie","das","andere","."],"Dieses Restaurant ist so gut wie das andere.","Equality: 'so + adjective + wie' (as good as).","Subject + sein + so + Adjective + wie + Object"),
("A2","Komparativ",["Der","Zug","ist","schneller","als","der","Bus","."],"Der Zug ist schneller als der Bus.","Standard comparative pattern: -er + als.","Subject + sein + Comparative + als + Subject"),
("A2","Komparativ",["Sie","lernt","fleißiger","als","ihr","Bruder","."],"Sie lernt fleißiger als ihr Bruder.","Adverb comparative: 'fleißig → fleißiger'; 'als' for comparison.","Subject + Verb + Adverb-er + als + Noun"),
("A2","Komparativ",["Heute","ist","es","wärmer","als","gestern","."],"Heute ist es wärmer als gestern.","Weather comparative; 'es' is the dummy weather subject.","Time + sein + es + Comparative + als + Time"),
("A2","Komparativ",["Meine","Wohnung","ist","kleiner","als","seine","."],"Meine Wohnung ist kleiner als seine.","Possessive pronoun 'seine' (his, referring to Wohnung) after 'als'.","Subject + sein + Comparative + als + Pronoun"),
("A2","Komparativ",["Er","arbeitet","mehr","als","alle","anderen","."],"Er arbeitet mehr als alle anderen.","Irregular comparative of 'viel': 'mehr' (more).","Subject + Verb + mehr + als + Pronoun/Noun"),
("A2","Komparativ",["Je","mehr","ich","lerne",",","desto","besser","werde","ich","."],"Je mehr ich lerne, desto besser werde ich.","'Je mehr…desto besser' = the more…the better; verb at end of first clause.","Je + mehr + Subject + Verb (end), desto + Adj + Verb + Subject"),
("A2","Imperativ",["Mach","bitte","die","Tür","zu","!"],"Mach bitte die Tür zu!","Imperative of separable verb: stem first, object in middle, prefix 'zu' at end.","Verb stem + bitte + Object + Prefix (end) + !"),
("A2","Imperativ",["Kommen","Sie","bitte","herein","!"],"Kommen Sie bitte herein!","Formal imperative: full verb + 'Sie' + 'bitte'; prefix 'herein' at end.","Verb + Sie + bitte + Prefix (end) + !"),
("A2","Imperativ",["Schreib","deinen","Namen","auf","das","Formular","!"],"Schreib deinen Namen auf das Formular!","Informal imperative (du-form): verb stem, then object, then 'auf + accusative'.","Verb stem + Object + auf + Accusative + !"),
("A2","Imperativ",["Seid","bitte","ruhig","!"],"Seid bitte ruhig!","Imperative ihr-form of 'sein': 'seid'; adjective after 'bitte'.","seid + bitte + Adjective + !"),
("A2","Imperativ",["Gehen","wir","zusammen","!"],"Gehen wir zusammen!","'Gehen wir' = let's go; verb first, 'wir' second.","Verb + wir + Adverb + !"),
("A2","Imperativ",["Hilf","mir","bitte","!"],"Hilf mir bitte!","Irregular imperative of 'helfen': 'hilf' (vowel change e→i); dative 'mir'.","hilf (irregular) + Dative + bitte + !"),
("A2","Imperativ",["Lest","den","Text","noch","einmal","!"],"Lest den Text noch einmal!","Ihr-form imperative: 'lest'; 'noch einmal' (once more) after object.","lest + Object + noch einmal + !"),
("A2","Imperativ",["Sprich","bitte","langsamer","!"],"Sprich bitte langsamer!","Irregular imperative: 'sprechen → sprich' (e→i vowel change); comparative adverb.","sprich (irregular) + bitte + Comparative adverb + !"),
("A2","Imperativ",["Nehmt","eure","Bücher","heraus","!"],"Nehmt eure Bücher heraus!","Ihr-form of separable 'herausnehmen': object before prefix.","nehmt + Possessive + Object + Prefix (end) + !"),
("A2","Modalverben",["Wir","können","das","Problem","lösen","."],"Wir können das Problem lösen.","'können' (can/be able to); object before infinitive at end.","Subject + können + Object + Infinitive (end)"),
("A2","Modalverben",["Er","darf","das","Zimmer","nicht","verlassen","."],"Er darf das Zimmer nicht verlassen.","'nicht' before the infinitive negates the action (prohibition).","Subject + Modal + Object + nicht + Infinitive (end)"),
("A2","Perfekt",["Ich","habe","meinen","Pass","vergessen","."],"Ich habe meinen Pass vergessen.","'vergessen' stays the same as its own participle (irregular, inseparable).","Subject + haben + Object + Participle (end)"),
("A2","Perfekt",["Er","ist","nach","Hause","gelaufen","."],"Er ist nach Hause gelaufen.","'laufen' uses 'sein' (movement verb); destination before participle.","Subject + sein + Destination + Participle (end)"),
("A2","Perfekt",["Wir","haben","das","Konzert","genossen","."],"Wir haben das Konzert genossen.","'genießen → genossen' irregular; inseparable: no 'ge-' prefix.","Subject + haben + Object + Participle (end)"),
("A2","Perfekt",["Du","hast","die","Aufgabe","erledigt","."],"Du hast die Aufgabe erledigt.","'erledigen → erledigt' regular; inseparable: no 'ge-'.","Subject + hast + Object + Participle (end)"),

# ══════════════════════════════════════════
# B1 — 50 sentences
# ══════════════════════════════════════════

# ── weil / da (351–365) ───────────────────
("B1","weil-Satz",["Ich","lerne","Deutsch",",","weil","ich","in","Deutschland","arbeiten","möchte","."],"Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.","In a 'weil' clause the verb moves to the very end; modal infinitive stays last.","Main clause + , + weil + Subject + … + Infinitive + Modal (end)"),
("B1","weil-Satz",["Er","kommt","nicht",",","weil","er","krank","ist","."],"Er kommt nicht, weil er krank ist.","'weil' sends the verb ('ist') to the end of the subordinate clause.","Main clause + , + weil + Subject + Adjective + Verb (end)"),
("B1","weil-Satz",["Wir","bleiben","zu","Hause",",","weil","das","Wetter","schlecht","ist","."],"Wir bleiben zu Hause, weil das Wetter schlecht ist.","Subordinating conjunction 'weil': verb at the very end.","Main clause + , + weil + Subject + Adjective + Verb (end)"),
("B1","weil-Satz",["Sie","ist","glücklich",",","weil","sie","die","Prüfung","bestanden","hat","."],"Sie ist glücklich, weil sie die Prüfung bestanden hat.","Perfect tense in weil-clause: participle then auxiliary at the very end.","Main clause + , + weil + Subject + Object + Participle + Auxiliary (end)"),
("B1","weil-Satz",["Ich","bin","müde",",","weil","ich","die","ganze","Nacht","gearbeitet","habe","."],"Ich bin müde, weil ich die ganze Nacht gearbeitet habe.","Perfect in weil-clause: auxiliary 'habe' comes after the participle (very end).","Main clause + , + weil + Subject + Time + Participle + haben (end)"),
("B1","weil-Satz",["Er","geht","früh","ins","Bett",",","weil","er","morgen","früh","aufstehen","muss","."],"Er geht früh ins Bett, weil er morgen früh aufstehen muss.","Modal + infinitive in weil-clause: infinitive then modal at very end.","Main clause + , + weil + Subject + Time + Infinitive + Modal (end)"),
("B1","weil-Satz",["Wir","freuen","uns",",","weil","wir","nächsten","Sommer","verreisen","werden","."],"Wir freuen uns, weil wir nächsten Sommer verreisen werden.","Future in weil-clause: infinitive then 'werden' at the end.","Main clause + , + weil + Subject + Time + Infinitive + werden (end)"),
("B1","weil-Satz",["Sie","lernt","viel",",","da","die","Prüfung","schwer","ist","."],"Sie lernt viel, da die Prüfung schwer ist.","'da' is a synonym of 'weil'; same verb-final rule applies.","Main clause + , + da + Subject + Adjective + Verb (end)"),
("B1","weil-Satz",["Ich","kaufe","keinen","Kaffee",",","weil","ich","kein","Geld","habe","."],"Ich kaufe keinen Kaffee, weil ich kein Geld habe.","'kein' negates the noun inside the weil-clause; verb at end.","Main clause + , + weil + Subject + kein + Noun + Verb (end)"),
("B1","weil-Satz",["Er","kann","nicht","mitkommen",",","weil","er","arbeiten","muss","."],"Er kann nicht mitkommen, weil er arbeiten muss.","Modal + infinitive in weil-clause; modal 'muss' at the very end.","Main clause + , + weil + Subject + Infinitive + Modal (end)"),
("B1","weil-Satz",["Sie","lächelt",",","weil","ihr","Mann","Blumen","mitgebracht","hat","."],"Sie lächelt, weil ihr Mann Blumen mitgebracht hat.","Separable participle in weil-clause ('mitgebracht'); auxiliary at end.","Main clause + , + weil + Subject + Object + Separable participle + haben (end)"),
("B1","weil-Satz",["Ich","mag","ihn",",","weil","er","immer","ehrlich","ist","."],"Ich mag ihn, weil er immer ehrlich ist.","'immer' (always) before the adjective; verb at end of weil-clause.","Main clause + , + weil + Subject + immer + Adjective + Verb (end)"),
("B1","weil-Satz",["Das","Restaurant","ist","voll",",","weil","heute","Wochenende","ist","."],"Das Restaurant ist voll, weil heute Wochenende ist.","Time adverb 'heute' before the noun in the weil-clause; verb at end.","Main clause + , + weil + Time + Noun + Verb (end)"),
("B1","weil-Satz",["Wir","nehmen","das","Taxi",",","weil","der","Bus","nicht","fährt","."],"Wir nehmen das Taxi, weil der Bus nicht fährt.","'nicht' before the verb at end of weil-clause.","Main clause + , + weil + Subject + nicht + Verb (end)"),
("B1","weil-Satz",["Er","freut","sich",",","weil","er","einen","neuen","Job","gefunden","hat","."],"Er freut sich, weil er einen neuen Job gefunden hat.","Perfect in weil-clause: participle then 'hat' at end.","Main clause + , + weil + Subject + Object + Participle + haben (end)"),

# ── dass / ob / wenn (366–385) ────────────
("B1","dass-Satz",["Ich","denke",",","dass","du","Recht","hast","."],"Ich denke, dass du Recht hast.","'dass' sends the finite verb ('hast') to the end of its clause.","Main clause + , + dass + Subject + Noun + Verb (end)"),
("B1","dass-Satz",["Er","sagt",",","dass","er","morgen","kommt","."],"Er sagt, dass er morgen kommt.","Time adverb 'morgen' before the verb at end of dass-clause.","Main clause + , + dass + Subject + Time + Verb (end)"),
("B1","dass-Satz",["Ich","weiß",",","dass","sie","in","Berlin","wohnt","."],"Ich weiß, dass sie in Berlin wohnt.","Location phrase before verb at end of dass-clause.","Main clause + , + dass + Subject + Location + Verb (end)"),
("B1","dass-Satz",["Sie","hofft",",","dass","das","Wetter","besser","wird","."],"Sie hofft, dass das Wetter besser wird.","'werden' (future auxiliary) at the very end of the dass-clause.","Main clause + , + dass + Subject + Adjective + werden (end)"),
("B1","dass-Satz",["Ich","bin","froh",",","dass","du","hier","bist","."],"Ich bin froh, dass du hier bist.","Adjective 'froh' in main clause; 'bist' at end of dass-clause.","Main clause (adj.) + , + dass + Subject + Adverb + Verb (end)"),
("B1","ob-Satz",["Er","fragt",",","ob","sie","kommt","."],"Er fragt, ob sie kommt.","'ob' introduces an indirect yes/no question; verb at the very end.","Main clause + , + ob + Subject + Verb (end)"),
("B1","ob-Satz",["Ich","weiß","nicht",",","ob","er","Zeit","hat","."],"Ich weiß nicht, ob er Zeit hat.","Indirect question with 'ob'; 'hat' at very end of ob-clause.","Main clause (neg.) + , + ob + Subject + Noun + Verb (end)"),
("B1","ob-Satz",["Sie","fragt",",","ob","wir","mitkommen","wollen","."],"Sie fragt, ob wir mitkommen wollen.","Modal verb 'wollen' at the very end of the ob-clause.","Main clause + , + ob + Subject + Infinitive + Modal (end)"),
("B1","wenn-Satz",["Wenn","ich","Zeit","habe",",","gehe","ich","ins","Kino","."],"Wenn ich Zeit habe, gehe ich ins Kino.","'wenn' clause fronted → verb ('gehe') jumps to position 1 of main clause.","wenn + Subject + Object + Verb (end), Verb + Subject + Complement"),
("B1","wenn-Satz",["Wenn","das","Wetter","schön","ist",",","machen","wir","einen","Ausflug","."],"Wenn das Wetter schön ist, machen wir einen Ausflug.","Verb-end in wenn-clause; verb-second in the following main clause.","wenn + Subject + Adjective + Verb (end), Verb + Subject + Object"),
("B1","wenn-Satz",["Ich","rufe","dich","an",",","wenn","ich","zu","Hause","bin","."],"Ich rufe dich an, wenn ich zu Hause bin.","Main clause first (separable verb); wenn-clause appended with verb at end.","Main clause + , + wenn + Subject + Location + Verb (end)"),
("B1","wenn-Satz",["Wenn","er","aufwacht",",","trinkt","er","zuerst","Kaffee","."],"Wenn er aufwacht, trinkt er zuerst Kaffee.","Separable verb 'aufwacht' at end of wenn-clause; main clause inverts.","wenn + Subject + Verb (end), Verb + Subject + Adverb + Object"),
("B1","dass-Satz",["Wir","glauben",",","dass","er","die","Wahrheit","sagt","."],"Wir glauben, dass er die Wahrheit sagt.","Object 'die Wahrheit' before verb at end of dass-clause.","Main clause + , + dass + Subject + Object + Verb (end)"),
("B1","dass-Satz",["Sie","wünscht","sich",",","dass","alle","glücklich","sind","."],"Sie wünscht sich, dass alle glücklich sind.","Reflexive verb in main clause; predicate adjective before 'sind' at end.","Main clause (reflexive) + , + dass + Subject + Adjective + Verb (end)"),
("B1","ob-Satz",["Ich","frage","mich",",","ob","das","richtig","ist","."],"Ich frage mich, ob das richtig ist.","Reflexive 'sich fragen' + ob-clause; adjective before verb at end.","Main clause (reflexive) + , + ob + Subject + Adjective + Verb (end)"),
("B1","ob-Satz",["Er","weiß","nicht",",","ob","er","die","Stelle","bekommt","."],"Er weiß nicht, ob er die Stelle bekommt.","Negation in main clause; object before verb at end of ob-clause.","Main clause (neg.) + , + ob + Subject + Object + Verb (end)"),
("B1","wenn-Satz",["Wenn","du","willst",",","kannst","du","mitkommen","."],"Wenn du willst, kannst du mitkommen.","Short wenn-clause; main clause has modal at position 1 after comma.","wenn + Subject + Modal (end), Modal + Subject + Infinitive"),

# ── Relativsatz (387–395) ─────────────────
("B1","Relativsatz",["Das","Buch",",","das","ich","lese",",","ist","sehr","interessant","."],"Das Buch, das ich lese, ist sehr interessant.","Relative pronoun 'das' (neuter, matches 'Buch'); verb 'lese' at end of relative clause.","Noun + , + Rel. pronoun + Subject + Verb (end) + , + Main verb"),
("B1","Relativsatz",["Der","Mann",",","der","dort","steht",",","ist","mein","Lehrer","."],"Der Mann, der dort steht, ist mein Lehrer.","'der' is the masculine nominative relative pronoun; verb at end of clause.","Noun + , + der + Adverb + Verb (end) + , + Main verb"),
("B1","Relativsatz",["Die","Frau",",","die","ich","kenne",",","heißt","Maria","."],"Die Frau, die ich kenne, heißt Maria.","Feminine relative pronoun 'die' (accusative here); verb at end.","Noun + , + die + Subject + Verb (end) + , + Main verb"),
("B1","Relativsatz",["Das","ist","die","Stadt",",","in","der","ich","geboren","bin","."],"Das ist die Stadt, in der ich geboren bin.","Prepositional relative clause: 'in der' (feminine dative, location).","Main clause + , + in + der + Subject + Participle + sein (end)"),
("B1","Relativsatz",["Der","Film",",","den","wir","gesehen","haben",",","war","sehr","gut","."],"Der Film, den wir gesehen haben, war sehr gut.","'den' = masculine accusative relative pronoun; perfect at end of clause.","Noun + , + den + Subject + Participle + haben (end) + , + Main verb"),
("B1","Relativsatz",["Das","Haus",",","in","dem","wir","wohnen",",","ist","sehr","alt","."],"Das Haus, in dem wir wohnen, ist sehr alt.","'in dem' (neuter dative, location); verb 'wohnen' at end of clause.","Noun + , + in dem + Subject + Verb (end) + , + Main verb"),
("B1","Relativsatz",["Ich","suche","jemanden",",","der","mir","helfen","kann","."],"Ich suche jemanden, der mir helfen kann.","Relative clause with modal: 'kann' at the very end.","Main clause + , + der + Dative + Infinitive + Modal (end)"),
("B1","Relativsatz",["Das","ist","das","Geschenk",",","das","ich","dir","gekauft","habe","."],"Das ist das Geschenk, das ich dir gekauft habe.","Perfect in relative clause: participle then 'habe' at end.","Main clause + , + das + Subject + Dative + Participle + haben (end)"),

# ── Extra A1 to reach 200 ─────────────────
("A1","Grundsätze",["Ich","komme","aus","der","Türkei","."],"Ich komme aus der Türkei.","'aus + der Türkei': Turkey is one of the few countries that takes an article ('die Türkei').","Subject + Verb + aus + Article + Country"),
("A1","Grundsätze",["Das","Wasser","ist","sehr","kalt","."],"Das Wasser ist sehr kalt.","Simple declarative: neuter subject + sein + sehr + adjective.","Subject (das) + sein + sehr + Adjective"),
("A1","Grundsätze",["Sie","tanzt","gern","mit","ihren","Freunden","."],"Sie tanzt gern mit ihren Freunden.","'gern' follows the verb; 'mit + dative plural' (ihren).","Subject + Verb + gern + mit + Dative plural"),
("A1","Grundsätze",["Wir","sitzen","im","Park","und","lesen","."],"Wir sitzen im Park und lesen.","Two verbs share the same subject; second verb at end without repeating subject.","Subject + Verb + Location + und + Verb"),
("A1","Grundsätze",["Er","öffnet","die","Tür","für","mich","."],"Er öffnet die Tür für mich.","Object ('die Tür') before 'für + accusative' (purpose/beneficiary).","Subject + Verb + Object + für + Pronoun"),
("A1","Grundsätze",["Ich","habe","kein","Auto",",","ich","fahre","Fahrrad","."],"Ich habe kein Auto, ich fahre Fahrrad.","Two main clauses with a comma; 'Fahrrad fahren' is a fixed phrase.","Subject + haben + kein + Noun, Subject + Verb + Noun"),
("A1","Grundsätze",["Der","Supermarkt","ist","um","die","Ecke","."],"Der Supermarkt ist um die Ecke.","'um die Ecke' (around the corner) is a fixed locative phrase.","Subject + sein + um die Ecke (fixed phrase)"),
("A1","Grundsätze",["Mein","Freund","kommt","aus","Brasilien","."],"Mein Freund kommt aus Brasilien.","'aus + country' (no article for most countries) expresses origin.","Possessive + Noun + Verb + aus + Country"),
("A1","Grundsätze",["Wir","lernen","jeden","Tag","neue","Wörter","."],"Wir lernen jeden Tag neue Wörter.","Time 'jeden Tag' after verb; accusative plural adjective '-e'.","Subject + Verb + Time + Adjective(-e) + Plural noun"),
("A1","Grundsätze",["Sie","schreibt","einen","Brief","an","ihre","Mutter","."],"Sie schreibt einen Brief an ihre Mutter.","Object first; 'an + accusative' shows the recipient's direction.","Subject + Verb + Object + an + Possessive + Noun"),
("A1","Grundsätze",["Das","ist","eine","gute","Idee","."],"Das ist eine gute Idee.","Feminine noun: 'eine gute Idee' (strong ending '-e' after indefinite article).","Das + sein + eine + Adjective(-e) + Noun"),
("A1","Grundsätze",["Er","macht","jeden","Abend","Sport","."],"Er macht jeden Abend Sport.","'Sport machen' is a fixed phrase; time 'jeden Abend' between verb and noun.","Subject + Verb + Time + Noun (set phrase)"),
("A1","Grundsätze",["Ich","trinke","einen","Kaffee","im","Café","."],"Ich trinke einen Kaffee im Café.","Masculine accusative 'einen Kaffee'; location 'im Café' (dative) at end.","Subject + Verb + einen + Noun + im + Place"),
("A1","Grundsätze",["Du","sprichst","sehr","gut","Deutsch","."],"Du sprichst sehr gut Deutsch.","Manner adverb phrase 'sehr gut' before the language object.","Subject + Verb + sehr gut + Language"),
("A1","Grundsätze",["Wir","gehen","zusammen","in","die","Stadt","."],"Wir gehen zusammen in die Stadt.","'zusammen' (together) after verb; 'in die Stadt' (accusative, direction).","Subject + Verb + zusammen + in + die + Noun"),
# ── Extra A2 to reach 150 ─────────────────
("A2","Dativ",["Er","empfiehlt","ihr","das","neue","Restaurant","."],"Er empfiehlt ihr das neue Restaurant.","'empfehlen': dative pronoun 'ihr' (her) before the accusative object.","Subject + empfehlen + Dative pronoun + Accusative"),
("A2","Präpositionen",["Sie","kümmert","sich","um","ihre","Eltern","."],"Sie kümmert sich um ihre Eltern.","'sich kümmern um + accusative' = to take care of someone.","Subject + sich kümmern + um + Accusative"),
# ── Passiv / Konjunktiv II (396–400) ──────
("B1","Passiv",["Das","Buch","wird","von","dem","Autor","geschrieben","."],"Das Buch wird von dem Autor geschrieben.","Passive present: 'werden' at position 2; past participle at the very end; agent with 'von + dative'.","Subject + werden + von + Dative (agent) + Participle (end)"),
("B1","Passiv",["Die","Fenster","werden","jeden","Tag","geputzt","."],"Die Fenster werden jeden Tag geputzt.","Agentless passive: time adverb before participle at end.","Subject + werden + Time + Participle (end)"),
("B1","Passiv",["Der","Brief","wurde","gestern","abgeschickt","."],"Der Brief wurde gestern abgeschickt.","Passive past (Präteritum): 'wurde' + time + separable participle at end.","Subject + wurde + Time + Participle (end)"),
("B1","Passiv",["Das","Essen","wird","gerade","zubereitet","."],"Das Essen wird gerade zubereitet.","'gerade' (right now) in passive shows ongoing action.","Subject + werden + gerade + Participle (end)"),
("B1","Konjunktiv II",["Wenn","ich","reich","wäre",",","würde","ich","reisen","."],"Wenn ich reich wäre, würde ich reisen.","Unreal conditional: 'wäre' (Konjunktiv II of sein) + 'würde + infinitive' in main clause.","wenn + Subject + Adjective + wäre (end), würde + Subject + Infinitive"),
("B1","Konjunktiv II",["Er","würde","gern","mehr","Sport","machen","."],"Er würde gern mehr Sport machen.","'würde + infinitive' expresses an unreal wish; 'gern' shows desire.","Subject + würde + gern + Object + Infinitive (end)"),
("B1","Konjunktiv II",["Könntest","du","mir","bitte","helfen","?"],"Könntest du mir bitte helfen?","Konjunktiv II of 'können' ('könntest') at position 1 for a polite request.","könntest + Subject + Dative + bitte + Infinitive (end) + ?"),
("B1","Konjunktiv II",["Ich","hätte","gern","mehr","Zeit","."],"Ich hätte gern mehr Zeit.","'hätte' = Konjunktiv II of 'haben'; expresses an unreal wish.","Subject + hätte + gern + Object"),
("B1","Konjunktiv II",["Du","solltest","mehr","schlafen","."],"Du solltest mehr schlafen.","'solltest' = Konjunktiv II of 'sollen'; used for advice.","Subject + solltest + mehr + Infinitive (end)"),
("B1","Konjunktiv II",["Wenn","er","früher","gekommen","wäre",",","hätten","wir","ihn","gesehen","."],"Wenn er früher gekommen wäre, hätten wir ihn gesehen.","Past unreal conditional: Konjunktiv II perfect (wäre + participle) in wenn-clause; hätten + participle in main clause.","wenn + Subject + Adverb + Participle + wäre (end), hätten + Subject + Object + Participle"),
]

print(f"Total raw sentences: {len(RAW)}")
counts = {}
for r in RAW:
    counts[r[0]] = counts.get(r[0], 0) + 1
print("Per level:", counts)

questions = []
n = 1
for (level, topic, tokens, correct, tip, structure) in RAW:
    scrambled = scramble(tokens)
    questions.append({
        "id":        sid(n),
        "level":     level,
        "topic":     topic,
        "words":     scrambled,
        "answer":    tokens,
        "correct":   correct,
        "tip":       tip,
        "structure": structure,
    })
    n += 1

out_path = r'C:\Users\ADELEKEOLORUNISOLAO\Desktop\goethe-trainer\public\data\sentence_order.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f"\nSaved {len(questions)} questions to {out_path}")
