const fs = require('fs');
const OUT = 'C:/Users/ADELEKEOLORUNISOLAO/Desktop/goethe-trainer/public/data/convo_b1.json';

const b1 = [
  {id:'CONV041',level:'B1',title:'Klimawandel und Alltag',description:'Zwei Freunde diskutieren über persönliche Maßnahmen gegen den Klimawandel.',
   speakers:[{name:'Leila',voice:1},{name:'Tobias',voice:2}],
   lines:[
    {speaker:'Leila',side:'left',de:'Tobias, hast du den neuen Bericht zum Klimawandel gelesen? Die Lage ist wirklich ernst.',en:'Tobias, did you read the new climate change report? The situation is really serious.'},
    {speaker:'Tobias',side:'right',de:'Ja, ich habe davon gehört. Aber was kann man als Einzelperson schon tun?',en:'Yes, I heard about it. But what can an individual do about it?'},
    {speaker:'Leila',side:'left',de:'Sehr viel! Ich esse zum Beispiel seit einem Jahr kein Fleisch mehr und fahre mit dem Rad zur Arbeit.',en:'A lot! For example, I have not eaten meat for a year and cycle to work.'},
    {speaker:'Tobias',side:'right',de:'Das ist beeindruckend. Aber reicht das wirklich aus, wenn große Unternehmen weiter so viel CO₂ ausstoßen?',en:'That is impressive. But is it really enough when large companies continue to emit so much CO₂?'},
    {speaker:'Leila',side:'left',de:'Natürlich brauchen wir auch politische Veränderungen. Aber jeder Beitrag zählt. Unser Konsumverhalten beeinflusst den Markt.',en:'Of course we also need political change. But every contribution counts. Our consumption behaviour influences the market.'},
    {speaker:'Tobias',side:'right',de:'Da hast du einen Punkt. Ich habe tatsächlich überlegt, weniger zu fliegen. Letztes Jahr war ich fünfmal im Ausland.',en:'You have a point there. I have actually been thinking about flying less. Last year I was abroad five times.'},
    {speaker:'Leila',side:'left',de:'Das wäre schon ein großer Schritt. Hast du schon mal Urlaub in Deutschland gemacht?',en:'That would already be a big step. Have you ever taken a holiday in Germany?'},
    {speaker:'Tobias',side:'right',de:'Ja, einmal in Bayern. Es war wunderschön, muss ich zugeben.',en:'Yes, once in Bavaria. It was beautiful, I have to admit.'},
    {speaker:'Leila',side:'left',de:'Siehst du! Man muss nicht weit reisen, um tolle Erfahrungen zu machen.',en:'You see! You don\'t have to travel far to have great experiences.'},
    {speaker:'Tobias',side:'right',de:'Stimmt. Ich werde auch anfangen, mehr auf meine Plastiknutzung zu achten.',en:'True. I will also start paying more attention to my plastic use.'},
    {speaker:'Leila',side:'left',de:'Prima! Kleine Schritte im Alltag machen zusammen einen großen Unterschied.',en:'Great! Small steps in everyday life together make a big difference.'},
    {speaker:'Tobias',side:'right',de:'Du hast mich überzeugt. Vielleicht kommen wir demnächst zusammen zur Fridays-for-Future-Demo?',en:'You have convinced me. Maybe we could go to the Fridays for Future demo together soon?'},
    {speaker:'Leila',side:'left',de:'Sehr gerne! Und ich zeige dir noch ein paar andere Möglichkeiten, wie man nachhaltiger leben kann.',en:'I\'d love that! And I\'ll show you a few other ways to live more sustainably.'},
    {speaker:'Tobias',side:'right',de:'Abgemacht. Danke, Leila – du inspirierst mich wirklich.',en:'Deal. Thank you, Leila – you really inspire me.'},
  ]},
  {id:'CONV042',level:'B1',title:'Digitalisierung im Arbeitsalltag',description:'Zwei Kollegen sprechen über die Auswirkungen digitaler Technologien auf ihre Arbeit.',
   speakers:[{name:'Frau Hartmann',voice:1},{name:'Herr Seidel',voice:2}],
   lines:[
    {speaker:'Frau Hartmann',side:'left',de:'Herr Seidel, wie finden Sie das neue digitale Projektmanagement-Tool, das wir letzte Woche eingeführt haben?',en:'Mr Seidel, what do you think of the new digital project management tool we introduced last week?'},
    {speaker:'Herr Seidel',side:'right',de:'Ehrlich gesagt bin ich noch nicht überzeugt. Die Einarbeitung hat viel Zeit gekostet.',en:'Honestly I am not yet convinced. The familiarisation has taken a lot of time.'},
    {speaker:'Frau Hartmann',side:'left',de:'Das verstehe ich. Aber langfristig werden wir effizienter arbeiten. Die Kommunikation im Team ist schon besser.',en:'I understand that. But in the long run we will work more efficiently. Team communication is already better.'},
    {speaker:'Herr Seidel',side:'right',de:'Das stimmt. Aber ich mache mir Sorgen, dass ältere Kollegen Schwierigkeiten haben könnten.',en:'That is true. But I am worried that older colleagues might have difficulties.'},
    {speaker:'Frau Hartmann',side:'left',de:'Deswegen haben wir ja die Schulungen angeboten. Haben Sie an dem Workshop teilgenommen?',en:'That is exactly why we offered the training sessions. Did you attend the workshop?'},
    {speaker:'Herr Seidel',side:'right',de:'Ja, kurz. Aber ich bräuchte mehr Übungszeit. Gibt es auch Online-Tutorials?',en:'Yes, briefly. But I would need more practice time. Are there also online tutorials?'},
    {speaker:'Frau Hartmann',side:'left',de:'Ja, auf der Plattform gibt es viele Videos. Ich schicke Ihnen den Link.',en:'Yes, there are many videos on the platform. I will send you the link.'},
    {speaker:'Herr Seidel',side:'right',de:'Danke. Glauben Sie, dass durch KI bald viele Stellen wegfallen werden?',en:'Thank you. Do you think that many jobs will soon disappear due to AI?'},
    {speaker:'Frau Hartmann',side:'left',de:'Manche schon – aber es entstehen auch neue Berufe. Wir müssen uns anpassen und weiterlernen.',en:'Some will – but new professions are also emerging. We need to adapt and keep learning.'},
    {speaker:'Herr Seidel',side:'right',de:'Das sehe ich auch so. Lebenslanges Lernen ist heute wichtiger denn je.',en:'I see it the same way. Lifelong learning is more important today than ever.'},
    {speaker:'Frau Hartmann',side:'left',de:'Genau. Unser Unternehmen bietet auch interne Weiterbildungen an. Haben Sie schon den Katalog gesehen?',en:'Exactly. Our company also offers internal further training. Have you already seen the catalogue?'},
    {speaker:'Herr Seidel',side:'right',de:'Noch nicht. Ich werde ihn mir heute noch ansehen.',en:'Not yet. I will look at it today.'},
    {speaker:'Frau Hartmann',side:'left',de:'Gut. Der Kurs über Datenanalyse soll besonders interessant sein.',en:'Good. The course on data analysis is said to be particularly interesting.'},
    {speaker:'Herr Seidel',side:'right',de:'Das klingt gut. Vielleicht melden wir uns ja zusammen an?',en:'That sounds good. Maybe we can sign up together?'},
  ]},
  {id:'CONV043',level:'B1',title:'Auslandssemester planen',description:'Eine Studentin bespricht mit ihrer Beraterin die Möglichkeiten für ein Auslandssemester.',
   speakers:[{name:'Amira',voice:1},{name:'Beraterin Frau Jung',voice:2}],
   lines:[
    {speaker:'Amira',side:'left',de:'Guten Tag, Frau Jung. Ich interessiere mich für ein Auslandssemester und bräuchte Ihre Beratung.',en:'Good day, Ms Jung. I am interested in a semester abroad and would need your advice.'},
    {speaker:'Beraterin Frau Jung',side:'right',de:'Herzlich willkommen, Amira. In welchem Semester sind Sie gerade?',en:'Welcome, Amira. Which semester are you currently in?'},
    {speaker:'Amira',side:'left',de:'Ich bin im dritten Semester Betriebswirtschaft. Ich würde gerne ab dem fünften Semester ins Ausland.',en:'I am in my third semester of business studies. I would like to go abroad from the fifth semester.'},
    {speaker:'Beraterin Frau Jung',side:'right',de:'Das ist ein guter Zeitpunkt. Welche Länder interessieren Sie?',en:'That is a good time. Which countries interest you?'},
    {speaker:'Amira',side:'left',de:'Am liebsten würde ich nach Spanien oder Argentinien, um mein Spanisch zu verbessern.',en:'I would most like to go to Spain or Argentina to improve my Spanish.'},
    {speaker:'Beraterin Frau Jung',side:'right',de:'Sehr gut. Wir haben Partnerschaftsabkommen mit mehreren Universitäten in beiden Ländern.',en:'Very good. We have partnership agreements with several universities in both countries.'},
    {speaker:'Amira',side:'left',de:'Werden meine Noten anerkannt, wenn ich zurückkomme?',en:'Will my grades be recognised when I come back?'},
    {speaker:'Beraterin Frau Jung',side:'right',de:'Ja, durch das ECTS-System werden die meisten Kurse angerechnet. Wichtig ist die Kursauswahl.',en:'Yes, through the ECTS system most courses are credited. The choice of courses is important.'},
    {speaker:'Amira',side:'left',de:'Und wie sieht es mit der Finanzierung aus? Das ist meine größte Sorge.',en:'And what about the financing? That is my biggest concern.'},
    {speaker:'Beraterin Frau Jung',side:'right',de:'Es gibt das Erasmus-Stipendium für europäische Länder. Für Argentinien gibt es andere Förderprogramme.',en:'There is the Erasmus scholarship for European countries. For Argentina there are other funding programmes.'},
    {speaker:'Amira',side:'left',de:'Wie hoch ist die monatliche Förderung beim Erasmus-Programm?',en:'How much is the monthly funding with the Erasmus programme?'},
    {speaker:'Beraterin Frau Jung',side:'right',de:'Zwischen dreihundert und fünfhundert Euro pro Monat, je nach Zielland.',en:'Between three hundred and five hundred euros per month, depending on the destination country.'},
    {speaker:'Amira',side:'left',de:'Das hilft schon sehr. Wann muss ich mich bewerben?',en:'That helps a lot. When do I have to apply?'},
    {speaker:'Beraterin Frau Jung',side:'right',de:'Die Bewerbungsfrist ist im November für das folgende Wintersemester. Ich empfehle frühzeitig anzufangen.',en:'The application deadline is in November for the following winter semester. I recommend starting early.'},
  ]},
  {id:'CONV044',level:'B1',title:'Berufswahl und Zukunft',description:'Vater und Sohn sprechen über die Berufswahl nach dem Abitur.',
   speakers:[{name:'Sohn Leon',voice:1},{name:'Vater Markus',voice:2}],
   lines:[
    {speaker:'Sohn Leon',side:'left',de:'Papa, ich weiß immer noch nicht, was ich nach dem Abitur machen soll.',en:'Dad, I still don\'t know what to do after my A-levels.'},
    {speaker:'Vater Markus',side:'right',de:'Das ist völlig normal, Leon. Was interessiert dich denn am meisten?',en:'That is completely normal, Leon. What interests you most?'},
    {speaker:'Sohn Leon',side:'left',de:'Ich finde Informatik super, aber auch Psychologie ist interessant. Ich kann mich nicht entscheiden.',en:'I think computer science is great, but psychology is also interesting. I can\'t decide.'},
    {speaker:'Vater Markus',side:'right',de:'Hast du schon Praktika in einem dieser Bereiche gemacht?',en:'Have you already done internships in any of these areas?'},
    {speaker:'Sohn Leon',side:'left',de:'Letztes Jahr war ich zwei Wochen in einer IT-Firma. Es hat mir gut gefallen.',en:'Last year I was at an IT company for two weeks. I enjoyed it.'},
    {speaker:'Vater Markus',side:'right',de:'Das ist ein gutes Zeichen. Was hat dir besonders gut gefallen?',en:'That is a good sign. What did you particularly enjoy?'},
    {speaker:'Sohn Leon',side:'left',de:'Das Lösen von Problemen und das Programmieren. Aber der soziale Kontakt hat mir gefehlt.',en:'Solving problems and programming. But I missed the social contact.'},
    {speaker:'Vater Markus',side:'right',de:'Dann wäre vielleicht Wirtschaftsinformatik ein guter Kompromiss. Da hast du beides.',en:'Then perhaps business informatics would be a good compromise. You have both there.'},
    {speaker:'Sohn Leon',side:'left',de:'Daran habe ich noch nicht gedacht! Das klingt gut. Welche Universitäten sind da gut?',en:'I hadn\'t thought of that! That sounds good. Which universities are good for that?'},
    {speaker:'Vater Markus',side:'right',de:'In München und Darmstadt gibt es sehr gute Programme. Schau dir die mal an.',en:'There are very good programmes in Munich and Darmstadt. Have a look at those.'},
    {speaker:'Sohn Leon',side:'left',de:'Ich werde heute Abend noch recherchieren. Aber was, wenn das Studium zu schwer ist?',en:'I will research this evening. But what if the studies are too difficult?'},
    {speaker:'Vater Markus',side:'right',de:'Schwierigkeiten gehören dazu. Wichtig ist, dass du für das Thema brennst.',en:'Difficulties are part of it. What matters is that you are passionate about the subject.'},
    {speaker:'Sohn Leon',side:'left',de:'Stimmt. Ich glaube, ich mache dieses Jahr noch einen Informatikkurs online, um zu testen, ob es das Richtige ist.',en:'True. I think I will do an online computer science course this year to test whether it\'s the right thing.'},
    {speaker:'Vater Markus',side:'right',de:'Ausgezeichnete Idee! Du kannst auch zum Berufsberater gehen. Die helfen gerne.',en:'Excellent idea! You can also go to a careers advisor. They are happy to help.'},
  ]},
  {id:'CONV045',level:'B1',title:'Gesundheitssystem — Erfahrungen',description:'Zwei Bekannte vergleichen das Gesundheitssystem in verschiedenen Ländern.',
   speakers:[{name:'Giulia',voice:1},{name:'Thomas',voice:2}],
   lines:[
    {speaker:'Giulia',side:'left',de:'Thomas, ich war letzte Woche beim Arzt und musste drei Wochen auf einen Termin warten. Ist das normal hier?',en:'Thomas, I was at the doctor last week and had to wait three weeks for an appointment. Is that normal here?'},
    {speaker:'Thomas',side:'right',de:'Leider schon, besonders bei Fachärzten. In Großstädten ist es noch schlimmer.',en:'Unfortunately yes, especially with specialists. In big cities it is even worse.'},
    {speaker:'Giulia',side:'left',de:'In Italien geht das schneller, aber die Qualität variiert sehr je nach Region.',en:'In Italy it is faster, but the quality varies greatly depending on the region.'},
    {speaker:'Thomas',side:'right',de:'Das deutsche System ist insgesamt sehr gut, aber die Bürokratie ist manchmal überwältigend.',en:'The German system is very good overall, but the bureaucracy is sometimes overwhelming.'},
    {speaker:'Giulia',side:'left',de:'Was ist der Unterschied zwischen gesetzlicher und privater Krankenversicherung?',en:'What is the difference between statutory and private health insurance?'},
    {speaker:'Thomas',side:'right',de:'Privatpatienten bekommen oft schneller Termine und haben Zugang zu bestimmten Leistungen.',en:'Private patients often get appointments faster and have access to certain services.'},
    {speaker:'Giulia',side:'left',de:'Das klingt ungerecht. Sollte Gesundheitsversorgung nicht für alle gleich sein?',en:'That sounds unfair. Shouldn\'t healthcare be the same for everyone?'},
    {speaker:'Thomas',side:'right',de:'Im Prinzip ja. Aber das ist eine politische Diskussion, die seit Jahrzehnten geführt wird.',en:'In principle yes. But that is a political discussion that has been going on for decades.'},
    {speaker:'Giulia',side:'left',de:'Gibt es genug Ärzte in Deutschland, oder gibt es einen Mangel?',en:'Are there enough doctors in Germany, or is there a shortage?'},
    {speaker:'Thomas',side:'right',de:'Es gibt einen Ärztemangel, besonders auf dem Land. Viele Dörfer haben keinen eigenen Arzt mehr.',en:'There is a shortage of doctors, especially in rural areas. Many villages no longer have their own doctor.'},
    {speaker:'Giulia',side:'left',de:'Das ist ein echtes Problem. Was sind die Gründe dafür?',en:'That is a real problem. What are the reasons for it?'},
    {speaker:'Thomas',side:'right',de:'Viele junge Ärzte wollen lieber in Städten arbeiten. Außerdem ist die Ausbildung sehr lang und teuer.',en:'Many young doctors prefer to work in cities. Also the training is very long and expensive.'},
    {speaker:'Giulia',side:'left',de:'Vielleicht könnten Telemedizin und KI dabei helfen, die Lücken zu füllen.',en:'Perhaps telemedicine and AI could help fill the gaps.'},
    {speaker:'Thomas',side:'right',de:'Das stimmt. Es gibt schon erste Ansätze, aber da ist noch viel Luft nach oben.',en:'That is true. There are already first approaches, but there is still a lot of room for improvement.'},
  ]},
  {id:'CONV046',level:'B1',title:'Wohnungskrise in der Stadt',description:'Zwei junge Erwachsene diskutieren über die Wohnungssituation in deutschen Großstädten.',
   speakers:[{name:'Nadia',voice:1},{name:'Fabian',voice:2}],
   lines:[
    {speaker:'Nadia',side:'left',de:'Fabian, ich suche seit vier Monaten eine Wohnung in München. Es ist wirklich frustrierend.',en:'Fabian, I have been looking for a flat in Munich for four months. It is really frustrating.'},
    {speaker:'Fabian',side:'right',de:'Das glaube ich dir. München ist eine der teuersten Städte Europas. Wie viel Miete kannst du dir leisten?',en:'I believe you. Munich is one of the most expensive cities in Europe. How much rent can you afford?'},
    {speaker:'Nadia',side:'left',de:'Maximal achthundert Euro warm. Aber für das Geld bekomme ich kaum zwanzig Quadratmeter.',en:'Eight hundred euros warm at most. But for that money I can barely get twenty square metres.'},
    {speaker:'Fabian',side:'right',de:'Das ist erschreckend. Hast du schon an Außenbezirke oder Umlandgemeinden gedacht?',en:'That is shocking. Have you thought about outer districts or surrounding communities?'},
    {speaker:'Nadia',side:'left',de:'Ja, aber dann brauche ich ein Auto oder zahle viel für den ÖPNV.',en:'Yes, but then I need a car or pay a lot for public transport.'},
    {speaker:'Fabian',side:'right',de:'Was ist deiner Meinung nach die Ursache dieser Krise?',en:'What do you think is the cause of this crisis?'},
    {speaker:'Nadia',side:'left',de:'Zu wenig Neubauten, steigende Bevölkerung und Spekulation durch Investoren.',en:'Too little new construction, rising population and speculation by investors.'},
    {speaker:'Fabian',side:'right',de:'Da stimme ich dir zu. Der Staat müsste mehr sozialen Wohnungsbau fördern.',en:'I agree with you. The state would need to promote more social housing.'},
    {speaker:'Nadia',side:'left',de:'Genau. In Wien funktioniert das gut. Fast die Hälfte der Bevölkerung wohnt dort in Gemeindebauten.',en:'Exactly. In Vienna that works well. Almost half the population lives in council housing there.'},
    {speaker:'Fabian',side:'right',de:'Das wäre ein Modell für Deutschland. Aber die Umsetzung dauert Jahre.',en:'That would be a model for Germany. But implementation takes years.'},
    {speaker:'Nadia',side:'left',de:'Ja, und ich brauche jetzt eine Wohnung, nicht in zehn Jahren.',en:'Yes, and I need a flat now, not in ten years.'},
    {speaker:'Fabian',side:'right',de:'Hast du schon WG-Zimmer in Betracht gezogen? Als Übergangslösung?',en:'Have you considered shared flat rooms? As a transitional solution?'},
    {speaker:'Nadia',side:'left',de:'Ich schau mal. Mit dreißig Jahren hätte ich nicht gedacht, dass ich noch in einer WG lande.',en:'I\'ll look into it. At thirty I hadn\'t thought I\'d end up in a shared flat.'},
    {speaker:'Fabian',side:'right',de:'Du bist nicht allein damit. Das ist leider die Realität für viele in unserer Generation.',en:'You are not alone in that. That is unfortunately the reality for many in our generation.'},
  ]},
  {id:'CONV047',level:'B1',title:'Soziale Medien — Fluch oder Segen?',description:'Zwei Freunde diskutieren über den Einfluss sozialer Medien.',
   speakers:[{name:'Rania',voice:1},{name:'Erik',voice:2}],
   lines:[
    {speaker:'Rania',side:'left',de:'Erik, ich habe Instagram für einen Monat gelöscht. Ich fühle mich viel besser seitdem.',en:'Erik, I deleted Instagram for a month. I feel much better since then.'},
    {speaker:'Erik',side:'right',de:'Interessant. Was hat dich dazu gebracht?',en:'Interesting. What led you to do that?'},
    {speaker:'Rania',side:'left',de:'Ich habe gemerkt, dass ich ständig mein Leben mit anderen verglichen habe. Das hat mich unglücklich gemacht.',en:'I noticed that I constantly compared my life with others. That made me unhappy.'},
    {speaker:'Erik',side:'right',de:'Das kenne ich. Aber soziale Medien haben doch auch Vorteile, oder?',en:'I know that. But social media does have advantages too, doesn\'t it?'},
    {speaker:'Rania',side:'left',de:'Ja, natürlich. Man bleibt mit Freunden in Kontakt und findet Gleichgesinnte.',en:'Yes, of course. You stay in contact with friends and find like-minded people.'},
    {speaker:'Erik',side:'right',de:'Genau. Außerdem sind sie für Aktivisten und NGOs wichtige Werkzeuge.',en:'Exactly. Also they are important tools for activists and NGOs.'},
    {speaker:'Rania',side:'left',de:'Stimmt. Aber die Algorithmen zeigen uns nur, was uns in unserer Meinung bestätigt. Das nennt man Echokammer.',en:'True. But the algorithms only show us what confirms our opinion. That\'s called an echo chamber.'},
    {speaker:'Erik',side:'right',de:'Das ist ein echtes Problem für die Demokratie. Desinformation verbreitet sich viel schneller als die Wahrheit.',en:'That is a real problem for democracy. Disinformation spreads much faster than the truth.'},
    {speaker:'Rania',side:'left',de:'Deshalb brauchen wir mehr Medienkompetenz in der Schule.',en:'That is why we need more media literacy in schools.'},
    {speaker:'Erik',side:'right',de:'Absolut. Und die Plattformen müssen mehr Verantwortung übernehmen.',en:'Absolutely. And the platforms need to take more responsibility.'},
    {speaker:'Rania',side:'left',de:'Ja, aber die verdienen so viel Geld mit unserem Aufmerksamkeit, dass sie wenig Anreiz haben, etwas zu ändern.',en:'Yes, but they earn so much money from our attention that they have little incentive to change anything.'},
    {speaker:'Erik',side:'right',de:'Da muss die Politik eingreifen. Gibt es solche Gesetze schon in Europa?',en:'Politics needs to intervene there. Are there such laws already in Europe?'},
    {speaker:'Rania',side:'left',de:'Ja, der Digital Services Act ist ein Anfang. Aber die Umsetzung muss besser überwacht werden.',en:'Yes, the Digital Services Act is a start. But implementation needs to be better monitored.'},
    {speaker:'Erik',side:'right',de:'Ich werde jetzt auch mal eine Social-Media-Pause machen. Du hast mich überzeugt.',en:'I am also going to take a social media break now. You have convinced me.'},
  ]},
  {id:'CONV048',level:'B1',title:'Ernährung und Nachhaltigkeit',description:'Zwei Bekannte sprechen über nachhaltige Ernährungsgewohnheiten.',
   speakers:[{name:'Sarah',voice:1},{name:'Kemal',voice:2}],
   lines:[
    {speaker:'Sarah',side:'left',de:'Kemal, ich versuche gerade, mich nachhaltiger zu ernähren. Hast du Tipps?',en:'Kemal, I am currently trying to eat more sustainably. Do you have any tips?'},
    {speaker:'Kemal',side:'right',de:'Gerne! Ich koche seit zwei Jahren fast nur vegetarisch. Was isst du normalerweise?',en:'Gladly! I have been cooking almost exclusively vegetarian for two years. What do you normally eat?'},
    {speaker:'Sarah',side:'left',de:'Ich esse gerne Fleisch, aber ich weiß, dass das viele Ressourcen verbraucht.',en:'I like eating meat, but I know it uses a lot of resources.'},
    {speaker:'Kemal',side:'right',de:'Ja, besonders Rindfleisch hat einen sehr hohen CO₂-Ausstoß. Schon weniger Fleisch zu essen hilft.',en:'Yes, especially beef has a very high CO₂ output. Even eating less meat helps.'},
    {speaker:'Sarah',side:'left',de:'Was empfiehlst du als Einstieg?',en:'What do you recommend as a starting point?'},
    {speaker:'Kemal',side:'right',de:'Vielleicht erst mal fleischfreie Tage einführen. Montag ohne Fleisch zum Beispiel.',en:'Maybe start by introducing meat-free days. Meatless Monday for example.'},
    {speaker:'Sarah',side:'left',de:'Das klingt machbar. Und was ist mit Fisch? Ist der nachhaltiger?',en:'That sounds doable. And what about fish? Is that more sustainable?'},
    {speaker:'Kemal',side:'right',de:'Kommt drauf an. Wildfang aus überfischten Gebieten ist ein Problem. Am besten mit Nachhaltigkeitslabel kaufen.',en:'It depends. Wild catch from overfished areas is a problem. Best to buy with a sustainability label.'},
    {speaker:'Sarah',side:'left',de:'Ah, ich kannte das MSC-Siegel noch nicht. Ich werde darauf achten.',en:'Ah, I didn\'t know the MSC label yet. I will pay attention to that.'},
    {speaker:'Kemal',side:'right',de:'Außerdem: regional und saisonal kaufen ist oft nachhaltiger als Bioprodukte aus dem Ausland.',en:'Also: buying regional and seasonal is often more sustainable than organic products from abroad.'},
    {speaker:'Sarah',side:'left',de:'Stimmt. Erdbeeren im Dezember aus Spanien – das ergibt wenig Sinn.',en:'True. Strawberries in December from Spain – that makes little sense.'},
    {speaker:'Kemal',side:'right',de:'Genau. Saisonkalender gibt es kostenlos als App. Sehr praktisch.',en:'Exactly. Seasonal calendars are available free as an app. Very practical.'},
    {speaker:'Sarah',side:'left',de:'Ich lade sie gleich herunter. Hast du ein Lieblingsrezept, das du mir empfehlen kannst?',en:'I\'ll download it right away. Do you have a favourite recipe you can recommend to me?'},
    {speaker:'Kemal',side:'right',de:'Linsensuppe mit Kurkuma und Ingwer. Günstig, lecker und super nachhaltig.',en:'Lentil soup with turmeric and ginger. Cheap, delicious and super sustainable.'},
  ]},
  {id:'CONV049',level:'B1',title:'Bildungssystem im Vergleich',description:'Zwei Studierende vergleichen das Bildungssystem in ihren Heimatländern.',
   speakers:[{name:'Priya',voice:1},{name:'Jens',voice:2}],
   lines:[
    {speaker:'Priya',side:'left',de:'Jens, wie würdest du das deutsche Bildungssystem beschreiben?',en:'Jens, how would you describe the German education system?'},
    {speaker:'Jens',side:'right',de:'Es ist sehr strukturiert und kostenlos bis zum Studium. Was ist der Unterschied zu Indien?',en:'It is very structured and free up to university. What is the difference to India?'},
    {speaker:'Priya',side:'left',de:'In Indien ist Bildung oft sehr teuer und der Druck auf Schüler ist enorm. Eltern investieren alles in die Ausbildung der Kinder.',en:'In India education is often very expensive and the pressure on pupils is enormous. Parents invest everything in their children\'s education.'},
    {speaker:'Jens',side:'right',de:'Das kenne ich aus Deutschland kaum. Hier gilt das Gymnasium als angesehen, aber es gibt auch gute Berufsausbildungen.',en:'I hardly know that from Germany. Here grammar school is regarded as prestigious, but there are also good vocational trainings.'},
    {speaker:'Priya',side:'left',de:'Das duale Ausbildungssystem in Deutschland ist wirklich einzigartig. In Indien gibt es so etwas kaum.',en:'The dual training system in Germany is really unique. In India there is hardly anything like it.'},
    {speaker:'Jens',side:'right',de:'Ja, viele Länder bewundern es. Auszubildende verdienen schon Geld und lernen gleichzeitig.',en:'Yes, many countries admire it. Trainees already earn money and learn at the same time.'},
    {speaker:'Priya',side:'left',de:'Was denkst du, hat das deutsche System auch Schwächen?',en:'What do you think, does the German system also have weaknesses?'},
    {speaker:'Jens',side:'right',de:'Ja, es hängt noch sehr vom sozialen Hintergrund ab, ob Kinder aufs Gymnasium kommen oder nicht.',en:'Yes, it still depends very much on social background whether children go to grammar school or not.'},
    {speaker:'Priya',side:'left',de:'Das ist überraschend. Ich dachte, in Deutschland ist Chancengleichheit stark verankert.',en:'That is surprising. I thought equality of opportunity is strongly anchored in Germany.'},
    {speaker:'Jens',side:'right',de:'In der Theorie ja. Aber Kinder aus bildungsfernen Familien haben immer noch schlechtere Chancen.',en:'In theory yes. But children from families with little education still have worse chances.'},
    {speaker:'Priya',side:'left',de:'Das ist ein weltweites Problem. Wie könnte man es lösen?',en:'That is a worldwide problem. How could it be solved?'},
    {speaker:'Jens',side:'right',de:'Mehr Förderung für benachteiligte Kinder, bessere Bezahlung für Lehrer und modernere Schulen.',en:'More support for disadvantaged children, better pay for teachers and more modern schools.'},
    {speaker:'Priya',side:'left',de:'Und auch Digitalisierung der Schulen. Viele Schulen hier haben noch keine ausreichende IT-Ausstattung.',en:'And also digitisation of schools. Many schools here still don\'t have adequate IT equipment.'},
    {speaker:'Jens',side:'right',de:'Stimmt. Da gibt es noch viel zu tun. Bildung sollte die höchste Priorität haben.',en:'True. There is still a lot to do there. Education should be the highest priority.'},
  ]},
  {id:'CONV050',level:'B1',title:'Heimweh und Identität',description:'Zwei Expats sprechen über das Leben in der Fremde und ihre Identität.',
   speakers:[{name:'Mei',voice:1},{name:'Omar',voice:2}],
   lines:[
    {speaker:'Mei',side:'left',de:'Omar, hast du manchmal Heimweh? Ich bin jetzt seit zwei Jahren in Deutschland und vermisse China sehr.',en:'Omar, do you sometimes feel homesick? I have been in Germany for two years now and miss China a lot.'},
    {speaker:'Omar',side:'right',de:'Ja, sehr. Besonders an Feiertagen. Die ägyptischen Feste sind so lebhaft – hier ist es viel stiller.',en:'Yes, very much. Especially on holidays. The Egyptian festivals are so lively – here it is much quieter.'},
    {speaker:'Mei',side:'left',de:'Genau. Das Neujahrsfest in China ist magisch. Hier feiere ich es meistens allein.',en:'Exactly. The New Year festival in China is magical. Here I usually celebrate it alone.'},
    {speaker:'Omar',side:'right',de:'Hast du eine Community hier gefunden? Das hat mir sehr geholfen.',en:'Have you found a community here? That helped me a lot.'},
    {speaker:'Mei',side:'left',de:'Ja, ich gehe manchmal in ein chinesisches Kulturzentrum. Aber ich will auch wirklich ankommen hier.',en:'Yes, I sometimes go to a Chinese cultural centre. But I also really want to settle here.'},
    {speaker:'Omar',side:'right',de:'Wie meinst du das – ankommen?',en:'What do you mean by – settle?'},
    {speaker:'Mei',side:'left',de:'Ich meine, nicht nur körperlich hier sein, sondern mich auch zugehörig fühlen.',en:'I mean not just being here physically, but also feeling a sense of belonging.'},
    {speaker:'Omar',side:'right',de:'Das braucht Zeit. Ich fühle mich nach drei Jahren immer noch zwischen zwei Kulturen.',en:'That takes time. After three years I still feel between two cultures.'},
    {speaker:'Mei',side:'left',de:'Ist das ein Problem oder eine Bereicherung?',en:'Is that a problem or an enrichment?'},
    {speaker:'Omar',side:'right',de:'Beides! Manchmal ist es anstrengend, keine klare Antwort auf die Frage zu haben: Woher kommst du?',en:'Both! Sometimes it is tiring not to have a clear answer to the question: where do you come from?'},
    {speaker:'Mei',side:'left',de:'Ich verstehe das sehr gut. Meine Antwort ist inzwischen: aus China, aber ich lebe in Deutschland.',en:'I understand that very well. My answer by now is: from China, but I live in Germany.'},
    {speaker:'Omar',side:'right',de:'Das ist eigentlich eine schöne Antwort. Vielleicht müssen wir Identität neu definieren.',en:'That is actually a nice answer. Perhaps we need to redefine identity.'},
    {speaker:'Mei',side:'left',de:'Ja, Identität ist nicht statisch. Sie entwickelt sich mit jeder Erfahrung.',en:'Yes, identity is not static. It develops with every experience.'},
    {speaker:'Omar',side:'right',de:'Genau. Und das macht uns reicher, auch wenn es manchmal schmerzt.',en:'Exactly. And that makes us richer, even if it sometimes hurts.'},
  ]},
  {id:'CONV051',level:'B1',title:'Ehrenamt und Gesellschaft',description:'Zwei Personen sprechen über freiwilliges Engagement.',
   speakers:[{name:'Anna',voice:1},{name:'David',voice:2}],
   lines:[
    {speaker:'Anna',side:'left',de:'David, ich habe gehört, du engagierst dich ehrenamtlich. Was machst du genau?',en:'David, I heard you do volunteer work. What exactly do you do?'},
    {speaker:'David',side:'right',de:'Ja, ich helfe seit einem Jahr bei der Tafeln mit – das ist eine Organisation, die Lebensmittel an Bedürftige verteilt.',en:'Yes, I have been helping at the Tafel for a year – that is an organisation that distributes food to those in need.'},
    {speaker:'Anna',side:'left',de:'Das ist toll! Wie viel Zeit investierst du pro Woche?',en:'That is great! How much time do you invest per week?'},
    {speaker:'David',side:'right',de:'Etwa vier Stunden samstags. Es ist manchmal körperlich anstrengend, aber sehr erfüllend.',en:'About four hours on Saturdays. It is sometimes physically demanding, but very fulfilling.'},
    {speaker:'Anna',side:'left',de:'Was hat dich dazu motiviert, anzufangen?',en:'What motivated you to start?'},
    {speaker:'David',side:'right',de:'Ich wollte meiner Gemeinschaft etwas zurückgeben. In Deutschland gibt es so viele Möglichkeiten.',en:'I wanted to give something back to my community. In Germany there are so many opportunities.'},
    {speaker:'Anna',side:'left',de:'Was bekommst du persönlich daraus?',en:'What do you personally get out of it?'},
    {speaker:'David',side:'right',de:'Ich treffe tolle Menschen, lerne viel und fühle mich nützlich. Das gibt mir Energie.',en:'I meet great people, learn a lot and feel useful. That gives me energy.'},
    {speaker:'Anna',side:'left',de:'Ich würde auch gerne etwas tun. Aber ich weiß nicht, wo ich anfangen soll.',en:'I would also like to do something. But I don\'t know where to start.'},
    {speaker:'David',side:'right',de:'Am einfachsten ist es, auf der Plattform ehrenamt.de zu suchen. Dort findet man alles in der Nähe.',en:'The easiest way is to search on the platform ehrenamt.de. You can find everything nearby there.'},
    {speaker:'Anna',side:'left',de:'Interessant! Welche Bereiche gibt es?',en:'Interesting! What areas are there?'},
    {speaker:'David',side:'right',de:'Sehr viele: Tierschutz, Flüchtlingshilfe, Kinderbetreuung, Naturschutz, Sport...',en:'Very many: animal welfare, refugee assistance, childcare, nature conservation, sport...'},
    {speaker:'Anna',side:'left',de:'Ich interessiere mich für Umweltschutz. Ich glaube, das wäre das Richtige für mich.',en:'I am interested in environmental protection. I think that would be the right thing for me.'},
    {speaker:'David',side:'right',de:'Super! Es gibt auch NABU und andere Naturschutzorganisationen. Da kann ich dir Kontakte geben.',en:'Great! There is also NABU and other nature conservation organisations. I can give you contacts there.'},
  ]},
  {id:'CONV052',level:'B1',title:'Arbeit und Work-Life-Balance',description:'Zwei Kollegen sprechen über Stress und Work-Life-Balance.',
   speakers:[{name:'Miriam',voice:1},{name:'Stefan',voice:2}],
   lines:[
    {speaker:'Miriam',side:'left',de:'Stefan, du siehst müde aus. Ist alles in Ordnung?',en:'Stefan, you look tired. Is everything alright?'},
    {speaker:'Stefan',side:'right',de:'Ehrlich gesagt nicht. Ich arbeite seit Wochen Überstunden und komme nicht zur Ruhe.',en:'Honestly not. I have been working overtime for weeks and can\'t find any rest.'},
    {speaker:'Miriam',side:'left',de:'Das klingt nach Burnout. Hast du mit deinem Chef gesprochen?',en:'That sounds like burnout. Have you spoken to your boss?'},
    {speaker:'Stefan',side:'right',de:'Nein, ich will nicht schwach wirken. Außerdem haben wir gerade so viele Projekte.',en:'No, I don\'t want to seem weak. Also we have so many projects right now.'},
    {speaker:'Miriam',side:'left',de:'Aber deine Gesundheit ist wichtiger als jedes Projekt. Burnout kann lange dauern.',en:'But your health is more important than any project. Burnout can last a long time.'},
    {speaker:'Stefan',side:'right',de:'Ich weiß. Aber wie soll ich das ansprechen, ohne meinen Job zu gefährden?',en:'I know. But how do I raise that without putting my job at risk?'},
    {speaker:'Miriam',side:'left',de:'Du könntest sagen, dass du effizienter arbeiten willst und deshalb eine bessere Aufgabenverteilung brauchst.',en:'You could say that you want to work more efficiently and therefore need a better distribution of tasks.'},
    {speaker:'Stefan',side:'right',de:'Das ist eine gute Idee. Sachlich und lösungsorientiert.',en:'That is a good idea. Factual and solution-oriented.'},
    {speaker:'Miriam',side:'left',de:'Genau. Und mach bitte wirklich Feierabend um eine bestimmte Zeit. Keine E-Mails mehr nach achtzehn Uhr.',en:'Exactly. And please really finish work at a specific time. No more emails after six o\'clock.'},
    {speaker:'Stefan',side:'right',de:'Leichter gesagt als getan. Mein Handy klingelt ständig.',en:'Easier said than done. My phone rings constantly.'},
    {speaker:'Miriam',side:'left',de:'Dann stell es auf stumm. Du bist kein Notarzt.',en:'Then put it on silent. You are not an emergency doctor.'},
    {speaker:'Stefan',side:'right',de:'Du hast recht. Ich mache heute Abend als Erstes einen langen Spaziergang.',en:'You are right. The first thing I\'ll do this evening is take a long walk.'},
    {speaker:'Miriam',side:'left',de:'Sehr gut. Und wenn es nicht besser wird, geh zum Hausarzt. Gesundheit kommt zuerst.',en:'Very good. And if it doesn\'t get better, go to your GP. Health comes first.'},
    {speaker:'Stefan',side:'right',de:'Danke, Miriam. Es ist gut, jemanden zu haben, der einem die Wahrheit sagt.',en:'Thank you, Miriam. It is good to have someone who tells you the truth.'},
  ]},
  {id:'CONV053',level:'B1',title:'Integration und Gesellschaft',description:'Eine Sozialarbeiterin und ein Flüchtling sprechen über Erfahrungen bei der Integration.',
   speakers:[{name:'Herr Al-Rashid',voice:1},{name:'Sozialarbeiterin Frau Koch',voice:2}],
   lines:[
    {speaker:'Herr Al-Rashid',side:'left',de:'Frau Koch, ich habe jetzt meinen B1-Sprachkurs abgeschlossen. Was sind die nächsten Schritte?',en:'Ms Koch, I have now completed my B1 language course. What are the next steps?'},
    {speaker:'Sozialarbeiterin Frau Koch',side:'right',de:'Herzlichen Glückwunsch! Das ist ein wichtiger Meilenstein. Haben Sie schon nach Arbeit gesucht?',en:'Congratulations! That is an important milestone. Have you already looked for work?'},
    {speaker:'Herr Al-Rashid',side:'left',de:'Ja, aber mein syrischer Abschluss wird hier nicht anerkannt. Das ist sehr frustrierend.',en:'Yes, but my Syrian degree is not recognised here. That is very frustrating.'},
    {speaker:'Sozialarbeiterin Frau Koch',side:'right',de:'Das ist ein verbreitetes Problem. Aber es gibt Möglichkeiten zur Anerkennung. Ich helfe Ihnen dabei.',en:'That is a widespread problem. But there are possibilities for recognition. I will help you with that.'},
    {speaker:'Herr Al-Rashid',side:'left',de:'Wirklich? Ich war Ingenieur in Syrien – sieben Jahre Erfahrung.',en:'Really? I was an engineer in Syria – seven years of experience.'},
    {speaker:'Sozialarbeiterin Frau Koch',side:'right',de:'Dann haben Sie gute Chancen. Die Ingenieurskammer prüft ausländische Abschlüsse.',en:'Then you have good chances. The engineers\' association examines foreign qualifications.'},
    {speaker:'Herr Al-Rashid',side:'left',de:'Was brauche ich dafür?',en:'What do I need for that?'},
    {speaker:'Sozialarbeiterin Frau Koch',side:'right',de:'Alle Dokumente aus Syrien, beglaubigte Übersetzungen und einen Nachweis über Ihre Berufserfahrung.',en:'All documents from Syria, certified translations and proof of your professional experience.'},
    {speaker:'Herr Al-Rashid',side:'left',de:'Ich habe meine Zeugnisse, aber einige Dokumente konnte ich nicht mitnehmen.',en:'I have my certificates, but I was unable to take some documents with me.'},
    {speaker:'Sozialarbeiterin Frau Koch',side:'right',de:'Das ist lösbar. Es gibt spezielle Verfahren für Flüchtlinge, deren Dokumente verloren gegangen sind.',en:'That is solvable. There are special procedures for refugees whose documents have been lost.'},
    {speaker:'Herr Al-Rashid',side:'left',de:'Das gibt mir Hoffnung. Ich möchte so gerne wieder in meinem Beruf arbeiten.',en:'That gives me hope. I would so love to work in my profession again.'},
    {speaker:'Sozialarbeiterin Frau Koch',side:'right',de:'Das werden Sie. Und bis zur Anerkennung gibt es Qualifizierungsmaßnahmen.',en:'You will. And until recognition there are qualification measures.'},
    {speaker:'Herr Al-Rashid',side:'left',de:'Ich bin so dankbar für Ihre Hilfe, Frau Koch.',en:'I am so grateful for your help, Ms Koch.'},
    {speaker:'Sozialarbeiterin Frau Koch',side:'right',de:'Das ist mein Job, und ich mache ihn sehr gerne. Wir machen das gemeinsam.',en:'That is my job, and I enjoy doing it very much. We will do this together.'},
  ]},
  {id:'CONV054',level:'B1',title:'Stadtplanung und Zukunft',description:'Ein Stadtrat und eine Bürgerin diskutieren über die Zukunft der Stadt.',
   speakers:[{name:'Bürgerin Lena',voice:1},{name:'Stadtrat Herr Vogel',voice:2}],
   lines:[
    {speaker:'Bürgerin Lena',side:'left',de:'Herr Vogel, danke, dass Sie sich Zeit für mich nehmen. Ich mache mir Sorgen um die Entwicklung unserer Stadt.',en:'Mr Vogel, thank you for taking the time to see me. I am worried about the development of our town.'},
    {speaker:'Stadtrat Herr Vogel',side:'right',de:'Ich höre gerne, was die Bürgerinnen und Bürger beschäftigt. Was ist Ihr Anliegen?',en:'I am happy to hear what concerns citizens. What is your concern?'},
    {speaker:'Bürgerin Lena',side:'left',de:'Die vielen Parkplätze in der Innenstadt. Die nehmen Platz weg, der für Grünflächen genutzt werden könnte.',en:'The many car parks in the town centre. They take up space that could be used for green areas.'},
    {speaker:'Stadtrat Herr Vogel',side:'right',de:'Das ist ein wichtiges Thema. Wir arbeiten gerade an einem neuen Mobilitätskonzept.',en:'That is an important topic. We are currently working on a new mobility concept.'},
    {speaker:'Bürgerin Lena',side:'left',de:'Was sieht das vor?',en:'What does that involve?'},
    {speaker:'Stadtrat Herr Vogel',side:'right',de:'Weniger Parkplätze in der Innenstadt, mehr Fahrradwege und ein verbesserter ÖPNV.',en:'Fewer car parks in the town centre, more cycle paths and improved public transport.'},
    {speaker:'Bürgerin Lena',side:'left',de:'Das klingt gut. Aber viele ältere Menschen sind auf das Auto angewiesen.',en:'That sounds good. But many older people depend on the car.'},
    {speaker:'Stadtrat Herr Vogel',side:'right',de:'Das stimmt. Deswegen planen wir auch einen Rufbusservice für Senioren.',en:'That is true. That is why we are also planning an on-demand bus service for seniors.'},
    {speaker:'Bürgerin Lena',side:'left',de:'Sehr gut! Und was ist mit mehr Bäumen und Grünflächen? Die Stadt wirkt sehr grau.',en:'Very good! And what about more trees and green spaces? The town looks very grey.'},
    {speaker:'Stadtrat Herr Vogel',side:'right',de:'In den nächsten zwei Jahren pflanzen wir tausend neue Bäume. Das ist bereits beschlossen.',en:'In the next two years we are planting a thousand new trees. That is already decided.'},
    {speaker:'Bürgerin Lena',side:'left',de:'Das freut mich wirklich. Können Bürger sich einbringen?',en:'That really pleases me. Can citizens get involved?'},
    {speaker:'Stadtrat Herr Vogel',side:'right',de:'Ja! Wir veranstalten im März eine Bürgerbeteiligung. Ich lade Sie herzlich ein.',en:'Yes! We are holding a citizen participation event in March. I warmly invite you.'},
    {speaker:'Bürgerin Lena',side:'left',de:'Ich komme gerne. Kann ich auch Freunde mitbringen?',en:'I am happy to come. Can I also bring friends?'},
    {speaker:'Stadtrat Herr Vogel',side:'right',de:'Selbstverständlich! Je mehr Bürger mitmachen, desto besser. Wir brauchen Ihre Ideen.',en:'Of course! The more citizens participate, the better. We need your ideas.'},
  ]},
  {id:'CONV055',level:'B1',title:'Reiseerfahrungen teilen',description:'Zwei Freundinnen erzählen sich von prägenden Reiseerlebnissen.',
   speakers:[{name:'Julia',voice:1},{name:'Hannah',voice:2}],
   lines:[
    {speaker:'Julia',side:'left',de:'Hannah, du warst doch letztes Jahr sechs Monate in Südamerika. Was war die prägende Erfahrung?',en:'Hannah, you were in South America for six months last year, weren\'t you. What was the formative experience?'},
    {speaker:'Hannah',side:'right',de:'Schwer zu sagen. Vielleicht die Zeit in einem kleinen Dorf in Ecuador, wo es keinen Strom gab.',en:'Hard to say. Perhaps the time in a small village in Ecuador where there was no electricity.'},
    {speaker:'Julia',side:'left',de:'Kein Strom? Wie war das?',en:'No electricity? What was that like?'},
    {speaker:'Hannah',side:'right',de:'Am Anfang war es schwer – kein Handy, kein Internet. Aber nach ein paar Tagen war es befreiend.',en:'At first it was difficult – no phone, no internet. But after a few days it was liberating.'},
    {speaker:'Julia',side:'left',de:'Was hast du in dieser Zeit gemacht?',en:'What did you do during that time?'},
    {speaker:'Hannah',side:'right',de:'Ich habe mit den Dorfbewohnern gearbeitet, Spanisch gelernt und abends Geschichten am Feuer gehört.',en:'I worked with the villagers, learned Spanish and listened to stories by the fire in the evenings.'},
    {speaker:'Julia',side:'left',de:'Das klingt unglaublich. Hat dich das verändert?',en:'That sounds incredible. Did it change you?'},
    {speaker:'Hannah',side:'right',de:'Ja, sehr. Ich schätze einfache Dinge jetzt viel mehr. Und ich konsumiere bewusster.',en:'Yes, very much. I appreciate simple things much more now. And I consume more consciously.'},
    {speaker:'Julia',side:'left',de:'Ich habe ähnliches nach meiner Reise nach Japan erfahren. Die Ruhe dort hat mich fasziniert.',en:'I experienced something similar after my trip to Japan. The calm there fascinated me.'},
    {speaker:'Hannah',side:'right',de:'Japan ist so anders. Was hat dich am meisten überrascht?',en:'Japan is so different. What surprised you most?'},
    {speaker:'Julia',side:'left',de:'Die Pünktlichkeit und das Respektverhalten. Alles läuft so geordnet ab.',en:'The punctuality and respectful behaviour. Everything runs so orderly.'},
    {speaker:'Hannah',side:'right',de:'Das ist beeindruckend. Wärst du gerne länger geblieben?',en:'That is impressive. Would you have liked to stay longer?'},
    {speaker:'Julia',side:'left',de:'Ja, auf jeden Fall. Aber es war schwer, die Sprache zu lernen. Kanji ist brutal.',en:'Yes, definitely. But it was difficult to learn the language. Kanji is brutal.'},
    {speaker:'Hannah',side:'right',de:'Ha! Dafür hast du jetzt Grundkenntnisse in Japanisch. Ich neidlose dich dafür.',en:'Ha! At least you now have basic knowledge of Japanese. I envy you for that.'},
  ]},
  {id:'CONV056',level:'B1',title:'Musik und Emotionen',description:'Zwei Freunde sprechen über die Bedeutung von Musik in ihrem Leben.',
   speakers:[{name:'Leo',voice:1},{name:'Maria',voice:2}],
   lines:[
    {speaker:'Leo',side:'left',de:'Maria, welche Musik hörst du, wenn du traurig bist?',en:'Maria, what music do you listen to when you are sad?'},
    {speaker:'Maria',side:'right',de:'Das ist eine interessante Frage. Ich höre dann oft klassische Musik oder ruhige Gitarrenlieder.',en:'That is an interesting question. I often listen to classical music or quiet guitar songs then.'},
    {speaker:'Leo',side:'left',de:'Ich dagegen höre dann laute Rockmusik. Das hilft mir, die Energie rauszulassen.',en:'I on the other hand listen to loud rock music then. That helps me to release the energy.'},
    {speaker:'Maria',side:'right',de:'Jeder verarbeitet Emotionen anders. Musik ist dabei sehr persönlich.',en:'Everyone processes emotions differently. Music is very personal in that regard.'},
    {speaker:'Leo',side:'left',de:'Absolut. Gibt es ein Lied, das eine besondere Bedeutung für dich hat?',en:'Absolutely. Is there a song that has a special meaning for you?'},
    {speaker:'Maria',side:'right',de:'Ja, „Die Gedanken sind frei" – das alte deutsche Volkslied. Es steht für Freiheit.',en:'Yes, "Die Gedanken sind frei" – the old German folk song. It stands for freedom.'},
    {speaker:'Leo',side:'left',de:'Das ist ein wunderschönes Lied. Ich kenne es aus der Schule.',en:'That is a beautiful song. I know it from school.'},
    {speaker:'Maria',side:'right',de:'Es hat eine lange Geschichte. Die Menschen haben es in schwierigen Zeiten gesungen.',en:'It has a long history. People sang it in difficult times.'},
    {speaker:'Leo',side:'left',de:'Ich finde, Musik verbindet Menschen über Kulturgrenzen hinweg.',en:'I think music connects people across cultural boundaries.'},
    {speaker:'Maria',side:'right',de:'Da stimme ich dir zu. Wenn man kein gemeinsames Wort hat, kann man zusammen singen.',en:'I agree with you there. When you don\'t share a common word, you can sing together.'},
    {speaker:'Leo',side:'left',de:'Spielst du eigentlich selbst ein Instrument?',en:'Do you actually play an instrument yourself?'},
    {speaker:'Maria',side:'right',de:'Ja, Gitarre – seit acht Jahren. Und du?',en:'Yes, guitar – for eight years. And you?'},
    {speaker:'Leo',side:'left',de:'Ich spiele Klavier, aber nur für mich. Ich wäre zu schüchtern, vor anderen zu spielen.',en:'I play piano, but only for myself. I would be too shy to play in front of others.'},
    {speaker:'Maria',side:'right',de:'Das solltest du überwinden. Musik teilen ist das Schönste daran.',en:'You should overcome that. Sharing music is the most beautiful thing about it.'},
  ]},
  {id:'CONV057',level:'B1',title:'Technologie und Privatsphäre',description:'Zwei Bekannte diskutieren über Datenschutz im digitalen Zeitalter.',
   speakers:[{name:'Hanna',voice:1},{name:'Sven',voice:2}],
   lines:[
    {speaker:'Hanna',side:'left',de:'Sven, hast du schon gehört, dass WhatsApp die Nutzerdaten wieder an Meta weitergibt?',en:'Sven, have you heard that WhatsApp is again passing user data on to Meta?'},
    {speaker:'Sven',side:'right',de:'Ja, das ärgert mich. Ich überlege, zu Signal zu wechseln.',en:'Yes, that annoys me. I am considering switching to Signal.'},
    {speaker:'Hanna',side:'left',de:'Das habe ich schon vor einem Jahr gemacht. Signal ist wirklich sicherer.',en:'I did that a year ago. Signal is really more secure.'},
    {speaker:'Sven',side:'right',de:'Aber meine Familie nutzt WhatsApp. Da ist es schwer, einfach zu wechseln.',en:'But my family uses WhatsApp. It is hard to simply switch there.'},
    {speaker:'Hanna',side:'left',de:'Das ist das Problem. Die Netzwerkeffekte machen es schwierig, Alternativen durchzusetzen.',en:'That is the problem. Network effects make it difficult to establish alternatives.'},
    {speaker:'Sven',side:'right',de:'Glaubst du, dass wir überhaupt noch Privatsphäre im Internet haben?',en:'Do you think we even have privacy on the internet anymore?'},
    {speaker:'Hanna',side:'left',de:'Kaum noch. Jede Suchanfrage, jeder Klick wird gespeichert und analysiert.',en:'Barely. Every search query, every click is stored and analysed.'},
    {speaker:'Sven',side:'right',de:'Das ist beunruhigend. Was kann man dagegen tun?',en:'That is worrying. What can one do about it?'},
    {speaker:'Hanna',side:'left',de:'VPN nutzen, datenschutzfreundliche Browser wie Firefox, und regelmäßig Cookies löschen.',en:'Use a VPN, privacy-friendly browsers like Firefox, and regularly delete cookies.'},
    {speaker:'Sven',side:'right',de:'Das klingt aufwendig. Ist das wirklich nötig?',en:'That sounds complicated. Is that really necessary?'},
    {speaker:'Hanna',side:'left',de:'Es hängt davon ab, wie wichtig dir deine Privatsphäre ist. Ich finde es den Aufwand wert.',en:'It depends on how important your privacy is to you. I think it is worth the effort.'},
    {speaker:'Sven',side:'right',de:'Ich fange mal mit Firefox an. Das ist zumindest ein Anfang.',en:'I\'ll start with Firefox. That is at least a start.'},
    {speaker:'Hanna',side:'left',de:'Gut! Und schau dir mal die DuckDuckGo-Suchmaschine an. Keine Nachverfolgung.',en:'Good! And have a look at the DuckDuckGo search engine. No tracking.'},
    {speaker:'Sven',side:'right',de:'Danke für die Tipps. Ich merke, ich muss mich mehr damit beschäftigen.',en:'Thank you for the tips. I realise I need to engage with this more.'},
  ]},
  {id:'CONV058',level:'B1',title:'Freundschaft auf Distanz',description:'Zwei alte Freunde, die in verschiedenen Städten leben, reden über ihre Freundschaft.',
   speakers:[{name:'Ben',voice:1},{name:'Sophia',voice:2}],
   lines:[
    {speaker:'Ben',side:'left',de:'Sophia, ich freue mich so, dass wir endlich wieder Zeit zum Reden haben!',en:'Sophia, I am so glad we finally have time to talk again!'},
    {speaker:'Sophia',side:'right',de:'Ich auch! Seit du nach Hamburg gezogen bist, sehen wir uns viel zu selten.',en:'Me too! Since you moved to Hamburg, we see each other far too rarely.'},
    {speaker:'Ben',side:'left',de:'Stimmt. Wie geht es dir so? Was gibt\'s Neues?',en:'True. How are you? What\'s new?'},
    {speaker:'Sophia',side:'right',de:'Ich habe eine neue Stelle angefangen – endlich in meinem Bereich. Ich bin sehr glücklich damit.',en:'I have started a new job – finally in my field. I am very happy about it.'},
    {speaker:'Ben',side:'left',de:'Das ist wunderbar! Das hast du dir so sehr gewünscht. Ich bin stolz auf dich.',en:'That is wonderful! You wished for that so much. I am proud of you.'},
    {speaker:'Sophia',side:'right',de:'Danke. Und wie läuft es bei dir in Hamburg?',en:'Thank you. And how is it going for you in Hamburg?'},
    {speaker:'Ben',side:'left',de:'Gut, aber die Stadt ist so anonym. Ich vermisse unsere gemeinsame Zeit in Köln.',en:'Good, but the city is so anonymous. I miss our time together in Cologne.'},
    {speaker:'Sophia',side:'right',de:'Ich auch. Weißt du noch, wie wir früher jeden Freitag ins Café gegangen sind?',en:'Me too. Do you remember how we used to go to the café every Friday?'},
    {speaker:'Ben',side:'left',de:'Natürlich! Und dann stundenlang gequatscht haben. Die Zeiten vermisse ich.',en:'Of course! And then chatted for hours. I miss those times.'},
    {speaker:'Sophia',side:'right',de:'Vielleicht können wir uns nächsten Monat treffen – ich könnte nach Hamburg kommen.',en:'Maybe we can meet next month – I could come to Hamburg.'},
    {speaker:'Ben',side:'left',de:'Das wäre fantastisch! Ich zeige dir die Stadt. Hamburg ist wirklich schön.',en:'That would be fantastic! I will show you the city. Hamburg is really beautiful.'},
    {speaker:'Sophia',side:'right',de:'Und dann gehen wir zum Fischmarkt und essen Fischbrötchen!',en:'And then we go to the fish market and eat fish rolls!'},
    {speaker:'Ben',side:'left',de:'Unbedingt! Auch wenn uns Kilometer trennen – unsere Freundschaft bleibt.',en:'Absolutely! Even if kilometres separate us – our friendship remains.'},
    {speaker:'Sophia',side:'right',de:'Das stimmt. Echte Freundschaft übersteht jede Distanz.',en:'That is true. True friendship survives any distance.'},
  ]},
  {id:'CONV059',level:'B1',title:'Zukunftsängste der Generation',description:'Zwei junge Erwachsene sprechen offen über ihre Zukunftssorgen.',
   speakers:[{name:'Kim',voice:1},{name:'Alex',voice:2}],
   lines:[
    {speaker:'Kim',side:'left',de:'Alex, machst du dir manchmal Sorgen um die Zukunft? Ich fühle mich oft überwältigt.',en:'Alex, do you sometimes worry about the future? I often feel overwhelmed.'},
    {speaker:'Alex',side:'right',de:'Ja, sehr. Klimawandel, Kriege, steigende Kosten – manchmal weiß ich nicht, wie die Welt in zwanzig Jahren aussieht.',en:'Yes, very much. Climate change, wars, rising costs – sometimes I don\'t know what the world will look like in twenty years.'},
    {speaker:'Kim',side:'left',de:'Genau das meine ich. Und dann kommen noch Fragen wie: Kann ich mir jemals eine Wohnung kaufen?',en:'That is exactly what I mean. And then come questions like: will I ever be able to buy a flat?'},
    {speaker:'Alex',side:'right',de:'Das Thema Eigentum bereitet mir auch Kopfzerbrechen. Immobilienpreise sind explodiert.',en:'The topic of property gives me a headache too. Real estate prices have exploded.'},
    {speaker:'Kim',side:'left',de:'Aber ich versuche, mich nicht davon lähmen zu lassen. Was tust du, wenn die Angst kommt?',en:'But I try not to let it paralyse me. What do you do when the fear comes?'},
    {speaker:'Alex',side:'right',de:'Ich konzentriere mich auf das, was ich kontrollieren kann. Und ich rede mit Freunden darüber.',en:'I focus on what I can control. And I talk to friends about it.'},
    {speaker:'Kim',side:'left',de:'Das hilft. Ich mache auch Meditation. Das gibt mir Ruhe.',en:'That helps. I also do meditation. That gives me calm.'},
    {speaker:'Alex',side:'right',de:'Meditation habe ich noch nie ausprobiert. Ist das schwer anzufangen?',en:'I have never tried meditation. Is it hard to start?'},
    {speaker:'Kim',side:'left',de:'Gar nicht. Schon zehn Minuten täglich helfen. Es gibt viele Apps dafür.',en:'Not at all. Even ten minutes daily helps. There are many apps for it.'},
    {speaker:'Alex',side:'right',de:'Vielleicht probiere ich es. Ich glaube, ich brauche mehr Techniken, um mit Stress umzugehen.',en:'Maybe I will try it. I think I need more techniques for dealing with stress.'},
    {speaker:'Kim',side:'left',de:'Und vergiss nicht: Unsere Generation ist trotz allem sehr resilient. Wir haben gelernt, uns anzupassen.',en:'And don\'t forget: our generation is very resilient despite everything. We have learned to adapt.'},
    {speaker:'Alex',side:'right',de:'Das stimmt. Und vielleicht lösen wir Probleme, die wir jetzt noch nicht sehen.',en:'That is true. And perhaps we will solve problems we cannot yet see.'},
    {speaker:'Kim',side:'left',de:'Genau. Hoffnung ist auch eine Form der Stärke.',en:'Exactly. Hope is also a form of strength.'},
    {speaker:'Alex',side:'right',de:'Schön gesagt. Ich fühle mich besser nach diesem Gespräch.',en:'Well said. I feel better after this conversation.'},
  ]},
  {id:'CONV060',level:'B1',title:'Literatur und Leben',description:'Eine Lehrerin und eine Schülerin sprechen über ein gemeinsam gelesenes Buch.',
   speakers:[{name:'Schülerin Ayse',voice:1},{name:'Lehrerin Frau Berg',voice:2}],
   lines:[
    {speaker:'Schülerin Ayse',side:'left',de:'Frau Berg, ich habe „Der Vorleser" jetzt zu Ende gelesen. Es hat mich sehr bewegt.',en:'Ms Berg, I have now finished reading "The Reader". It moved me deeply.'},
    {speaker:'Lehrerin Frau Berg',side:'right',de:'Das freut mich zu hören, Ayse. Was hat dich besonders berührt?',en:'I am glad to hear that, Ayse. What particularly moved you?'},
    {speaker:'Schülerin Ayse',side:'left',de:'Die Beziehung zwischen Hanna und Michael. Und wie Schuld und Scham das ganze Leben beeinflussen können.',en:'The relationship between Hanna and Michael. And how guilt and shame can influence a whole life.'},
    {speaker:'Lehrerin Frau Berg',side:'right',de:'Genau das ist das Kernthema. Bernhard Schlink zeigt, wie komplex moralische Urteile sein können.',en:'That is exactly the core theme. Bernhard Schlink shows how complex moral judgements can be.'},
    {speaker:'Schülerin Ayse',side:'left',de:'Ich fand es schwer, Hanna zu mögen, aber auch schwer, sie zu verurteilen.',en:'I found it hard to like Hanna, but also hard to judge her.'},
    {speaker:'Lehrerin Frau Berg',side:'right',de:'Das ist die Stärke des Buches. Es zwingt uns, unsere eigenen moralischen Überzeugungen zu hinterfragen.',en:'That is the strength of the book. It forces us to question our own moral convictions.'},
    {speaker:'Schülerin Ayse',side:'left',de:'Warum kann Hanna nicht lesen? Das war lange nicht klar.',en:'Why can\'t Hanna read? That was not clear for a long time.'},
    {speaker:'Lehrerin Frau Berg',side:'right',de:'Ihr Analphabetismus ist ein Symbol. Er steht für Unwissenheit und Ausgrenzung.',en:'Her illiteracy is a symbol. It stands for ignorance and exclusion.'},
    {speaker:'Schülerin Ayse',side:'left',de:'Und das Vorlesen als verbindendes Element – das fand ich sehr poetisch.',en:'And the reading aloud as a connecting element – I found that very poetic.'},
    {speaker:'Lehrerin Frau Berg',side:'right',de:'Wunderschön beobachtet. Literatur ist manchmal das einzige, was Menschen verbindet.',en:'Beautifully observed. Literature is sometimes the only thing that connects people.'},
    {speaker:'Schülerin Ayse',side:'left',de:'Können Sie mir andere Bücher empfehlen, die ähnlich denken lassen?',en:'Can you recommend other books that make you think similarly?'},
    {speaker:'Lehrerin Frau Berg',side:'right',de:'„Effi Briest" von Fontane oder „Die Blechtrommel" von Grass – beides große deutsche Romane.',en:'"Effi Briest" by Fontane or "The Tin Drum" by Grass – both great German novels.'},
    {speaker:'Schülerin Ayse',side:'left',de:'Ich werde sie lesen! Literatur hilft mir wirklich, die Welt besser zu verstehen.',en:'I will read them! Literature really helps me to understand the world better.'},
    {speaker:'Lehrerin Frau Berg',side:'right',de:'Das ist das Schönste, was mir eine Schülerin sagen kann. Weiter so, Ayse!',en:'That is the most beautiful thing a pupil can say to me. Keep it up, Ayse!'},
  ]},
];

fs.writeFileSync(OUT, JSON.stringify(b1, null, 2));
console.log('✅ Saved', b1.length, 'B1 conversations to', OUT);
