const fs = require('fs');
const OUT = 'C:/Users/ADELEKEOLORUNISOLAO/Desktop/goethe-trainer/public/data/convo_a2.json';

const a2 = [
  {id:'CONV021',level:'A2',title:'Das Vorstellungsgespräch',description:'Frau Yilmaz bewirbt sich um eine Stelle als Assistentin.',
   speakers:[{name:'Frau Yilmaz',voice:1},{name:'Herr Schäfer',voice:2}],
   lines:[
    {speaker:'Frau Yilmaz',side:'left',de:'Guten Morgen, Herr Schäfer. Ich bin Canan Yilmaz. Ich freue mich sehr über diese Einladung.',en:'Good morning, Mr Schäfer. I am Canan Yilmaz. I am very pleased about this invitation.'},
    {speaker:'Herr Schäfer',side:'right',de:'Willkommen, Frau Yilmaz. Bitte setzen Sie sich. Erzählen Sie etwas über sich.',en:'Welcome, Ms Yilmaz. Please have a seat. Tell me something about yourself.'},
    {speaker:'Frau Yilmaz',side:'left',de:'Ich habe drei Jahre Erfahrung in der Verwaltung und spreche Deutsch, Englisch und Türkisch.',en:'I have three years of experience in administration and speak German, English and Turkish.'},
    {speaker:'Herr Schäfer',side:'right',de:'Sehr gut. Warum möchten Sie bei uns arbeiten?',en:'Very good. Why do you want to work with us?'},
    {speaker:'Frau Yilmaz',side:'left',de:'Ihr Unternehmen hat einen sehr guten Ruf und ich möchte in einem internationalen Team arbeiten.',en:'Your company has a very good reputation and I would like to work in an international team.'},
    {speaker:'Herr Schäfer',side:'right',de:'Was sind Ihre Stärken?',en:'What are your strengths?'},
    {speaker:'Frau Yilmaz',side:'left',de:'Ich bin sehr organisiert, arbeite gern im Team und lerne schnell.',en:'I am very organised, enjoy working in a team and learn quickly.'},
    {speaker:'Herr Schäfer',side:'right',de:'Und Ihre Schwächen?',en:'And your weaknesses?'},
    {speaker:'Frau Yilmaz',side:'left',de:'Manchmal bin ich zu perfektionistisch, aber ich arbeite daran.',en:'Sometimes I am too much of a perfectionist, but I am working on it.'},
    {speaker:'Herr Schäfer',side:'right',de:'Gut. Wann könnten Sie anfangen?',en:'Good. When could you start?'},
    {speaker:'Frau Yilmaz',side:'left',de:'Ab dem ersten nächsten Monats wäre ich verfügbar.',en:'I would be available from the first of next month.'},
    {speaker:'Herr Schäfer',side:'right',de:'Sehr schön. Wir melden uns bis Ende der Woche bei Ihnen.',en:'Very good. We will get back to you by the end of the week.'},
  ]},
  {id:'CONV022',level:'A2',title:'Wohnungssuche',description:'Lena besichtigt eine Wohnung und stellt Fragen.',
   speakers:[{name:'Lena',voice:1},{name:'Vermieter Herr Wagner',voice:2}],
   lines:[
    {speaker:'Lena',side:'left',de:'Guten Tag! Ich bin Lena Kraft. Ich habe einen Termin zur Wohnungsbesichtigung.',en:'Good day! I am Lena Kraft. I have an appointment to view the flat.'},
    {speaker:'Vermieter Herr Wagner',side:'right',de:'Herzlich willkommen! Kommen Sie rein. Das ist das Wohnzimmer.',en:'Welcome! Come in. This is the living room.'},
    {speaker:'Lena',side:'left',de:'Oh, das ist schön und hell! Wie groß ist die Wohnung?',en:'Oh, this is lovely and bright! How big is the flat?'},
    {speaker:'Vermieter Herr Wagner',side:'right',de:'Sechzig Quadratmeter, zwei Zimmer, Küche und Bad.',en:'Sixty square metres, two rooms, kitchen and bathroom.'},
    {speaker:'Lena',side:'left',de:'Ist die Küche möbliert?',en:'Is the kitchen furnished?'},
    {speaker:'Vermieter Herr Wagner',side:'right',de:'Ja, mit Kühlschrank und Herd. Die anderen Zimmer sind leer.',en:'Yes, with fridge and cooker. The other rooms are empty.'},
    {speaker:'Lena',side:'left',de:'Was kostet die Miete?',en:'How much is the rent?'},
    {speaker:'Vermieter Herr Wagner',side:'right',de:'Achthundert Euro kalt, plus zweihundert Nebenkosten.',en:'Eight hundred euros cold rent, plus two hundred utilities.'},
    {speaker:'Lena',side:'left',de:'Ist Haustier erlaubt? Ich habe eine kleine Katze.',en:'Are pets allowed? I have a small cat.'},
    {speaker:'Vermieter Herr Wagner',side:'right',de:'Eine Katze ist kein Problem. Hunde leider nicht.',en:'A cat is no problem. Dogs unfortunately not.'},
    {speaker:'Lena',side:'left',de:'Wann wäre der früheste Einzugstermin?',en:'What would be the earliest move-in date?'},
    {speaker:'Vermieter Herr Wagner',side:'right',de:'Ab dem ersten des nächsten Monats. Haben Sie Interesse?',en:'From the first of next month. Are you interested?'},
  ]},
  {id:'CONV023',level:'A2',title:'Reise planen',description:'Zwei Freunde planen einen Urlaub nach Spanien.',
   speakers:[{name:'Jonas',voice:1},{name:'Nina',voice:2}],
   lines:[
    {speaker:'Jonas',side:'left',de:'Nina, hast du schon Pläne für den Sommer?',en:'Nina, do you already have plans for summer?'},
    {speaker:'Nina',side:'right',de:'Noch nicht. Ich würde gerne verreisen. Hast du eine Idee?',en:'Not yet. I would love to travel. Do you have an idea?'},
    {speaker:'Jonas',side:'left',de:'Wie wäre es mit Spanien? Barcelona soll sehr schön sein.',en:'How about Spain? Barcelona is supposed to be very beautiful.'},
    {speaker:'Nina',side:'right',de:'Tolle Idee! Wann möchtest du fahren?',en:'Great idea! When do you want to go?'},
    {speaker:'Jonas',side:'left',de:'Mitte Juli wäre perfekt. Zwei Wochen?',en:'Mid-July would be perfect. Two weeks?'},
    {speaker:'Nina',side:'right',de:'Ja! Fliegen wir oder fahren wir mit dem Zug?',en:'Yes! Shall we fly or take the train?'},
    {speaker:'Jonas',side:'left',de:'Ich habe billige Flüge gefunden, nur neunzig Euro hin und zurück.',en:'I found cheap flights, only ninety euros return.'},
    {speaker:'Nina',side:'right',de:'Wow! Und wo übernachten wir?',en:'Wow! And where will we stay?'},
    {speaker:'Jonas',side:'left',de:'Ich habe ein Apartment in der Nähe des Strandes gefunden.',en:'I found an apartment near the beach.'},
    {speaker:'Nina',side:'right',de:'Perfekt! Ich kümmere mich um die Reisekrankenversicherung.',en:'Perfect! I will take care of the travel health insurance.'},
    {speaker:'Jonas',side:'left',de:'Super. Und ich buche die Flüge und das Apartment.',en:'Great. And I will book the flights and the apartment.'},
    {speaker:'Nina',side:'right',de:'Ich kann es kaum erwarten! Das wird eine tolle Reise.',en:'I can hardly wait! This will be a great trip.'},
  ]},
  {id:'CONV024',level:'A2',title:'Beim Arzt — Termin vereinbaren',description:'Frau Berg ruft in der Arztpraxis an.',
   speakers:[{name:'Frau Berg',voice:1},{name:'Sprechstundenhilfe',voice:2}],
   lines:[
    {speaker:'Frau Berg',side:'left',de:'Guten Morgen. Ich würde gerne einen Termin bei Doktor Müller vereinbaren.',en:'Good morning. I would like to make an appointment with Doctor Müller.'},
    {speaker:'Sprechstundenhilfe',side:'right',de:'Guten Morgen. Sind Sie bereits Patient bei uns?',en:'Good morning. Are you already a patient with us?'},
    {speaker:'Frau Berg',side:'left',de:'Ja, ich bin seit zwei Jahren Patientin. Mein Name ist Berg, Sabine Berg.',en:'Yes, I have been a patient for two years. My name is Berg, Sabine Berg.'},
    {speaker:'Sprechstundenhilfe',side:'right',de:'Einen Moment, ich suche Ihre Daten. Was fehlt Ihnen denn?',en:'One moment, I am searching for your details. What is the matter with you?'},
    {speaker:'Frau Berg',side:'left',de:'Ich habe seit einer Woche starke Rückenschmerzen.',en:'I have had severe back pain for a week.'},
    {speaker:'Sprechstundenhilfe',side:'right',de:'Verstehe. Haben Sie Fieber oder andere Beschwerden?',en:'I understand. Do you have a fever or other complaints?'},
    {speaker:'Frau Berg',side:'left',de:'Nein, nur der Rücken. Aber es ist wirklich schlimm.',en:'No, just my back. But it is really bad.'},
    {speaker:'Sprechstundenhilfe',side:'right',de:'Ich schaue kurz in den Terminkalender. Können Sie Donnerstag um vierzehn Uhr?',en:'Let me quickly check the appointment calendar. Can you come Thursday at two o\'clock?'},
    {speaker:'Frau Berg',side:'left',de:'Donnerstag geht leider nicht. Ich arbeite bis sechzehn Uhr.',en:'Thursday unfortunately does not work. I work until four o\'clock.'},
    {speaker:'Sprechstundenhilfe',side:'right',de:'Dann hätten wir noch Freitag um sieben Uhr dreißig morgens.',en:'Then we have Friday at seven thirty in the morning.'},
    {speaker:'Frau Berg',side:'left',de:'Freitagmorgen passt mir gut. Den nehme ich.',en:'Friday morning works well for me. I will take that.'},
    {speaker:'Sprechstundenhilfe',side:'right',de:'Gut. Bitte bringen Sie Ihre Versichertenkarte mit. Bis Freitag!',en:'Good. Please bring your insurance card. See you Friday!'},
  ]},
  {id:'CONV025',level:'A2',title:'Bei der Bank',description:'Herr Kim möchte ein Konto eröffnen.',
   speakers:[{name:'Herr Kim',voice:1},{name:'Bankberaterin Frau Groß',voice:2}],
   lines:[
    {speaker:'Herr Kim',side:'left',de:'Guten Tag. Ich möchte gern ein Konto bei Ihrer Bank eröffnen.',en:'Good day. I would like to open an account at your bank.'},
    {speaker:'Bankberaterin Frau Groß',side:'right',de:'Herzlich willkommen. Ich helfe Ihnen gerne. Haben Sie bereits eine Bank in Deutschland?',en:'Welcome. I am happy to help you. Do you already have a bank in Germany?'},
    {speaker:'Herr Kim',side:'left',de:'Nein, ich bin erst seit drei Monaten hier. Ich komme aus Südkorea.',en:'No, I have only been here for three months. I come from South Korea.'},
    {speaker:'Bankberaterin Frau Groß',side:'right',de:'Kein Problem. Ich brauche Ihren Reisepass und Ihre Meldebescheinigung.',en:'No problem. I need your passport and your registration certificate.'},
    {speaker:'Herr Kim',side:'left',de:'Hier sind die Dokumente.',en:'Here are the documents.'},
    {speaker:'Bankberaterin Frau Groß',side:'right',de:'Danke. Möchten Sie ein Girokonto oder auch ein Sparkonto?',en:'Thank you. Would you like a current account or also a savings account?'},
    {speaker:'Herr Kim',side:'left',de:'Erst ein Girokonto, bitte. Und eine EC-Karte.',en:'A current account first, please. And a debit card.'},
    {speaker:'Bankberaterin Frau Groß',side:'right',de:'Natürlich. Möchten Sie auch Online-Banking einrichten?',en:'Of course. Would you also like to set up online banking?'},
    {speaker:'Herr Kim',side:'left',de:'Ja, gerne. Ist das kostenlos?',en:'Yes, please. Is that free of charge?'},
    {speaker:'Bankberaterin Frau Groß',side:'right',de:'Das Girokonto ist kostenlos, wenn monatlich über siebenhundert Euro eingehen.',en:'The current account is free if more than seven hundred euros are received per month.'},
    {speaker:'Herr Kim',side:'left',de:'Ich verdiene mehr als das. Das ist kein Problem.',en:'I earn more than that. That is no problem.'},
    {speaker:'Bankberaterin Frau Groß',side:'right',de:'Perfekt. Die Karte erhalten Sie in etwa fünf Werktagen per Post.',en:'Perfect. You will receive the card by post in about five working days.'},
  ]},
  {id:'CONV026',level:'A2',title:'Eine Reklamation',description:'Frau Sommer beschwert sich über ein defektes Produkt.',
   speakers:[{name:'Frau Sommer',voice:1},{name:'Kundenservice Marco',voice:2}],
   lines:[
    {speaker:'Frau Sommer',side:'left',de:'Guten Tag. Ich habe vor zwei Wochen einen Mixer bei Ihnen gekauft, aber er funktioniert nicht mehr.',en:'Good day. I bought a blender from you two weeks ago, but it no longer works.'},
    {speaker:'Kundenservice Marco',side:'right',de:'Das tut mir leid, Frau Sommer. Haben Sie noch den Kassenbon?',en:'I am sorry, Ms Sommer. Do you still have the receipt?'},
    {speaker:'Frau Sommer',side:'left',de:'Ja, natürlich. Hier ist er.',en:'Yes, of course. Here it is.'},
    {speaker:'Kundenservice Marco',side:'right',de:'Danke. Was genau ist das Problem mit dem Mixer?',en:'Thank you. What exactly is the problem with the blender?'},
    {speaker:'Frau Sommer',side:'left',de:'Er macht ein lautes Geräusch und schaltet sich dann einfach aus.',en:'It makes a loud noise and then simply switches off.'},
    {speaker:'Kundenservice Marco',side:'right',de:'Haben Sie ihn korrekt verwendet? Immer mit Deckel?',en:'Did you use it correctly? Always with the lid?'},
    {speaker:'Frau Sommer',side:'left',de:'Natürlich! Ich habe die Anleitung genau gelesen.',en:'Of course! I read the instructions carefully.'},
    {speaker:'Kundenservice Marco',side:'right',de:'Das Gerät ist noch unter Garantie. Wir tauschen es aus.',en:'The device is still under warranty. We will exchange it.'},
    {speaker:'Frau Sommer',side:'left',de:'Kann ich sofort ein neues mitnehmen?',en:'Can I take a new one immediately?'},
    {speaker:'Kundenservice Marco',side:'right',de:'Leider haben wir das Modell gerade nicht auf Lager.',en:'Unfortunately we do not have that model in stock at the moment.'},
    {speaker:'Frau Sommer',side:'left',de:'Wie lange muss ich warten?',en:'How long will I have to wait?'},
    {speaker:'Kundenservice Marco',side:'right',de:'Etwa eine Woche. Wir schicken ihn Ihnen kostenlos nach Hause.',en:'About a week. We will send it to you at home free of charge.'},
  ]},
  {id:'CONV027',level:'A2',title:'Stadtführung',description:'Eine Touristin nimmt an einer Stadtführung teil.',
   speakers:[{name:'Touristin Sophie',voice:1},{name:'Stadtführer Thomas',voice:2}],
   lines:[
    {speaker:'Stadtführer Thomas',side:'right',de:'Willkommen zur Stadtführung durch die Altstadt! Mein Name ist Thomas.',en:'Welcome to the city tour through the old town! My name is Thomas.'},
    {speaker:'Touristin Sophie',side:'left',de:'Guten Tag! Wie lange dauert die Führung?',en:'Good day! How long does the tour take?'},
    {speaker:'Stadtführer Thomas',side:'right',de:'Ungefähr zwei Stunden. Wir beginnen hier am Marktplatz.',en:'About two hours. We start here at the market square.'},
    {speaker:'Touristin Sophie',side:'left',de:'Was ist das für ein Gebäude da drüben?',en:'What is that building over there?'},
    {speaker:'Stadtführer Thomas',side:'right',de:'Das ist das Rathaus, gebaut im Jahre 1485. Es ist das älteste Gebäude der Stadt.',en:'That is the town hall, built in the year 1485. It is the oldest building in the city.'},
    {speaker:'Touristin Sophie',side:'left',de:'Wow, so alt! Kann man das Rathaus besichtigen?',en:'Wow, so old! Can you visit the town hall?'},
    {speaker:'Stadtführer Thomas',side:'right',de:'Ja, täglich von neun bis siebzehn Uhr. Der Eintritt ist frei.',en:'Yes, daily from nine to five o\'clock. Entry is free.'},
    {speaker:'Touristin Sophie',side:'left',de:'Und was ist die Geschichte dieses Platzes?',en:'And what is the history of this square?'},
    {speaker:'Stadtführer Thomas',side:'right',de:'Hier fand früher jeden Mittwoch ein großer Markt statt. Das ist seit dem Mittelalter so.',en:'A large market used to take place here every Wednesday. It has been like this since the Middle Ages.'},
    {speaker:'Touristin Sophie',side:'left',de:'Faszinierend! Gibt es gute Restaurants in der Nähe?',en:'Fascinating! Are there good restaurants nearby?'},
    {speaker:'Stadtführer Thomas',side:'right',de:'Ja, viele! Nach der Führung empfehle ich das Restaurant „Zum alten Keller".',en:'Yes, many! After the tour I recommend the restaurant "Zum alten Keller".'},
    {speaker:'Touristin Sophie',side:'left',de:'Vielen Dank für die tollen Informationen!',en:'Thank you very much for the great information!'},
  ]},
  {id:'CONV028',level:'A2',title:'Ein Rezept kochen',description:'Zwei Freunde kochen zusammen und folgen einem Rezept.',
   speakers:[{name:'Aiko',voice:1},{name:'Daniel',voice:2}],
   lines:[
    {speaker:'Aiko',side:'left',de:'Daniel, ich möchte heute Abend Pasta Carbonara machen. Kannst du mir helfen?',en:'Daniel, I want to make Pasta Carbonara tonight. Can you help me?'},
    {speaker:'Daniel',side:'right',de:'Natürlich! Ich kenne das Rezept auswendig. Was haben wir schon?',en:'Of course! I know the recipe by heart. What do we already have?'},
    {speaker:'Aiko',side:'left',de:'Ich habe Spaghetti, Eier und Parmesan. Was fehlt noch?',en:'I have spaghetti, eggs and Parmesan. What else is missing?'},
    {speaker:'Daniel',side:'right',de:'Wir brauchen noch Speck, Knoblauch und schwarzen Pfeffer.',en:'We still need bacon, garlic and black pepper.'},
    {speaker:'Aiko',side:'left',de:'Ich habe keinen Speck, aber Schinken. Geht das auch?',en:'I do not have bacon, but ham. Does that also work?'},
    {speaker:'Daniel',side:'right',de:'Geht, aber es schmeckt etwas anders. Zuerst kochst du das Wasser für die Pasta.',en:'It works, but it tastes slightly different. First you boil the water for the pasta.'},
    {speaker:'Aiko',side:'left',de:'Okay. Und was mache ich mit den Eiern?',en:'Okay. And what do I do with the eggs?'},
    {speaker:'Daniel',side:'right',de:'Du schlägst zwei Eier auf und vermischst sie mit Parmesan und Pfeffer.',en:'You crack two eggs and mix them with Parmesan and pepper.'},
    {speaker:'Aiko',side:'left',de:'Und dann?',en:'And then?'},
    {speaker:'Daniel',side:'right',de:'Dann brätst du den Schinken an und gibst alles mit der fertigen Pasta zusammen.',en:'Then you fry the ham and mix everything together with the cooked pasta.'},
    {speaker:'Aiko',side:'left',de:'Klingt lecker! Das wichtigste ist, die Eier nicht zu erhitzen, oder?',en:'Sounds delicious! The most important thing is not to heat the eggs, right?'},
    {speaker:'Daniel',side:'right',de:'Genau! Sonst wird ein Rührei daraus. Die Hitze der Pasta reicht.',en:'Exactly! Otherwise you end up with scrambled eggs. The heat of the pasta is enough.'},
  ]},
  {id:'CONV029',level:'A2',title:'Im Fitnessstudio anmelden',description:'Kai möchte Mitglied in einem Fitnessstudio werden.',
   speakers:[{name:'Kai',voice:1},{name:'Mitarbeiterin Lisa',voice:2}],
   lines:[
    {speaker:'Kai',side:'left',de:'Hallo! Ich würde gerne Mitglied in Ihrem Fitnessstudio werden.',en:'Hello! I would like to become a member of your gym.'},
    {speaker:'Mitarbeiterin Lisa',side:'right',de:'Herzlich willkommen! Ich zeige Ihnen gern die verschiedenen Tarife.',en:'Welcome! I am happy to show you the different membership rates.'},
    {speaker:'Kai',side:'left',de:'Ich möchte vor allem Krafttraining machen und manchmal schwimmen.',en:'I mainly want to do weight training and sometimes swim.'},
    {speaker:'Mitarbeiterin Lisa',side:'right',de:'Dann empfehle ich unser Premium-Paket — Gym plus Schwimmbad.',en:'Then I recommend our Premium package — gym plus swimming pool.'},
    {speaker:'Kai',side:'left',de:'Was kostet das im Monat?',en:'How much does that cost per month?'},
    {speaker:'Mitarbeiterin Lisa',side:'right',de:'Fünfundvierzig Euro pro Monat bei einem Jahresvertrag.',en:'Forty-five euros per month with an annual contract.'},
    {speaker:'Kai',side:'left',de:'Gibt es auch einen Monatsvertrag?',en:'Is there also a monthly contract?'},
    {speaker:'Mitarbeiterin Lisa',side:'right',de:'Ja, aber dann kostet es fünfundfünfzig Euro monatlich.',en:'Yes, but then it costs fifty-five euros per month.'},
    {speaker:'Kai',side:'left',de:'Kann ich das Studio erst mal ausprobieren?',en:'Can I try out the studio first?'},
    {speaker:'Mitarbeiterin Lisa',side:'right',de:'Ja, eine Woche kostenlos Probe-Training ist möglich.',en:'Yes, one week of free trial training is possible.'},
    {speaker:'Kai',side:'left',de:'Super! Dann würde ich gerne jetzt gleich starten.',en:'Great! Then I would like to start right now.'},
    {speaker:'Mitarbeiterin Lisa',side:'right',de:'Perfekt. Ich brauche nur Ihren Ausweis und eine Unterschrift.',en:'Perfect. I just need your ID and a signature.'},
  ]},
  {id:'CONV030',level:'A2',title:'Beim Umzug helfen',description:'Zwei Freunde organisieren gemeinsam den Umzug.',
   speakers:[{name:'Paula',voice:1},{name:'Ben',voice:2}],
   lines:[
    {speaker:'Paula',side:'left',de:'Ben, ich ziehe nächsten Samstag um. Kannst du mir helfen?',en:'Ben, I am moving next Saturday. Can you help me?'},
    {speaker:'Ben',side:'right',de:'Natürlich! Was muss alles gemacht werden?',en:'Of course! What all needs to be done?'},
    {speaker:'Paula',side:'left',de:'Wir müssen die Möbel tragen, Kisten packen und Kleinigkeiten einräumen.',en:'We have to carry the furniture, pack boxes and put small things away.'},
    {speaker:'Ben',side:'right',de:'Hast du schon einen Transporter gemietet?',en:'Have you already rented a van?'},
    {speaker:'Paula',side:'left',de:'Ja, für sechs Stunden. Er kostet neunzig Euro.',en:'Yes, for six hours. It costs ninety euros.'},
    {speaker:'Ben',side:'right',de:'Gut. Wie viele Kisten hast du schon gepackt?',en:'Good. How many boxes have you already packed?'},
    {speaker:'Paula',side:'left',de:'Etwa zwanzig. Aber die Küche muss ich noch packen.',en:'About twenty. But I still have to pack the kitchen.'},
    {speaker:'Ben',side:'right',de:'Ich komme Freitagabend schon vorbei und helfe dir mit der Küche.',en:'I will come by on Friday evening already and help you with the kitchen.'},
    {speaker:'Paula',side:'left',de:'Das wäre super! Soll ich noch jemanden fragen?',en:'That would be great! Should I ask anyone else?'},
    {speaker:'Ben',side:'right',de:'Lass mal noch Marco fragen. Zu dritt geht es schneller.',en:'Let\'s also ask Marco. Three people will be faster.'},
    {speaker:'Paula',side:'left',de:'Gute Idee. Ich frage ihn heute Abend noch.',en:'Good idea. I will ask him this evening.'},
    {speaker:'Ben',side:'right',de:'Und danach gehen wir alle Pizza essen — als Dankeschön!',en:'And afterwards we all go for pizza — as a thank-you!'},
  ]},
  {id:'CONV031',level:'A2',title:'Zugverspätung',description:'Zwei Reisende warten auf einen verspäteten Zug.',
   speakers:[{name:'Herr Richter',voice:1},{name:'Frau Osei',voice:2}],
   lines:[
    {speaker:'Herr Richter',side:'left',de:'Entschuldigung, wissen Sie warum der Zug nach Frankfurt noch nicht da ist?',en:'Excuse me, do you know why the train to Frankfurt has not arrived yet?'},
    {speaker:'Frau Osei',side:'right',de:'Nein, aber auf der Tafel steht: Verspätung dreißig Minuten.',en:'No, but the board says: thirty minutes delay.'},
    {speaker:'Herr Richter',side:'left',de:'Das ist ärgerlich. Ich habe eine Anschlussbahn um siebzehn Uhr.',en:'That is annoying. I have a connecting train at five o\'clock.'},
    {speaker:'Frau Osei',side:'right',de:'Das wird dann knapp. Haben Sie die DB-App?',en:'That will be tight then. Do you have the DB app?'},
    {speaker:'Herr Richter',side:'left',de:'Ja. Da steht, es gibt noch einen Zug um achtzehn Uhr.',en:'Yes. It says there is another train at six o\'clock.'},
    {speaker:'Frau Osei',side:'right',de:'Das wäre zumindest ein Notfallplan.',en:'That would at least be a back-up plan.'},
    {speaker:'Herr Richter',side:'left',de:'Stimmt. Ich rufe kurz meinen Kollegen an und sage ihm Bescheid.',en:'True. I will quickly call my colleague and let him know.'},
    {speaker:'Frau Osei',side:'right',de:'Gute Idee. Und wenn Sie den Anschluss verpassen, können Sie die Fahrgastrechte nutzen.',en:'Good idea. And if you miss the connection, you can use passenger rights.'},
    {speaker:'Herr Richter',side:'left',de:'Stimmt, ab sechzig Minuten Verspätung gibt es Erstattung.',en:'True, from sixty minutes delay you get reimbursement.'},
    {speaker:'Frau Osei',side:'right',de:'Genau. Heben Sie unbedingt Ihre Fahrkarte auf.',en:'Exactly. Make sure you keep your ticket.'},
    {speaker:'Herr Richter',side:'left',de:'Danke für den Tipp! Hoffentlich kommt der Zug bald.',en:'Thank you for the tip! Hopefully the train will come soon.'},
    {speaker:'Frau Osei',side:'right',de:'Ja, wir können nur warten. Gute Reise dann!',en:'Yes, we can only wait. Have a good journey then!'},
  ]},
  {id:'CONV032',level:'A2',title:'Konflikt unter Nachbarn',description:'Zwei Nachbarn sprechen über eine Beschwerde.',
   speakers:[{name:'Frau Klein',voice:1},{name:'Herr Braun',voice:2}],
   lines:[
    {speaker:'Frau Klein',side:'left',de:'Guten Abend, Herr Braun. Darf ich kurz mit Ihnen sprechen?',en:'Good evening, Mr Braun. May I speak with you briefly?'},
    {speaker:'Herr Braun',side:'right',de:'Natürlich, Frau Klein. Was gibt es?',en:'Of course, Ms Klein. What is it?'},
    {speaker:'Frau Klein',side:'left',de:'Es tut mir leid, aber Ihre Musik war letzte Nacht sehr laut.',en:'I am sorry, but your music was very loud last night.'},
    {speaker:'Herr Braun',side:'right',de:'Oh, das wusste ich nicht. Wie spät war es?',en:'Oh, I did not know that. What time was it?'},
    {speaker:'Frau Klein',side:'left',de:'Es war nach Mitternacht. Ich konnte nicht schlafen.',en:'It was after midnight. I could not sleep.'},
    {speaker:'Herr Braun',side:'right',de:'Das tut mir sehr leid! Ich hatte Besuch und wir haben das vergessen.',en:'I am very sorry! I had guests and we forgot about it.'},
    {speaker:'Frau Klein',side:'left',de:'Ich verstehe das. Aber nach zweiundzwanzig Uhr gilt die Nachtruhe.',en:'I understand that. But the quiet hours apply after ten o\'clock.'},
    {speaker:'Herr Braun',side:'right',de:'Sie haben vollkommen Recht. Das passiert nicht wieder.',en:'You are absolutely right. It will not happen again.'},
    {speaker:'Frau Klein',side:'left',de:'Danke. Wenn Sie mal eine Party planen, sagen Sie mir bitte vorher Bescheid.',en:'Thank you. If you plan a party, please let me know in advance.'},
    {speaker:'Herr Braun',side:'right',de:'Das mache ich. Und ich entschuldige mich nochmals.',en:'I will do that. And I apologise once again.'},
    {speaker:'Frau Klein',side:'left',de:'Kein Problem. Guten Abend noch.',en:'No problem. Good evening.'},
    {speaker:'Herr Braun',side:'right',de:'Guten Abend, Frau Klein. Und danke für Ihr Verständnis.',en:'Good evening, Ms Klein. And thank you for your understanding.'},
  ]},
  {id:'CONV033',level:'A2',title:'In der Bibliothek',description:'Ein Student fragt nach Büchern in der Bibliothek.',
   speakers:[{name:'Student Malik',voice:1},{name:'Bibliothekarin Frau Engel',voice:2}],
   lines:[
    {speaker:'Student Malik',side:'left',de:'Guten Tag. Ich suche Bücher über die Weimarer Republik für meine Hausarbeit.',en:'Good day. I am looking for books about the Weimar Republic for my essay.'},
    {speaker:'Bibliothekarin Frau Engel',side:'right',de:'Das finde ich gerne für Sie. Sind Sie Student hier?',en:'I will gladly find that for you. Are you a student here?'},
    {speaker:'Student Malik',side:'left',de:'Ja, ich studiere Geschichte im zweiten Semester.',en:'Yes, I am studying history in my second semester.'},
    {speaker:'Bibliothekarin Frau Engel',side:'right',de:'Gut. Wir haben mehrere Bücher dazu. Soll ich eine Recherche machen?',en:'Good. We have several books on that. Shall I do a search?'},
    {speaker:'Student Malik',side:'left',de:'Ja, bitte. Ich brauche hauptsächlich Primärquellen.',en:'Yes, please. I mainly need primary sources.'},
    {speaker:'Bibliothekarin Frau Engel',side:'right',de:'Einen Moment. Wir haben fünf relevante Werke. Drei stehen im Regal, zwei sind ausgeliehen.',en:'One moment. We have five relevant works. Three are on the shelf, two are on loan.'},
    {speaker:'Student Malik',side:'left',de:'Kann ich die ausgeliehenen vormerken?',en:'Can I reserve the ones on loan?'},
    {speaker:'Bibliothekarin Frau Engel',side:'right',de:'Ja, kein Problem. Ich brauche Ihren Studentenausweis.',en:'Yes, no problem. I need your student ID.'},
    {speaker:'Student Malik',side:'left',de:'Hier bitte. Wie lange darf ich die Bücher behalten?',en:'Here you go. How long may I keep the books?'},
    {speaker:'Bibliothekarin Frau Engel',side:'right',de:'Vier Wochen, mit einmaliger Verlängerung möglich.',en:'Four weeks, with one renewal possible.'},
    {speaker:'Student Malik',side:'left',de:'Perfekt. Gibt es auch Online-Zugang zu Archiven?',en:'Perfect. Is there also online access to archives?'},
    {speaker:'Bibliothekarin Frau Engel',side:'right',de:'Ja, mit Ihrer Studentenkennung auf unserer Homepage. Viel Erfolg bei der Arbeit!',en:'Yes, with your student login on our homepage. Good luck with your work!'},
  ]},
  {id:'CONV034',level:'A2',title:'Ausflug planen',description:'Eine Familie plant einen Tagesausflug.',
   speakers:[{name:'Mama Sandra',voice:1},{name:'Papa Felix',voice:2}],
   lines:[
    {speaker:'Mama Sandra',side:'left',de:'Felix, was machen wir am Sonntag mit den Kindern?',en:'Felix, what shall we do with the children on Sunday?'},
    {speaker:'Papa Felix',side:'right',de:'Ich dachte an einen Ausflug in den Tierpark. Die Kinder lieben Tiere.',en:'I was thinking of a trip to the animal park. The children love animals.'},
    {speaker:'Mama Sandra',side:'left',de:'Gute Idee! Wie weit ist der Tierpark von hier?',en:'Good idea! How far is the animal park from here?'},
    {speaker:'Papa Felix',side:'right',de:'Etwa vierzig Minuten mit dem Auto.',en:'About forty minutes by car.'},
    {speaker:'Mama Sandra',side:'left',de:'Müssen wir vorher Tickets kaufen oder geht das auch an der Kasse?',en:'Do we have to buy tickets in advance or is it possible at the box office too?'},
    {speaker:'Papa Felix',side:'right',de:'Online ist es günstiger. Ich schaue mal auf der Website.',en:'It is cheaper online. Let me check on the website.'},
    {speaker:'Mama Sandra',side:'left',de:'Was kostet der Eintritt für eine Familie?',en:'How much is the entrance fee for a family?'},
    {speaker:'Papa Felix',side:'right',de:'Achtundzwanzig Euro für zwei Erwachsene und zwei Kinder.',en:'Twenty-eight euros for two adults and two children.'},
    {speaker:'Mama Sandra',side:'left',de:'Das ist fair. Sollen wir ein Picknick mitnehmen?',en:'That is fair. Shall we take a picnic?'},
    {speaker:'Papa Felix',side:'right',de:'Ja, das spart Geld. Ich backe morgen Brötchen.',en:'Yes, that saves money. I will bake bread rolls tomorrow.'},
    {speaker:'Mama Sandra',side:'left',de:'Wunderbar! Die Kinder werden sich so freuen.',en:'Wonderful! The children will be so pleased.'},
    {speaker:'Papa Felix',side:'right',de:'Es wird ein toller Tag. Ich freue mich auch!',en:'It will be a great day. I am looking forward to it too!'},
  ]},
  {id:'CONV035',level:'A2',title:'Sprachkurs — Diskussion',description:'Zwei Kursteilnehmer sprechen über Lernmethoden.',
   speakers:[{name:'Priya',voice:1},{name:'Carlos',voice:2}],
   lines:[
    {speaker:'Priya',side:'left',de:'Carlos, wie lernst du am liebsten Deutsch?',en:'Carlos, what is your favourite way to learn German?'},
    {speaker:'Carlos',side:'right',de:'Ich schaue viele deutsche Serien und lese Nachrichten. Und du?',en:'I watch many German series and read the news. And you?'},
    {speaker:'Priya',side:'left',de:'Ich lerne hauptsächlich mit Karteikarten und spreche viel mit meinen Nachbarn.',en:'I mainly learn with flashcards and speak a lot with my neighbours.'},
    {speaker:'Carlos',side:'right',de:'Das ist eine super Methode. Sprichst du auch mit Deutschen auf der Straße?',en:'That is a great method. Do you also speak with Germans in the street?'},
    {speaker:'Priya',side:'left',de:'Ja, aber am Anfang war ich sehr nervös. Jetzt macht es mir Spaß.',en:'Yes, but at first I was very nervous. Now I enjoy it.'},
    {speaker:'Carlos',side:'right',de:'Mir auch. Die Grammatik finde ich noch schwierig — besonders der Genitiv.',en:'Me too. I still find the grammar difficult — especially the genitive.'},
    {speaker:'Priya',side:'left',de:'Ja, das ist komplex. Ich empfehle das Buch „Deutsche Grammatik für Ausländer".',en:'Yes, that is complex. I recommend the book "Deutsche Grammatik für Ausländer".'},
    {speaker:'Carlos',side:'right',de:'Danke! Hörst du auch deutsche Podcasts?',en:'Thank you! Do you also listen to German podcasts?'},
    {speaker:'Priya',side:'left',de:'Ja, „Slow German" ist perfekt für unser Niveau. Sehr empfehlenswert.',en:'Yes, "Slow German" is perfect for our level. Highly recommended.'},
    {speaker:'Carlos',side:'right',de:'Den kenne ich! Die Sprecherin spricht wirklich langsam und deutlich.',en:'I know that one! The speaker really speaks slowly and clearly.'},
    {speaker:'Priya',side:'left',de:'Vielleicht können wir zusammen einen Tandemparter suchen?',en:'Maybe we can look for a tandem partner together?'},
    {speaker:'Carlos',side:'right',de:'Tolle Idee! Ein Muttersprachler wäre ideal.',en:'Great idea! A native speaker would be ideal.'},
  ]},
  {id:'CONV036',level:'A2',title:'Telefonat — Termin verschieben',description:'Herr Meier muss seinen Termin absagen.',
   speakers:[{name:'Herr Meier',voice:1},{name:'Sekretärin Frau Becker',voice:2}],
   lines:[
    {speaker:'Herr Meier',side:'left',de:'Guten Tag, Frau Becker. Ich muss leider meinen Termin morgen absagen.',en:'Good day, Ms Becker. I unfortunately have to cancel my appointment tomorrow.'},
    {speaker:'Sekretärin Frau Becker',side:'right',de:'Oh, das ist schade. Ist alles in Ordnung?',en:'Oh, that is a pity. Is everything alright?'},
    {speaker:'Herr Meier',side:'left',de:'Ja, danke. Ich habe nur kurzfristig eine Dienstreise bekommen.',en:'Yes, thank you. I have just received a business trip at short notice.'},
    {speaker:'Sekretärin Frau Becker',side:'right',de:'Kein Problem. Wann wären Sie wieder in der Stadt?',en:'No problem. When will you be back in town?'},
    {speaker:'Herr Meier',side:'left',de:'Nächste Woche Donnerstag bin ich wieder zurück.',en:'I will be back next Thursday.'},
    {speaker:'Sekretärin Frau Becker',side:'right',de:'Ich schaue in den Kalender. Wie wäre Freitag um zehn Uhr?',en:'Let me check the calendar. How about Friday at ten o\'clock?'},
    {speaker:'Herr Meier',side:'left',de:'Freitag passt gut. Morgens ist besser für mich.',en:'Friday works well. Mornings are better for me.'},
    {speaker:'Sekretärin Frau Becker',side:'right',de:'Gut, dann trage ich Sie für Freitag, zehn Uhr ein.',en:'Good, then I will put you down for Friday at ten o\'clock.'},
    {speaker:'Herr Meier',side:'left',de:'Perfekt. Ich bekomme noch eine Bestätigung per E-Mail?',en:'Perfect. I will still get a confirmation by email?'},
    {speaker:'Sekretärin Frau Becker',side:'right',de:'Natürlich. Ich schicke Ihnen gleich eine.',en:'Of course. I will send you one straight away.'},
    {speaker:'Herr Meier',side:'left',de:'Danke vielmals. Auf Wiederhören!',en:'Thank you very much. Goodbye!'},
    {speaker:'Sekretärin Frau Becker',side:'right',de:'Auf Wiederhören! Gute Reise!',en:'Goodbye! Have a good trip!'},
  ]},
  {id:'CONV037',level:'A2',title:'Einen Brief schreiben — Hilfe',description:'Fatima braucht Hilfe bei einem offiziellen Brief.',
   speakers:[{name:'Fatima',voice:1},{name:'Berater Herr Wolf',voice:2}],
   lines:[
    {speaker:'Fatima',side:'left',de:'Hallo, ich brauche Hilfe. Ich muss einen Brief an das Amt schreiben, aber mein Deutsch ist noch nicht so gut.',en:'Hello, I need help. I have to write a letter to the office, but my German is not yet so good.'},
    {speaker:'Berater Herr Wolf',side:'right',de:'Kein Problem, ich helfe Ihnen gerne. Worum geht es?',en:'No problem, I am happy to help you. What is it about?'},
    {speaker:'Fatima',side:'left',de:'Ich möchte eine Verlängerung meiner Aufenthaltserlaubnis beantragen.',en:'I would like to apply for an extension of my residence permit.'},
    {speaker:'Berater Herr Wolf',side:'right',de:'Gut. Als erstes kommt die Anschrift des Amtes, dann Ihre Adresse.',en:'Good. First comes the address of the office, then your address.'},
    {speaker:'Fatima',side:'left',de:'Schreibe ich „Sehr geehrte Damen und Herren"?',en:'Do I write "Sehr geehrte Damen und Herren"?'},
    {speaker:'Berater Herr Wolf',side:'right',de:'Genau, das ist die richtige formelle Anrede.',en:'Exactly, that is the correct formal salutation.'},
    {speaker:'Fatima',side:'left',de:'Und wie fange ich den Text an?',en:'And how do I start the text?'},
    {speaker:'Berater Herr Wolf',side:'right',de:'„Hiermit beantrage ich die Verlängerung meiner Aufenthaltserlaubnis…"',en:'"Hereby I apply for the extension of my residence permit…"'},
    {speaker:'Fatima',side:'left',de:'Und am Ende? „Mit freundlichen Grüßen"?',en:'And at the end? "Mit freundlichen Grüßen"?'},
    {speaker:'Berater Herr Wolf',side:'right',de:'Ganz genau. Dann Ihre Unterschrift und Ihr Name.',en:'Exactly right. Then your signature and your name.'},
    {speaker:'Fatima',side:'left',de:'Welche Dokumente soll ich beilegen?',en:'Which documents should I enclose?'},
    {speaker:'Berater Herr Wolf',side:'right',de:'Ihren Reisepass, die alte Erlaubnis und ein aktuelles Foto.',en:'Your passport, the old permit and a recent photo.'},
  ]},
  {id:'CONV038',level:'A2',title:'Am Fundbüro',description:'Jemand sucht sein verlorenes Portemonnaie.',
   speakers:[{name:'Herr Santos',voice:1},{name:'Fundbüro-Mitarbeiterin',voice:2}],
   lines:[
    {speaker:'Herr Santos',side:'left',de:'Guten Tag. Ich habe heute Morgen im Bus mein Portemonnaie verloren.',en:'Good day. I lost my wallet on the bus this morning.'},
    {speaker:'Fundbüro-Mitarbeiterin',side:'right',de:'Das tut mir leid. Wann und wo genau war das?',en:'I am sorry to hear that. When and where exactly was that?'},
    {speaker:'Herr Santos',side:'left',de:'Heute gegen neun Uhr, in der Linie 47, Richtung Stadtmitte.',en:'Today at around nine o\'clock, on line 47, heading towards the city centre.'},
    {speaker:'Fundbüro-Mitarbeiterin',side:'right',de:'Wie sah das Portemonnaie aus?',en:'What did the wallet look like?'},
    {speaker:'Herr Santos',side:'left',de:'Es war schwarz aus Leder, mit einem roten Reißverschluss.',en:'It was black leather, with a red zip.'},
    {speaker:'Fundbüro-Mitarbeiterin',side:'right',de:'Was war darin?',en:'What was in it?'},
    {speaker:'Herr Santos',side:'left',de:'Etwa dreißig Euro, mein Ausweis und einige Visitenkarten.',en:'About thirty euros, my ID card and some business cards.'},
    {speaker:'Fundbüro-Mitarbeiterin',side:'right',de:'Ich schaue in der Liste. Einen Moment.',en:'Let me check the list. One moment.'},
    {speaker:'Herr Santos',side:'left',de:'Danke. Ich hoffe sehr, dass jemand es abgegeben hat.',en:'Thank you. I really hope someone handed it in.'},
    {speaker:'Fundbüro-Mitarbeiterin',side:'right',de:'Tatsächlich! Hier ist ein schwarzes Portemonnaie von Linie 47. Mit rotem Reißverschluss.',en:'Actually! Here is a black wallet from line 47. With a red zip.'},
    {speaker:'Herr Santos',side:'left',de:'Das ist meins! Oh, wie erleichtert bin ich!',en:'That is mine! Oh, how relieved I am!'},
    {speaker:'Fundbüro-Mitarbeiterin',side:'right',de:'Bitte unterschreiben Sie hier. Schön, dass es ein gutes Ende hat!',en:'Please sign here. It is lovely that it has a happy ending!'},
  ]},
  {id:'CONV039',level:'A2',title:'Kulturschock',description:'Eine Studentin aus Japan erzählt von ihren ersten Erlebnissen in Deutschland.',
   speakers:[{name:'Yuki',voice:1},{name:'Kommilitonin Sophie',voice:2}],
   lines:[
    {speaker:'Yuki',side:'left',de:'Sophie, darf ich dich etwas fragen? Mir ist gestern etwas Seltsames passiert.',en:'Sophie, may I ask you something? Something strange happened to me yesterday.'},
    {speaker:'Kommilitonin Sophie',side:'right',de:'Natürlich! Was ist passiert?',en:'Of course! What happened?'},
    {speaker:'Yuki',side:'left',de:'Ich war im Supermarkt und habe einfach nur gegrinst, aber die Leute haben mich seltsam angeschaut.',en:'I was in the supermarket and simply smiled, but people looked at me strangely.'},
    {speaker:'Kommilitonin Sophie',side:'right',de:'Ha, das kenne ich! Deutsche lächeln Fremde nicht so oft an wie in anderen Kulturen.',en:'Ha, I know that! Germans do not smile at strangers as often as in other cultures.'},
    {speaker:'Yuki',side:'left',de:'Ah, interessant! In Japan lächelt man immer, um höflich zu sein.',en:'Ah, interesting! In Japan you always smile to be polite.'},
    {speaker:'Kommilitonin Sophie',side:'right',de:'Hier bedeutet ein Lächeln zu Fremden manchmal, dass man etwas will.',en:'Here a smile at strangers sometimes means you want something.'},
    {speaker:'Yuki',side:'left',de:'Das erklärt viel! Und noch etwas: Warum reden die Deutschen so direkt?',en:'That explains a lot! And one more thing: why do Germans speak so directly?'},
    {speaker:'Kommilitonin Sophie',side:'right',de:'Direktheit ist bei uns normal. Es bedeutet nicht, dass man unhöflich ist.',en:'Directness is normal here. It does not mean one is being rude.'},
    {speaker:'Yuki',side:'left',de:'Ich verstehe. Am Anfang dachte ich, ich hätte etwas falsch gemacht.',en:'I understand. At first I thought I had done something wrong.'},
    {speaker:'Kommilitonin Sophie',side:'right',de:'Nein, gar nicht! Die meisten Deutschen sind sehr hilfsbereit, wenn man fragt.',en:'No, not at all! Most Germans are very helpful when you ask.'},
    {speaker:'Yuki',side:'left',de:'Das stimmt. Meine Nachbarin hat mir sofort bei der Heizung geholfen.',en:'That is true. My neighbour helped me with the heating immediately.'},
    {speaker:'Kommilitonin Sophie',side:'right',de:'Siehst du? Deutschland ist anders, aber man gewöhnt sich daran.',en:'You see? Germany is different, but you get used to it.'},
  ]},
  {id:'CONV040',level:'A2',title:'Paket abholen',description:'Frau Torres holt ein Paket von der Post ab.',
   speakers:[{name:'Frau Torres',voice:1},{name:'Postmitarbeiter',voice:2}],
   lines:[
    {speaker:'Frau Torres',side:'left',de:'Guten Tag. Ich habe einen Abholschein für ein Paket bekommen.',en:'Good day. I received a collection slip for a parcel.'},
    {speaker:'Postmitarbeiter',side:'right',de:'Guten Tag! Den Schein bitte.',en:'Good day! The slip please.'},
    {speaker:'Frau Torres',side:'left',de:'Hier ist er. Das Paket kam gestern an, aber ich war nicht zu Hause.',en:'Here it is. The parcel arrived yesterday, but I was not at home.'},
    {speaker:'Postmitarbeiter',side:'right',de:'Ich suche es kurz. Haben Sie auch Ihren Ausweis dabei?',en:'I will quickly look for it. Do you also have your ID with you?'},
    {speaker:'Frau Torres',side:'left',de:'Ja, hier ist mein Personalausweis.',en:'Yes, here is my identity card.'},
    {speaker:'Postmitarbeiter',side:'right',de:'Danke. Einen Moment, ich hole das Paket.',en:'Thank you. One moment, I will get the parcel.'},
    {speaker:'Frau Torres',side:'left',de:'Darf ich fragen, ob das Paket aus dem Ausland kommt?',en:'May I ask whether the parcel is coming from abroad?'},
    {speaker:'Postmitarbeiter',side:'right',de:'Ja, laut System aus Portugal. Sieht schwer aus.',en:'Yes, according to the system from Portugal. Looks heavy.'},
    {speaker:'Frau Torres',side:'left',de:'Das sind bestimmt Bücher von meiner Mutter.',en:'That is certainly books from my mother.'},
    {speaker:'Postmitarbeiter',side:'right',de:'Hier bitte! Fast fünf Kilo. Brauchen Sie eine Tüte?',en:'Here you go! Almost five kilos. Do you need a bag?'},
    {speaker:'Frau Torres',side:'left',de:'Nein danke, ich habe meinen Rucksack.',en:'No thank you, I have my backpack.'},
    {speaker:'Postmitarbeiter',side:'right',de:'Gut. Unterschreiben Sie bitte hier. Schönen Tag noch!',en:'Good. Please sign here. Have a nice day!'},
  ]},
];

fs.writeFileSync(OUT, JSON.stringify(a2, null, 2));
console.log('✅ Saved', a2.length, 'A2 conversations to', OUT);
