/* Generate new verb entries to merge into public/data/verbs.json.
   - Candidate infinitives come from the docx (word list only).
   - Conjugations are generated by our verified engine (NOT from the docx).
   - English meanings: use the docx gloss only if it is clean English;
     otherwise fall back to a curated map; otherwise skip the verb.
   Output: scripts/new_verbs.json  (for review before merge) */
const fs = require('fs');
const { conjugate } = require('./conj_engine.cjs');

const absent = JSON.parse(fs.readFileSync(require('os').tmpdir() + '/absent.json', 'utf8'));
const site   = JSON.parse(fs.readFileSync('public/data/verbs.json', 'utf8'));
const siteSet = new Set(site.map(v => v.verb.toLowerCase().trim()));

/* Non-verbs that happen to end in -en/-eln/-ern (adjectives, adverbs, numbers, participles-as-adjectives). */
const DENY = new Set([
  'einzeln','einverstanden','gleichermaßen','draußen','drinnen','hinten','vorn','vorne','oben','unten',
  'sieben','silbern','golden','eigen','eben','offen','schüchtern','abgesehen','ausgefallen','ausgewogen',
  'insofern','ostern','sofern','sozusagen','stattdessen','umstritten','unzufrieden','zufrieden','verloren',
  'vorhanden','zerbrochen','zerrissen','zusammen','ausgeschlossen','ausgesprochen','besessen','gefangen',
  'geschlossen','verschieden','verschiedenen','betrunken','erwachsen','geschieden','gelungen','dagegen',
  'daneben','übermorgen','morgen','übrigen','übrigens','wenigstens','keinen','meinen','seinen','deinen',
  'umgeben','durchschauen','übersetzen','umfahren','umstellen', // ambiguous separable/inseparable — skip to avoid wrong forms
  'radfahren','glückwünschen','reinlegen','hauen','verbergen', // unreliable base / not a clean infinitive
]);

/* Curated English meanings for common verbs whose docx gloss is corrupted/missing.
   Keyed by infinitive (with umlauts). */
const MEANINGS = {
  'abheben':'to withdraw (money) / take off','aufheben':'to pick up / preserve','abbiegen':'to turn (off)',
  'abstimmen':'to vote / coordinate','achten':'to respect / pay attention','anhaben':'to have on / wear',
  'ankündigen':'to announce','anschließen':'to connect / join','ansehen':'to look at / watch',
  'anstellen':'to employ / turn on','anzeigen':'to display / report','aufführen':'to perform',
  'aufladen':'to charge / load up','aufregen':'to upset / excite','ausfallen':'to be cancelled / fall out',
  'ausreichen':'to be sufficient','ausschließen':'to exclude','ausstellen':'to exhibit / issue',
  'beraten':'to advise','beschreiben':'to describe','besitzen':'to own / possess','besprechen':'to discuss',
  'bestehen':'to pass (exam) / consist of','betreffen':'to concern / affect','beweisen':'to prove',
  'beziehen':'to obtain / relate to','behalten':'to keep / retain','einbrechen':'to break in',
  'einnehmen':'to take (medicine) / earn','einrichten':'to set up / furnish','eintragen':'to enter / register',
  'enthalten':'to contain','entlassen':'to dismiss / release','entsprechen':'to correspond to',
  'entsorgen':'to dispose of','erfüllen':'to fulfil','ergänzen':'to complete / add','erleben':'to experience',
  'erledigen':'to deal with / handle','ersetzen':'to replace','erweitern':'to expand','erziehen':'to raise / educate',
  'fangen':'to catch','fließen':'to flow','frieren':'to freeze / be cold','gefallen':'to please / be liking',
  'gehören':'to belong','gelingen':'to succeed','genießen':'to enjoy','geschehen':'to happen',
  'gestehen':'to confess','gewinnen':'to win','gießen':'to pour / water','graben':'to dig','greifen':'to grab',
  'heben':'to lift','hängen':'to hang','kriechen':'to crawl','lassen':'to let / leave','leihen':'to lend / borrow',
  'messen':'to measure','nennen':'to name / call','pfeifen':'to whistle','preisen':'to praise','raten':'to advise / guess',
  'reiben':'to rub','riechen':'to smell','saugen':'to suck / vacuum','schieben':'to push','schießen':'to shoot',
  'schmelzen':'to melt','schreien':'to scream','schweigen':'to be silent','spinnen':'to spin / be crazy',
  'springen':'to jump','stechen':'to sting / stab','stehlen':'to steal','sterben':'to die','stinken':'to stink',
  'stoßen':'to push / bump','streichen':'to paint / cancel','treiben':'to drive / do (sport)','treten':'to step / kick',
  'wachsen':'to grow','weisen':'to point / direct','wenden':'to turn','wiegen':'to weigh','winden':'to wind',
  'erscheinen':'to appear','betreuen':'to look after / supervise','begleiten':'to accompany','dienen':'to serve',
  'fehlen':'to be missing / lacking','fegen':'to sweep','dehnen':'to stretch','drücken':'to press / push',
  'duzen':'to address informally','dolmetschen':'to interpret','fördern':'to promote / support','füttern':'to feed',
  'grenzen':'to border','gründen':'to found / establish','hupen':'to honk','husten':'to cough','heizen':'to heat',
  'bremsen':'to brake','brennen':'to burn','bluten':'to bleed','beleidigen':'to insult','benutzen':'to use',
  'beachten':'to observe / heed','bemerken':'to notice','folgen':'to follow','fordern':'to demand',
  'formulieren':'to formulate','festlegen':'to determine / fix','festsetzen':'to set / fix','feststellen':'to ascertain',
  'betreuen':'to care for','erreichen':'to reach / achieve','erhöhen':'to raise / increase','entfernen':'to remove',
  'entdecken':'to discover','entwickeln':'to develop','erweitern':'to expand','ernähren':'to feed / nourish',
  'erinnern':'to remind / remember','hetzen':'to rush / agitate','hageln':'to hail','donnern':'to thunder',
  'blitzen':'to flash (lightning)','grinsen':'to grin','grillen':'to grill / barbecue','googeln':'to google',
  'bloggen':'to blog','chatten':'to chat','dekorieren':'to decorate','demonstrieren':'to demonstrate',
  'diskutieren':'to discuss','fotografieren':'to photograph','finanzieren':'to finance','garantieren':'to guarantee',
  'abonnieren':'to subscribe','akzeptieren':'to accept','argumentieren':'to argue','aktualisieren':'to update',
  'evaluieren':'to evaluate','experimentieren':'to experiment','diagnostizieren':'to diagnose','differenzieren':'to differentiate',
  'beabsichtigen':'to intend','bedeuten':'to mean','begegnen':'to encounter','behandeln':'to treat','behaupten':'to claim',
  'berechnen':'to calculate','berichten':'to report','beruhigen':'to calm','beschädigen':'to damage','beschäftigen':'to occupy / employ',
  'besorgen':'to obtain / get','bestrafen':'to punish','beurteilen':'to judge / assess','bewirken':'to bring about',
  'bewältigen':'to cope with','bezeichnen':'to designate / call','beeinflussen':'to influence','beeinträchtigen':'to impair',
  'benachteiligen':'to disadvantage','berücksichtigen':'to take into account','beschleunigen':'to accelerate',
  'beschränken':'to limit','begründen':'to justify','benötigen':'to need / require','befürchten':'to fear',
  'beinhalten':'to contain','betrügen':'to deceive / cheat','dünsten':'to steam (food)',
};

/* Decide if a docx gloss is clean English we can trust. */
function cleanMeaning(m){
  if(!m) return null;
  m=m.trim();
  // must be English: no German letters, not a conjugated-form artifact
  if(/[äöüßÄÖÜ]/.test(m)) return null;
  // reject if it looks like a German separable präsens ("hebt ab", "stimmt ab")
  if(/^[a-z]+\s+(ab|an|auf|aus|ein|mit|nach|vor|zu|her|hin|los|weg)$/i.test(m)) return null;
  // reject single German-looking word (likely a conjugated form)
  if(/^[a-zäöü]+t$/i.test(m) && !/^(to |[A-Z])/.test(m)) return null;
  if(m.length<2) return null;
  return m;
}

const out=[];
const seen=new Set();
let skipped=0;
for(const c of absent){
  const verb=c.verb.trim();
  const key=verb.toLowerCase();
  if(siteSet.has(key) || seen.has(key)) continue;
  if(DENY.has(key)) { skipped++; continue; }
  if(!/(en|eln|ern)$/.test(verb)) { skipped++; continue; }  // must be infinitive form
  const r=conjugate(verb,'',c.level);
  if(!r){ skipped++; continue; }
  // meaning: prefer curated, else clean docx gloss, else skip
  let meaning = MEANINGS[verb] || cleanMeaning(c.meaning);
  if(!meaning){ skipped++; continue; }
  r.meaning=meaning;
  // id: ascii-safe
  r.id = verb.replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/\s+/g,'_');
  r.level = c.level || 'A2';
  seen.add(key);
  out.push(r);
}

fs.writeFileSync('scripts/new_verbs.json', JSON.stringify(out,null,1));
console.log('Generated:', out.length, '| skipped:', skipped);
const byCat={}; const byLvl={};
for(const v of out){ byCat[v.category]=(byCat[v.category]||0)+1; byLvl[v.level]=(byLvl[v.level]||0)+1; }
console.log('By category:', byCat);
console.log('By level:', byLvl);
